function [y] = gyro_load(x, grade)
%GYRO_LOAD  A graded gyro's mass [kg] and power [W]: the catalogue unit's x over the grade.
%   x: real[1] (passed a plain number)
%   grade: real[1] (passed a plain number)
%   returns y: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    y = 0;
    y = (x / grade);
end
