function [fit] = sensor_star_tracker(fine, knob)
%SENSOR_STAR_TRACKER  Whether the star tracker is fitted: the fine class, or the loop's knob.
%   fine: bool (passed true or false)
%   knob: bool (passed true or false)
%   returns fit: bool (passed true or false)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    fit = false;
    fit = (fine || knob);
end
