function [normals, sun_axis] = sensor_sun()
%SENSOR_SUN  The fine Sun sensors' normals, one on each face (row i the i-th sensor's), and the power face's axis.
%   returns normals: real[1][3][6] (passed a plain number)
%   returns sun_axis: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    normals = zeros(6, 3);
    sun_axis = zeros(3, 1);
    normals = [([1; 0; 0]).'; ([(-(1)); 0; 0]).'; ([0; 1; 0]).'; ([0; (-(1)); 0]).'; ([0; 0; 1]).'; ([0; 0; (-(1))]).'];
    sun_axis = [0; 0; (-(1))];
end
