function [dipole_max, per_amp, current_max, resistance, time_constant, mass, power, volume] = mtq_coil(m)
%MTQ_COIL  A coil of dipole m [A m^2]: its dipole per ampere, current, resistance [ohm], time constant [s], mass [kg], power at
%   the full dipole [W] and volume [L], linear in the dipole from the SYN-CT-1 anchor.
%   m: real[1] (passed a plain number)
%   returns dipole_max: real[1] (passed a plain number)
%   returns per_amp: real[1] (passed a plain number)
%   returns current_max: real[1] (passed a plain number)
%   returns resistance: int (passed a whole number)
%   returns time_constant: real[1] (passed a plain number)
%   returns mass: real[1] (passed a plain number)
%   returns power: real[1] (passed a plain number)
%   returns volume: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    dipole_max = 0;
    per_amp = 0;
    current_max = 0;
    resistance = 0;
    time_constant = 0;
    mass = 0;
    power = 0;
    volume = 0;
    kk = (m / 0.45);
    dipole_max = m;
    per_amp = 4.5;
    current_max = (m / 4.5);
    resistance = 30;
    time_constant = 0.005;
    mass = (0.03 * kk);
    power = (0.3 * kk);
    volume = (0.012 * kk);
end
