function [m_dump, m_mom, m_det, m] = mtq_dipoles(tau_dist, b_min, h_secular, b_mean, period, h_detumble, req_detumble)
%MTQ_DIPOLES  The dipoles the coil must give: dumping the worst torque tau_dist at half the least field b_min, the orbit's secular
%   momentum h_secular over an orbit of period [s] at 0.3 of the mean field b_mean, the detumble's momentum h_detumble in
%   half the detumble time (req.detumble [min], or three orbits when blank: nan) at 0.3 of the mean field; the coil's
%   the largest, at least 0.05.
%   tau_dist: real[1] (passed a plain number)
%   b_min: real[1] (passed a plain number)
%   h_secular: real[1] (passed a plain number)
%   b_mean: real[1] (passed a plain number)
%   period: real[1] (passed a plain number)
%   h_detumble: real[1] (passed a plain number)
%   req_detumble: real[1] (passed a plain number)
%   returns m_dump: real[1] (passed a plain number)
%   returns m_mom: real[1] (passed a plain number)
%   returns m_det: real[1] (passed a plain number)
%   returns m: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    m_dump = 0;
    m_mom = 0;
    m_det = 0;
    m = 0;
    td = asils.pc.choose(isnan(req_detumble), ((3 * period) / 60), req_detumble);
    m_dump = ((2 * tau_dist) / (0.5 * b_min));
    m_mom = ((2 * h_secular) / ((0.3 * b_mean) * period));
    m_det = (h_detumble / ((((0.3 * b_mean) * 0.5) * td) * 60));
    m = asils.models.sizedemand.size_max(asils.models.sizedemand.size_max(asils.models.sizedemand.size_max(m_dump, m_mom), m_det), 0.05);
end
