function [r, mag] = star_entry(k, n)
%STAR_ENTRY  Star k (from 0) of a catalogue of n: its direction (ECI, unit) and its magnitude.
%   tolerance: 1e-10
%   (The hash multiplies sin by 43758.5453 and 12345.6789, so a last-bit difference in sin between the reference
%   interpreter and the platform grows about 4e4 times; the engine's own maths is the platform's.)
%   k: int (passed a whole number)
%   n: int (passed a whole number)
%   returns r: real[1][3] (passed a plain number)
%   returns mag: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    r = zeros(3, 1);
    mag = 0;
    kf = (k + 0.5);
    nf = n;
    z = (1 - ((2 * kf) / nf));
    ph = ((pi * (1 + asils.pc.sqrt_(5))) * kf);
    rr = asils.pc.sqrt_((1 - (z * z)));
    r0 = [(rr * cos(ph)); (rr * sin(ph)); z];
    h1 = (asils.models.starcat.star_frac((sin((kf * 12.9898)) * 43758.5453)) - 0.5);
    h2 = (asils.models.starcat.star_frac((sin((kf * 78.233)) * 12345.6789)) - 0.5);
    e1 = [(-(sin(ph))); cos(ph); 0];
    e2 = [r0(2)*e1(3) - r0(3)*e1(2); r0(3)*e1(1) - r0(1)*e1(3); r0(1)*e1(2) - r0(2)*e1(1)];
    dsp = (0.35 * asils.pc.sqrt_(((4 * pi) / nf)));
    v = [(r0(1) + (dsp * ((h1 * e1(1)) + (h2 * e2(1))))); (r0(2) + (dsp * ((h1 * e1(2)) + (h2 * e2(2))))); (r0(3) + (dsp * ((h1 * e1(3)) + (h2 * e2(3)))))];
    r = asils.models.facets.unit_or_zero(v);
    mag = (1 + (5 * asils.models.starcat.star_frac(((kf * asils.pc.sqrt_(2)) + (0.5 * h1)))));
end
