function [q_ref, w_ref, wd_ref] = guidance(kind, r, v, t, q_off, roll_deg, t0, t_slew, axis, q_inertial, sun_axis, roll_axis, sun_eci, flip)
%GUIDANCE  The reference of guidance `kind` (0 nadir, 1 target, 2 slew, 3 inertial, 4 Sun) at time t on the
%   orbit (r, v): the attitude, its rate in the reference frame, and its rate's derivative.
%   kind: int (passed a whole number)
%   r: real[m][3] (passed in m)
%   v: real[m/s][3] (passed in m/s)
%   t: real[s] (passed in s)
%   q_off: real[1][4] (passed a plain number)
%   roll_deg: real[1] (passed a plain number)
%   t0: real[s] (passed in s)
%   t_slew: real[s] (passed in s)
%   axis: real[1][3] (passed a plain number)
%   q_inertial: real[1][4] (passed a plain number)
%   sun_axis: real[1][3] (passed a plain number)
%   roll_axis: real[1][3] (passed a plain number)
%   sun_eci: real[1][3] (passed a plain number)
%   flip: bool (passed true or false)
%   returns q_ref: real[1][4] (passed a plain number)
%   returns w_ref: real[1/s][3] (passed in 1/s)
%   returns wd_ref: real[1/s^2][3] (passed in 1/s^2)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    q_ref = zeros(4, 1);
    w_ref = zeros(3, 1);
    wd_ref = zeros(3, 1);
    rh = asils.pc.unit_(r);
    vh = asils.pc.unit_(v);
    mr = (rh * (-(1)));
    nrm = asils.pc.unit_(asils.pc.cross_(vh, mr));
    ram = asils.pc.unit_(asils.pc.cross_(mr, nrm));
    rr = zeros(3, 3);
    for i = (0):((3) - 1)
        rr(1, (i) + 1) = (-(ram((i) + 1)));
        rr(2, (i) + 1) = (-(rh((i) + 1)));
        rr(3, (i) + 1) = (-(nrm((i) + 1)));
    end
    q_nad = asils.relations.shared.fromdcm(rr);
    if ((((q_off(1) ~= 0) || (q_off(2) ~= 0)) || (q_off(3) ~= 0)) || (q_off(4) ~= 0))
        q_nad = asils.relations.shared.qmult(q_nad, q_off);
    end
    if flip
        u = [1; 0; 0];
        if (asils.pc.norm_(roll_axis) > 0)
            u = asils.pc.unit_(roll_axis);
        end
        q_nad = asils.relations.shared.qmult(q_nad, [u(1); u(2); u(3); 0]);
    end
    w_orb = (asils.pc.cross_(r, v) * (1 / asils.pc.dot_(r, r)));
    wd_ref = zeros(3, 1);
    ax = [1; 0; 0];
    if (asils.pc.norm_(axis) > 0)
        ax = asils.pc.unit_(axis);
    end
    if (kind == 1)
        q_ref = asils.relations.shared.qmult(q_nad, asils.relations.shared.fromrotvec((ax * (roll_deg * (pi / 180)))));
        w_ref = asils.pc.mv(asils.relations.gdn.dcm(q_ref), w_orb);
    elseif (kind == 2)
        tau = asils.pc.clamp(((t - t0) / t_slew), 0, 1);
        sd = 0;
        sdd = 0;
        ph = (roll_deg * (pi / 180));
        if ((t > t0) && (t < (t0 + t_slew)))
            sd = ((1 - cos(((2 * pi) * tau))) / t_slew);
            sdd = (((2 * pi) * sin(((2 * pi) * tau))) / (t_slew * t_slew));
        end
        s = (tau - (sin(((2 * pi) * tau)) / (2 * pi)));
        q_ref = asils.relations.shared.qmult(q_nad, asils.relations.shared.fromrotvec((ax * (ph * s))));
        wo = asils.pc.mv(asils.relations.gdn.dcm(q_ref), w_orb);
        tr = asils.pc.cross_((ax * (ph * sd)), wo);
        for i = (0):((3) - 1)
            w_ref((i) + 1) = (wo((i) + 1) + ((ax((i) + 1) * ph) * sd));
            wd_ref((i) + 1) = (((ax((i) + 1) * ph) * sdd) - tr((i) + 1));
        end
    elseif (kind == 3)
        q_ref = q_inertial;
        w_ref = zeros(3, 1);
    elseif (kind == 4)
        a = [0; 0; (-(1))];
        if (asils.pc.norm_(sun_axis) > 0)
            a = asils.pc.unit_(sun_axis);
        end
        b = [1; 0; 0];
        if (asils.pc.norm_(roll_axis) > 0)
            b = roll_axis;
        end
        ab = asils.pc.dot_(a, b);
        for i = (0):((3) - 1)
            b((i) + 1) = (b((i) + 1) - (ab * a((i) + 1)));
        end
        if (asils.pc.norm_(b) < 0.000001)
            b = [((-(a(2))) * a(1)); (1 - (a(2) * a(2))); ((-(a(2))) * a(3))];
        end
        b = asils.pc.unit_(b);
        s = asils.pc.unit_(sun_eci);
        e2 = zeros(3, 1);
        for i = (0):((3) - 1)
            e2((i) + 1) = (nrm((i) + 1) - (asils.pc.dot_(nrm, s) * s((i) + 1)));
        end
        if (asils.pc.norm_(e2) < 0.000001)
            e2 = [((-(s(3))) * s(1)); ((-(s(3))) * s(2)); (1 - (s(3) * s(3)))];
        end
        e2 = asils.pc.unit_(e2);
        b3 = asils.pc.cross_(a, b);
        e3 = asils.pc.cross_(s, e2);
        m = zeros(3, 3);
        for i = (0):((3) - 1)
            for j = (0):((3) - 1)
                m((i) + 1, (j) + 1) = (((a((i) + 1) * s((j) + 1)) + (b((i) + 1) * e2((j) + 1))) + (b3((i) + 1) * e3((j) + 1)));
            end
        end
        q_ref = asils.relations.shared.fromdcm(m);
        w_ref = zeros(3, 1);
    else
        q_ref = q_nad;
        w_ref = asils.pc.mv(asils.relations.gdn.dcm(q_nad), w_orb);
    end
end
