function [q] = fsw_payload_offset(boresight)
%FSW_PAYLOAD_OFFSET  The payload's offset from the nadir frame the guidance turns by (gd_q_off): the rotation taking +Y_B to the product's
%   payload boresight, the flight software's own boresight_offset (fsw_guidance).
%   boresight: real[1][3] (passed a plain number)
%   returns q: real[1][4] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    q = zeros(4, 1);
    q = asils.models.guidance.boresight_offset(boresight);
end
