function [ju] = fsw_axis_inertia(a, j, u)
%FSW_AXIS_INERTIA  The body's inertia about the body axis b = a u, the unit axis u taken through the attitude matrix a: b'J b.
%   a: real[1][3][3] (passed a plain number)
%   j: real[1][3][3] (passed a plain number)
%   u: real[1][3] (passed a plain number)
%   returns ju: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    ju = 0;
    b = [a(1, 1)*u(1) + a(1, 2)*u(2) + a(1, 3)*u(3); a(2, 1)*u(1) + a(2, 2)*u(2) + a(2, 3)*u(3); a(3, 1)*u(1) + a(3, 2)*u(2) + a(3, 3)*u(3)];
    jb = [j(1, 1)*b(1) + j(1, 2)*b(2) + j(1, 3)*b(3); j(2, 1)*b(1) + j(2, 2)*b(2) + j(2, 3)*b(3); j(3, 1)*b(1) + j(3, 2)*b(2) + j(3, 3)*b(3)];
    ju = (((b(1) * jb(1)) + (b(2) * jb(2))) + (b(3) * jb(3)));
end
