function [ff] = fsw_gg_feedforward(q_off, j)
%FSW_GG_FEEDFORWARD  The gravity-gradient feed-forward of the magnetic pointing states (mtq_gg_ff, when the scenario states none): bit 0 the
%   Sun state, bit 1 the nadir state. In the nadir attitude the flight software's guidance gives (at a reference point of
%   the orbit, 7000 km along x moving at 7.5 km/s along y; the payload offset q_off applied) the gradient restores the
%   attitude only inside the Lagrange region, J_normal >= J_along > J_nadir (equal transverse inertias, a relative 1e-9
%   apart, are neutral, not unstable): there the nadir state keeps the gradient as its spring (1: the Sun state only);
%   outside it the nadir state cancels it too (3).
%   q_off: real[1][4] (passed a plain number)
%   j: real[1][3][3] (passed a plain number)
%   returns ff: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    ff = 0;
    r = [7000000; 0; 0];
    v = [0; 7500; 0];
    z3 = zeros(3, 1);
    q0 = zeros(4, 1);
    [q, w, wd] = asils.models.guidance.guidance(0, r, v, 0, q_off, 0, 0, 0, z3, q0, z3, z3, z3, false);
    a = asils.models.math.dcm(q);
    jz = asils.models.fswbody.fsw_axis_inertia(a, j, [(-(1)); 0; 0]);
    ja = asils.models.fswbody.fsw_axis_inertia(a, j, [0; 1; 0]);
    jn = asils.models.fswbody.fsw_axis_inertia(a, j, [0; 0; 1]);
    ff = 3;
    if ((jn >= (ja * (1 - 1e-9))) && (ja > (jz * (1 + 1e-9))))
        ff = 1;
    end
end
