function [fb] = facet_sum(f, u_b, p)
%FACET_SUM  The body-frame force of one beam of pressure p arriving from u_b (unit, from the spacecraft towards the source, body
%   axes) on the lit facets: an array's normal turned to the beam, a double-sided facet lit from behind flipped.
%   f: ScFacets (passed rec)
%   u_b: real[1][3] (passed a plain number)
%   p: real[1] (passed a plain number)
%   returns fb: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    fb = zeros(3, 1);
    fb = zeros(3, 1);
    for j = (0):((f.nf) - 1)
        n = (f.n((j) + 1, :)).';
        if (f.kind((j) + 1) == fix(2))
            n = asils.models.srp.srp_array_normal((f.axis((j) + 1, :)).', u_b);
        end
        cth = (n(1)*u_b(1) + n(2)*u_b(2) + n(3)*u_b(3));
        if ((f.dbl((j) + 1) == 1) && (cth < 0))
            n = [(-(n(1))); (-(n(2))); (-(n(3)))];
            cth = (-(cth));
        end
        if (~(cth <= 0))
            k = ((p * f.a((j) + 1)) * cth);
            ka = (f.alpha((j) + 1) + f.rho_d((j) + 1));
            kn = (2 * ((f.rho_s((j) + 1) * cth) + (f.rho_d((j) + 1) / 3)));
            for i = (0):((3) - 1)
                fb((i) + 1) = (fb((i) + 1) - (k * ((ka * u_b((i) + 1)) + (kn * n((i) + 1)))));
            end
        end
    end
end
