function s = ScFacets_zero()
%SCFACETS_ZERO  a ScFacets with every field zero
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = struct();
    s.nf = 0;
    s.kind = zeros(16, 1);
    s.n = zeros(16, 3);
    s.a = zeros(16, 1);
    s.alpha = zeros(16, 1);
    s.rho_s = zeros(16, 1);
    s.rho_d = zeros(16, 1);
    s.axis = zeros(16, 3);
    s.dbl = zeros(16, 1);
end
