function [cr] = srp_cr(has_cfg, cfg_cr, has_sc, sc_cr)
%SRP_CR  The cannonball's reflectivity factor forces.srp takes: the force set's when it states one, else the spacecraft's,
%   else 1.3.
%   has_cfg: bool (passed true or false)
%   cfg_cr: real[1] (passed a plain number)
%   has_sc: bool (passed true or false)
%   sc_cr: real[1] (passed a plain number)
%   returns cr: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    cr = 0;
    if has_cfg
        cr = cfg_cr;
    elseif has_sc
        cr = sc_cr;
    else
        cr = 1.3;
    end
end
