function [g] = srp_add_array(f, a, axis, alpha, rho_s, rho_d)
%SRP_ADD_ARRAY  srp.addArray(F, A, axis, opt): one double-sided solar array of area a turning about axis.
%   f: ScFacets (passed rec)
%   a: real[1] (passed a plain number)
%   axis: real[1][3] (passed a plain number)
%   alpha: real[1] (passed a plain number)
%   rho_s: real[1] (passed a plain number)
%   rho_d: real[1] (passed a plain number)
%   returns g: ScFacets (passed rec)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    g = asils.models.srp.ScFacets_zero();
    g = asils.models.srp.facet_add(f, 2, [0; 0; 0], a, alpha, rho_s, rho_d, axis, true);
end
