function [nrm] = srp_array_normal(axis, s_hat_b)
%SRP_ARRAY_NORMAL  srp.arrayNormal(axis, sHat_b): the best-lit normal of an array turning about axis, towards s_hat_b (body frame).
%   axis: real[1][3] (passed a plain number)
%   s_hat_b: real[1][3] (passed a plain number)
%   returns nrm: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    nrm = zeros(3, 1);
    na = sqrt(axis(1)*axis(1) + axis(2)*axis(2) + axis(3)*axis(3));
    ax = [(axis(1) / na); (axis(2) / na); (axis(3) / na)];
    sa = (s_hat_b(1)*ax(1) + s_hat_b(2)*ax(2) + s_hat_b(3)*ax(3));
    proj = [(s_hat_b(1) - (sa * ax(1))); (s_hat_b(2) - (sa * ax(2))); (s_hat_b(3) - (sa * ax(3)))];
    if (sqrt(proj(1)*proj(1) + proj(2)*proj(2) + proj(3)*proj(3)) < 1e-9)
        t = [1; 0; 0];
        h__477 = ax(1);
        if h__477 < 0, h__477 = -h__477; elseif h__477 == 0, h__477 = 0; end
        if (h__477 > 0.9)
            t = [0; 1; 0];
        end
        ta = (t(1)*ax(1) + t(2)*ax(2) + t(3)*ax(3));
        proj = [(t(1) - (ta * ax(1))); (t(2) - (ta * ax(2))); (t(3) - (ta * ax(3)))];
    end
    np = sqrt(proj(1)*proj(1) + proj(2)*proj(2) + proj(3)*proj(3));
    nrm = [(proj(1) / np); (proj(2) / np); (proj(3) / np)];
end
