function [p] = earth_ir_pressure(r)
%EARTH_IR_PRESSURE  The infrared pressure [N/m^2] at the inertial position r.
%   r: real[m][3] (passed in m)
%   returns p: real[Pa] (passed in kg/(m s^2))
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    p = 0;
    rn = sqrt(r(1)*r(1) + r(2)*r(2) + r(3)*r(3));
    vf = ((6378137 / rn) * (6378137 / rn));
    p = ((237 / 299792458) * vf);
end
