function [tau] = aero_torque(rho, v, c_d, a_fr, c_pa)
%AERO_TORQUE  The aerodynamic torque: tau = 1/2 rho v^2 C_D A c_pa.
%   rho: real[kg/m^3] (passed in kg/m^3)
%   v: real[m/s] (passed in m/s)
%   c_d: real[1] (passed a plain number)
%   a_fr: real[m^2] (passed in m^2)
%   c_pa: real[m] (passed in m)
%   returns tau: real[N m] (passed in m^2 kg/s^2)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    tau = 0;
    tau = (((((0.5 * rho) * asils.pc.ipow(v, 2)) * c_d) * a_fr) * c_pa);
end
