function [p] = coil_power(a, m_max, p_max)
%COIL_POWER  The power [W] of a coil whose dipole averaged a over the step, of largest dipole m_max drawing p_max there.
%   a: real[1] (passed a plain number)
%   m_max: real[1] (passed a plain number)
%   p_max: real[1] (passed a plain number)
%   returns p: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    p = 0;
    h__2 = a;
    if h__2 < 0, h__2 = -h__2; elseif h__2 == 0, h__2 = 0; end
    p = ((h__2 / m_max) * p_max);
end
