function [ok, rec, nc] = de440_record(seg, et)
%DE440_RECORD  The record of a segment that covers et, from env's slice, chosen as de440.state chooses it (floor((et - INIT) /
%   INTLEN), held to the segment's records); ok is false when the slice does not hold it.
%   seg: DeSegment (passed a choice, as its option's number)
%   et: real[1] (passed a plain number)
%   returns ok: bool (passed true or false)
%   returns rec: real[1][DE_REC] (passed a plain number)
%   returns nc: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    ok = false;
    rec = zeros(62, 1);
    nc = 0;
    D__DE440_EARTH = asils.models.de440slice.DE440_EARTH();
    D__DE440_EMB = asils.models.de440slice.DE440_EMB();
    D__DE440_MOON = asils.models.de440slice.DE440_MOON();
    D__DE440_SEGMENTS = asils.models.de440slice.DE440_SEGMENTS();
    D__DE440_SUN = asils.models.de440slice.DE440_SUN();
    s = fix(seg);
    init = D__DE440_SEGMENTS((s) + 1, 3);
    intlen = D__DE440_SEGMENTS((s) + 1, 4);
    rsize = fix(D__DE440_SEGMENTS((s) + 1, 5));
    nc = fix(D__DE440_SEGMENTS((s) + 1, 6));
    n = D__DE440_SEGMENTS((s) + 1, 7);
    kf = floor(((et - init) / intlen));
    if (~(kf >= 0))
        kf = 0;
    end
    if (kf > (n - 1))
        kf = (n - 1);
    end
    j = (fix(kf) - fix(D__DE440_SEGMENTS((s) + 1, 8)));
    ok = ((j >= 0) && (j < fix(D__DE440_SEGMENTS((s) + 1, 9))));
    rec = zeros(62, 1);
    if ok
        i = ((0):((rsize) - 1)).';
        if ~isempty(i)
            if (seg == 0)
                rec((i) + 1) = (D__DE440_SUN((j) + 1, (i) + 1)).';
            elseif (seg == 1)
                rec((i) + 1) = (D__DE440_EMB((j) + 1, (i) + 1)).';
            elseif (seg == 2)
                rec((i) + 1) = (D__DE440_EARTH((j) + 1, (i) + 1)).';
            else
                rec((i) + 1) = (D__DE440_MOON((j) + 1, (i) + 1)).';
            end
        end
    end
end
