function [o, u] = mag_sample(u, d, b_body, m_coil)
%MAG_SAMPLE  The field the magnetometer reads [T] for the body field b_body [T] with the coils' body dipole m_coil [A m^2].
%   u: inout MagUnit (passed rec)
%   d: MagDesc (passed rec)
%   b_body: real[1][3] (passed a plain number)
%   m_coil: real[1][3] (passed a plain number)
%   returns o: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    o = zeros(3, 1);
    o = [1e-9; 0; 0];
    if (~u.dead)
        g = u.g;
        [t__603, t__604] = asils.models.magnoise.mag_noise([u.m(1, 1)*b_body(1) + u.m(1, 2)*b_body(2) + u.m(1, 3)*b_body(3); u.m(2, 1)*b_body(1) + u.m(2, 2)*b_body(2) + u.m(2, 3)*b_body(3); u.m(3, 1)*b_body(1) + u.m(3, 2)*b_body(2) + u.m(3, 3)*b_body(3)], u.b, d.noise, d.k_coil, m_coil, g);
        v = t__603;
        g = t__604;
        u.g = g;
        for i = (0):((3) - 1)
            o((i) + 1) = asils.models.coilsat.act_clamp(v((i) + 1), (-(d.range)), d.range);
        end
    end
end
