function [tau] = torque_authority(m_av, b_min, n_mtq)
%TORQUE_AUTHORITY  The torque the coils give about the worst axis: m B_min min(n, 3)/3 (fewer than three coils
%   leave axes without authority).
%   m_av: real[A m^2] (passed in m^2 A)
%   b_min: real[T] (passed in kg/(s^2 A))
%   n_mtq: int (passed a whole number)
%   returns tau: real[N m] (passed in m^2 kg/s^2)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    tau = 0;
    h__15 = n_mtq;
    h__16 = 3;
    if h__16 < h__15, h__15 = h__16; end
    tau = (((m_av * b_min) * h__15) / 3);
end
