function [d] = sun_distance_au(t_epoch)
%SUN_DISTANCE_AU  The Earth-Sun distance in AU at a time from J2000.0 (Vallado 2013, algorithm 29).
%   t_epoch: real[yr] (passed in s)
%   returns d: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    d = 0;
    tc = (t_epoch / 3155760000);
    m = ((357.5291092 + (35999.05034 * tc)) * 0.017453292519943295);
    d = ((1.000140612 - (0.016708617 * cos(m))) - (0.000139589 * cos((2 * m))));
end
