function dev = load(productId)
%ASILS.PRODUCT.LOAD  A catalogue product -> the device parameter block P.dev.
%   Reads data/products/<id>.json and every part it fills from data/parts/.
%   A slot the product does not fill is marked fitted = false.
    R = asils.util.root();
    pr = asils.util.readjson(fullfile(R, 'data', 'products', [productId '.json']));
    fills = pr.fill; if ~iscell(fills), fills = num2cell(fills); end
    dev = struct('id', pr.id, 'label', pr.label, 'algorithms', {pr.algorithms});
    dev.boresight = [0;1;0];
    if isfield(pr, 'payload_boresight_body'), dev.boresight = pr.payload_boresight_body(:)/norm(pr.payload_boresight_body); end
    dev.gyro.fitted = false; dev.mag.fitted = false; dev.sun.fitted = false;
    dev.st.fitted = false; dev.mtq.fitted = false; dev.rw.fitted = false; dev.gps.fitted = false;
    for i = 1:numel(fills)
        f = fills{i};
        p = asils.util.readjson(fullfile(R, 'data', 'parts', [f.part '.json']));
        nm = p.nominal; ds = asils.util.getf(p, 'dispersion', struct());
        sig = @(key, d) sigma_(ds, key, d);
        switch f.slot
            case 'coils'
                dev.mtq = struct('fitted', true, 'part', f.part, 'axes', axes_(f.axes_body), ...
                    'm_max', nm.dipole_max_Am2, 'p_max', nm.power_at_max_W, ...
                    'scale_sigma', sig('dipole_scale', 0), 'misalign_rad', sig('axis_misalignment_rad', 0));
            case 'wheels'
                dev.rw = struct('fitted', true, 'part', f.part, 'axes', axes_(f.axes_body), ...
                    'h_max', nm.h_max_Nms, 'torque_max', nm.torque_max_Nm, 'J', nm.rotor_inertia_kgm2, ...
                    'coulomb', nm.friction_coulomb_Nm, 'viscous', nm.friction_viscous_Nms, ...
                    'torque_noise', 0.001, 'friction_comp', 0.95, 'eta', 0.8, 'p_steady', nm.power_steady_W, ...
                    'torque_scale_sigma', sig('torque_scale', 0), ...
                    'friction_scale_lo', ds.friction_scale.lo, 'friction_scale_hi', ds.friction_scale.hi, ...
                    'misalign_rad', sig('axis_misalignment_rad', 0));
            case 'star_tracker'
                if isfield(f, 'boresights_body'), bs = axes_(f.boresights_body); else, bs = axes_(f.boresight_body(:)'); end
                dev.st = struct('fitted', true, 'part', f.part, 'boresight', bs, ...
                    'noise_cross', nm.noise_cross_rad, 'noise_roll', nm.noise_roll_rad, ...
                    'rate_hz', nm.rate_Hz, 'latency', nm.latency_s, 'max_rate', nm.max_rate_rad_s, ...
                    'sun_excl', nm.sun_exclusion_rad, 'earth_excl', nm.earth_exclusion_rad, ...
                    'bias_sigma', sig('bias_rad', 0), 'misalign_sigma', sig('axis_misalignment_rad', 0), ...
                    'power', nm.power_W);
                if isfield(f, 'calibrated_residual_rad')     % in-orbit alignment calibration
                    dev.st.bias_sigma = f.calibrated_residual_rad; dev.st.misalign_sigma = 0;
                end
            case 'magnetometer'
                dev.mag = struct('fitted', true, 'part', f.part, 'noise', nm.noise_T_rms, ...
                    'bias_T', nm.bias_T, 'bias_sigma', sig('bias_T', 0), 'range', nm.range_T, ...
                    'rate_hz', nm.rate_Hz, 'sf_sigma', sig('scale_factor', 0), ...
                    'misalign_rad', sig('axis_misalignment_rad', 0), 'k_coil', 5e-6);
            case 'sun_sensors'
                dev.sun = struct('fitted', true, 'part', f.part, 'normals', axes_(f.normals_body), ...
                    'noise', nm.accuracy_rad, 'fov_rad', nm.fov_half_angle_rad, 'rate_hz', nm.rate_Hz, ...
                    'bias_sigma', sig('bias_rad', 0));
            case 'gyro'
                dev.gyro = struct('fitted', true, 'part', f.part, 'arw', nm.arw_rad_per_sqrt_s, ...
                    'rrw', nm.rrw_rad_per_s_sqrt_s, 'range', nm.range_rad_s, 'rate_hz', nm.rate_Hz, ...
                    'bias_sigma', sig('bias_rad_s', 0), 'sf_sigma', sig('scale_factor', 0), ...
                    'misalign_rad', sig('axis_misalignment_rad', 0));
            case 'gnss'
                dev.gps = struct('fitted', true, 'part', f.part, 'pos_sigma', nm.pos_sigma_m, ...
                    'vel_sigma', nm.vel_sigma_m_s, 'rate_hz', nm.rate_Hz);
        end
    end
end
function A = axes_(a)
    if iscell(a), a = cell2mat(cellfun(@(x) x(:)', a, 'UniformOutput', false)); end
    A = a';                                   % 3 x n
    for j = 1:size(A,2), A(:,j) = A(:,j)/norm(A(:,j)); end
end
function s = sigma_(ds, key, d)
    s = d;
    if isfield(ds, key) && isfield(ds.(key), 'sigma'), s = ds.(key).sigma; end
end
