function [zhat, e1, e2, shat, rho_max] = cap_frame(r_sat, r_sun)
%CAP_FRAME  The frame of the visible cap seen from r_sat: the zenith, two directions across it, the Sun's direction from the
%   Earth (the Sun at r_sun) and the cap's angular radius.
%   r_sat: real[1][3] (passed a plain number)
%   r_sun: real[1][3] (passed a plain number)
%   returns zhat: real[1][3] (passed a plain number)
%   returns e1: real[1][3] (passed a plain number)
%   returns e2: real[1][3] (passed a plain number)
%   returns shat: real[1][3] (passed a plain number)
%   returns rho_max: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    zhat = zeros(3, 1);
    e1 = zeros(3, 1);
    e2 = zeros(3, 1);
    shat = zeros(3, 1);
    rho_max = 0;
    re = getfield(asils.models.de440.de440_constants(), 're_earth');
    d = asils.pc.norm_(r_sat);
    zhat = [(r_sat(1) / d); (r_sat(2) / d); (r_sat(3) / d)];
    ns = asils.pc.norm_(r_sun);
    shat = [(r_sun(1) / ns); (r_sun(2) / ns); (r_sun(3) / ns)];
    rho_max = asils.pc.acos_(asils.models.srp.min_one((re / d)));
    t = [1; 0; 0];
    if (asils.pc.fabs(zhat(1)) > 0.9)
        t = [0; 1; 0];
    end
    c = asils.pc.cross_(zhat, t);
    n1 = asils.pc.norm_(c);
    e1 = [(c(1) / n1); (c(2) / n1); (c(3) / n1)];
    e2 = asils.pc.cross_(zhat, e1);
end
