function [t, disp] = couple_axis(tau, sigma, disp)
%COUPLE_AXIS  The couple's torque tau turned by its misalignment (sigma [rad]), drawn from disp.
%   tau: real[N m][3] (passed in m^2 kg/s^2)
%   sigma: real[1] (passed a plain number)
%   disp: inout stream (passed a random stream, as six numbers)
%   returns t: real[N m][3] (passed in m^2 kg/s^2)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    t = zeros(3, 1);
    [t__7, t__8] = asils.pc.stream_normal3(disp);
    th = t__7;
    disp = t__8;
    h__4 = asils.models.coildisp.small_rotation((th * sigma));
    t = [h__4(1, 1)*tau(1) + h__4(1, 2)*tau(2) + h__4(1, 3)*tau(3); h__4(2, 1)*tau(1) + h__4(2, 2)*tau(2) + h__4(2, 3)*tau(3); h__4(3, 1)*tau(1) + h__4(3, 2)*tau(2) + h__4(3, 3)*tau(3)];
end
