#!/usr/bin/env python3
"""The explanation kit: the one copy of the CSS and script that every HTML page
uses to follow the explanation standard adcs-explain/1 (SPEC.md §5.12).

    python3 tools/explain_kit.py --write   put the kit into every template
    python3 tools/explain_kit.py --check   exit 1 if any template's copy differs

Every template is a single self-contained file (it must open from disk, offline,
with no second file), so each carries its own copy of the kit between the
markers below. This module is the source; the copies are generated, and CI
fails when one drifts.

What the kit gives a page:

* the depth switch, Learn · Read · Expert (E03). Content marked
  data-show="learn read" is shown only at those depths. The reader's choice is
  remembered in this browser when the browser allows it, and the page works when
  it does not;
* the four kind badges, tutorial, how-to, reference and explanation (E02);
* claim chips, sourced [n], derived, reference and example (E18);
* the station labels, Say it simply, Now the real thing, Where the simple
  version breaks, Try it (E10);
* the boxes for the answer (E01), a common wrong idea (E13), an analogy and
  where it breaks (E14), a why-chain (E15), and where the page breaks (E20);
* window.ADCS_EXPLAIN, for pages drawn by script: badge(kind), claim(type,
  label, href), station(step), state(ok, word).
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATES = [
    "forms/node_form.html",
    "forms/case_editor.html",
    "forms/library.html",
    "results/template.html",
]

CSS_BEGIN, CSS_END = "/* explain-kit:css:begin (generated by tools/explain_kit.py; do not edit here) */", "/* explain-kit:css:end */"
JS_BEGIN, JS_END = "/* explain-kit:js:begin (generated by tools/explain_kit.py; do not edit here) */", "/* explain-kit:js:end */"

CSS = r"""
.xk-depth { display: inline-flex; border: 1px solid var(--line-2, #c3c2b7); border-radius: 8px; overflow: hidden; }
.xk-depth button { border: 0; border-radius: 0; padding: 5px 10px; font-size: 12px; background: var(--raised); color: var(--ink-2); }
.xk-depth button + button { border-left: 1px solid var(--line-2, #c3c2b7); }
.xk-depth button[aria-pressed="true"] { background: var(--accent); color: #fff; }
body[data-depth="learn"] [data-show]:not([data-show~="learn"]),
body[data-depth="read"] [data-show]:not([data-show~="read"]),
body[data-depth="expert"] [data-show]:not([data-show~="expert"]) { display: none !important; }
.xk-kind { display: inline-block; font-size: 10.5px; font-weight: 700; letter-spacing: .06em; text-transform: uppercase;
  padding: 1px 7px; border-radius: 5px; border: 1px solid var(--line-2, #c3c2b7); color: var(--ink-2); vertical-align: 2px; margin-left: 8px; white-space: nowrap; }
.xk-kind::before { margin-right: 4px; font-weight: 400; }
.xk-kind[data-k="tutorial"]::before { content: "\25B6"; }
.xk-kind[data-k="how-to"]::before { content: "\2192"; }
.xk-kind[data-k="reference"]::before { content: "\2261"; }
.xk-kind[data-k="explanation"]::before { content: "?"; }
.xk-claim { display: inline-block; font-size: 11px; line-height: 1.4; padding: 0 6px; border-radius: 4px; margin: 0 2px;
  border: 1px solid var(--line-2, #c3c2b7); color: var(--ink-2); text-decoration: none; overflow-wrap: anywhere; max-width: 100%; vertical-align: 1px; }
.xk-claim[data-claim="sourced"] { color: var(--accent-ink); border-color: var(--accent); }
.xk-claim[data-claim="example"] { border-style: dashed; }
.xk-answer { font-size: 17px; line-height: 1.45; margin: 4px 0 14px; padding: 12px 14px; border-radius: 10px;
  background: var(--raised); border: 1px solid var(--line); border-left: 4px solid var(--accent); }
.xk-crumbs { font-size: 12px; color: var(--ink-2); margin: 0 0 8px; display: flex; flex-wrap: wrap; gap: 4px; align-items: center; }
.xk-crumbs span + span::before { content: "\203A"; margin: 0 6px 0 2px; color: var(--muted); }
.xk-crumbs span:last-child { color: var(--ink); font-weight: 600; }
.xk-step { font-size: 11px; font-weight: 700; letter-spacing: .05em; text-transform: uppercase; color: var(--muted); margin: 14px 0 4px; display: flex; gap: 8px; align-items: center; }
.xk-step b { display: inline-grid; place-items: center; width: 20px; height: 20px; border-radius: 50%; background: var(--accent-soft); color: var(--accent-ink); font-size: 11px; }
.xk-box { border: 1px solid var(--line); border-radius: 10px; padding: 10px 12px; margin: 8px 0; background: var(--raised); font-size: 14px; }
.xk-box > .xk-h { font-size: 12px; font-weight: 700; color: var(--ink-2); margin-bottom: 3px; }
.xk-box.wrong { border-left: 4px solid var(--bad, #d03b3b); }
.xk-box.analogy { border-left: 4px solid var(--accent); }
.xk-box.breaks { border-left: 4px solid var(--warn-ink, #7a5300); }
.xk-box.try { border-left: 4px solid var(--good, #0ca30c); }
.xk-box [data-explain="analogy-breaks"], .xk-box [data-explain="because"] { margin-top: 6px; }
.xk-why { margin: 6px 0; padding-left: 18px; }
.xk-why li { margin: 2px 0; }
.xk-why li:last-child { font-weight: 600; }
.xk-state { display: inline-flex; gap: 5px; align-items: center; font-weight: 600; }
.xk-state[data-state="ok"] { color: var(--good-ink, #006300); }
.xk-state[data-state="bad"] { color: var(--bad, #d03b3b); }
.xk-state[data-state="warn"] { color: var(--warn-ink, #7a5300); }
.xk-state[data-state="none"] { color: var(--ink-2); }
.xk-reveal { margin-top: 6px; }
.xk-reveal[hidden] { display: none; }
@media print { .xk-depth { display: none !important; } body [data-show] { display: revert !important; } }
"""

JS = r"""
(function () {
  "use strict";
  var KINDS = { "tutorial": "Tutorial", "how-to": "How-to", "reference": "Reference", "explanation": "Explanation" };
  var DEPTHS = [["learn", "Learn", "Every exercise, answers hidden until you try"],
                ["read", "Read", "The answer, the explanation and the pictures"],
                ["expert", "Expert", "The answer, the relation, the limits and the sources"]];
  var KEY = "adcs-explain-depth";
  function get() { try { return localStorage.getItem(KEY); } catch (e) { return null; } }
  function put(v) { try { localStorage.setItem(KEY, v); } catch (e) { /* the page works without it */ } }
  function setDepth(d) {
    if (!DEPTHS.some(function (x) { return x[0] === d; })) d = "read";
    document.body.setAttribute("data-depth", d);
    Array.prototype.forEach.call(document.querySelectorAll("[data-depth-switch] button"), function (b) {
      b.setAttribute("aria-pressed", b.getAttribute("data-d") === d ? "true" : "false");
    });
  }
  function mountSwitch(host) {
    var box = document.createElement("div");
    box.className = "xk-depth"; box.setAttribute("data-depth-switch", ""); box.setAttribute("role", "group");
    box.setAttribute("aria-label", "How much to show");
    DEPTHS.forEach(function (x) {
      var b = document.createElement("button");
      b.type = "button"; b.textContent = x[1]; b.title = x[2]; b.setAttribute("data-d", x[0]);
      b.addEventListener("click", function () { setDepth(x[0]); put(x[0]); });
      box.appendChild(b);
    });
    host.appendChild(box);
    return box;
  }
  function badge(kind) {
    var s = document.createElement("span");
    s.className = "xk-kind"; s.setAttribute("data-k", kind); s.textContent = KINDS[kind] || kind;
    s.title = { "tutorial": "Learn by doing it once", "how-to": "Do one task", "reference": "Look something up",
                "explanation": "Understand why" }[kind] || "";
    return s;
  }
  function claim(type, label, href) {
    var a = document.createElement(href ? "a" : "span");
    a.className = "xk-claim"; a.setAttribute("data-claim", type);
    if (href) a.setAttribute("href", href);
    a.textContent = label || type;
    a.title = { "sourced": "Stated in the cited source", "derived": "Worked here from sourced relations",
                "reference": "The reference case's value, unconfirmed until a person confirms it",
                "example": "A demonstration or a made-up number" }[type] || "";
    return a;
  }
  function station(step, n) {
    var names = { simply: "Say it simply", real: "Now the real thing", breaks: "Where the simple version breaks", "try": "Try it" };
    var d = document.createElement("div");
    d.className = "xk-step"; d.setAttribute("data-step", step);
    var b = document.createElement("b"); b.textContent = String(n || ({ simply: 1, real: 2, breaks: 3, "try": 4 })[step]);
    d.appendChild(b); d.appendChild(document.createTextNode(names[step] || step));
    return d;
  }
  function state(kind, word) {
    var s = document.createElement("span");
    s.className = "xk-state"; s.setAttribute("data-state", kind);
    var i = document.createElement("span"); i.setAttribute("aria-hidden", "true");
    i.textContent = { ok: "✔", bad: "✖", warn: "!", none: "–" }[kind] || "•";
    s.appendChild(i); s.appendChild(document.createTextNode(word));
    return s;
  }
  window.ADCS_EXPLAIN = { badge: badge, claim: claim, station: station, state: state, setDepth: setDepth, mountSwitch: mountSwitch };
  function start() {
    Array.prototype.forEach.call(document.querySelectorAll("[data-depth-host]"), function (h) { if (!h.querySelector("[data-depth-switch]")) mountSwitch(h); });
    Array.prototype.forEach.call(document.querySelectorAll("[data-kind]"), function (sec) {
      var h = sec.querySelector("h2, h3");
      if (h && !h.querySelector(".xk-kind")) h.appendChild(badge(sec.getAttribute("data-kind")));
    });
    setDepth(document.body.getAttribute("data-depth") || get() || "read");
  }
  window.ADCS_EXPLAIN.start = start;
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", start); else start();
})();
"""


def block(begin, body, end):
    return begin + "\n" + body.strip("\n") + "\n" + end


def apply(text):
    """The template's text with the kit's two blocks replaced (or inserted)."""
    css = block(CSS_BEGIN, CSS, CSS_END)
    js = block(JS_BEGIN, JS, JS_END)
    if CSS_BEGIN in text:
        text = re.sub(re.escape(CSS_BEGIN) + r".*?" + re.escape(CSS_END), lambda m: css, text, count=1, flags=re.S)
    else:
        i = text.index("</style>")
        text = text[:i] + css + "\n" + text[i:]
    if JS_BEGIN in text:
        text = re.sub(re.escape(JS_BEGIN) + r".*?" + re.escape(JS_END), lambda m: js, text, count=1, flags=re.S)
    else:
        i = text.index("</head>")
        text = text[:i] + "<script>\n" + js + "\n</script>\n" + text[i:]
    return text


def page_head():
    """The kit for a page a tool writes whole (the quarterly narrative)."""
    return block(CSS_BEGIN, CSS, CSS_END), block(JS_BEGIN, JS, JS_END)


def main():
    args = sys.argv[1:]
    if args not in (["--write"], ["--check"]):
        print(__doc__)
        return 2
    stale = []
    for rel in TEMPLATES:
        p = os.path.join(ROOT, rel)
        text = open(p, encoding="utf-8").read()
        new = apply(text)
        if new != text:
            if args == ["--write"]:
                open(p, "w", encoding="utf-8").write(new)
                print("wrote the kit into %s" % rel)
            else:
                stale.append(rel)
    if stale:
        print("STALE: %s — run python3 tools/explain_kit.py --write" % ", ".join(stale))
        return 1
    if args == ["--check"]:
        print("the explanation kit is current in %d templates" % len(TEMPLATES))
    return 0


if __name__ == "__main__":
    sys.exit(main())
