function [m] = coil_dipole(pwm, m_max, s)
%COIL_DIPOLE  The coils' dipole (body) from the flight software's PWM words, each a fraction of m_max.
%   pwm: int[3] (passed a whole number)
%   m_max: real[A m^2] (passed in m^2 A)
%   s: EmuScale (passed rec)
%   returns m: real[A m^2][3] (passed in m^2 A)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    m = zeros(3, 1);
    m = zeros(3, 1);
    for i = (0):((3) - 1)
        m((i) + 1) = ((pwm((i) + 1) / s.word) * m_max);
    end
end
