function [c] = emu_count(x, lo, hi)
%EMU_COUNT  The counts of x (in counts, not yet whole) in a field from lo to hi: held to the range, rounded half away from zero;
%   a value that is not a number gives none.
%   x: real[1] (passed a plain number)
%   lo: real[1] (passed a plain number)
%   hi: real[1] (passed a plain number)
%   returns c: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    c = 0;
    c = 0;
    if (~isnan(x))
        h__644 = x;
        h__645 = lo;
        if h__645 > h__644, h__644 = h__645; end
        h__645 = hi;
        if h__645 < h__644, h__644 = h__645; end
        c = fix(round(h__644));
    end
end
