function [c] = quat_counts(q, s)
%QUAT_COUNTS  A star-tracker head's quaternion q (ECI to body, scalar last) as its frame's counts (Q30).
%   q: real[1][4] (passed a plain number)
%   s: EmuScale (passed rec)
%   returns c: int[4] (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    c = zeros(4, 1);
    c = zeros(4, 1);
    for k = (0):((4) - 1)
        c((k) + 1) = asils.models.emucodec.emu_count((q((k) + 1) / s.q), s.lo32, s.hi32);
    end
end
