function [v] = rd16(b0, b1)
%RD16  A little-endian signed 16-bit field.
%   b0: int (passed a whole number)
%   b1: int (passed a whole number)
%   returns v: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    v = 0;
    v = (b0 + (256 * b1));
    if (v >= 32768)
        v = (v - 65536);
    end
end
