function [st, st_len, gps, gps_len] = read_streams(st_junk, st_nj, st_pl, st_n, st_fault, st_k, gps_junk, gps_nj, gps_pl, gps_n, gps_fault, gps_k)
%READ_STREAMS  Test streams for a read: one for the star tracker, one for the GNSS receiver.
%   st_junk: int[8] (passed a whole number)
%   st_nj: int (passed a whole number)
%   st_pl: int[36] (passed a whole number)
%   st_n: int (passed a whole number)
%   st_fault: int (passed a whole number)
%   st_k: int (passed a whole number)
%   gps_junk: int[8] (passed a whole number)
%   gps_nj: int (passed a whole number)
%   gps_pl: int[36] (passed a whole number)
%   gps_n: int (passed a whole number)
%   gps_fault: int (passed a whole number)
%   gps_k: int (passed a whole number)
%   returns st: int[96] (passed a whole number)
%   returns st_len: int (passed a whole number)
%   returns gps: int[96] (passed a whole number)
%   returns gps_len: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    st = zeros(96, 1);
    st_len = 0;
    gps = zeros(96, 1);
    gps_len = 0;
    [t__427, t__428] = asils.models.drivers.uart_stream(st_junk, st_nj, st_pl, st_n, 144, st_fault, st_k);
    st = t__427;
    st_len = t__428;
    [t__429, t__430] = asils.models.drivers.uart_stream(gps_junk, gps_nj, gps_pl, gps_n, 145, gps_fault, gps_k);
    gps = t__429;
    gps_len = t__430;
end
