function [payload, n_found] = uart_frame(b, len, sync2)
%UART_FRAME  The newest complete frame with the second sync byte sync2 in a UART byte stream (EB sync2 n
%   payload CRC-16 lo hi): the payload and its length, or -1 when none is whole and checks. The
%   driver keeps the bytes of a frame not yet whole for its next read; a stream here is one read.
%   vectors: 24
%   inputs from: uart_stream
%   b: int[96] (passed a whole number)
%   len: int (passed a whole number)
%   sync2: int (passed a whole number)
%   returns payload: int[64] (passed a whole number)
%   returns n_found: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    payload = zeros(64, 1);
    n_found = 0;
    payload = zeros(64, 1);
    n_found = (-(1));
    base = 0;
    done = false;
    for pass = (0):((48) - 1)
        if (~done)
            s = 0;
            for k = (0):((96) - 1)
                if ((((base + s) + 1) < len) && (~((b(((base + s)) + 1) == 235) && (b((((base + s) + 1)) + 1) == sync2))))
                    s = (s + 1);
                end
            end
            if (((base + s) + 3) > len)
                done = true;
            else
                n = b((((base + s) + 2)) + 1);
                if (((((base + s) + 3) + n) + 2) > len)
                    done = true;
                else
                    pl = zeros(64, 1);
                    crc_in = zeros(64, 1);
                    i = ((0):((asils.pc.fmin(n, 64)) - 1)).';
                    if ~isempty(i)
                        crc_in((i) + 1) = reshape(b(((((base + s) + 3) + i)) + 1), [], 1);
                    end
                    if ((n <= 64) && (asils.models.drivers.crc16(crc_in, n) == bitor(b(((((base + s) + 3) + n)) + 1), bitshift(b(((((base + s) + 4) + n)) + 1), 8))))
                        i = ((0):((n) - 1)).';
                        if ~isempty(i)
                            pl((i) + 1) = reshape(b(((((base + s) + 3) + i)) + 1), [], 1);
                        end
                        payload = pl;
                        n_found = n;
                    end
                    base = (((base + s) + 5) + n);
                end
            end
        end
    end
end
