function [gh] = igrf_gh(dy)
%IGRF_GH  The Gauss coefficients at a decimal year: straight-line between the two epochs around it,
%   extrapolated from the last interval.
%   dy: real[1] (passed a plain number)
%   returns gh: real[1][195] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    gh = zeros(195, 1);
    D__IGRF_GH = asils.models.igrf13.IGRF_GH();
    D__IGRF_YEAR = asils.models.igrf13.IGRF_YEAR();
    i = 0;
    t__514 = ((0):((25) - 1)).';
    for ii = t__514(logical((D__IGRF_YEAR(((t__514 + 1)) + 1) <= dy))).'
        i = (ii + 1);
    end
    if (i >= 25)
        i = 24;
    end
    f = ((dy - D__IGRF_YEAR((i) + 1)) / (D__IGRF_YEAR(((i + 1)) + 1) - D__IGRF_YEAR((i) + 1)));
    k = ((0):((195) - 1)).';
    gh((k) + 1) = ((D__IGRF_GH((i) + 1, (k) + 1)).' + (((D__IGRF_GH(((i + 1)) + 1, (k) + 1)).' - (D__IGRF_GH((i) + 1, (k) + 1)).') .* f));
end
