function v = TIDAL_PM_LIBRATION(varargin)
%TIDAL_PM_LIBRATION  TIDAL_PM_LIBRATION: IERS Conventions (2010), chapters 5 and 8 (Petit and Luzum, IERS Technical Note 36) and their software: ORTHO_EOP and CNMTX (Ray 1994 ocean tides), PMSDNUT2 and UTLIBR (Brzezinski), RG_ZONT2 (table 8.1); as the Octave POP's ports
%   read by tools/readers.py (matlab_matrix) from matlab_sils/pop/03_frames_time/tidal_eop_models/tidal_pm_libration.m (sha256 1c951c6e292f6a58), the developer's revision S7.2b
%   data: real[1][11][10]; SI: a plain number
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    persistent T
    if isempty(T)
        T = [
            1, -1, 0, -2, 0, -1, 1.1196992, -0.4, 0.3, -0.3, -0.4
            1, -1, 0, -2, 0, -2, 1.1195149, -2.3, 1.3, -1.3, -2.3
            1, 1, 0, -2, -2, -2, 1.1134606, -0.4, 0.3, -0.3, -0.4
            1, 0, 0, -2, 0, -1, 1.0759762, -2.1, 1.2, -1.2, -2.1
            1, 0, 0, -2, 0, -2, 1.0758059, -11.4, 6.5, -6.5, -11.4
            1, -1, 0, 0, 0, 0, 1.0347187, 0.8, -0.5, 0.5, 0.8
            1, 0, 0, -2, 2, -2, 1.0027454, -4.8, 2.7, -2.7, -4.8
            1, 0, 0, 0, 0, 0, 0.9972696, 14.3, -8.2, 8.2, 14.3
            1, 0, 0, 0, 0, -1, 0.9971233, 1.9, -1.1, 1.1, 1.9
            1, 1, 0, 0, 0, 0, 0.9624365, 0.8, -0.4, 0.4, 0.8
        ];
    end
    if nargin == 0, v = T; else, v = T(varargin{:}); end
end
