function [raan] = ltan_raan(sun, ltan_h)
%LTAN_RAAN  The RAAN [rad], in [0, 2 pi), of an orbit whose ascending node is at local time ltan_h [h], the Sun at sun
%   (geocentric, J2000).
%   sun: real[m][3] (passed in m)
%   ltan_h: real[1] (passed a plain number)
%   returns raan: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    raan = 0;
    x = (atan2(sun(2), sun(1)) + ((((ltan_h - 12) * 15) * pi) / 180));
    turn = (2 * pi);
    m = rem(x, turn);
    raan = asils.pc.choose((m < 0), (m + asils.pc.fabs(turn)), m);
end
