function [cmd_r] = alloc_idle(cmd_r0, nr, zh, h_t_rot, rot_gi, rot_kind, zero_cmg)
%ALLOC_IDLE  The rotor command outside the fine states: each rotor held at its momentum target, a CMG rotor's
%   torque command zero when asked (its own speed loop holds it).
%   cmd_r0: real[1][8] (passed a plain number)
%   nr: int (passed a whole number)
%   zh: real[1][8] (passed a plain number)
%   h_t_rot: real[1][8] (passed a plain number)
%   rot_gi: int[8] (passed a whole number)
%   rot_kind: int[8] (passed a whole number)
%   zero_cmg: bool (passed true or false)
%   returns cmd_r: real[1][8] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    cmd_r = zeros(8, 1);
    cmd_r = cmd_r0;
    for i = (0):((nr) - 1)
        cmd_r((i) + 1) = ((-(0.2)) * (zh((i) + 1) - h_t_rot((i) + 1)));
        if ((zero_cmg && (rot_gi((i) + 1) > 0)) && (rot_kind((i) + 1) == 2))
            cmd_r((i) + 1) = 0;
        end
    end
end
