function s = CtlState_zero()
%CTLSTATE_ZERO  a CtlState with every field zero
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = struct();
    s.q = zeros(4, 1);
    s.w_est = zeros(3, 1);
    s.q_ref = zeros(4, 1);
    s.w_ref = zeros(3, 1);
    s.i_q = zeros(3, 1);
    s.tau_req = zeros(3, 1);
    s.mode = 0;
    s.s_prop = zeros(3, 1);
    s.s_prop_ok = false;
    s.cap = zeros(3, 1);
    s.hcap = zeros(3, 1);
end
