function [u] = addsec(utc, sec)
%ADDSEC  op.addsec: a UTC [Y Mo D H Mi S] plus some seconds, through datenum and datevec (leap seconds not represented, as
%   MATLAB).
%   utc: real[1][6] (passed a plain number)
%   sec: real[1] (passed a plain number)
%   returns u: real[1][6] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    u = zeros(6, 1);
    dn = (asils.models.timescales.datenum(utc(1), utc(2), utc(3), utc(4), utc(5), utc(6)) + (sec / 86400));
    u = asils.models.timescales.datevec(dn);
end
