function [v] = datevec(date)
%DATEVEC  Octave's datevec(datenum) for a scalar: [Y Mo D H Mi S], the seconds rounded to the datenum's resolution as Octave
%   rounds them.
%   date: real[1] (passed a plain number)
%   returns v: real[1][6] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    v = zeros(6, 1);
    z = (floor(date) - 60);
    a = floor(((z - 0.25) / 36524.25));
    b = (((z - 0.25) + a) - floor((a / 4)));
    y = floor((b / 365.25));
    c = (fix((b - floor((365.25 * y)))) + 1);
    m = fix((((5 * c) + 456) / 153));
    d = (c - fix((((153 * m) - 457) / 5)));
    if (m > 12)
        y = (y + 1);
        m = (m - 12);
    end
    fracd = (date - floor(date));
    h__537 = ((2.220446049250313e-16 * 86400) * date);
    if h__537 < 0, h__537 = -h__537; elseif h__537 == 0, h__537 = 0; end
    tmps = h__537;
    if (tmps == 0)
        tmps = 1;
    end
    h__538 = log2(tmps);
    if ~isreal(h__538), h__538 = NaN; end
    h__539 = (2)^(floor((-(h__538))));
    if ~isreal(h__539), h__539 = NaN; end
    srnd = h__539;
    s = (round(((86400 * fracd) * srnd)) / srnd);
    h = floor((s / 3600));
    s = (s - (3600 * h));
    mi = floor((s / 60));
    s = (s - (60 * mi));
    v = [y; m; d; h; mi; s];
end
