function [g] = gmst82(jd_ut1)
%GMST82  timeconv.gmst82: the Greenwich mean sidereal time (IAU 1982) [rad] of a UT1 Julian date.
%   jd_ut1: real[1] (passed a plain number)
%   returns g: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    g = 0;
    tu = ((jd_ut1 - 2451545) / 36525);
    sec = (((67310.54841 + (((876600 * 3600) + 8640184.812866) * tu)) + (0.093104 * asils.pc.ipow(tu, 2))) - (0.0000062 * asils.pc.pow_(tu, 3)));
    g = asils.models.timescales.deg2rad((asils.models.timescales.omod(sec, 86400) / 240));
end
