function [s] = j2000sec(jd_tt)
%J2000SEC  jd_tt: real[1] (passed a plain number)
%   returns s: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = 0;
    s = ((jd_tt - 2451545) * 86400);
end
