function [n] = tai_minus_utc(jd_utc)
%TAI_MINUS_UTC  timeconv.taiMinusUTC: TAI - UTC [s] at a UTC Julian date, 10 before 1972, else the last leap-second row whose
%   first of the month (0 h UTC) is at or before it.
%   jd_utc: real[1] (passed a plain number)
%   returns n: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    n = 0;
    n = 10;
    for i = (0):((28) - 1)
        if (jd_utc >= asils.models.timescales.cal2jd(asils.models.leapsec.LEAP_SECONDS((i) + 1, 1), asils.models.leapsec.LEAP_SECONDS((i) + 1, 2), 1, 0, 0, 0))
            n = asils.models.leapsec.LEAP_SECONDS((i) + 1, 3);
        end
    end
end
