function [j] = tt2utc(jd_tt)
%TT2UTC  jd_tt: real[1] (passed a plain number)
%   returns j: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    j = 0;
    j = asils.models.timescales.tai2utc(asils.models.timescales.tt2tai(jd_tt));
end
