function [j] = utc2tai(jd_utc)
%UTC2TAI  UTC to TAI, TAI to UTC (the leap looked up on the TAI date, as MATLAB), TAI to TT and back, TT to UTC, UTC to TT.
%   jd_utc: real[1] (passed a plain number)
%   returns j: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    j = 0;
    j = (jd_utc + (asils.models.timescales.tai_minus_utc(jd_utc) / 86400));
end
