function [tau, mdot, p] = thrusters_apply(s, d, duty, t)
%THRUSTERS_APPLY  The couples' duties over the period t: (the torque [N m], the propellant flow [kg/s], the power [W]).
%   s: ThrusterSet (passed rec)
%   d: ThrusterDesc (passed rec)
%   duty: real[1][ACT_NC] (passed a plain number)
%   t: real[s] (passed in s)
%   returns tau: real[N m][3] (passed in m^2 kg/s^2)
%   returns mdot: real[kg/s] (passed in kg/s)
%   returns p: real[W] (passed in m^2 kg/s^3)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    tau = zeros(3, 1);
    mdot = 0;
    p = 0;
    tau = [0; 0; 0];
    fs = 0;
    p = 0;
    for j = (0):((d.nc) - 1)
        on = asils.models.rcsmib.valve_on_time(duty((j) + 1), t, d.mib, d.res);
        if s.failed((j) + 1)
            on = 0;
        end
        f = (on / t);
        tau = (tau + ((s.tau((j) + 1, :)).' * (f * s.tscale((j) + 1))));
        fs = (fs + (f * s.tscale((j) + 1)));
        if (on > 0)
            p = (p + asils.models.rcsvalve.valve_power(on, d.valve_power));
        end
    end
    mdot = asils.models.rcsisp.rcs_mass_flow(fs, d.thrust, s.isp);
end
