function y = call(name, x)
%CALL  a function by its registry name (module::name), inputs and outputs flattened (row-major, SI)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    switch name
        case 'ctl::settling_time_2pct'
            [o1] = asils.physics.ctl.settling_time_2pct(x(1), x(2));
            y = [double(o1)];
        case 'env::dipole'
            [o1, o2] = asils.physics.env.dipole();
            y = [double(o1); double(o2)];
        case 'env::max_magnetic_latitude'
            [o1] = asils.physics.env.max_magnetic_latitude(x(1));
            y = [double(o1)];
        case 'env::dipole_field_equator'
            [o1] = asils.physics.env.dipole_field_equator(x(1));
            y = [double(o1)];
        case 'env::dipole_field_max'
            [o1] = asils.physics.env.dipole_field_max(x(1), x(2));
            y = [double(o1)];
        case 'env::density_at'
            [o1] = asils.physics.env.density_at(x(1), x(2));
            y = [double(o1)];
        case 'env::sun_distance_au'
            [o1] = asils.physics.env.sun_distance_au(x(1));
            y = [double(o1)];
        case 'env::solar_pressure'
            [o1] = asils.physics.env.solar_pressure(x(1));
            y = [double(o1)];
        case 'fmr::ring_momentum'
            [o1] = asils.physics.fmr.ring_momentum(x(1), x(2), x(3), x(4));
            y = [double(o1)];
        case 'fmr::spin_down_time'
            [o1] = asils.physics.fmr.spin_down_time(x(1), x(2), x(3));
            y = [double(o1)];
        case 'fmr::holding_power_laminar'
            [o1] = asils.physics.fmr.holding_power_laminar(x(1), x(2), x(3), x(4), x(5), x(6));
            y = [double(o1)];
        case 'fmr::pump_pressure_for_torque'
            [o1] = asils.physics.fmr.pump_pressure_for_torque(x(1), x(2), x(3), x(4));
            y = [double(o1)];
        case 'fmr::reynolds'
            [o1] = asils.physics.fmr.reynolds(x(1), x(2), x(3), x(4));
            y = [double(o1)];
        case 'fmr::conduction_pump_pressure'
            [o1] = asils.physics.fmr.conduction_pump_pressure(x(1), x(2), x(3), x(4));
            y = [double(o1)];
        case 'gnc::magnetic_torque'
            [o1] = asils.physics.gnc.magnetic_torque(x(1), x(2));
            y = [double(o1)];
        case 'gnc::total_disturbance_torque'
            [o1] = asils.physics.gnc.total_disturbance_torque(x(1), x(2), x(3), x(4));
            y = [double(o1)];
        case 'gnc::magnetorquer_dipole_required'
            [o1] = asils.physics.gnc.magnetorquer_dipole_required(x(1), x(2), x(3));
            y = [double(o1)];
        case 'gnc::pointing_error_rss'
            [o1] = asils.physics.gnc.pointing_error_rss(reshape(x(1:5), 5, 1));
            y = [double(o1)];
        case 'gnc::gravity_gradient_torque_worst'
            [o1] = asils.physics.gnc.gravity_gradient_torque_worst(x(1), x(2), x(3));
            y = [double(o1)];
        case 'gnc::aero_torque'
            [o1] = asils.physics.gnc.aero_torque(x(1), x(2), x(3), x(4), x(5));
            y = [double(o1)];
        case 'gnc::solar_pressure_torque_at'
            [o1] = asils.physics.gnc.solar_pressure_torque_at(x(1), x(2), x(3), x(4));
            y = [double(o1)];
        case 'gnc::secular_momentum_per_orbit'
            [o1] = asils.physics.gnc.secular_momentum_per_orbit(x(1), x(2));
            y = [double(o1)];
        case 'mission::closure'
            [o1, o2] = asils.physics.mission.closure(x(1), x(2), x(3));
            y = [double(o1); double(o2)];
        case 'mtq::dipole_to_reject'
            [o1] = asils.physics.mtq.dipole_to_reject(x(1), x(2));
            y = [double(o1)];
        case 'mtq::torque_authority'
            [o1] = asils.physics.mtq.torque_authority(x(1), x(2), x(3));
            y = [double(o1)];
        case 'mtq::coil_dipole'
            [o1] = asils.physics.mtq.coil_dipole(x(1), x(2), x(3));
            y = [double(o1)];
        case 'orbit::radius'
            [o1] = asils.physics.orbit.radius(x(1));
            y = [double(o1)];
        case 'orbit::circular_period'
            [o1] = asils.physics.orbit.circular_period(x(1));
            y = [double(o1)];
        case 'orbit::mean_motion'
            [o1] = asils.physics.orbit.mean_motion(x(1));
            y = [double(o1)];
        case 'orbit::circular_speed'
            [o1] = asils.physics.orbit.circular_speed(x(1));
            y = [double(o1)];
        case 'orbit::eclipse_fraction'
            [o1] = asils.physics.orbit.eclipse_fraction(x(1), x(2));
            y = [double(o1)];
        case 'orbit::sun_ra_dec'
            [o1, o2] = asils.physics.orbit.sun_ra_dec(x(1));
            y = [double(o1); double(o2)];
        case 'orbit::beta_angle'
            [o1] = asils.physics.orbit.beta_angle(x(1), x(2), x(3));
            y = [double(o1)];
        case 'rcs::propellant_per_slew'
            [o1] = asils.physics.rcs.propellant_per_slew(x(1), x(2), x(3));
            y = [double(o1)];
        case 'rcs::propellant_per_year'
            [o1] = asils.physics.rcs.propellant_per_year(x(1), x(2), x(3));
            y = [double(o1)];
        case 'risk::highest_level'
            [o1] = asils.physics.risk.highest_level(reshape(x(1:7), 7, 1));
            y = [double(o1)];
        case 'risk::net_closed'
            [o1] = asils.physics.risk.net_closed(x(1), x(2));
            y = [double(o1)];
        case 'risk::share_tested'
            [o1, o2] = asils.physics.risk.share_tested(x(1), x(2));
            y = [double(o1); double(o2)];
        case 'rw::bang_bang_peak_momentum'
            [o1] = asils.physics.rw.bang_bang_peak_momentum(x(1), x(2), x(3));
            y = [double(o1)];
        case 'rw::bang_bang_peak_torque'
            [o1] = asils.physics.rw.bang_bang_peak_torque(x(1), x(2), x(3));
            y = [double(o1)];
        case 'rw::cyclic_momentum_quarter_orbit'
            [o1] = asils.physics.rw.cyclic_momentum_quarter_orbit(x(1), x(2));
            y = [double(o1)];
        otherwise
            error('pcode:call', 'no function %s', name);
    end
end
