function [sigma_h] = ring_flow_noise(k_hv, sigma_v)
%RING_FLOW_NOISE  The flow sensor's noise in momentum [N m s], one sigma: the ring's momentum per flow speed k_hv [N m s/(m/s)] times
%   the part's flow_sensor_noise_m_s sigma [m/s].
%   k_hv: real[1] (passed a plain number)
%   sigma_v: real[1] (passed a plain number)
%   returns sigma_h: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    sigma_h = 0;
    sigma_h = (k_hv * sigma_v);
end
