/* estimation: 03 - Estimation (03_estimation.md): the multiplicative extended Kalman filter, TRIAD, the q-method and the star-tracker latency, operation for operation as fsw/src/adcs_est.c and fsw-rs/src/est.rs. The filter's record (adcs_mekf_t, est::Mekf) is passed as its parts: q, b, P. */
/* Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit. */
#include "adcs_alg.h"
#include "adcs_alg_rt.h"

estimation_mekf_init_out estimation_mekf_init(pc_a4f q0, double sa, double sb) {
    pc_a4f q = ((pc_a4f){0});
    pc_a3f b = ((pc_a3f){0});
    pc_a6a6f p = ((pc_a6a6f){0});
    q = q0;
    b = ((pc_a3f){0});
    p = ((pc_a6a6f){0});
    {
        int64_t end__20 = INT64_C(3);
        int64_t i = INT64_C(0);
        while (i < end__20) {
            p.v[(i)].v[(i)] = (sa * sa);
            p.v[((i + INT64_C(3)))].v[((i + INT64_C(3)))] = (sb * sb);
            i += 1;
        }
    }
    {
        estimation_mekf_init_out r__;
        r__.q = q;
        r__.b = b;
        r__.p = p;
        return r__;
    }
}

estimation_mekf_predict_out estimation_mekf_predict(pc_a4f q0, pc_a3f b, pc_a6a6f p0, double arw, double rrw, pc_a3f wm, double dt) {
    pc_a4f q = ((pc_a4f){0});
    pc_a6a6f p = ((pc_a6a6f){0});
    double sv2 = (arw * arw);
    double su2 = (rrw * rrw);
    pc_a3f w = pc_sub_a3f(wm, b);
    q = math_qnorm(math_qmult(q0, math_fromrotvec(pc_scale_a3f(w, dt))));
    pc_a3a3f ww = math_skew(w);
    pc_a3a3f w2 = pc_mm_a3a3f_a3a3f(ww, ww);
    pc_a6a6f phi = ((pc_a6a6f){0});
    {
        int64_t end__21 = INT64_C(3);
        int64_t i = INT64_C(0);
        while (i < end__21) {
            {
                int64_t end__22 = INT64_C(3);
                int64_t j = INT64_C(0);
                while (j < end__22) {
                    phi.v[(i)].v[(j)] = ((((i == j) ? 1.0 : 0.0) - (ww.v[(i)].v[(j)] * dt)) + (((0.5 * w2.v[(i)].v[(j)]) * dt) * dt));
                    j += 1;
                }
            }
            phi.v[(i)].v[((i + INT64_C(3)))] = (-(dt));
            phi.v[((i + INT64_C(3)))].v[((i + INT64_C(3)))] = 1.0;
            i += 1;
        }
    }
    pc_a6a6f t = ((pc_a6a6f){0});
    {
        int64_t end__23 = INT64_C(6);
        int64_t i = INT64_C(0);
        while (i < end__23) {
            {
                int64_t end__24 = INT64_C(6);
                int64_t j = INT64_C(0);
                while (j < end__24) {
                    t.v[(i)].v[(j)] = 0.0;
                    {
                        int64_t end__25 = INT64_C(6);
                        int64_t l = INT64_C(0);
                        while (l < end__25) {
                            t.v[(i)].v[(j)] = (t.v[(i)].v[(j)] + (phi.v[(i)].v[(l)] * p0.v[(l)].v[(j)]));
                            l += 1;
                        }
                    }
                    j += 1;
                }
            }
            i += 1;
        }
    }
    p = ((pc_a6a6f){0});
    {
        int64_t end__26 = INT64_C(6);
        int64_t i = INT64_C(0);
        while (i < end__26) {
            {
                int64_t end__27 = INT64_C(6);
                int64_t j = INT64_C(0);
                while (j < end__27) {
                    p.v[(i)].v[(j)] = 0.0;
                    {
                        int64_t end__28 = INT64_C(6);
                        int64_t l = INT64_C(0);
                        while (l < end__28) {
                            p.v[(i)].v[(j)] = (p.v[(i)].v[(j)] + (t.v[(i)].v[(l)] * phi.v[(j)].v[(l)]));
                            l += 1;
                        }
                    }
                    j += 1;
                }
            }
            i += 1;
        }
    }
    {
        int64_t end__29 = INT64_C(3);
        int64_t i = INT64_C(0);
        while (i < end__29) {
            p.v[(i)].v[(i)] = (p.v[(i)].v[(i)] + ((sv2 * dt) + ((((su2 * dt) * dt) * dt) / 3.0)));
            p.v[(i)].v[((i + INT64_C(3)))] = (p.v[(i)].v[((i + INT64_C(3)))] + ((((-(su2)) * dt) * dt) / 2.0));
            p.v[((i + INT64_C(3)))].v[(i)] = (p.v[((i + INT64_C(3)))].v[(i)] + ((((-(su2)) * dt) * dt) / 2.0));
            p.v[((i + INT64_C(3)))].v[((i + INT64_C(3)))] = (p.v[((i + INT64_C(3)))].v[((i + INT64_C(3)))] + (su2 * dt));
            i += 1;
        }
    }
    {
        estimation_mekf_predict_out r__;
        r__.q = q;
        r__.p = p;
        return r__;
    }
}

estimation_update3_out estimation_update3(pc_a4f q0, pc_a3f b0, pc_a6a6f p0, pc_a3a6f h, pc_a3a3f r, pc_a3f y, double gate) {
    pc_a4f q = ((pc_a4f){0});
    pc_a3f b = ((pc_a3f){0});
    pc_a6a6f p = ((pc_a6a6f){0});
    bool took = false;
    q = q0;
    b = b0;
    p = p0;
    took = false;
    pc_a6a3f pht = ((pc_a6a3f){0});
    {
        int64_t end__30 = INT64_C(6);
        int64_t i = INT64_C(0);
        while (i < end__30) {
            {
                int64_t end__31 = INT64_C(3);
                int64_t j = INT64_C(0);
                while (j < end__31) {
                    pht.v[(i)].v[(j)] = 0.0;
                    {
                        int64_t end__32 = INT64_C(6);
                        int64_t l = INT64_C(0);
                        while (l < end__32) {
                            pht.v[(i)].v[(j)] = (pht.v[(i)].v[(j)] + (p0.v[(i)].v[(l)] * h.v[(j)].v[(l)]));
                            l += 1;
                        }
                    }
                    j += 1;
                }
            }
            i += 1;
        }
    }
    pc_a3a3f s = ((pc_a3a3f){0});
    {
        int64_t end__33 = INT64_C(3);
        int64_t i = INT64_C(0);
        while (i < end__33) {
            {
                int64_t end__34 = INT64_C(3);
                int64_t j = INT64_C(0);
                while (j < end__34) {
                    s.v[(i)].v[(j)] = r.v[(i)].v[(j)];
                    {
                        int64_t end__35 = INT64_C(6);
                        int64_t l = INT64_C(0);
                        while (l < end__35) {
                            s.v[(i)].v[(j)] = (s.v[(i)].v[(j)] + (h.v[(i)].v[(l)] * pht.v[(l)].v[(j)]));
                            l += 1;
                        }
                    }
                    j += 1;
                }
            }
            i += 1;
        }
    }
    math_inv3_out t__36 = math_inv3(s);
    pc_a3a3f si = t__36.r;
    bool ok = t__36.ok;
    if (ok) {
        double chi = 0.0;
        {
            int64_t end__37 = INT64_C(3);
            int64_t i = INT64_C(0);
            while (i < end__37) {
                {
                    int64_t end__38 = INT64_C(3);
                    int64_t j = INT64_C(0);
                    while (j < end__38) {
                        chi = (chi + ((y.v[(i)] * si.v[(i)].v[(j)]) * y.v[(j)]));
                        j += 1;
                    }
                }
                i += 1;
            }
        }
        if (((chi == chi) && (!((gate > 0.0) && (chi > gate))))) {
            took = true;
            pc_a6a3f g = ((pc_a6a3f){0});
            {
                int64_t end__39 = INT64_C(6);
                int64_t i = INT64_C(0);
                while (i < end__39) {
                    {
                        int64_t end__40 = INT64_C(3);
                        int64_t j = INT64_C(0);
                        while (j < end__40) {
                            g.v[(i)].v[(j)] = 0.0;
                            {
                                int64_t end__41 = INT64_C(3);
                                int64_t l = INT64_C(0);
                                while (l < end__41) {
                                    g.v[(i)].v[(j)] = (g.v[(i)].v[(j)] + (pht.v[(i)].v[(l)] * si.v[(l)].v[(j)]));
                                    l += 1;
                                }
                            }
                            j += 1;
                        }
                    }
                    i += 1;
                }
            }
            pc_a6f dx = ((pc_a6f){0});
            {
                int64_t end__42 = INT64_C(6);
                int64_t i = INT64_C(0);
                while (i < end__42) {
                    dx.v[(i)] = 0.0;
                    {
                        int64_t end__43 = INT64_C(3);
                        int64_t l = INT64_C(0);
                        while (l < end__43) {
                            dx.v[(i)] = (dx.v[(i)] + (g.v[(i)].v[(l)] * y.v[(l)]));
                            l += 1;
                        }
                    }
                    i += 1;
                }
            }
            q = math_qnorm(math_qmult(q0, ((pc_a4f){ { (0.5 * dx.v[0]), (0.5 * dx.v[1]), (0.5 * dx.v[2]), 1.0 } })));
            {
                int64_t end__44 = INT64_C(3);
                int64_t i = INT64_C(0);
                while (i < end__44) {
                    b.v[(i)] = (b0.v[(i)] + dx.v[((i + INT64_C(3)))]);
                    i += 1;
                }
            }
            pc_a6a6f ikh = ((pc_a6a6f){0});
            {
                int64_t end__45 = INT64_C(6);
                int64_t i = INT64_C(0);
                while (i < end__45) {
                    {
                        int64_t end__46 = INT64_C(6);
                        int64_t j = INT64_C(0);
                        while (j < end__46) {
                            ikh.v[(i)].v[(j)] = ((i == j) ? 1.0 : 0.0);
                            {
                                int64_t end__47 = INT64_C(3);
                                int64_t l = INT64_C(0);
                                while (l < end__47) {
                                    ikh.v[(i)].v[(j)] = (ikh.v[(i)].v[(j)] - (g.v[(i)].v[(l)] * h.v[(l)].v[(j)]));
                                    l += 1;
                                }
                            }
                            j += 1;
                        }
                    }
                    i += 1;
                }
            }
            pc_a6a6f t = ((pc_a6a6f){0});
            {
                int64_t end__48 = INT64_C(6);
                int64_t i = INT64_C(0);
                while (i < end__48) {
                    {
                        int64_t end__49 = INT64_C(6);
                        int64_t j = INT64_C(0);
                        while (j < end__49) {
                            t.v[(i)].v[(j)] = 0.0;
                            {
                                int64_t end__50 = INT64_C(6);
                                int64_t l = INT64_C(0);
                                while (l < end__50) {
                                    t.v[(i)].v[(j)] = (t.v[(i)].v[(j)] + (ikh.v[(i)].v[(l)] * p0.v[(l)].v[(j)]));
                                    l += 1;
                                }
                            }
                            j += 1;
                        }
                    }
                    i += 1;
                }
            }
            {
                int64_t end__51 = INT64_C(6);
                int64_t i = INT64_C(0);
                while (i < end__51) {
                    {
                        int64_t end__52 = INT64_C(6);
                        int64_t j = INT64_C(0);
                        while (j < end__52) {
                            p.v[(i)].v[(j)] = 0.0;
                            {
                                int64_t end__53 = INT64_C(6);
                                int64_t l = INT64_C(0);
                                while (l < end__53) {
                                    p.v[(i)].v[(j)] = (p.v[(i)].v[(j)] + (t.v[(i)].v[(l)] * ikh.v[(j)].v[(l)]));
                                    l += 1;
                                }
                            }
                            j += 1;
                        }
                    }
                    i += 1;
                }
            }
            {
                int64_t end__54 = INT64_C(6);
                int64_t i = INT64_C(0);
                while (i < end__54) {
                    {
                        int64_t end__55 = INT64_C(6);
                        int64_t j = INT64_C(0);
                        while (j < end__55) {
                            {
                                int64_t end__56 = INT64_C(3);
                                int64_t a = INT64_C(0);
                                while (a < end__56) {
                                    {
                                        int64_t end__57 = INT64_C(3);
                                        int64_t c = INT64_C(0);
                                        while (c < end__57) {
                                            p.v[(i)].v[(j)] = (p.v[(i)].v[(j)] + ((g.v[(i)].v[(a)] * r.v[(a)].v[(c)]) * g.v[(j)].v[(c)]));
                                            c += 1;
                                        }
                                    }
                                    a += 1;
                                }
                            }
                            j += 1;
                        }
                    }
                    i += 1;
                }
            }
        }
    }
    {
        estimation_update3_out r__;
        r__.q = q;
        r__.b = b;
        r__.p = p;
        r__.took = took;
        return r__;
    }
}

estimation_mekf_vector_out estimation_mekf_vector(pc_a4f q0, pc_a3f b0, pc_a6a6f p0, pc_a3f bm, pc_a3f rr, double sigma, double gate) {
    pc_a4f q = ((pc_a4f){0});
    pc_a3f b = ((pc_a3f){0});
    pc_a6a6f p = ((pc_a6a6f){0});
    bool took = false;
    pc_a3f bu = pc_unit_a3f(bm);
    pc_a3f ru = pc_unit_a3f(rr);
    pc_a3f bh = pc_mv_a3a3f(math_dcm(q0), ru);
    pc_a3a3f sk = math_skew(bh);
    pc_a3a6f h = ((pc_a3a6f){0});
    {
        int64_t end__58 = INT64_C(3);
        int64_t i = INT64_C(0);
        while (i < end__58) {
            {
                int64_t end__59 = INT64_C(6);
                int64_t j = INT64_C(0);
                while (j < end__59) {
                    h.v[(i)].v[(j)] = ((j < INT64_C(3)) ? sk.v[(i)].v[(j)] : 0.0);
                    j += 1;
                }
            }
            i += 1;
        }
    }
    pc_a3a3f r = ((pc_a3a3f){0});
    {
        int64_t end__60 = INT64_C(3);
        int64_t i = INT64_C(0);
        while (i < end__60) {
            {
                int64_t end__61 = INT64_C(3);
                int64_t j = INT64_C(0);
                while (j < end__61) {
                    r.v[(i)].v[(j)] = ((i == j) ? (sigma * sigma) : 0.0);
                    j += 1;
                }
            }
            i += 1;
        }
    }
    {
        estimation_update3_out t__62 = estimation_update3(q0, b0, p0, h, r, pc_sub_a3f(bu, bh), gate);
        q = t__62.q;
        b = t__62.b;
        p = t__62.p;
        took = t__62.took;
    }
    {
        estimation_mekf_vector_out r__;
        r__.q = q;
        r__.b = b;
        r__.p = p;
        r__.took = took;
        return r__;
    }
}

estimation_mekf_quat_out estimation_mekf_quat(pc_a4f q0, pc_a3f b0, pc_a6a6f p0, pc_a4f qm, double sc, double sr, pc_a3f bs, double gate) {
    pc_a4f q = ((pc_a4f){0});
    pc_a3f b = ((pc_a3f){0});
    pc_a6a6f p = ((pc_a6a6f){0});
    bool took = false;
    pc_a4f dq = math_qerr(q0, qm);
    pc_a3f y = ((pc_a3f){0});
    {
        int64_t end__63 = INT64_C(3);
        int64_t i = INT64_C(0);
        while (i < end__63) {
            y.v[(i)] = (2.0 * dq.v[(i)]);
            i += 1;
        }
    }
    pc_a3a6f h = ((pc_a3a6f){0});
    pc_a3a3f r = ((pc_a3a3f){0});
    {
        int64_t end__64 = INT64_C(3);
        int64_t i = INT64_C(0);
        while (i < end__64) {
            {
                int64_t end__65 = INT64_C(6);
                int64_t j = INT64_C(0);
                while (j < end__65) {
                    h.v[(i)].v[(j)] = ((i == j) ? 1.0 : 0.0);
                    j += 1;
                }
            }
            {
                int64_t end__66 = INT64_C(3);
                int64_t j = INT64_C(0);
                while (j < end__66) {
                    r.v[(i)].v[(j)] = (((i == j) ? (sc * sc) : 0.0) + ((((sr * sr) - (sc * sc)) * bs.v[(i)]) * bs.v[(j)]));
                    j += 1;
                }
            }
            i += 1;
        }
    }
    {
        estimation_update3_out t__67 = estimation_update3(q0, b0, p0, h, r, y, gate);
        q = t__67.q;
        b = t__67.b;
        p = t__67.p;
        took = t__67.took;
    }
    {
        estimation_mekf_quat_out r__;
        r__.q = q;
        r__.b = b;
        r__.p = p;
        r__.took = took;
        return r__;
    }
}

estimation_triad_out estimation_triad(pc_a3f b1, pc_a3f b2, pc_a3f r1, pc_a3f r2) {
    pc_a4f q = ((pc_a4f){0});
    bool ok = false;
    ok = false;
    q = ((pc_a4f){0});
    if (((pc_norm_a3f(pc_cross_a3f(b1, b2)) > ((0.001 * pc_norm_a3f(b1)) * pc_norm_a3f(b2))) && (pc_norm_a3f(pc_cross_a3f(r1, r2)) > ((0.001 * pc_norm_a3f(r1)) * pc_norm_a3f(r2))))) {
        ok = true;
        pc_a3f tb0 = pc_unit_a3f(b1);
        pc_a3f tb1 = pc_unit_a3f(pc_cross_a3f(b1, b2));
        pc_a3f tb2 = pc_cross_a3f(tb0, tb1);
        pc_a3f tr0 = pc_unit_a3f(r1);
        pc_a3f tr1 = pc_unit_a3f(pc_cross_a3f(r1, r2));
        pc_a3f tr2 = pc_cross_a3f(tr0, tr1);
        pc_a3a3f a = ((pc_a3a3f){0});
        {
            int64_t end__68 = INT64_C(3);
            int64_t i = INT64_C(0);
            while (i < end__68) {
                {
                    int64_t end__69 = INT64_C(3);
                    int64_t j = INT64_C(0);
                    while (j < end__69) {
                        a.v[(i)].v[(j)] = (((tb0.v[(i)] * tr0.v[(j)]) + (tb1.v[(i)] * tr1.v[(j)])) + (tb2.v[(i)] * tr2.v[(j)]));
                        j += 1;
                    }
                }
                i += 1;
            }
        }
        q = math_fromdcm(a);
    }
    {
        estimation_triad_out r__;
        r__.q = q;
        r__.ok = ok;
        return r__;
    }
}

estimation_quest_out estimation_quest(pc_a16a3f bv, pc_a16a3f rv, pc_a16f w, int64_t n) {
    pc_a4f q = ((pc_a4f){0});
    double loss = 0.0;
    pc_a3a3f bb = ((pc_a3a3f){0});
    double ws = 0.0;
    {
        int64_t end__70 = n;
        int64_t l = INT64_C(0);
        while (l < end__70) {
            double wl = w.v[(l)];
            ws = (ws + wl);
            {
                int64_t end__71 = INT64_C(3);
                int64_t i = INT64_C(0);
                while (i < end__71) {
                    {
                        int64_t end__72 = INT64_C(3);
                        int64_t j = INT64_C(0);
                        while (j < end__72) {
                            bb.v[(i)].v[(j)] = (bb.v[(i)].v[(j)] + ((wl * bv.v[(l)].v[(i)]) * rv.v[(l)].v[(j)]));
                            j += 1;
                        }
                    }
                    i += 1;
                }
            }
            l += 1;
        }
    }
    double sg = ((bb.v[0].v[0] + bb.v[1].v[1]) + bb.v[2].v[2]);
    pc_a3f z = ((pc_a3f){ { (bb.v[1].v[2] - bb.v[2].v[1]), (bb.v[2].v[0] - bb.v[0].v[2]), (bb.v[0].v[1] - bb.v[1].v[0]) } });
    pc_a4a4f k = ((pc_a4a4f){0});
    {
        int64_t end__73 = INT64_C(3);
        int64_t i = INT64_C(0);
        while (i < end__73) {
            {
                int64_t end__74 = INT64_C(3);
                int64_t j = INT64_C(0);
                while (j < end__74) {
                    k.v[(i)].v[(j)] = ((bb.v[(i)].v[(j)] + bb.v[(j)].v[(i)]) - ((i == j) ? sg : 0.0));
                    j += 1;
                }
            }
            k.v[(i)].v[3] = z.v[(i)];
            k.v[3].v[(i)] = z.v[(i)];
            i += 1;
        }
    }
    k.v[3].v[3] = sg;
    math_jacobi_eig4_out t__75 = math_jacobi_eig4(k);
    pc_a4f lam = t__75.lam;
    pc_a4a4f v = t__75.v;
    int64_t im = INT64_C(0);
    {
        int64_t end__76 = INT64_C(4);
        int64_t i = INT64_C(1);
        while (i < end__76) {
            if ((lam.v[(i)] > lam.v[(im)])) {
                im = i;
            }
            i += 1;
        }
    }
    q = math_qnorm(((pc_a4f){ { v.v[0].v[(im)], v.v[1].v[(im)], v.v[2].v[(im)], v.v[3].v[(im)] } }));
    loss = (ws - lam.v[(im)]);
    {
        estimation_quest_out r__;
        r__.q = q;
        r__.loss = loss;
        return r__;
    }
}

pc_a4f estimation_latency(pc_a4f q_st, pc_a3f w, double lat) {
    pc_a4f q = ((pc_a4f){0});
    q = math_qnorm(math_qmult(q_st, math_fromrotvec(pc_scale_a3f(w, lat))));
    return q;
}
