/* steplaws: 05, 06 and 07 at the level of the tick (05_control.md, 07_allocation.md, 02 for the orbit): the laws the shell runs on the flight software's own state - the magnetic pointing law it selects, the large-error capture, the rotor Sun acquisition, the rotor allocation with lost axes, the rotor idle command, the onboard orbit's acceleration - operation for operation as the helpers of fsw/src/adcs_fsw.c (adcs_ctl_*, adcs_alloc_*, adcs_orbit_acc) and fsw-rs/src/fsw.rs. */
/* Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit. */
#include "adcs_alg.h"
#include "adcs_alg_rt.h"

CtlState steplaws_ctl_mtq(CtlState st_, CtlParams cp) {
    CtlState s = ((CtlState){0});
    s = st_;
    int64_t law = cp.mtq_law;
    if ((law == INT64_C(0))) {
        s.tau_req = control_mtq_pd(s.q, s.w_est, s.q_ref, s.w_ref, cp.g_kp, cp.g_kd);
    } else if ((law == INT64_C(3))) {
        pc_a4f qe = math_qmult(math_qconj(s.q_ref), s.q);
        pc_a3f wr = pc_mv_a3a3f(math_dcm(qe), s.w_ref);
        {
            int64_t end__114 = INT64_C(3);
            int64_t i = INT64_C(0);
            while (i < end__114) {
                s.tau_req.v[(i)] = ((-(cp.g_kd.v[(i)])) * (s.w_est.v[(i)] - wr.v[(i)]));
                i += 1;
            }
        }
    } else if ((law == INT64_C(4))) {
        s.tau_req = control_mtq_lovera(s.q, s.w_est, s.q_ref, s.w_ref, cp.j, cp.mtq_eps, cp.mtq_k1, cp.mtq_k2);
    } else if (((law == INT64_C(5)) || (law == INT64_C(6)))) {
        bool ok = false;
        if ((law == INT64_C(6))) {
            control_mtq_avanzini_out t__115 = control_mtq_avanzini(s.q, s.w_est, s.q_ref, s.w_ref, cp.j, cp.mtq_k16, cp.mtq_lam16);
            pc_a3f t6 = t__115.tau;
            bool ok6 = t__115.ok;
            ok = ok6;
            if (ok) {
                s.tau_req = t6;
            }
        }
        if ((!ok)) {
            s.tau_req = control_mtq_celani(s.q, s.w_est, s.q_ref, s.w_ref, cp.mtq_eps, cp.mtq_k1, cp.mtq_k2);
        }
    } else if ((law == INT64_C(7))) {
        pc_a4f qe = math_qmult(math_qconj(s.q_ref), s.q);
        pc_a3a3f a = math_dcm(qe);
        pc_a3f wr = pc_mv_a3a3f(a, s.w_ref);
        pc_a3f we = pc_sub_a3f(s.w_est, wr);
        pc_a3f e3 = ((s.mode == INT64_C(9)) ? cp.sun_axis : cp.roll_axis);
        pc_a3f tgt = pc_mv_a3a3f(a, e3);
        if (((s.mode == INT64_C(9)) && s.s_prop_ok)) {
            tgt = pc_unit_a3f(s.s_prop);
        }
        s.tau_req = control_mtq_boresight(e3, tgt, we, cp.sb_kp, cp.sb_kd);
        if ((((s.mode == INT64_C(1)) && (cp.sb_kroll > 0.0)) && (pc_dot_a3f(e3, tgt) > cp.sb_roll_gate))) {
            double d = pc_dot_a3f(cp.sun_axis, e3);
            pc_a3f pa = ((pc_a3f){0});
            {
                int64_t end__116 = INT64_C(3);
                int64_t i = INT64_C(0);
                while (i < end__116) {
                    pa.v[(i)] = (cp.sun_axis.v[(i)] - (d * e3.v[(i)]));
                    i += 1;
                }
            }
            if ((pc_norm_a3f(pa) > 0.000001)) {
                pa = pc_unit_a3f(pa);
                pc_a3f pd = pc_mv_a3a3f(a, pa);
                pc_a3f c = pc_cross_a3f(pa, pd);
                double r = ((cp.sb_kroll * atan2(pc_dot_a3f(c, e3), pc_dot_a3f(pa, pd))) - (cp.sb_kdroll * pc_dot_a3f(we, e3)));
                {
                    int64_t end__117 = INT64_C(3);
                    int64_t i = INT64_C(0);
                    while (i < end__117) {
                        s.tau_req.v[(i)] = (s.tau_req.v[(i)] + (r * e3.v[(i)]));
                        i += 1;
                    }
                }
            }
        }
    } else if ((law == INT64_C(8))) {
        s.tau_req = control_mtq_tango(s.q, s.w_est, s.q_ref, s.w_ref, cp.mtq_pth, cp.mtq_pw);
    } else {
        pc_a3f z = ((pc_a3f){0});
        {
            control_control_law_out t__118 = control_control_law(s.q, s.w_est, s.q_ref, s.w_ref, s.i_q, cp.mtq_period, cp.g_law, cp.g_kp, cp.g_kd, cp.g_ki, cp.g_klqr, cp.g_lambda, cp.g_phi, cp.g_gs, cp.g_err_max, cp.g_int_max, cp.j, z, z);
            s.tau_req = t__118.tau;
            s.i_q = t__118.i_q;
        }
    }
    return s;
}

steplaws_ctl_capture_out steplaws_ctl_capture(CtlState st_, CtlParams cp, pc_a3f hdev) {
    CtlState s = ((CtlState){0});
    bool on = false;
    s = st_;
    on = false;
    if ((!((s.mode == INT64_C(4)) || (cp.capture_deg <= 0.0)))) {
        pc_a4f qe = math_qerr(s.q_ref, s.q);
        double th = (2.0 * acos(((qe.v[3] > 1.0) ? 1.0 : qe.v[3])));
        if ((!(th < (cp.capture_deg * (3.141592653589793 / 180.0))))) {
            on = true;
            double n = sqrt((((qe.v[0] * qe.v[0]) + (qe.v[1] * qe.v[1])) + (qe.v[2] * qe.v[2])));
            if ((n < 1.0e-12)) {
                n = 1.0e-12;
            }
            pc_a3f e = ((pc_a3f){ { (qe.v[0] * (1.0 / n)), (qe.v[1] * (1.0 / n)), (qe.v[2] * (1.0 / n)) } });
            double jm = cp.j.v[0].v[0];
            if ((cp.j.v[1].v[1] > jm)) {
                jm = cp.j.v[1].v[1];
            }
            if ((cp.j.v[2].v[2] > jm)) {
                jm = cp.j.v[2].v[2];
            }
            double mincap = s.cap.v[0];
            double minh = s.hcap.v[0];
            {
                int64_t end__119 = INT64_C(3);
                int64_t i = INT64_C(1);
                while (i < end__119) {
                    if ((s.cap.v[(i)] < mincap)) {
                        mincap = s.cap.v[(i)];
                    }
                    if ((s.hcap.v[(i)] < minh)) {
                        minh = s.hcap.v[(i)];
                    }
                    i += 1;
                }
            }
            double alpha = ((0.5 * mincap) / jm);
            double wmax = (cp.capture_rate_deg_s * (3.141592653589793 / 180.0));
            if ((((0.5 * minh) / jm) < wmax)) {
                wmax = ((0.5 * minh) / jm);
            }
            pc_a3f wref = pc_mv_a3a3f(math_dcm(qe), s.w_ref);
            double sp = sqrt(((2.0 * alpha) * th));
            if ((wmax < sp)) {
                sp = wmax;
            }
            pc_a3f wc = ((pc_a3f){0});
            {
                int64_t end__120 = INT64_C(3);
                int64_t i = INT64_C(0);
                while (i < end__120) {
                    wc.v[(i)] = (wref.v[(i)] - (e.v[(i)] * sp));
                    i += 1;
                }
            }
            double kr = ((4.0 * alpha) / ((wmax > 0.000001) ? wmax : 0.000001));
            if ((kr > 0.5)) {
                kr = 0.5;
            }
            pc_a3f gy = pc_cross_a3f(s.w_est, pc_add_a3f(pc_mv_a3a3f(cp.j, s.w_est), hdev));
            pc_a3f x = ((pc_a3f){0});
            {
                int64_t end__121 = INT64_C(3);
                int64_t i = INT64_C(0);
                while (i < end__121) {
                    x.v[(i)] = (kr * (wc.v[(i)] - s.w_est.v[(i)]));
                    i += 1;
                }
            }
            s.tau_req = pc_add_a3f(pc_mv_a3a3f(cp.j, x), gy);
        }
    }
    {
        steplaws_ctl_capture_out r__;
        r__.s = s;
        r__.on = on;
        return r__;
    }
}

CtlState steplaws_ctl_sun_acq(CtlState st_, CtlParams cp, pc_a3f hdev) {
    CtlState s = ((CtlState){0});
    s = st_;
    double wmax = (cp.sa_w_max_deg_s * (3.141592653589793 / 180.0));
    pc_a3f wc = ((pc_a3f){0});
    pc_a3f a = cp.sun_axis;
    if (s.s_prop_ok) {
        pc_a3f sv = pc_unit_a3f(s.s_prop);
        pc_a3f c = pc_cross_a3f(a, sv);
        if ((pc_dot_a3f(sv, a) < (-(0.95)))) {
            c = pc_cross_a3f(a, ((pc_a3f){ { 1.0, 0.0, 0.0 } }));
            if ((pc_norm_a3f(c) < 0.1)) {
                c = pc_cross_a3f(a, ((pc_a3f){ { 0.0, 1.0, 0.0 } }));
            }
            c = pc_unit_a3f(c);
        }
        wc = pc_scale_a3f(c, (wmax / 0.5));
        double n = pc_norm_a3f(wc);
        if ((n > wmax)) {
            wc = pc_scale_a3f(wc, (wmax / n));
        }
    }
    pc_a3f gy = pc_cross_a3f(s.w_est, pc_add_a3f(pc_mv_a3a3f(cp.j, s.w_est), hdev));
    pc_a3f x = ((pc_a3f){0});
    {
        int64_t end__122 = INT64_C(3);
        int64_t i = INT64_C(0);
        while (i < end__122) {
            x.v[(i)] = (cp.sa_kd * (wc.v[(i)] - s.w_est.v[(i)]));
            i += 1;
        }
    }
    s.tau_req = pc_add_a3f(pc_mv_a3a3f(cp.j, x), gy);
    return s;
}

steplaws_alloc_rotors_out steplaws_alloc_rotors(pc_a3f tau_rot, pc_a3a8f a, pc_a8f cmd_r0, pc_a4f cmd_g0, int64_t nr, int64_t ng, pc_a8i rot_gi, pc_a8i rot_kind, pc_a8b rot_failed, pc_a8f zh, pc_a4a3f gim_axis, double gim_rate_max, double cmg_lam0, double cmg_mu, double cmg_k_null, pc_a8f rot_h0) {
    pc_a8f cmd_r = ((pc_a8f){0});
    pc_a4f cmd_g = ((pc_a4f){0});
    cmd_r = cmd_r0;
    cmd_g = cmd_g0;
    pc_a8i fixed = ((pc_a8i){0});
    int64_t nf = INT64_C(0);
    {
        int64_t end__123 = nr;
        int64_t i = INT64_C(0);
        while (i < end__123) {
            if (((rot_gi.v[(i)] == INT64_C(0)) && (!rot_failed.v[(i)]))) {
                fixed.v[(nf)] = i;
                nf = (nf + INT64_C(1));
            }
            i += 1;
        }
    }
    if ((nf > INT64_C(0))) {
        pc_a3a8f af = ((pc_a3a8f){0});
        {
            int64_t end__124 = nf;
            int64_t i = INT64_C(0);
            while (i < end__124) {
                {
                    int64_t end__125 = INT64_C(3);
                    int64_t k = INT64_C(0);
                    while (k < end__125) {
                        af.v[(k)].v[(i)] = a.v[(k)].v[(fixed.v[(i)])];
                        k += 1;
                    }
                }
                i += 1;
            }
        }
        pc_a8a3f pi8 = math_pinv_rows(af, nf);
        {
            int64_t end__126 = nf;
            int64_t i = INT64_C(0);
            while (i < end__126) {
                cmd_r.v[(fixed.v[(i)])] = (-((((pi8.v[(i)].v[0] * tau_rot.v[0]) + (pi8.v[(i)].v[1] * tau_rot.v[1])) + (pi8.v[(i)].v[2] * tau_rot.v[2]))));
                i += 1;
            }
        }
    }
    if ((ng > INT64_C(0))) {
        bool wheels = false;
        {
            int64_t end__127 = nr;
            int64_t i = INT64_C(0);
            while (i < end__127) {
                if ((rot_kind.v[(i)] == INT64_C(3))) {
                    wheels = true;
                }
                i += 1;
            }
        }
        allocation_steer_sr_out t__128 = allocation_steer_sr(tau_rot, a, zh, nr, ng, rot_gi, gim_axis, gim_rate_max, cmg_lam0, cmg_mu, wheels);
        pc_a4f gd = t__128.gdot;
        pc_a8f hd = t__128.hdot;
        {
            int64_t end__129 = ng;
            int64_t j = INT64_C(0);
            while (j < end__129) {
                cmd_g.v[(j)] = gd.v[(j)];
                j += 1;
            }
        }
        if (wheels) {
            {
                int64_t end__130 = nr;
                int64_t i = INT64_C(0);
                while (i < end__130) {
                    if ((rot_gi.v[(i)] > INT64_C(0))) {
                        cmd_r.v[(i)] = (hd.v[(i)] - (cmg_k_null * (zh.v[(i)] - rot_h0.v[(i)])));
                    }
                    i += 1;
                }
            }
        }
    }
    {
        steplaws_alloc_rotors_out r__;
        r__.cmd_r = cmd_r;
        r__.cmd_g = cmd_g;
        return r__;
    }
}

pc_a8f steplaws_alloc_idle(pc_a8f cmd_r0, int64_t nr, pc_a8f zh, pc_a8f h_t_rot, pc_a8i rot_gi, pc_a8i rot_kind, bool zero_cmg) {
    pc_a8f cmd_r = ((pc_a8f){0});
    cmd_r = cmd_r0;
    {
        int64_t end__131 = nr;
        int64_t i = INT64_C(0);
        while (i < end__131) {
            cmd_r.v[(i)] = ((-(0.2)) * (zh.v[(i)] - h_t_rot.v[(i)]));
            if (((zero_cmg && (rot_gi.v[(i)] > INT64_C(0))) && (rot_kind.v[(i)] == INT64_C(2)))) {
                cmd_r.v[(i)] = 0.0;
            }
            i += 1;
        }
    }
    return cmd_r;
}

pc_a3f steplaws_orbit_acc(pc_a3f r, double mu) {
    pc_a3f a = ((pc_a3f){0});
    double rn = pc_norm_a3f(r);
    a = ((pc_a3f){0});
    if ((rn > 1.0)) {
        double r2 = (rn * rn);
        double zr = ((r.v[2] * r.v[2]) / r2);
        double k = ((-(mu)) / (r2 * rn));
        double f = ((((((-(1.5)) * 0.00108262668) * mu) * 6378137.0) * 6378137.0) / ((r2 * r2) * rn));
        a = ((pc_a3f){ { ((k * r.v[0]) + ((f * r.v[0]) * (1.0 - (5.0 * zr)))), ((k * r.v[1]) + ((f * r.v[1]) * (1.0 - (5.0 * zr)))), ((k * r.v[2]) + ((f * r.v[2]) * (3.0 - (5.0 * zr)))) } });
    }
    return a;
}
