function [mx, mmt, c, d, u, s] = algebra(x, y, rate)
%ALGEBRA  Matrix and vector algebra: M x, M M^T, cross, dot, unit, and element assignment.
%   x: real[m][3] (passed in m)
%   y: real[m][3] (passed in m)
%   rate: real[1/s] (passed in 1/s)
%   returns mx: real[m/s][3] (passed in m/s)
%   returns mmt: real[1/s^2][3][3] (passed in 1/s^2)
%   returns c: real[m^2][3] (passed in m^2)
%   returns d: real[m^2] (passed in m^2)
%   returns u: real[1][3] (passed a plain number)
%   returns s: real[m][3] (passed in m)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    mx = zeros(3, 1);
    mmt = zeros(3, 3);
    c = zeros(3, 1);
    d = 0;
    u = zeros(3, 1);
    s = zeros(3, 1);
    M = [([rate; 0; 0]).'; ([0; (2 * rate); 0]).'; ([0; 0; (3 * rate)]).'];
    M(1, 2) = (0.5 * rate);
    M(3, :) = [rate; rate; rate].';
    mx = [M(1, 1)*x(1) + M(1, 2)*x(2) + M(1, 3)*x(3); M(2, 1)*x(1) + M(2, 2)*x(2) + M(2, 3)*x(3); M(3, 1)*x(1) + M(3, 2)*x(2) + M(3, 3)*x(3)];
    mmt = asils.pc.mm(M, (M).');
    c = [x(2)*y(3) - x(3)*y(2); x(3)*y(1) - x(1)*y(3); x(1)*y(2) - x(2)*y(1)];
    d = (x(1)*y(1) + x(2)*y(2) + x(3)*y(3));
    u = asils.pc.unit_((x - y));
    s = ((((-(x)) + (2 * y)) - [1.0; 0.0; 0.0]) + (x / 2));
end
