function [n, v] = domain(x)
%DOMAIN  Outside the real domain sqrt, asin, acos, log, log10, log2 and pow give nan in every translation, as C's, Rust's and the
%   interpreter's do (MATLAB's own are complex there: its runtime's asils.pc.sqrt_ and the rest give nan). Which are nan, as
%   bits, and a value from inside the domain.
%   x: real[1] (passed a plain number)
%   returns n: int (passed a whole number)
%   returns v: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    n = 0;
    v = 0;
    n = 0;
    h__35 = x;
    if h__35 < 0, h__35 = NaN; else, h__35 = sqrt(h__35); end
    if isnan(h__35)
        n = (n + 1);
    end
    h__36 = asin(x);
    if ~isreal(h__36), h__36 = NaN; end
    if isnan(h__36)
        n = (n + 2);
    end
    h__37 = acos(x);
    if ~isreal(h__37), h__37 = NaN; end
    if isnan(h__37)
        n = (n + 4);
    end
    h__38 = log(x);
    if ~isreal(h__38), h__38 = NaN; end
    if isnan(h__38)
        n = (n + 8);
    end
    h__39 = log10(x);
    if ~isreal(h__39), h__39 = NaN; end
    if isnan(h__39)
        n = (n + 16);
    end
    h__40 = log2(x);
    if ~isreal(h__40), h__40 = NaN; end
    if isnan(h__40)
        n = (n + 32);
    end
    h__41 = (x)^(0.5);
    if ~isreal(h__41), h__41 = NaN; end
    if isnan(h__41)
        n = (n + 64);
    end
    if (x >= 0)
        h__43 = x;
        if h__43 < 0, h__43 = NaN; else, h__43 = sqrt(h__43); end
        h__44 = log((x + 1));
        if ~isreal(h__44), h__44 = NaN; end
        h__42 = (h__43 + h__44);
    else
        h__45 = acos((x / 3));
        if ~isreal(h__45), h__45 = NaN; end
        h__42 = h__45;
    end
    v = h__42;
end
