function [y, w, g] = jitter(g, x)
%JITTER  A stream handed in by reference, as a model's noise is: drawn from and given back.
%   g: inout stream (passed a random stream, as six numbers)
%   x: real[1] (passed a plain number)
%   returns y: real[1] (passed a plain number)
%   returns w: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    y = 0;
    w = 0;
    [t__27, t__28] = asils.pc.stream_uniform(g);
    u = t__27;
    g = t__28;
    y = (x + u);
    [t__29, t__30] = asils.pc.stream_normal(g);
    w = t__29;
    g = t__30;
end
