function [y, seen, st] = least(st, x)
%LEAST  The least value seen, from a state that starts at inf.
%   x: real[s] (passed in s)
%   returns y: real[s] (passed in s)
%   returns seen: bool (passed true or false)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    if isempty(st)
        st = struct();
        st.low = Inf;
    end
    y = 0;
    seen = false;
    h__28 = st.low;
    h__29 = x;
    if h__29 < h__28, h__28 = h__29; end
    st.low = h__28;
    seen = isfinite(st.low);
    if seen
        h__30 = st.low;
    else
        h__30 = 0;
    end
    y = h__30;
end
