function [y, z] = lookup(t)
%LOOKUP  t: real[s] (passed in s)
%   returns y: real[m] (passed in m)
%   returns z: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    y = 0;
    z = 0;
    [x0, yy, zz] = asils.pcselftest.selftest.curve(t);
    y = yy;
    z = zz;
end
