function [first, capped, fin, nn, k, z] = nonfinite(x, y, n)
%NONFINITE  Values that are not finite: inf and nan take any unit, as a bare 0 does; isnan and isfinite test them.
%   x: real[s] (passed in s)
%   y: real[1] (passed a plain number)
%   n: int (passed a whole number)
%   returns first: real[s] (passed in s)
%   returns capped: real[s] (passed in s)
%   returns fin: bool (passed true or false)
%   returns nn: bool (passed true or false)
%   returns k: int (passed a whole number)
%   returns z: real[s] (passed in s)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    first = 0;
    capped = 0;
    fin = false;
    nn = false;
    k = 0;
    z = 0;
    t = Inf;
    if (x < 0)
        t = (-(Inf));
    end
    h__19 = x;
    h__20 = (Inf * 1);
    if h__20 < h__19, h__19 = h__20; end
    first = h__19;
    h__21 = x;
    h__22 = (-(Inf));
    if h__22 > h__21, h__21 = h__22; end
    h__22 = 2;
    if h__22 < h__21, h__21 = h__22; end
    capped = h__21;
    fin = (isfinite(t) || isfinite((y / n)));
    q = ((y - y) / (y - y));
    nn = ((isnan(q) && (~isnan(y))) && (~isnan(n)));
    if isfinite(t)
        h__23 = 1;
    else
        if (t > 0)
            h__24 = 2;
        else
            h__24 = 3;
        end
        h__23 = h__24;
    end
    k = h__23;
    if isfinite(t)
        h__25 = t;
    else
        h__26 = (-(Inf));
        h__27 = x;
        if h__27 > h__26, h__26 = h__27; end
        h__25 = h__26;
    end
    z = h__25;
end
