function [lo, hi, cl, ri, fl, fm, q, ni, pick, pos] = numbers(a, b, n, m)
%NUMBERS  Integers, booleans, min/max/clamp, rounding, fmod and the inline if.
%   a: real[1] (passed a plain number)
%   b: real[1] (passed a plain number)
%   n: int (passed a whole number)
%   m: int (passed a whole number)
%   returns lo: real[1] (passed a plain number)
%   returns hi: real[1] (passed a plain number)
%   returns cl: real[1] (passed a plain number)
%   returns ri: real[1] (passed a plain number)
%   returns fl: real[1] (passed a plain number)
%   returns fm: real[1] (passed a plain number)
%   returns q: real[1] (passed a plain number)
%   returns ni: int (passed a whole number)
%   returns pick: real[1] (passed a plain number)
%   returns pos: bool (passed true or false)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    lo = 0;
    hi = 0;
    cl = 0;
    ri = 0;
    fl = 0;
    fm = 0;
    q = 0;
    ni = 0;
    pick = 0;
    pos = false;
    lo = asils.pc.fmin(asils.pc.fmin(a, b), 0);
    hi = asils.pc.fmax(a, b);
    cl = asils.pc.clamp(a, (-(1)), b);
    ri = round((a * 2.5));
    fl = (floor(a) + ceil(b));
    fm = rem(a, 0.75);
    q = (n / m);
    ni = ((asils.pc.clamp((n * m), (-(10)), 10) + asils.pc.fmax(n, m)) - asils.pc.fmin(n, 2));
    pick = asils.pc.choose((a > b), asils.pc.ipow(a, 2), (-(asils.pc.ipow(b, 3))));
    pos = (((a > 0) && (~(b > 0))) || (n == 0));
end
