function s = Probe_zero()
%PROBE_ZERO  a Probe with every field zero
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = struct();
    s.v = zeros(3, 1);
    s.k = 0;
    s.seen = false;
    s.m = zeros(3, 3);
end
