function s = Unit_zero()
%UNIT_ZERO  a Unit with every field zero
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = struct();
    s.kind = 0;
    s.h = 0;
end
