function [m, disp] = sensor_misalignment(sigma, disp)
%SENSOR_MISALIGNMENT  The matrix of a sensor's misalignment: a small rotation of three normal draws times sigma [rad] (sensors.rs mis).
%   sigma: real[1] (passed a plain number)
%   disp: inout stream (passed a random stream, as six numbers)
%   returns m: real[1][3][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    m = zeros(3, 3);
    [t__583, t__584] = asils.pc.stream_normal3(disp);
    e = t__583;
    disp = t__584;
    m = asils.models.coildisp.small_rotation((e * sigma));
end
