function [m, disp] = sensor_scale(sigma, disp)
%SENSOR_SCALE  The diagonal matrix of a sensor's scale factors, 1 + sigma n on each axis in turn (sensors.rs sf).
%   sigma: real[1] (passed a plain number)
%   disp: inout stream (passed a random stream, as six numbers)
%   returns m: real[1][3][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    m = zeros(3, 3);
    [t__497, t__498] = asils.pc.stream_normal(disp);
    z0 = t__497;
    disp = t__498;
    [t__499, t__500] = asils.pc.stream_normal(disp);
    z1 = t__499;
    disp = t__500;
    [t__501, t__502] = asils.pc.stream_normal(disp);
    z2 = t__501;
    disp = t__502;
    m = [([(1 + (sigma * z0)); 0; 0]).'; ([0; (1 + (sigma * z1)); 0]).'; ([0; 0; (1 + (sigma * z2))]).'];
end
