function [m, disp] = sensor_matrix(misalign, sf_sigma, disp)
%SENSOR_MATRIX  A sensor's matrix (true axes to measured): its misalignment times its scale factors, drawn in that order.
%   misalign: real[1] (passed a plain number)
%   sf_sigma: real[1] (passed a plain number)
%   disp: inout stream (passed a random stream, as six numbers)
%   returns m: real[1][3][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    m = zeros(3, 3);
    [t__591, t__592] = asils.models.gyroaxes.sensor_misalignment(misalign, disp);
    a = t__591;
    disp = t__592;
    [t__593, t__594] = asils.models.gyroaxes.sensor_scale(sf_sigma, disp);
    b = t__593;
    disp = t__594;
    m = asils.pc.mm(a, b);
end
