function [q] = boresight_offset(bs_in)
%BORESIGHT_OFFSET  The rotation taking +Y_B (the nadir axis of the base frame) to the payload axis.
%   bs_in: real[1][3] (passed a plain number)
%   returns q: real[1][4] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    q = zeros(4, 1);
    ey = [0; 1; 0];
    bs = asils.pc.unit_(bs_in);
    ax = asils.pc.cross_(ey, bs);
    c = asils.pc.dot_(ey, bs);
    s = asils.pc.norm_(ax);
    if (s < 1e-12)
        q = [0; 0; 0; 1];
        if (c <= 0)
            q = [1; 0; 0; 0];
        end
    else
        k = (ax * (1 / s));
        kk = asils.groups.shared.skew(k);
        k2 = asils.pc.mm(kk, kk);
        a = zeros(3, 3);
        for i = (0):((3) - 1)
            for j = (0):((3) - 1)
                a((i) + 1, (j) + 1) = ((asils.pc.choose((i == j), 1, 0) + (s * kk((i) + 1, (j) + 1))) + ((1 - c) * k2((i) + 1, (j) + 1)));
            end
        end
        q = asils.groups.shared.fromdcm(a);
    end
end
