function [p] = wheel_power(p_steady, tm, om, eta)
%WHEEL_POWER  The power [W]: p_steady + |tm om|/eta.
%   p_steady: real[1] (passed a plain number)
%   tm: real[1] (passed a plain number)
%   om: real[1] (passed a plain number)
%   eta: real[1] (passed a plain number)
%   returns p: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    p = 0;
    p = (p_steady + (asils.pc.fabs((tm * om)) / eta));
end
