function [d] = delaunay(t)
%DELAUNAY  The IERS 2010 Delaunay arguments l, l', F, D, Om [rad] at t Julian centuries.
%   t: real[1] (passed a plain number)
%   returns d: real[1][5] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    d = zeros(5, 1);
    as2r = 0.00000484813681109536;
    d(1) = (asils.models.timescales.omod((485868.249036 + (t * (1717915923.2178 + (t * (31.8792 + (t * (0.051635 + (t * (-(0.0002447)))))))))), 1296000) * as2r);
    d(2) = (asils.models.timescales.omod((1287104.793048 + (t * (129596581.0481 + (t * ((-(0.5532)) + (t * (0.000136 + (t * (-(0.00001149)))))))))), 1296000) * as2r);
    d(3) = (asils.models.timescales.omod((335779.526232 + (t * (1739527262.8478 + (t * ((-(12.7512)) + (t * ((-(0.001037)) + (t * 0.00000417)))))))), 1296000) * as2r);
    d(4) = (asils.models.timescales.omod((1072260.703692 + (t * (1602961601.209 + (t * ((-(6.3706)) + (t * (0.006593 + (t * (-(0.00003169)))))))))), 1296000) * as2r);
    d(5) = (asils.models.timescales.omod((450160.398036 + (t * ((-(6962890.5431)) + (t * (7.4722 + (t * (0.007702 + (t * (-(0.00005939)))))))))), 1296000) * as2r);
end
