function [arg] = libration_args(rmjd)
%LIBRATION_ARGS  [GMST + pi, l, l', F, D, Om] [rad] as PMSDNUT2 and UTLIBR build them, at a modified Julian date.
%   rmjd: real[1] (passed a plain number)
%   returns arg: real[1][6] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    arg = zeros(6, 1);
    t = ((rmjd - 51544.5) / 36525);
    d = asils.models.tidaleop.delaunay(t);
    gmst = asils.models.timescales.omod((67310.54841 + (t * ((8640184.812866 + 3155760000) + (t * (0.093104 + (t * (-(0.0000062)))))))), 86400);
    arg = [asils.models.timescales.omod(((gmst / (86400 / (2 * pi))) + pi), (2 * pi)); d(1); d(2); d(3); d(4); d(5)];
end
