function [dxp, dyp, dut1] = tidal_eop(mjd)
%TIDAL_EOP  The full sub-daily correction: ocean tides plus the libration in polar motion and UT1 [micro-arcsec, micro-s].
%   mjd: real[1] (passed a plain number)
%   returns dxp: real[1] (passed a plain number)
%   returns dyp: real[1] (passed a plain number)
%   returns dut1: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    dxp = 0;
    dyp = 0;
    dut1 = 0;
    [ox, oy, ou] = asils.models.tidaleop.tidal_eop_ocean(mjd);
    [px, py] = asils.models.tidaleop.tidal_pm_libration(mjd);
    [uu, ul] = asils.models.tidaleop.tidal_ut1_libration(mjd);
    dxp = (ox + px);
    dyp = (oy + py);
    dut1 = (ou + uu);
end
