function [dut1] = tidal_ut1_zonal(mjd)
%TIDAL_UT1_ZONAL  RG_ZONT2: the zonal-tide variation of UT1 [s] (62 terms), to regularise UT1 before it is interpolated.
%   mjd: real[1] (passed a plain number)
%   returns dut1: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    dut1 = 0;
    D__TIDAL_UT1_ZONAL = asils.models.tidaleopterms.TIDAL_UT1_ZONAL();
    t = ((mjd - 51544.5) / 36525);
    d = asils.models.tidaleop.delaunay(t);
    acc = 0;
    for r = (0):((62) - 1)
        a = asils.models.timescales.omod((((((D__TIDAL_UT1_ZONAL((r) + 1, 1) * d(1)) + (D__TIDAL_UT1_ZONAL((r) + 1, 2) * d(2))) + (D__TIDAL_UT1_ZONAL((r) + 1, 3) * d(3))) + (D__TIDAL_UT1_ZONAL((r) + 1, 4) * d(4))) + (D__TIDAL_UT1_ZONAL((r) + 1, 5) * d(5))), (2 * pi));
        acc = (acc + ((D__TIDAL_UT1_ZONAL((r) + 1, 7) * sin(a)) + (D__TIDAL_UT1_ZONAL((r) + 1, 8) * cos(a))));
    end
    dut1 = (acc * 0.0001);
end
