function [xd] = plant_deriv(x, inertia, iinv, minv, m, f, tau_ext, tau_r, gdot)
%PLANT_DERIV  The state's rate under the external torque tau_ext [N m] (body), the rotors' torques tau_r [N m] along their axes and
%   the gimbal rates gdot [rad/s]; inertia [kg m^2] and its inverse iinv, minv the inverse of the reduced inertia (iinv
%   when the mode is off), m the rotors' geometry and f the flexible mode.
%   x: PlantState (passed rec)
%   inertia: real[1][3][3] (passed a plain number)
%   iinv: real[1][3][3] (passed a plain number)
%   minv: real[1][3][3] (passed a plain number)
%   m: RotorGeometry (passed rec)
%   f: Flex (passed rec)
%   tau_ext: real[1][3] (passed a plain number)
%   tau_r: real[1][DYN_NR] (passed a plain number)
%   gdot: real[1][DYN_NG] (passed a plain number)
%   returns xd: PlantState (passed rec)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    xd = asils.models.rigidbody.PlantState_zero();
    w = x.w;
    hr = [0; 0; 0];
    hd = [0; 0; 0];
    for ir = (0):((m.nr) - 1)
        a = (m.a0((ir) + 1, :)).';
        jg = m.gi((ir) + 1);
        if (jg > 0)
            dj = x.d(((jg - 1)) + 1);
            c = cos(dj);
            s = sin(dj);
            for k1 = (0):((3) - 1)
                a((k1) + 1) = ((c * m.a0((ir) + 1, (k1) + 1)) + (s * m.t0((ir) + 1, (k1) + 1)));
                ta = (((-(s)) * m.a0((ir) + 1, (k1) + 1)) + (c * m.t0((ir) + 1, (k1) + 1)));
                hd((k1) + 1) = (hd((k1) + 1) + ((x.h((ir) + 1) * gdot(((jg - 1)) + 1)) * ta));
            end
        end
        for k2 = (0):((3) - 1)
            hr((k2) + 1) = (hr((k2) + 1) + (a((k2) + 1) * x.h((ir) + 1)));
            hd((k2) + 1) = (hd((k2) + 1) + (a((k2) + 1) * tau_r((ir) + 1)));
        end
    end
    ht = [0; 0; 0];
    if f.on
        ht = ((asils.pc.mv(inertia, w) + hr) + (f.delta * x.etad));
    else
        ht = (asils.pc.mv(inertia, w) + hr);
    end
    g = asils.pc.cross_(w, ht);
    xd = asils.models.rigidbody.PlantState_zero();
    xd.q = asils.models.rigidbody.quat_rate(x.q, w);
    if f.on
        pull = asils.models.flexmode.flex_pull(f, x.eta, x.etad);
        rhs = [(((tau_ext(1) - hd(1)) - g(1)) + (f.delta(1) * pull)); (((tau_ext(2) - hd(2)) - g(2)) + (f.delta(2) * pull)); (((tau_ext(3) - hd(3)) - g(3)) + (f.delta(3) * pull))];
        wd = asils.pc.mv(minv, rhs);
        xd.w = wd;
        xd.eta = x.etad;
        xd.etad = ((-(pull)) - asils.pc.dot_(f.delta, wd));
    else
        rhs0 = [((tau_ext(1) - hd(1)) - g(1)); ((tau_ext(2) - hd(2)) - g(2)); ((tau_ext(3) - hd(3)) - g(3))];
        xd.w = asils.pc.mv(iinv, rhs0);
    end
    hdot = zeros(8, 1);
    for ih = (0):((m.nr) - 1)
        hdot((ih) + 1) = tau_r((ih) + 1);
    end
    ddot = zeros(4, 1);
    for jd = (0):((m.ng) - 1)
        ddot((jd) + 1) = gdot((jd) + 1);
    end
    xd.h = hdot;
    xd.d = ddot;
end
