function [T] = m2_5(r)
%M2_5  The node's answer, T, as circular_period gives it.
%   r: real[km] (passed in m)
%   returns T: real[s] (passed in s)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    T = 0;
    T = asils.groups.env.circular_period(r);
end
