function [B_max] = m3_1(r, lambda_max)
%M3_1  The node's answer, B_max, as dipole_field_max gives it.
%   r: real[km] (passed in m)
%   lambda_max: real[deg] (passed a plain number)
%   returns B_max: real[T] (passed in kg/(s^2 A))
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    B_max = 0;
    B_max = asils.groups.env.dipole_field_max(r, lambda_max);
end
