function [tau] = radiation_torque(g, sb, p)
%RADIATION_TORQUE  The torque [N m] of light of pressure p arriving from the body direction sb (unit, towards the source) on the faces.
%   g: Facets (passed rec)
%   sb: real[1][3] (passed a plain number)
%   p: real[Pa] (passed in kg/(m s^2))
%   returns tau: real[N m][3] (passed in m^2 kg/s^2)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    tau = zeros(3, 1);
    tau = [0; 0; 0];
    for j = (0):((6) - 1)
        c = asils.pc.dot_(sb, (g.n((j) + 1, :)).');
        if (~(c <= 0))
            f = [0; 0; 0];
            for k = (0):((3) - 1)
                f((k) + 1) = ((((-(p)) * g.a((j) + 1)) * c) * (((1 - g.rho_spec) * sb((k) + 1)) + ((2 * ((g.rho_spec * c) + (g.rho_diff / 3))) * g.n((j) + 1, (k) + 1))));
            end
            tau = (tau + asils.pc.cross_((g.rho((j) + 1, :)).', f));
        end
    end
end
