function [worst, tau_dist, h_dist, h_secular, dump_dflt, w0, w0_dflt, h_detumble, slew_deg, sangle_dflt, slew_s, slew_dflt, w_slew, a_slew, h_slew, tau_slew, life_yr, life_dflt, slews_per_day, k_h, h_req, tau_req, fine] = demand(tau_peak, h_cyclic, h_secular_orbit, t_orb, dump_h, w0_case, sangle_case, slew_case, life_case, spd_case, hsat, k_h_knob, k_tau, j, ake)
%DEMAND  What the case asks of an actuator, from the worst survey (tau_peak, h_cyclic, h_secular_orbit per attitude, the
%   orbit's period t_orb [s]), the case's lines (req.dump [h], mission.w0 [deg/s], mission.sangle [deg], req.slew [s],
%   mission.life [yr], mission.spd, req.hsat, req.ake [deg]: nan when blank), the momentum margin the loop sets (k_h_knob,
%   nan when it sets none), the torque margin k_tau and the principal moments j [kg m^2]:
%   - the worst attitude (the first of the largest peak torques) and its torque;
%   - the momentum held between dumps: req.dump hours of the secular momentum, or a quarter orbit's, with the cyclic;
%   - the detumble's momentum, the largest moment at the tip-off rate;
%   - the reference slew: twice its angle over its time (rate), 2 pi its angle over its time squared (acceleration), at
%   the largest moment;
%   - the margins: k_h (the loop's, else 1/(1 - req.hsat) for a stated share of saturation, else 2) on the larger of the
%   held and the slew's momentum, k_tau on the larger of the worst and the slew's torque;
%   - the fine class: a stated req.ake at most 0.05 deg.
%   Each default taken is said (the *_dflt flags).
%   tau_peak: real[1][4] (passed a plain number)
%   h_cyclic: real[1][4] (passed a plain number)
%   h_secular_orbit: real[1][4] (passed a plain number)
%   t_orb: real[1] (passed a plain number)
%   dump_h: real[1] (passed a plain number)
%   w0_case: real[1] (passed a plain number)
%   sangle_case: real[1] (passed a plain number)
%   slew_case: real[1] (passed a plain number)
%   life_case: real[1] (passed a plain number)
%   spd_case: real[1] (passed a plain number)
%   hsat: real[1] (passed a plain number)
%   k_h_knob: real[1] (passed a plain number)
%   k_tau: real[1] (passed a plain number)
%   j: real[1][3] (passed a plain number)
%   ake: real[1] (passed a plain number)
%   returns worst: int (passed a whole number)
%   returns tau_dist: real[1] (passed a plain number)
%   returns h_dist: real[1] (passed a plain number)
%   returns h_secular: real[1] (passed a plain number)
%   returns dump_dflt: bool (passed true or false)
%   returns w0: real[1] (passed a plain number)
%   returns w0_dflt: bool (passed true or false)
%   returns h_detumble: real[1] (passed a plain number)
%   returns slew_deg: real[1] (passed a plain number)
%   returns sangle_dflt: bool (passed true or false)
%   returns slew_s: real[1] (passed a plain number)
%   returns slew_dflt: bool (passed true or false)
%   returns w_slew: real[1] (passed a plain number)
%   returns a_slew: real[1] (passed a plain number)
%   returns h_slew: real[1] (passed a plain number)
%   returns tau_slew: real[1] (passed a plain number)
%   returns life_yr: real[1] (passed a plain number)
%   returns life_dflt: bool (passed true or false)
%   returns slews_per_day: real[1] (passed a plain number)
%   returns k_h: real[1] (passed a plain number)
%   returns h_req: real[1] (passed a plain number)
%   returns tau_req: real[1] (passed a plain number)
%   returns fine: bool (passed true or false)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    worst = 0;
    tau_dist = 0;
    h_dist = 0;
    h_secular = 0;
    dump_dflt = false;
    w0 = 0;
    w0_dflt = false;
    h_detumble = 0;
    slew_deg = 0;
    sangle_dflt = false;
    slew_s = 0;
    slew_dflt = false;
    w_slew = 0;
    a_slew = 0;
    h_slew = 0;
    tau_slew = 0;
    life_yr = 0;
    life_dflt = false;
    slews_per_day = 0;
    k_h = 0;
    h_req = 0;
    tau_req = 0;
    fine = false;
    [dw0, dsl, dss, dlf, dspd, dkh, dheld, dake] = asils.models.sizedemand.demand_defaults();
    worst = 0;
    for a = (0):((4) - 1)
        if (tau_peak((a) + 1) > tau_peak((worst) + 1))
            worst = a;
        end
    end
    tau_dist = tau_peak((worst) + 1);
    held = dheld;
    dump_dflt = true;
    if (isfinite(dump_h) && (dump_h > 0))
        held = ((dump_h * 3600) / t_orb);
        dump_dflt = false;
    end
    h_dist = (-(1.7976931348623157e+308));
    h_secular = (-(1.7976931348623157e+308));
    for a = (0):((4) - 1)
        h__125 = h_dist;
        h__126 = (h_cyclic((a) + 1) + (held * h_secular_orbit((a) + 1)));
        if h__126 > h__125, h__125 = h__126; end
        h_dist = h__125;
        h__127 = h_secular;
        h__128 = h_secular_orbit((a) + 1);
        if h__128 > h__127, h__127 = h__128; end
        h_secular = h__127;
    end
    w0_dflt = isnan(w0_case);
    if w0_dflt
        h__129 = dw0;
    else
        h__129 = w0_case;
    end
    w0 = h__129;
    jmax = (-(1.7976931348623157e+308));
    for i = (0):((3) - 1)
        h__130 = jmax;
        h__131 = j((i) + 1);
        if h__131 > h__130, h__130 = h__131; end
        jmax = h__130;
    end
    h_detumble = (((jmax * w0) * pi) / 180);
    sangle_dflt = isnan(sangle_case);
    if sangle_dflt
        h__132 = dsl;
    else
        h__132 = sangle_case;
    end
    slew_deg = h__132;
    slew_dflt = isnan(slew_case);
    if slew_dflt
        h__133 = dss;
    else
        h__133 = slew_case;
    end
    slew_s = h__133;
    w_slew = ((((2 * slew_deg) * pi) / 180) / slew_s);
    a_slew = (((((2 * pi) * slew_deg) * pi) / 180) / (slew_s * slew_s));
    h_slew = (jmax * w_slew);
    tau_slew = (jmax * a_slew);
    life_dflt = isnan(life_case);
    if life_dflt
        h__134 = dlf;
    else
        h__134 = life_case;
    end
    life_yr = h__134;
    if isnan(spd_case)
        h__135 = dspd;
    else
        h__135 = spd_case;
    end
    slews_per_day = h__135;
    if isnan(k_h_knob)
        k_h = dkh;
        if ((isfinite(hsat) && (hsat > 0)) && (hsat < 1))
            k_h = (1 / (1 - hsat));
        end
    else
        k_h = k_h_knob;
    end
    h_req = (k_h * asils.models.sizedemand.size_max(h_dist, h_slew));
    tau_req = (k_tau * asils.models.sizedemand.size_max(tau_dist, tau_slew));
    fine = (isfinite(ake) && (ake <= dake));
end
