function [c] = size_min(a, b)
%SIZE_MIN  The smaller of a and b as the code's f64::min takes it: a value that is not a number left out, equal values the first.
%   a: real[1] (passed a plain number)
%   b: real[1] (passed a plain number)
%   returns c: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    c = 0;
    if isnan(a)
        c = b;
    else
        h__114 = a;
        h__115 = b;
        if h__115 < h__114, h__114 = h__115; end
        c = h__114;
    end
end
