function [c] = size_max(a, b)
%SIZE_MAX  The larger of a and b as the code's f64::max takes it: a value that is not a number left out, equal values the first.
%   a: real[1] (passed a plain number)
%   b: real[1] (passed a plain number)
%   returns c: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    c = 0;
    if isnan(a)
        c = b;
    else
        h__112 = a;
        h__113 = b;
        if h__113 > h__112, h__112 = h__113; end
        c = h__112;
    end
end
