function [epoch_days, f107] = survey_sweep(i)
%SURVEY_SWEEP  The season and the solar activity of survey i (seasons outer, activities inner): the days from the case's epoch to
%   the season (a quarter year apart) and the F10.7 index [sfu] the density takes (ECSS-E-ST-10-04C's long-term low and
%   high), its 81-day mean the same.
%   i: int (passed a whole number)
%   returns epoch_days: real[1] (passed a plain number)
%   returns f107: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    epoch_days = 0;
    f107 = 0;
    days = [0; 91.3; 182.6; 273.9];
    flux = [65; 250];
    epoch_days = days((fix((i) / (2))) + 1);
    f107 = flux((rem(i, 2)) + 1);
end
