function [spots, ns, img, work, ia, ib] = st_centroid(img, cam, work, ia, ib)
%ST_CENTROID  The spots of a frame (n x n, column by column): the background bg as the median of the frame and its spread as 1.4826
%   times the median absolute deviation (in work); the pixels above bg + k_sigma times it, brightest first (equal ones
%   column by column; in ia, over ib); each more than 2 pixels inside the edge and 4 or more (in x or y) from every spot
%   already found gives a spot: the centre of gravity of the background-subtracted 5 x 5 window round it (negatives as 0),
%   [x, y, flux (e-)], until max_spots. How many.
%   length: 576
%   img: inout real[1][*] (passed a plain number)
%   cam: StCamera (passed rec)
%   work: inout real[1][*] (passed a plain number)
%   ia: inout int[*] (passed a whole number)
%   ib: inout int[*] (passed a whole number)
%   returns spots: real[1][3][ST_SPOTS] (passed a plain number)
%   returns ns: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    spots = zeros(32, 3);
    ns = 0;
    n = cam.n;
    np = (n * n);
    for l = (0):((np) - 1)
        work((l) + 1) = img((l) + 1);
    end
    [t__218, t__219] = asils.models.stcentroid.st_median(work, np);
    bg = t__218;
    work = t__219;
    for l2 = (0):((np) - 1)
        work((l2) + 1) = asils.pc.fabs((img((l2) + 1) - bg));
    end
    [t__220, t__221] = asils.models.stcentroid.st_median(work, np);
    mad = t__220;
    work = t__221;
    sg = (1.4826 * mad);
    thr = (bg + (cam.k_sigma * sg));
    m = 0;
    for l3 = (0):((np) - 1)
        if (img((l3) + 1) > thr)
            ia((m) + 1) = l3;
            m = (m + 1);
        end
    end
    [t__222, t__223, t__224, t__225] = asils.models.stcentroid.st_sort_desc(img, ia, ib, m);
    passes = t__222;
    img = t__223;
    ia = t__224;
    ib = t__225;
    cap = asils.pc.fmin(cam.max_spots, 32);
    ns = 0;
    done = false;
    for q = (0):((m) - 1)
        if (~done)
            l4 = ia((q) + 1);
            x = (fix((l4) / (n)) + 1);
            y = (rem(l4, n) + 1);
            if (~((((x < 3) || (y < 3)) || (x > (n - 2))) || (y > (n - 2))))
                xf = x;
                yf = y;
                near = false;
                for s = (0):((ns) - 1)
                    if ((asils.pc.fabs((spots((s) + 1, 1) - xf)) < 4) && (asils.pc.fabs((spots((s) + 1, 2) - yf)) < 4))
                        near = true;
                    end
                end
                if (~near)
                    tot = 0;
                    sx = 0;
                    sy = 0;
                    for c = (0):((5) - 1)
                        for r = (0):((5) - 1)
                            w = asils.pc.fmax((img(((((((x + c) - 2) - 1) * n) + (((y + r) - 2) - 1))) + 1) - bg), 0);
                            tot = (tot + w);
                            sx = (sx + ((c - 2) * w));
                            sy = (sy + ((r - 2) * w));
                        end
                    end
                    spots((ns) + 1, :) = [(xf + (sx / tot)); (yf + (sy / tot)); tot].';
                    ns = (ns + 1);
                    if (ns >= cap)
                        done = true;
                    end
                end
            end
        end
    end
end
