function [passes, key, ix, tmp] = st_sort_desc(key, ix, tmp, m)
%ST_SORT_DESC  Order ix[0..m] by key (descending), equal keys in the order given: a bottom-up merge sort over tmp. How many passes.
%   length: 64
%   key: inout real[1][*] (passed a plain number)
%   ix: inout int[*] (passed a whole number)
%   tmp: inout int[*] (passed a whole number)
%   m: int (passed a whole number)
%   returns passes: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    passes = 0;
    passes = 0;
    w = 1;
    for it = (0):((62) - 1)
        if (w < m)
            if (rem(passes, 2) == 0)
                [t__150, t__151, t__152, t__153] = asils.models.stcentroid.st_merge_desc(key, ix, tmp, m, w);
                z0 = t__150;
                key = t__151;
                ix = t__152;
                tmp = t__153;
            else
                [t__154, t__155, t__156, t__157] = asils.models.stcentroid.st_merge_desc(key, tmp, ix, m, w);
                z1 = t__154;
                key = t__155;
                tmp = t__156;
                ix = t__157;
            end
            passes = (passes + 1);
            w = (2 * w);
        end
    end
    if (rem(passes, 2) == 1)
        for i = (0):((m) - 1)
            ix((i) + 1) = tmp((i) + 1);
        end
    end
end
