function [passes, key, ix, tmp] = st_sort_desc(key, ix, tmp, m)
%ST_SORT_DESC  Order ix[0..m] by key (descending), equal keys in the order given: a bottom-up merge sort over tmp. How many passes.
%   length: 64
%   key: inout real[1][*] (passed a plain number)
%   ix: inout int[*] (passed a whole number)
%   tmp: inout int[*] (passed a whole number)
%   m: int (passed a whole number)
%   returns passes: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    passes = 0;
    passes = 0;
    w = 1;
    for it = (0):((62) - 1)
        if (w < m)
            if (rem(passes, 2) == 0)
                [t__614, t__615, t__616, t__617] = asils.models.stcentroid.st_merge_desc(key, ix, tmp, m, w);
                z0 = t__614;
                key = t__615;
                ix = t__616;
                tmp = t__617;
            else
                [t__618, t__619, t__620, t__621] = asils.models.stcentroid.st_merge_desc(key, tmp, ix, m, w);
                z1 = t__618;
                key = t__619;
                tmp = t__620;
                ix = t__621;
            end
            passes = (passes + 1);
            w = (2 * w);
        end
    end
    if (rem(passes, 2) == 1)
        for i = (0):((m) - 1)
            ix((i) + 1) = tmp((i) + 1);
        end
    end
end
