"""The offline pages (tools/pages.py) and TRI-NETRA Files in a real browser (docs/RELEASE_PLAN.md P3).

The browser test (tests/browser/files.test.mjs) needs Node.js, Playwright and Chromium; without
them it is skipped, and says so. Owner: Agastya. Copyright (c) 2026 Agastya. All rights reserved.
"""
import os
import pathlib
import shutil
import sqlite3
import subprocess
import sys
import tempfile
import unittest

import _path  # puts tools/ on the import path
import pages
import tndb

_ = _path  # imported for its effect: tools/ on sys.path

ROOT = pathlib.Path(__file__).resolve().parents[1]
NODE = shutil.which("node")
# Playwright as CI installs it (PLAYWRIGHT_MODULE, .github/workflows/ci.yml) or as this machine has it
PLAYWRIGHT = next((pathlib.Path(p) for p in (os.environ.get("PLAYWRIGHT_MODULE"), "/opt/node22/lib/node_modules/playwright/index.mjs")
                   if p and pathlib.Path(p).is_file()), None)


def node_file(path, version=None):
    def fill(c):
        c.execute("INSERT INTO node VALUES ('n1', 'sheet', 'act', 's1', 'l3', 'computed', 'Wheel torque', 'draft', 'A. Author', 1)")
        c.executemany("INSERT INTO content VALUES (?, ?, ?, ?)",
                      [("theory", "equation", "tau = J*wdot", "seed"), ("theory", "value", "0.1", "seed")])
    tndb.create(path, "node", "n1", fill=fill, sync=False)
    if version:
        with sqlite3.connect(path) as c:
            c.execute("UPDATE meta SET value = ? WHERE key = 'format_version'", (str(version),))


class Rules(unittest.TestCase):
    def test_every_page_builds_and_keeps_the_rules(self):
        with tempfile.TemporaryDirectory() as d:
            for _name, (p, n) in pages.build(d).items():
                self.assertLess(n, pages.MAX_PAGE_BYTES)
                text = p.read_text()
                self.assertIn("Generated by tools/pages.py", text)
                self.assertNotRegex(text, pages.OUTSIDE)

    def test_a_page_that_makes_its_own_button_is_refused(self):
        self.assertTrue(pages.component_problems_text("x.js", 'const b = h("button", {}, "Go");'))
        self.assertTrue(pages.component_problems_text("x.js", "el.style.color = 'red';"))
        self.assertTrue(pages.component_problems_text("x.js", "el.innerHTML = s;"))
        self.assertFalse(pages.component_problems_text("x.js", 'const b = button("Go", f);'))

    def test_an_outside_host_is_found(self):
        for s in ['<script src="https://cdn.example/x.js">', "url('https://fonts.example/a.woff2')", '@import url("http://x/y.css")',
                  'fetch("https://api.example/")', 'import("https://esm.example/m.js")']:
            self.assertRegex(s, pages.OUTSIDE, s)
        self.assertNotRegex("// see https://github.com/kripken/emscripten/issues/5820", pages.OUTSIDE)

    def test_a_vendored_file_that_differs_from_its_pin_is_refused(self):
        with tempfile.TemporaryDirectory() as d:
            v = pathlib.Path(d) / "vendor"
            shutil.copytree(ROOT / "design" / "vendor", v)
            f = v / "fonts" / "inter-latin-400-normal.woff2"
            f.write_bytes(f.read_bytes() + b"x")
            with self.assertRaises(pages.PageError) as e:
                pages.vendored(v)
            self.assertIn("VENDOR.toml pins", str(e.exception))


@unittest.skipUnless(NODE and PLAYWRIGHT, "Node.js and Playwright (with its Chromium) are needed for the browser test")
class Browser(unittest.TestCase):
    def test_files_in_the_browser(self):
        with tempfile.TemporaryDirectory() as d:
            d = pathlib.Path(d)
            page = pages.build(d / "pages")["files"][0]
            node_file(d / "n1.node.tndb")
            node_file(d / "newer.node.tndb", version=2)
            r = subprocess.run([NODE, str(ROOT / "tests" / "browser" / "files.test.mjs"), str(page), str(d)],
                               capture_output=True, text=True, timeout=600, env={**os.environ, "PLAYWRIGHT_MODULE": str(PLAYWRIGHT)})
            sys.stdout.write(r.stdout[-4000:])
            self.assertEqual(r.returncode, 0, r.stdout[-4000:] + r.stderr[-2000:])
            # what the page wrote is a design file tools/tndb.py accepts, with the change and its revision
            saved = d / "saved.node.tndb"
            self.assertEqual(tndb.check(saved), [])
            with sqlite3.connect(saved) as c:
                self.assertEqual(c.execute("SELECT value FROM content WHERE field = 'value'").fetchone()[0], "0.25")
                self.assertEqual(c.execute("SELECT by FROM revision").fetchall(), [("Asha",)])


if __name__ == "__main__":
    unittest.main()
