function [m, me, p, s] = coilset_apply(s, d, m_cmd, dt)
%COILSET_APPLY  The body dipole command [A m^2] held for dt: (the true body dipole averaged over the step, the true body dipole at
%   its end, the power [W]).
%   s: inout CoilSet (passed rec)
%   d: CoilDesc (passed rec)
%   m_cmd: real[1][3] (passed a plain number)
%   dt: real[1] (passed a plain number)
%   returns m: real[1][3] (passed a plain number)
%   returns me: real[1][3] (passed a plain number)
%   returns p: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    m = zeros(3, 1);
    me = zeros(3, 1);
    p = 0;
    m = [0; 0; 0];
    me = [0; 0; 0];
    p = 0;
    for j = (0):((d.n) - 1)
        mc = asils.models.coilsat.coil_command((s.pinv((j) + 1, :)).', m_cmd, d.m_max);
        if s.dead((j) + 1)
            mc = 0;
            s.m((j) + 1) = 0;
        end
        [e, av] = asils.models.coillag.coil_lag(s.m((j) + 1), mc, d.tau, dt);
        s.m((j) + 1) = e;
        s.mc((j) + 1) = mc;
        p = (p + asils.models.coilpower.coil_power(av, d.m_max, d.p_max));
        m = (m + ((s.a((j) + 1, :)).' * (av * s.scale((j) + 1))));
        me = (me + ((s.a((j) + 1, :)).' * (e * s.scale((j) + 1))));
    end
end
