function [s, disp] = coilset_new(d, disp)
%COILSET_NEW  The coil set of a description, its dispersion drawn from disp.
%   d: CoilDesc (passed rec)
%   disp: inout stream (passed a random stream, as six numbers)
%   returns s: CoilSet (passed rec)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = asils.models.coilset.CoilSet_zero();
    s = asils.models.coilset.CoilSet_zero();
    [t__4, t__5, t__6] = asils.models.coildisp.coil_dispersion(d.n, d.axes, d.scale_sigma, d.misalign, disp);
    sc = t__4;
    a = t__5;
    disp = t__6;
    s.scale = sc;
    s.a = a;
    s.pinv = asils.models.coilaxes.coil_allocation(d.axes, d.n);
end
