function [f] = denorm_factor(n, m)
%DENORM_FACTOR  denormFactor(n, m) of grav.sphericalHarmonic: sqrt((2 - d0m)(2n + 1)/((n - m + 1)...(n + m))).
%   n: int (passed a whole number)
%   m: int (passed a whole number)
%   returns f: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    f = 0;
    if (m == 0)
        h__268 = 1;
    else
        h__268 = 2;
    end
    d = h__268;
    p = 1;
    for k = (((n - m) + 1)):((((n + m) + 1)) - 1)
        p = (p * k);
    end
    h__269 = ((d * ((2 * n) + 1)) / p);
    if h__269 < 0, h__269 = NaN; else, h__269 = sqrt(h__269); end
    f = h__269;
end
