function [ae] = from_ecef(c, a)
%FROM_ECEF  forces.gravity's frames: a_eci = C' a_ecef.
%   c: real[1][3][3] (passed a plain number)
%   a: real[1][3] (passed a plain number)
%   returns ae: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    ae = zeros(3, 1);
    h__290 = (c).';
    ae = [h__290(1, 1)*a(1) + h__290(1, 2)*a(2) + h__290(1, 3)*a(3); h__290(2, 1)*a(1) + h__290(2, 2)*a(2) + h__290(2, 3)*a(3); h__290(3, 1)*a(1) + h__290(3, 2)*a(2) + h__290(3, 3)*a(3)];
end
