function [ae] = from_ecef(c, a)
%FROM_ECEF  forces.gravity's frames: a_eci = C' a_ecef.
%   c: real[1][3][3] (passed a plain number)
%   a: real[1][3] (passed a plain number)
%   returns ae: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    ae = zeros(3, 1);
    ae = asils.pc.mv((c).', a);
end
