function [n] = onorm(v)
%ONORM  Octave's norm of a 3-vector: the scaled accumulator of its vector_norm (norm_accumulator_2), which can differ from
%   sqrt(x^2 + y^2 + z^2) in the last bit.
%   v: real[1][3] (passed a plain number)
%   returns n: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    n = 0;
    scl = 0;
    sum = 1;
    for i = (0):((3) - 1)
        h__266 = v((i) + 1);
        if h__266 < 0, h__266 = -h__266; elseif h__266 == 0, h__266 = 0; end
        t = h__266;
        if (scl == t)
            sum = (sum + 1);
        elseif (scl < t)
            q = (scl / t);
            sum = (sum * (q * q));
            sum = (sum + 1);
            scl = t;
        elseif (t ~= 0)
            q2 = (t / scl);
            sum = (sum + (q2 * q2));
        end
    end
    h__267 = sum;
    if h__267 < 0, h__267 = NaN; else, h__267 = sqrt(h__267); end
    n = (scl * h__267);
end
