function [u, cbar, sbar] = potential(r, mu, re, cbar, sbar, stride, nmax)
%POTENTIAL  grav.potential(r, mu, Re, Cbar, Sbar, nmax): the geopotential U [m^2/s^2] (a = +grad U; not pole-safe, as the
%   MATLAB), from normalised coefficients (row-major, stride `stride`).
%   vectors: 2
%   r: real[1][3] (passed a plain number)
%   mu: real[1] (passed a plain number)
%   re: real[1] (passed a plain number)
%   cbar: inout real[1][GRAV_CS] (passed a plain number)
%   sbar: inout real[1][GRAV_CS] (passed a plain number)
%   stride: int (passed a whole number)
%   nmax: int (passed a whole number)
%   returns u: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    u = 0;
    x = r(1);
    y = r(2);
    z = r(3);
    rn = asils.models.gravity.onorm(r);
    h__284 = asin((z / rn));
    if ~isreal(h__284), h__284 = NaN; end
    phi = h__284;
    lam = atan2(y, x);
    sp = sin(phi);
    cp = cos(phi);
    st = (nmax + 1);
    p = asils.models.gravity.norm_legendre_pot(sp, cp, nmax);
    cml = zeros(121, 1);
    sml = zeros(121, 1);
    for m = (0):(((nmax + 1)) - 1)
        cml((m) + 1) = cos((m * lam));
        sml((m) + 1) = sin((m * lam));
    end
    acc = 0;
    rr = (re / rn);
    for n = (0):(((nmax + 1)) - 1)
        h__285 = (rr)^(n);
        if ~isreal(h__285), h__285 = NaN; end
        rn_pow = h__285;
        inner = 0;
        for m = (0):(((n + 1)) - 1)
            inner = (inner + (p((((n * st) + m)) + 1) * ((cbar((((n * stride) + m)) + 1) * cml((m) + 1)) + (sbar((((n * stride) + m)) + 1) * sml((m) + 1)))));
        end
        acc = (acc + (rn_pow * inner));
    end
    u = ((mu / rn) * acc);
end
