function [a] = moon_turn(x)
%MOON_TURN  An angle in degrees reduced to one turn, in rad (ephem.rs moon's d).
%   x: real[1] (passed a plain number)
%   returns a: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    a = 0;
    a = (rem(x, 360) * 0.017453292519943295);
end
