function [mu, max_mu, free, certified] = fq_certify(law, g, c_bo, inc_deg, alt_km)
%FQ_CERTIFY  The certificate of one law: the case's orbit (its inclination [deg] and altitude [km]: a circle of radius 6378137 m
%   plus the altitude, mean motion sqrt(3.986004418e14/a^3)), the monodromy matrix in FLOQUET_STEPS steps, its
%   multipliers' moduli (the toolbox's eig, |mu| by hypot) in descending order, the free directions (1 for the boresight
%   law without its weak roll, else 0), the largest multiplier past them, and whether it is below 1 (certified).
%   Held to the multipliers tools/floquet.py committed with numpy (1.0.0) within the absolute tolerance below on each |mu|,
%   with every verdict the same (tests/test_floquet.py), and not bit for bit: numpy's matrix products ran on OpenBLAS's
%   kernels with fused multiply-add and its eigenvalues on LAPACK's dgeev, where this method sums left to right with none
%   and takes EISPACK's eigenvalues. Measured (9 Oct 2026, the 14 certificates of both cases): 2.3e-13 at most (ais_3u,
%   Celani 2026, whose small multipliers lie close together), the eigenvalue solve alone 6.6e-14 at most (the toolbox's
%   eig against dgeev on the same matrix); the reference frame equal. A verdict decided within the tolerance of 1 is not
%   held by it: ais_3u's rate damping is certified at max |mu| = 1 - 2.5e-13 (1 - 3.0e-13 here), a direction the law
%   leaves marginal, judged by rounding.
%   held to numpy: 1e-12
%   The translations are held to the interpreter within the tolerance below, relative to the largest output: the central
%   difference amplifies the maths library's last bit (sin, cos, pow, hypot) about 1e7 times.
%   tolerance: 1e-6
%   vectors: 2
%   law: MtqAlg (passed a choice, as its option's number)
%   g: FqGains (passed rec)
%   c_bo: real[1][3][3] (passed a plain number)
%   inc_deg: real[1] (passed a plain number)
%   alt_km: real[1] (passed a plain number)
%   returns mu: real[1][6] (passed a plain number)
%   returns max_mu: real[1] (passed a plain number)
%   returns free: int (passed a whole number)
%   returns certified: bool (passed true or false)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    mu = zeros(6, 1);
    max_mu = 0;
    free = 0;
    certified = false;
    inc = (inc_deg * (pi / 180));
    a = (6378137 + (alt_km * 1000));
    h__49 = (a)^(3);
    if ~isreal(h__49), h__49 = NaN; end
    h__50 = (398600441800000 / h__49);
    if h__50 < 0, h__50 = NaN; else, h__50 = sqrt(h__50); end
    n = h__50;
    phi = asils.models.floquet.fq_monodromy(law, g, c_bo, inc, n, 1500);
    ev = asils.pc.eig_(phi);
    am = zeros(6, 1);
    for i = (0):((6) - 1)
        am((i) + 1) = hypot(ev((i) + 1, 1), ev((i) + 1, 2));
    end
    s = asils.pc.sort_(am);
    i = ((0):((6) - 1)).';
    mu((i) + 1) = reshape(s(((5 - i)) + 1), [], 1);
    if ((law == 7) && (~(g.sb_kroll > 0)))
        h__51 = 1;
    else
        h__51 = 0;
    end
    free = h__51;
    max_mu = mu((free) + 1);
    certified = (max_mu < 1);
end
