function [c_bo, t, mode, rx, ry, rz, qx, qy, qz, qw] = fq_frame(t, mode, rx, ry, rz, qx, qy, qz, qw, q_off, roll_axis)
%FQ_FRAME  The flight software's nadir reference, body <- orbit (x along track, y = -orbit normal, z = nadir). Guidance builds the
%   reference rows [-ram, -r, -n] (04_guidance.md), R0 in orbit axes, then applies the boresight offset q_off and, when
%   the yaw flip is on, 180 deg about the boresight (the roll axis). Which of the two the mission flew is read from its
%   nadir phases (modes 2 and 3, nadir_mtq and nadir_fine, numbered from 1): their later half (of n samples, the last n -
%   floor(n/2)), each sample's orbit axes from its position and the velocity since the one before, summed as the attitude
%   flown makes them (dcm(q) times the orbit axes); the candidate nearer that sum (the larger trace of C^T acc; the first
%   on a tie). The run's channels by sample: time [s], mode, position (ECI) [m], attitude (x y z w).
%   length: 16
%   t: inout real[1][*] (passed a plain number)
%   mode: inout real[1][*] (passed a plain number)
%   rx: inout real[1][*] (passed a plain number)
%   ry: inout real[1][*] (passed a plain number)
%   rz: inout real[1][*] (passed a plain number)
%   qx: inout real[1][*] (passed a plain number)
%   qy: inout real[1][*] (passed a plain number)
%   qz: inout real[1][*] (passed a plain number)
%   qw: inout real[1][*] (passed a plain number)
%   q_off: real[1][4] (passed a plain number)
%   roll_axis: real[1][3] (passed a plain number)
%   returns c_bo: real[1][3][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    c_bo = zeros(3, 3);
    r0m = [([(-(1)); 0; 0]).'; ([0; 0; 1]).'; ([0; 1; 0]).'];
    u = (roll_axis / asils.pc.norm_(roll_axis));
    a0 = asils.pc.mm(asils.models.math.dcm(q_off), r0m);
    a1 = asils.pc.mm(asils.models.math.dcm([u(1); u(2); u(3); 0]), a0);
    nsel = 0;
    for k = (0):((numel(t)) - 1)
        ma = (fix(mode((k) + 1)) - 1);
        if ((ma == 1) || (ma == 2))
            nsel = (nsel + 1);
        end
    end
    skip = fix((nsel) / (2));
    acc = zeros(3, 3);
    seen = 0;
    have = false;
    rp = zeros(3, 1);
    tp = 0;
    for k = (0):((numel(t)) - 1)
        mb = (fix(mode((k) + 1)) - 1);
        if ((mb == 1) || (mb == 2))
            if (seen >= skip)
                r1 = [rx((k) + 1); ry((k) + 1); rz((k) + 1)];
                if have
                    v = ((r1 - rp) / (t((k) + 1) - tp));
                    z = ((-(r1)) / asils.pc.norm_(r1));
                    hv = asils.pc.cross_(r1, v);
                    y = ((-(hv)) / asils.pc.norm_(hv));
                    x = asils.pc.cross_(y, z);
                    co = [(x).'; (y).'; (z).'];
                    acc = (acc + asils.pc.mm(asils.models.math.dcm([qx((k) + 1); qy((k) + 1); qz((k) + 1); qw((k) + 1)]), (co).'));
                end
                rp = r1;
                tp = t((k) + 1);
                have = true;
            end
            seen = (seen + 1);
        end
    end
    m0 = asils.pc.mm((a0).', acc);
    m1 = asils.pc.mm((a1).', acc);
    c_bo = a0;
    if (((m1(1, 1) + m1(2, 2)) + m1(3, 3)) > ((m0(1, 1) + m0(2, 2)) + m0(3, 3)))
        c_bo = a1;
    end
end
