function [q] = fq_rv2q(v)
%FQ_RV2Q  The quaternion of a small rotation vector: [v sin(|v|/2)/|v|, cos(|v|/2)]; below 1e-15 rad [v/2, 1].
%   v: real[1][3] (passed a plain number)
%   returns q: real[1][4] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    q = zeros(4, 1);
    a = sqrt(v(1)*v(1) + v(2)*v(2) + v(3)*v(3));
    if (a < 1e-15)
        q = [(v(1) / 2); (v(2) / 2); (v(3) / 2); 1];
    else
        s = (sin((a / 2)) / a);
        q = [(v(1) * s); (v(2) * s); (v(3) * s); cos((a / 2))];
    end
end
