function [tau] = fq_torque(law, g, qe, w, wref_r, e3)
%FQ_TORQUE  The flight software's law (05_control.md), nonlinear, with q_e = q_ref^-1 q and the reference rate w_ref in the
%   reference frame, its sign the scalar part's; e3 the roll axis.
%   law: MtqAlg (passed a choice, as its option's number)
%   g: FqGains (passed rec)
%   qe: real[1][4] (passed a plain number)
%   w: real[1][3] (passed a plain number)
%   wref_r: real[1][3] (passed a plain number)
%   e3: real[1][3] (passed a plain number)
%   returns tau: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    tau = zeros(3, 1);
    am = asils.models.math.dcm(qe);
    we = (w - asils.pc.mv(am, wref_r));
    sg = asils.pc.choose((qe(4) >= 0), 1, (-(1)));
    qv = [qe(1); qe(2); qe(3)];
    tau = zeros(3, 1);
    if (law == 0)
        for i = (0):((3) - 1)
            tau((i) + 1) = (((-(g.mtq_Kp((i) + 1))) * (sg * qv((i) + 1))) - (g.mtq_Kd((i) + 1) * we((i) + 1)));
        end
    elseif (law == 3)
        for i = (0):((3) - 1)
            tau((i) + 1) = ((-(g.mtq_Kd((i) + 1))) * we((i) + 1));
        end
    elseif (law == 4)
        e = g.mtq_eps;
        jwe = asils.pc.mv(g.J, we);
        for i = (0):((3) - 1)
            tau((i) + 1) = (-(((((e * e) * g.mtq_k1) * (sg * qv((i) + 1))) + ((e * g.mtq_k2) * jwe((i) + 1)))));
        end
    elseif (law == 5)
        e5 = g.mtq_eps;
        for i = (0):((3) - 1)
            tau((i) + 1) = (-(((((e5 * e5) * g.mtq_k1) * (sg * qv((i) + 1))) + ((e5 * g.mtq_k2) * we((i) + 1)))));
        end
    elseif (law == 6)
        n = asils.pc.norm_(wref_r);
        ep = (wref_r / n);
        sgm = asils.pc.mv(am, ep);
        jp = asils.pc.dot_(asils.pc.mv((g.J).', ep), ep);
        th = ((2 * sg) * asils.pc.dot_(qv, ep));
        eta = ((jp * n) * (1 - (g.mtq_lam16 * th)));
        jw = asils.pc.mv(g.J, w);
        k = g.mtq_k16;
        for i = (0):((3) - 1)
            tau((i) + 1) = ((k * ((eta * sgm((i) + 1)) - jw((i) + 1))) + (k * ((eta * ep((i) + 1)) - jw((i) + 1))));
        end
    elseif (law == 7)
        ab = asils.pc.mv(am, e3);
        tau = ((g.sb_kp * asils.pc.cross_(e3, ab)) - (g.sb_kd * we));
        if ((g.sb_kroll > 0) && (asils.pc.dot_(e3, ab) > g.sb_roll_gate))
            pa = (g.sun_axis - (asils.pc.dot_(g.sun_axis, e3) * e3));
            if (asils.pc.norm_(pa) > 0.000001)
                pn = (pa / asils.pc.norm_(pa));
                pd = asils.pc.mv(am, pn);
                tau = (tau + (((g.sb_kroll * atan2(asils.pc.dot_(asils.pc.cross_(pn, pd), e3), asils.pc.dot_(pn, pd))) - (g.sb_kdroll * asils.pc.dot_(we, e3))) * e3));
            end
        end
    elseif (law == 8)
        pq = asils.pc.mv(g.mtq_Pth, ((2 * sg) * qv));
        pw = asils.pc.mv(g.mtq_Pw, we);
        for i = (0):((3) - 1)
            tau((i) + 1) = (-((pq((i) + 1) + pw((i) + 1))));
        end
    end
end
