function [mag_ok, b, gyro_ok, w, sun_ok, sun, es_ok, nadir, st_ok, st_valid, q_st, gps_ok, r, v, h, delta] = drv_read(mag_rx, gyro_rx, sun_rx, es_rx, st, st_len, gps, gps_len, can_id, can_dlc, can_data, n_can, has_gyro, has_sun, has_es, has_st, has_gps, nr, rot_gi)
%DRV_READ  A read of every sensor (09_drivers_hal.md): the magnetometer (I2C: status, B int16 of 1e-4/32768 T),
%   the gyro (SPI: status, w int32 of 5/2^23 rad/s), the Sun-sensor set and the Earth sensor (I2C:
%   status, a Q15 unit vector), the star tracker (UART frame EB 90: heads, each valid and q int32
%   Q30), the GNSS receiver (UART frame EB 91: fix, r int32 cm, v int32 mm/s) and the momentum
%   devices' telemetry (CAN 0x200 + i, 8 bytes: h int32 of 1e-9 N m s, gimbal angle int32 of 1e-7 rad).
%   A status bit 0 clear, or a part not fitted, leaves its reading at 0 and its flag false.
%   vectors: 32
%   inputs from: read_streams
%   mag_rx: int[7] (passed a whole number)
%   gyro_rx: int[13] (passed a whole number)
%   sun_rx: int[7] (passed a whole number)
%   es_rx: int[7] (passed a whole number)
%   st: int[96] (passed a whole number)
%   st_len: int (passed a whole number)
%   gps: int[96] (passed a whole number)
%   gps_len: int (passed a whole number)
%   can_id: int[8] (passed a whole number)
%   can_dlc: int[8] (passed a whole number)
%   can_data: int[8][8] (passed a whole number)
%   n_can: int (passed a whole number)
%   has_gyro: bool (passed true or false)
%   has_sun: bool (passed true or false)
%   has_es: bool (passed true or false)
%   has_st: bool (passed true or false)
%   has_gps: bool (passed true or false)
%   nr: int (passed a whole number)
%   rot_gi: int[8] (passed a whole number)
%   returns mag_ok: bool (passed true or false)
%   returns b: real[T][3] (passed in kg/(s^2 A))
%   returns gyro_ok: bool (passed true or false)
%   returns w: real[rad/s][3] (passed in 1/s)
%   returns sun_ok: bool (passed true or false)
%   returns sun: real[1][3] (passed a plain number)
%   returns es_ok: bool (passed true or false)
%   returns nadir: real[1][3] (passed a plain number)
%   returns st_ok: bool (passed true or false)
%   returns st_valid: bool[2] (passed true or false)
%   returns q_st: real[1][4][2] (passed a plain number)
%   returns gps_ok: bool (passed true or false)
%   returns r: real[m][3] (passed in m)
%   returns v: real[m/s][3] (passed in m/s)
%   returns h: real[N m s][8] (passed in m^2 kg/s)
%   returns delta: real[rad][4] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    mag_ok = false;
    b = zeros(3, 1);
    gyro_ok = false;
    w = zeros(3, 1);
    sun_ok = false;
    sun = zeros(3, 1);
    es_ok = false;
    nadir = zeros(3, 1);
    st_ok = false;
    st_valid = zeros(2, 1);
    q_st = zeros(2, 4);
    gps_ok = false;
    r = zeros(3, 1);
    v = zeros(3, 1);
    h = zeros(8, 1);
    delta = zeros(4, 1);
    mag_ok = (bitand(mag_rx(1), 1) == 1);
    b = zeros(3, 1);
    if mag_ok
        for i = (0):((3) - 1)
            b((i) + 1) = (asils.alg.drivers.rd16(mag_rx(((1 + (2 * i))) + 1), mag_rx(((2 + (2 * i))) + 1)) * (0.0001 / 32768));
        end
    end
    gyro_ok = (has_gyro && (bitand(gyro_rx(1), 1) == 1));
    w = zeros(3, 1);
    if gyro_ok
        for i = (0):((3) - 1)
            w((i) + 1) = (asils.alg.drivers.rd32(gyro_rx(((1 + (4 * i))) + 1), gyro_rx(((2 + (4 * i))) + 1), gyro_rx(((3 + (4 * i))) + 1), gyro_rx(((4 + (4 * i))) + 1)) * (5 / 8388608));
        end
    end
    sun_ok = (has_sun && (bitand(sun_rx(1), 1) == 1));
    sun = zeros(3, 1);
    if sun_ok
        for i = (0):((3) - 1)
            sun((i) + 1) = (asils.alg.drivers.rd16(sun_rx(((1 + (2 * i))) + 1), sun_rx(((2 + (2 * i))) + 1)) / 32767);
        end
    end
    es_ok = (has_es && (bitand(es_rx(1), 1) == 1));
    nadir = zeros(3, 1);
    if es_ok
        for i = (0):((3) - 1)
            nadir((i) + 1) = (asils.alg.drivers.rd16(es_rx(((1 + (2 * i))) + 1), es_rx(((2 + (2 * i))) + 1)) / 32767);
        end
    end
    st_ok = false;
    st_valid = [false; false];
    q_st = zeros(2, 4);
    if has_st
        [pl, n] = asils.alg.drivers.uart_frame(st, st_len, 144);
        if (n > 0)
            for hd = (0):((2) - 1)
                if ((hd < pl(1)) && ((1 + (17 * (hd + 1))) <= n))
                    e = (1 + (17 * hd));
                    st_valid((hd) + 1) = (bitand(pl((e) + 1), 1) == 1);
                    for k = (0):((4) - 1)
                        q_st((hd) + 1, (k) + 1) = (asils.alg.drivers.rd32(pl((((e + 1) + (4 * k))) + 1), pl((((e + 2) + (4 * k))) + 1), pl((((e + 3) + (4 * k))) + 1), pl((((e + 4) + (4 * k))) + 1)) / 1073741824);
                    end
                    if st_valid((hd) + 1)
                        st_ok = true;
                    end
                end
            end
        end
    end
    gps_ok = false;
    r = zeros(3, 1);
    v = zeros(3, 1);
    if has_gps
        [pg, ng] = asils.alg.drivers.uart_frame(gps, gps_len, 145);
        if ((ng >= 25) && (bitand(pg(1), 1) == 1))
            gps_ok = true;
            for i = (0):((3) - 1)
                r((i) + 1) = (asils.alg.drivers.rd32(pg(((1 + (4 * i))) + 1), pg(((2 + (4 * i))) + 1), pg(((3 + (4 * i))) + 1), pg(((4 + (4 * i))) + 1)) * 0.01);
                v((i) + 1) = (asils.alg.drivers.rd32(pg(((13 + (4 * i))) + 1), pg(((14 + (4 * i))) + 1), pg(((15 + (4 * i))) + 1), pg(((16 + (4 * i))) + 1)) * 0.001);
            end
        end
    end
    h = zeros(8, 1);
    delta = zeros(4, 1);
    for f = (0):((n_can) - 1)
        id = can_id((f) + 1);
        if (((id >= 512) && (id < 520)) && (can_dlc((f) + 1) >= 8))
            ri = (id - 512);
            d = (can_data((f) + 1, :)).';
            h((ri) + 1) = (asils.alg.drivers.rd32(d(1), d(2), d(3), d(4)) * 1e-9);
            if ((ri < nr) && (rot_gi((ri) + 1) > 0))
                delta(((rot_gi((ri) + 1) - 1)) + 1) = (asils.alg.drivers.rd32(d(5), d(6), d(7), d(8)) * 1e-7);
            end
        end
    end
end
