function [t_s] = settling_time_2pct(w_n, zeta)
%SETTLING_TIME_2PCT  The 2 per cent settling time of a second-order loop: t_s = 4/(zeta w_n).
%   w_n: real[rad/s] (passed in 1/s)
%   zeta: real[1] (passed a plain number)
%   returns t_s: real[s] (passed in s)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    t_s = 0;
    t_s = (4 / (zeta * w_n));
end
