function s = Flex_zero()
%FLEX_ZERO  a Flex with every field zero
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = struct();
    s.on = false;
    s.delta = zeros(3, 1);
    s.omega = 0;
    s.zeta = 0;
end
