function [y] = momentum_limited(hd, h, h_max, at_limit)
%MOMENTUM_LIMITED  A rotor's momentum rate hd at momentum h: at or beyond its capacity h_max and growing, the rate at the limit.
%   hd: real[1] (passed a plain number)
%   h: real[1] (passed a plain number)
%   h_max: real[1] (passed a plain number)
%   at_limit: real[1] (passed a plain number)
%   returns y: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    y = 0;
    y = asils.pc.choose(((asils.pc.fabs(h) >= h_max) && (sign(hd) == sign(h))), at_limit, hd);
end
