function [held] = static_hold(h, tq, fs, dt)
%STATIC_HOLD  Whether static friction (breakaway torque fs [N m]) holds a rotor of momentum h at rest over a step dt, the torque
%   on it tq.
%   h: real[1] (passed a plain number)
%   tq: real[1] (passed a plain number)
%   fs: real[1] (passed a plain number)
%   dt: real[1] (passed a plain number)
%   returns held: bool (passed true or false)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    held = false;
    held = ((asils.pc.fabs(h) <= (fs * dt)) && (asils.pc.fabs(tq) <= fs));
end
