function [v, g] = mag_noise(mb, b, noise, k_coil, m_coil, g)
%MAG_NOISE  The reading before its range [T]: mb the field through the unit's matrix, b its bias, noise the noise's sigma [T], k_coil
%   the coils' coupling [T/(A m^2)] and m_coil their body dipole [A m^2].
%   mb: real[1][3] (passed a plain number)
%   b: real[1][3] (passed a plain number)
%   noise: real[1] (passed a plain number)
%   k_coil: real[1] (passed a plain number)
%   m_coil: real[1][3] (passed a plain number)
%   g: inout stream (passed a random stream, as six numbers)
%   returns v: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    v = zeros(3, 1);
    [t__168, t__169] = asils.pc.stream_normal3(g);
    n = t__168;
    g = t__169;
    v = [0; 0; 0];
    for i = (0):((3) - 1)
        v((i) + 1) = (((mb((i) + 1) + b((i) + 1)) + (noise * n((i) + 1))) + (k_coil * m_coil((i) + 1)));
    end
end
