function rings = fmr(Dm, k, bx)
%ASILS.SIZING.FMR  The fluid loop: X, Y, Z rings, each designed with its electromagnetic DC conduction pump
%   (design/sizefmr.pc, act/sizepump.pc), and the spare on the body diagonal when the loop asks for it
%   (act/sizering.pc). The engine's adcs-design fmr and ring.
%   rings = asils.sizing.fmr(Dm, asils.sizing.knobs(), [0.34 0.10 0.10])     a cell of 3 (or 4) parts
%   Owner: Agastya. Copyright (c) 2026 Agastya. All rights reserved.
    [faces, per] = asils.models.sizefmr.fmr_faces(bx(:));
    [h, tau] = asils.models.sizefmr.fmr_need(Dm.h_req, Dm.tau_req, asils.sizing.scale_(k, 'fmr'));
    ax = {'X', 'Y', 'Z'};
    rings = cell(1, 3);
    for i = 1:3, rings{i} = ring_(Dm, k, h, tau, faces(i), per(i), ax{i}, [ax{i} ' axis']); end
    if k.fmr_spare
        [area, perim] = asils.models.sizering.ring_section(bx(:), asils.models.sizering.spare_axis());
        [hs, taus] = asils.models.sizefmr.fmr_spare_need(h, tau);
        rings{4} = ring_(Dm, k, hs, taus, area, perim, 'S', 'spare, skewed on the body diagonal');
    end
end

function p = ring_(Dm, k, h, tau, face, perim, tag, what)
% one fluid ring with its electromagnetic pump, designed for momentum h and torque tau in a loop of face m^2, perim m
    [s0, l1] = asils.models.sizefmr.fmr_loop(face, perim);
    ds = asils.models.sizepump.pump_design(h, tau, s0, l1, k.fmr_lambda);
    assert(ds.found, 'asils:sizing:refused', 'no feasible pump design (ring %s: h %.3g N m s, tau %.3g N m, lambda %g)', ...
        tag, h, tau, k.fmr_lambda);
    [rho, mu, ~, melt] = asils.models.sizepump.pump_fluid();
    [dipole_max, per_amp, current_max] = asils.models.sizefmr.fmr_no_dipole();
    nm = struct('bore_m', ds.d, 'loops', ds.loops, 'v_max_m_s', ds.v_max, 'h_max_Nms', ds.h_max, 'enclosed_area_m2', ds.s, ...
        'channel_length_m', ds.l, 'reynolds_cruise', ds.re, 'v_cruise_m_s', ds.v_cruise, ...
        'pump', struct('type', 'DC conduction pump, electromagnet C-core', 'B_gap_T', ds.b, 'active_length_m', ds.lp, 'gap_m', ds.gap, ...
            'ampere_turns', ds.ni, 'electrode_current_design_A', ds.i_design, 'electrode_current_cruise_A', ds.i_cruise, ...
            'dp_design_Pa', ds.dp_design, 'dp_cruise_Pa', ds.dp_cruise, 'coil_power_W', ds.p_coil, ...
            'electrode_power_cruise_W', ds.p_elec_cruise, 'copper_kg', ds.m_cu, 'iron_kg', ds.m_fe, 'lambda_kg_per_W', k.fmr_lambda, ...
            'efficiency_cruise', ds.eta_cruise), ...
        'pump_torque_max_Nm', ds.tau_max, 'field_power_W', ds.p_coil, 'power_steady_W', ds.p_steady, 'power_peak_W', ds.p_peak, ...
        'pump_efficiency', ds.eta, 'fluid_mass_kg', ds.m_fluid, 'mass_kg', ds.mass, ...
        'fluid', 'galinstan', 'fluid_density_kg_m3', rho, 'fluid_viscosity_Pa_s', mu, 'pump_type', 'dc-conduction, electromagnet', ...
        'melt_point_K', melt, 'dipole_max_Am2', dipole_max, 'dipole_per_amp_Am2_per_A', per_amp, 'current_max_A', current_max, ...
        'volume_L', asils.models.sizefmr.fmr_volume(face));
    [fd, flo, fhi, pd, plo, phi, wd, wm, ws, md, mm, ms] = asils.models.sizefmr.fmr_dispersion(ds.eta, k.fmr_flow_sigma);
    p = struct('part_number', sprintf('SZ-%s-FMR-%s', Dm.case, tag), 'kind', 'magneto_fluidic_panel', ...
        'name', sprintf('Sized fluid momentum loop with electromagnetic pump, %s (our product) — %s', what, Dm.case), ...
        'status', 'sized', 'source', 'asils.sizing (the design''s empump)', 'made', 'in-house', 'descriptor_version', 1);
    p.nominal = nm;
    p.dispersion = struct('friction_scale', asils.sizing.spread_(fd, flo, fhi), 'pump_efficiency', asils.sizing.spread_(pd, plo, phi), ...
        'flow_sensor_noise_m_s', asils.sizing.spread_(wd, wm, ws), 'axis_misalignment_rad', asils.sizing.spread_(md, mm, ms));
    [ok, lam, mass, power, coil, v_max, bore, b, loops] = asils.models.sizepump.pump_pareto(h, tau, s0, l1);
    par = {};
    for i = 1:numel(ok)
        if ok(i) == 1
            par{end+1} = struct('lambda', lam(i), 'mass_kg', mass(i), 'power_W', power(i), 'coil_W', coil(i), 'v_max', v_max(i), ...
                'bore_m', bore(i), 'B_T', b(i), 'loops', loops(i)); %#ok<AGROW>
        end
    end
    p.sizing = struct('h_req_Nms', Dm.h_req, 'tau_req_Nm', Dm.tau_req, 'h_ring_Nms', h, 'tau_ring_Nm', tau, ...
        'flow_sensor_sigma_m_s', k.fmr_flow_sigma, 'face_m2', face, 'perimeter_m', perim, 'scale', asils.sizing.scale_(k, 'fmr'), ...
        'lambda_kg_per_W', k.fmr_lambda, 'pareto', {par}, ...
        'law', 'galinstan loop + DC conduction pump with an electromagnet, designed together: least mass + lambda x steady power (empump.rs)');
end
