function p = rcs(Dm, k, bx)
%ASILS.SIZING.RCS  The N2O cold-gas thrusters (design/sizercs.pc: sizercs's rcs_size, rcs_part, rcs_dispersion; the
%   engine's adcs-design rcs).
%   p = asils.sizing.rcs(Dm, asils.sizing.knobs(), [0.34 0.10 0.10])
%   Owner: Agastya. Copyright (c) 2026 Agastya. All rights reserved.
    s = asils.sizing.scale_(k, 'rcs');
    [thrust, f_req, arm_long, arm_short, it_det, it_dump, it_slew, mprop, mslew, tank_volume, tank_radius, tank_wall, dry_mass, ...
     mass, volume, isp_budget] = asils.models.sizercs.rcs_size(Dm.tau_req, Dm.h_detumble, Dm.h_secular, Dm.slews_per_day, Dm.h_slew, Dm.life_yr, ...
        Dm.orbit_period_s, Dm.J(:), bx(:), s);
    [isp, thrusters, mib, valve_res, tank_pressure, meop, valve_power, power_steady] = asils.models.sizercs.rcs_part();
    p = asils.sizing.part_(Dm.case, 'RCS', 'rcs', 'Sized N2O cold-gas RCS, 6 couples (our product)', 'in-house');
    p.nominal = struct('thrust_N', thrust, 'isp_s', isp, 'propellant', 'N2O', 'thrusters', thrusters, 'mib_s', mib, ...
        'valve_res_s', valve_res, 'arm_long_m', arm_long, 'arm_short_m', arm_short, 'propellant_kg', mprop, ...
        'tank_volume_L', tank_volume, 'tank_radius_m', tank_radius, 'tank_wall_m', tank_wall, 'tank_pressure_bar', tank_pressure, ...
        'meop_bar', meop, 'valve_power_W', valve_power, 'power_steady_W', power_steady, 'dry_mass_kg', dry_mass, 'mass_kg', mass, ...
        'volume_L', volume);
    [td, tm, ts, id, ilo, ihi, md, mm, ms] = asils.models.sizercs.rcs_dispersion();
    p.dispersion = struct('thrust_scale', asils.sizing.spread_(td, tm, ts), 'isp_s', asils.sizing.spread_(id, ilo, ihi), ...
        'axis_misalignment_rad', asils.sizing.spread_(md, mm, ms));
    p.sizing = struct('F_req_N', f_req, 'impulse_detumble_Ns', it_det, 'impulse_dumping_Ns', it_dump, 'impulse_slews_Ns', it_slew, ...
        'propellant_if_slews_on_rcs_kg', mslew, 'life_yr', Dm.life_yr, 'isp_budget_s', isp_budget, 'scale', s, ...
        'law', 'N2O self-pressurised, Isp 60 s budget (60-80 s), Al-7075 sphere at 70 bar MEOP');
end
