function [m] = maxabs3(a)
%MAXABS3  The largest |a_i|.
%   a: real[1][3] (passed a plain number)
%   returns m: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    m = 0;
    m = asils.pc.fabs(a(1));
    if (asils.pc.fabs(a(2)) > m)
        m = asils.pc.fabs(a(2));
    end
    if (asils.pc.fabs(a(3)) > m)
        m = asils.pc.fabs(a(3));
    end
end
