function [p] = pinv_rows(a, n)
%PINV_ROWS  The minimum-norm right inverse of the first n columns of a 3 x 8 matrix, rank-safe:
%   S = A A^T + eps I, eps = 1e-12 max(trace(S)/3, 1e-30); returns A^T S^-1 (8 x 3, rows past n zero).
%   a: real[1][8][3] (passed a plain number)
%   n: int (passed a whole number)
%   returns p: real[1][3][8] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    p = zeros(8, 3);
    s = zeros(3, 3);
    i = ((0):((3) - 1)).';
    j = (0):((3) - 1);
    s((i) + 1, (j) + 1) = 0;
    for k = (0):((n) - 1)
        s((i) + 1, (j) + 1) = (s((i) + 1, (j) + 1) + (a((i) + 1, (k) + 1) .* (a((j) + 1, (k) + 1)).'));
    end
    tr = (((s(1, 1) + s(2, 2)) + s(3, 3)) / 3);
    if (tr > 1e-30)
        h__6 = tr;
    else
        h__6 = 1e-30;
    end
    eps = (1e-12 * h__6);
    for i = (0):((3) - 1)
        s((i) + 1, (i) + 1) = (s((i) + 1, (i) + 1) + eps);
    end
    [si, ok] = asils.alg.math.inv3(s);
    k = ((0):((n) - 1)).';
    if ~isempty(k)
        j = (0):((3) - 1);
        p((k) + 1, (j) + 1) = ((((a(1, (k) + 1)).' .* si(1, (j) + 1)) + ((a(2, (k) + 1)).' .* si(2, (j) + 1))) + ((a(3, (k) + 1)).' .* si(3, (j) + 1)));
    end
end
