//! The vector dispatcher: call a function by name with its inputs flattened (SI). Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
#![allow(unused_mut, unused_variables, unreachable_code, clippy::all)]

/// The outputs, flattened, or None when there is no such function or too few inputs.
pub fn call(name: &str, x: &[f64]) -> Option<Vec<f64>> {
    let mut out = Vec::new();
    match name {
        "ctl::settling_time_2pct" => {
            if x.len() != 2 { return None; }
            let r = crate::ctl::settling_time_2pct(x[0], x[1]);
            out.push(r);
        }
        "env::dipole" => {
            if x.len() != 0 { return None; }
            let r = crate::env::dipole();
            out.push(r.0);
            out.push(r.1);
        }
        "env::max_magnetic_latitude" => {
            if x.len() != 1 { return None; }
            let r = crate::env::max_magnetic_latitude(x[0]);
            out.push(r);
        }
        "env::dipole_field_equator" => {
            if x.len() != 1 { return None; }
            let r = crate::env::dipole_field_equator(x[0]);
            out.push(r);
        }
        "env::dipole_field_max" => {
            if x.len() != 2 { return None; }
            let r = crate::env::dipole_field_max(x[0], x[1]);
            out.push(r);
        }
        "env::density_at" => {
            if x.len() != 2 { return None; }
            let r = crate::env::density_at(x[0], x[1]);
            out.push(r);
        }
        "env::sun_distance_au" => {
            if x.len() != 1 { return None; }
            let r = crate::env::sun_distance_au(x[0]);
            out.push(r);
        }
        "env::solar_pressure" => {
            if x.len() != 1 { return None; }
            let r = crate::env::solar_pressure(x[0]);
            out.push(r);
        }
        "fmr::ring_momentum" => {
            if x.len() != 4 { return None; }
            let r = crate::fmr::ring_momentum(x[0], x[1], x[2], x[3]);
            out.push(r);
        }
        "fmr::spin_down_time" => {
            if x.len() != 3 { return None; }
            let r = crate::fmr::spin_down_time(x[0], x[1], x[2]);
            out.push(r);
        }
        "fmr::holding_power_laminar" => {
            if x.len() != 6 { return None; }
            let r = crate::fmr::holding_power_laminar(x[0], x[1], x[2], x[3], x[4], x[5]);
            out.push(r);
        }
        "fmr::pump_pressure_for_torque" => {
            if x.len() != 4 { return None; }
            let r = crate::fmr::pump_pressure_for_torque(x[0], x[1], x[2], x[3]);
            out.push(r);
        }
        "fmr::reynolds" => {
            if x.len() != 4 { return None; }
            let r = crate::fmr::reynolds(x[0], x[1], x[2], x[3]);
            out.push(r);
        }
        "fmr::conduction_pump_pressure" => {
            if x.len() != 4 { return None; }
            let r = crate::fmr::conduction_pump_pressure(x[0] as i64, x[1], x[2], x[3]);
            out.push(r);
        }
        "gnc::magnetic_torque" => {
            if x.len() != 2 { return None; }
            let r = crate::gnc::magnetic_torque(x[0], x[1]);
            out.push(r);
        }
        "gnc::total_disturbance_torque" => {
            if x.len() != 4 { return None; }
            let r = crate::gnc::total_disturbance_torque(x[0], x[1], x[2], x[3]);
            out.push(r);
        }
        "gnc::magnetorquer_dipole_required" => {
            if x.len() != 3 { return None; }
            let r = crate::gnc::magnetorquer_dipole_required(x[0], x[1], x[2]);
            out.push(r);
        }
        "gnc::pointing_error_rss" => {
            if x.len() != 5 { return None; }
            let r = crate::gnc::pointing_error_rss([x[0], x[1], x[2], x[3], x[4]]);
            out.push(r);
        }
        "gnc::gravity_gradient_torque_worst" => {
            if x.len() != 3 { return None; }
            let r = crate::gnc::gravity_gradient_torque_worst(x[0], x[1], x[2]);
            out.push(r);
        }
        "gnc::aero_torque" => {
            if x.len() != 5 { return None; }
            let r = crate::gnc::aero_torque(x[0], x[1], x[2], x[3], x[4]);
            out.push(r);
        }
        "gnc::solar_pressure_torque_at" => {
            if x.len() != 4 { return None; }
            let r = crate::gnc::solar_pressure_torque_at(x[0], x[1], x[2], x[3]);
            out.push(r);
        }
        "gnc::secular_momentum_per_orbit" => {
            if x.len() != 2 { return None; }
            let r = crate::gnc::secular_momentum_per_orbit(x[0], x[1]);
            out.push(r);
        }
        "mission::closure" => {
            if x.len() != 3 { return None; }
            let r = crate::mission::closure(x[0], x[1], x[2] as i64);
            out.push(if r.0 { 1.0 } else { 0.0 });
            out.push(r.1);
        }
        "mtq::dipole_to_reject" => {
            if x.len() != 2 { return None; }
            let r = crate::mtq::dipole_to_reject(x[0], x[1]);
            out.push(r);
        }
        "mtq::torque_authority" => {
            if x.len() != 3 { return None; }
            let r = crate::mtq::torque_authority(x[0], x[1], x[2] as i64);
            out.push(r);
        }
        "mtq::coil_dipole" => {
            if x.len() != 3 { return None; }
            let r = crate::mtq::coil_dipole(x[0] as i64, x[1], x[2]);
            out.push(r);
        }
        "orbit::radius" => {
            if x.len() != 1 { return None; }
            let r = crate::orbit::radius(x[0]);
            out.push(r);
        }
        "orbit::circular_period" => {
            if x.len() != 1 { return None; }
            let r = crate::orbit::circular_period(x[0]);
            out.push(r);
        }
        "orbit::mean_motion" => {
            if x.len() != 1 { return None; }
            let r = crate::orbit::mean_motion(x[0]);
            out.push(r);
        }
        "orbit::circular_speed" => {
            if x.len() != 1 { return None; }
            let r = crate::orbit::circular_speed(x[0]);
            out.push(r);
        }
        "orbit::eclipse_fraction" => {
            if x.len() != 2 { return None; }
            let r = crate::orbit::eclipse_fraction(x[0], x[1]);
            out.push(r);
        }
        "orbit::sun_ra_dec" => {
            if x.len() != 1 { return None; }
            let r = crate::orbit::sun_ra_dec(x[0]);
            out.push(r.0);
            out.push(r.1);
        }
        "orbit::beta_angle" => {
            if x.len() != 3 { return None; }
            let r = crate::orbit::beta_angle(x[0], x[1], x[2]);
            out.push(r);
        }
        "rcs::propellant_per_slew" => {
            if x.len() != 3 { return None; }
            let r = crate::rcs::propellant_per_slew(x[0], x[1], x[2]);
            out.push(r);
        }
        "rcs::propellant_per_year" => {
            if x.len() != 3 { return None; }
            let r = crate::rcs::propellant_per_year(x[0], x[1], x[2] as i64);
            out.push(r);
        }
        "risk::highest_level" => {
            if x.len() != 7 { return None; }
            let r = crate::risk::highest_level([x[0] as i64, x[1] as i64, x[2] as i64, x[3] as i64, x[4] as i64, x[5] as i64, x[6] as i64]);
            out.push(r as f64);
        }
        "risk::net_closed" => {
            if x.len() != 2 { return None; }
            let r = crate::risk::net_closed(x[0] as i64, x[1] as i64);
            out.push(r as f64);
        }
        "risk::share_tested" => {
            if x.len() != 2 { return None; }
            let r = crate::risk::share_tested(x[0] as i64, x[1] as i64);
            out.push(r.0);
            out.push(if r.1 { 1.0 } else { 0.0 });
        }
        "rw::bang_bang_peak_momentum" => {
            if x.len() != 3 { return None; }
            let r = crate::rw::bang_bang_peak_momentum(x[0], x[1], x[2]);
            out.push(r);
        }
        "rw::bang_bang_peak_torque" => {
            if x.len() != 3 { return None; }
            let r = crate::rw::bang_bang_peak_torque(x[0], x[1], x[2]);
            out.push(r);
        }
        "rw::cyclic_momentum_quarter_orbit" => {
            if x.len() != 2 { return None; }
            let r = crate::rw::cyclic_momentum_quarter_orbit(x[0], x[1]);
            out.push(r);
        }
        _ => return None,
    }
    Some(out)
}

/// A proc called once per entry of `calls`, its state carried from each call to the next.
pub fn call_seq(name: &str, calls: &[Vec<f64>]) -> Option<Vec<Vec<f64>>> {
    let mut outs = Vec::new();
    match name {
        _ => return None,
    }
    Some(outs)
}
