//! mtq: Magnetorquer sizing. source: smad2011, idmas_v2
//! Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
#![allow(unused_mut, unused_variables, unused_parens, unused_assignments, unused_imports, unreachable_code, non_snake_case, clippy::all)]
use crate::rt;

/// The dipole that rejects a disturbance torque in the weakest field: m = tau/B_min.
/// - tau_d: real[N m] (passed in m^2 kg/s^2)
/// - b_min: real[T] (passed in kg/(s^2 A))
/// - returns m: real[A m^2] (passed in m^2 A)
#[allow(clippy::too_many_arguments)]
pub fn dipole_to_reject(tau_d: f64, b_min: f64) -> f64 {
    let mut m: f64 = 0.0;
    m = (tau_d / b_min);
    m
}

/// The torque the coils give about the worst axis: m B_min min(n, 3)/3 (fewer than three coils
/// leave axes without authority).
/// - m_av: real[A m^2] (passed in m^2 A)
/// - b_min: real[T] (passed in kg/(s^2 A))
/// - n_mtq: int (passed a whole number)
/// - returns tau: real[N m] (passed in m^2 kg/s^2)
#[allow(clippy::too_many_arguments)]
pub fn torque_authority(m_av: f64, b_min: f64, n_mtq: i64) -> f64 {
    let mut tau: f64 = 0.0;
    tau = (((m_av * b_min) * (rt::imin(n_mtq, 3) as f64)) / 3.0);
    tau
}

/// The dipole of a coil: m = N I A.
/// - n_turns: int (passed a whole number)
/// - current: real[A] (passed in A)
/// - area: real[m^2] (passed in m^2)
/// - returns m: real[A m^2] (passed in m^2 A)
#[allow(clippy::too_many_arguments)]
pub fn coil_dipole(n_turns: i64, current: f64, area: f64) -> f64 {
    let mut m: f64 = 0.0;
    m = (((n_turns as f64) * current) * area);
    m
}
