function [tau] = aero_torque(rm, v_rel, rho, g)
%AERO_TORQUE  The aerodynamic torque [N m], body axes, of air of density rho meeting the faces at v_rel (inertial, the velocity
%   relative to the co-rotating atmosphere), rm the inertial-to-body matrix; none where there is no air.
%   rm: real[1][3][3] (passed a plain number)
%   v_rel: real[m/s][3] (passed in m/s)
%   rho: real[kg/m^3] (passed in kg/m^3)
%   g: Facets (passed rec)
%   returns tau: real[N m][3] (passed in m^2 kg/s^2)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    tau = zeros(3, 1);
    tau = [0; 0; 0];
    if (rho > 0)
        vb = [rm(1, 1)*v_rel(1) + rm(1, 2)*v_rel(2) + rm(1, 3)*v_rel(3); rm(2, 1)*v_rel(1) + rm(2, 2)*v_rel(2) + rm(2, 3)*v_rel(3); rm(3, 1)*v_rel(1) + rm(3, 2)*v_rel(2) + rm(3, 3)*v_rel(3)];
        vv = sqrt(vb(1)*vb(1) + vb(2)*vb(2) + vb(3)*vb(3));
        vh = (vb * (1 / vv));
        for j = (0):((6) - 1)
            c = (vh(1)*g.n((j) + 1, 1) + vh(2)*g.n((j) + 1, 2) + vh(3)*g.n((j) + 1, 3));
            if (~(c <= 0))
                k2 = ((g.sigma_n * g.vb_ratio) + (((2 - g.sigma_n) - g.sigma_t) * c));
                f = [0; 0; 0];
                for k = (0):((3) - 1)
                    f((k) + 1) = ((((((-(rho)) * vv) * vv) * g.a((j) + 1)) * c) * ((g.sigma_t * vh((k) + 1)) + (k2 * g.n((j) + 1, (k) + 1))));
                end
                tau = (tau + [g.rho((j) + 1, 2)*f(3) - g.rho((j) + 1, 3)*f(2); g.rho((j) + 1, 3)*f(1) - g.rho((j) + 1, 1)*f(3); g.rho((j) + 1, 1)*f(2) - g.rho((j) + 1, 2)*f(1)]);
            end
        end
    end
end
