function [tau] = aero_torque(rm, v_rel, rho, g)
%AERO_TORQUE  The aerodynamic torque [N m], body axes, of air of density rho meeting the faces at v_rel (inertial, the velocity
%   relative to the co-rotating atmosphere), rm the inertial-to-body matrix; none where there is no air.
%   rm: real[1][3][3] (passed a plain number)
%   v_rel: real[m/s][3] (passed in m/s)
%   rho: real[kg/m^3] (passed in kg/m^3)
%   g: Facets (passed rec)
%   returns tau: real[N m][3] (passed in m^2 kg/s^2)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    tau = zeros(3, 1);
    tau = [0; 0; 0];
    if (rho > 0)
        vb = asils.pc.mv(rm, v_rel);
        vv = asils.pc.norm_(vb);
        vh = (vb * (1 / vv));
        for j = (0):((6) - 1)
            c = asils.pc.dot_(vh, (g.n((j) + 1, :)).');
            if (~(c <= 0))
                k2 = ((g.sigma_n * g.vb_ratio) + (((2 - g.sigma_n) - g.sigma_t) * c));
                f = [0; 0; 0];
                for k = (0):((3) - 1)
                    f((k) + 1) = ((((((-(rho)) * vv) * vv) * g.a((j) + 1)) * c) * ((g.sigma_t * vh((k) + 1)) + (k2 * g.n((j) + 1, (k) + 1))));
                end
                tau = (tau + asils.pc.cross_((g.rho((j) + 1, :)).', f));
            end
        end
    end
end
