function [g] = facets_box(box_m, cm, sigma_n, sigma_t, vb_ratio, refl, spec_frac)
%FACETS_BOX  The six faces of a box of edges box_m with the centre of mass at cm from its centre (body axes), the surface's
%   accommodation, re-emitted speed share, reflectivity and the specular share of what it reflects.
%   box_m: real[m][3] (passed in m)
%   cm: real[m][3] (passed in m)
%   sigma_n: real[1] (passed a plain number)
%   sigma_t: real[1] (passed a plain number)
%   vb_ratio: real[1] (passed a plain number)
%   refl: real[1] (passed a plain number)
%   spec_frac: real[1] (passed a plain number)
%   returns g: Facets (passed rec)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    g = asils.models.facets.Facets_zero();
    lx = box_m(1);
    ly = box_m(2);
    lz = box_m(3);
    n = [([1; 0; 0]).'; ([(-(1)); 0; 0]).'; ([0; 1; 0]).'; ([0; (-(1)); 0]).'; ([0; 0; 1]).'; ([0; 0; (-(1))]).'];
    rho = zeros(6, 3);
    j = ((0):((6) - 1)).';
    k = (0):((3) - 1);
    rho((j) + 1, (k) + 1) = (((n((j) + 1, (k) + 1) .* reshape(box_m((k) + 1), 1, [])) ./ 2) - reshape(cm((k) + 1), 1, []));
    g = asils.models.facets.Facets_zero();
    g.n = n;
    g.a = [(ly * lz); (ly * lz); (lx * lz); (lx * lz); (lx * ly); (lx * ly)];
    g.rho = rho;
    g.sigma_n = sigma_n;
    g.sigma_t = sigma_t;
    g.vb_ratio = vb_ratio;
    g.rho_spec = (refl * spec_frac);
    g.rho_diff = (refl * (1 - spec_frac));
end
