function [u] = unit_or_zero(a)
%UNIT_OR_ZERO  a made unit, as the engine's la::unit: a times the inverse of its norm; below 1e-300 the zero vector.
%   a: real[1][3] (passed a plain number)
%   returns u: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    u = zeros(3, 1);
    n = sqrt(a(1)*a(1) + a(2)*a(2) + a(3)*a(3));
    if (n < 1e-300)
        u = [0; 0; 0];
    else
        u = (a * (1 / n));
    end
end
