function [n, t] = case_mean_motion(h)
%CASE_MEAN_MOTION  The case's circular orbit at altitude h: its mean motion n and period t.
%   h: real[km] (passed in m)
%   returns n: real[1/s] (passed in 1/s)
%   returns t: real[s] (passed in s)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    n = 0;
    t = 0;
    r = (6378137 + h);
    n = asils.pc.sqrt_((398600441800000 / asils.pc.ipow(r, 3)));
    t = ((2 * pi) / n);
end
