function [t] = dispersed_period(h)
%DISPERSED_PERIOD  The period of the circular orbit at a dispersed altitude h (a campaign's alt_km).
%   h: real[km] (passed in m)
%   returns t: real[s] (passed in s)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    t = 0;
    r = (6378137 + h);
    t = ((2 * pi) * asils.pc.sqrt_((asils.pc.ipow(r, 3) / 398600441800000)));
end
