function [u, j] = shifted_epoch(jd0, days)
%SHIFTED_EPOCH  The epoch moved by days [day] from the Julian date jd0: the UTC date and its Julian date.
%   jd0: real[1] (passed a plain number)
%   days: real[1] (passed a plain number)
%   returns u: real[1][6] (passed a plain number)
%   returns j: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    u = zeros(6, 1);
    j = 0;
    [t__374, t__375] = asils.models.caseorbit.whole_second_epoch((jd0 + days));
    u = t__374;
    j = t__375;
end
