function [lambda, gs] = fsw_rw_smc(wn, z, phi)
%FSW_RW_SMC  The fine pointing's sliding mode: its surface's slope lambda = wn/(2 z) and its gain Gs = 2 z wn phi on each axis, phi
%   the boundary layer (fsw_param_rw_phi).
%   wn: real[1] (passed a plain number)
%   z: real[1] (passed a plain number)
%   phi: real[1] (passed a plain number)
%   returns lambda: real[1] (passed a plain number)
%   returns gs: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    lambda = 0;
    gs = zeros(3, 1);
    lambda = (wn / (2 * z));
    g = (((2 * z) * wn) * phi);
    gs = [g; g; g];
end
