function [e_next] = battery_step(e, p_gen, load, t0, t, batt_wh)
%BATTERY_STEP  The battery's energy [Wh] at time t [s], from e [Wh] at the sample before, t0 [s]: the arrays' power p_gen [W] less the
%   load [W] over the step in hours, held between empty and full (batt_wh [Wh]).
%   e: real[1] (passed a plain number)
%   p_gen: real[1] (passed a plain number)
%   load: real[1] (passed a plain number)
%   t0: real[1] (passed a plain number)
%   t: real[1] (passed a plain number)
%   batt_wh: real[1] (passed a plain number)
%   returns e_next: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    e_next = 0;
    dt_h = ((t - t0) / 3600);
    h__108 = (e + ((p_gen - load) * dt_h));
    h__109 = 0;
    if h__109 > h__108, h__108 = h__109; end
    h__109 = batt_wh;
    if h__109 < h__108, h__108 = h__109; end
    e_next = h__108;
end
