function [u] = power_sun_unit(a)
%POWER_SUN_UNIT  The Sun's direction made unit as the engine makes it (the toolbox's la::unit: a times 1/|a|, a zero vector below
%   1e-300).
%   a: real[1][3] (passed a plain number)
%   returns u: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    u = zeros(3, 1);
    n = sqrt((((a(1) * a(1)) + (a(2) * a(2))) + (a(3) * a(3))));
    if (n < 1e-300)
        u = [0; 0; 0];
    else
        k = (1 / n);
        u = [(a(1) * k); (a(2) * k); (a(3) * k)];
    end
end
