function [k1, k2, dr_k, dr_k2] = fsw_sun_spin_gains(g, jzz)
%FSW_SUN_SPIN_GAINS  The Sun spin's gains from the gain scale g and the inertia about the spin axis jzz [kg m^2].
%   g: real[1] (passed a plain number)
%   jzz: real[1] (passed a plain number)
%   returns k1: real[1] (passed a plain number)
%   returns k2: real[1] (passed a plain number)
%   returns dr_k: real[1] (passed a plain number)
%   returns dr_k2: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    k1 = 0;
    k2 = 0;
    dr_k = 0;
    dr_k2 = 0;
    k1 = (0.01 * g);
    k2 = (0.05 * g);
    dr_k = (0.01 * g);
    dr_k2 = (0.5 * jzz);
end
