function [p] = solar_pressure_at(d)
%SOLAR_PRESSURE_AT  The Sun's radiation pressure [N/m^2] at a distance d from the Sun: 4.56e-6 N/m^2 at 1 AU, as the inverse square.
%   d: real[m] (passed in m)
%   returns p: real[Pa] (passed in kg/(m s^2))
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    p = 0;
    p = ((0.00000456 * (149597870700 / d)) * (149597870700 / d));
end
