function [thrust, f_req, arm_long, arm_short, it_det, it_dump, it_slew, mprop, mslew, tank_volume, tank_radius, tank_wall, dry_mass, mass, volume, isp_budget] = rcs_size(tau_req, h_detumble, h_secular, spd, h_slew, life, period, j, bx, s)
%RCS_SIZE  The thruster part sized for the case's torque tau_req [N m], detumble momentum h_detumble and secular momentum per
%   orbit h_secular [N m s], slews a day spd, each slew's momentum h_slew [N m s], life [yr], orbit period [s], principal
%   moments j [kg m^2], box bx [m] and the authority scale s.
%   tau_req: real[1] (passed a plain number)
%   h_detumble: real[1] (passed a plain number)
%   h_secular: real[1] (passed a plain number)
%   spd: real[1] (passed a plain number)
%   h_slew: real[1] (passed a plain number)
%   life: real[1] (passed a plain number)
%   period: real[1] (passed a plain number)
%   j: real[1][3] (passed a plain number)
%   bx: real[1][3] (passed a plain number)
%   s: real[1] (passed a plain number)
%   returns thrust: real[1] (passed a plain number)
%   returns f_req: real[1] (passed a plain number)
%   returns arm_long: real[1] (passed a plain number)
%   returns arm_short: real[1] (passed a plain number)
%   returns it_det: real[1] (passed a plain number)
%   returns it_dump: real[1] (passed a plain number)
%   returns it_slew: real[1] (passed a plain number)
%   returns mprop: real[1] (passed a plain number)
%   returns mslew: real[1] (passed a plain number)
%   returns tank_volume: real[1] (passed a plain number)
%   returns tank_radius: real[1] (passed a plain number)
%   returns tank_wall: real[1] (passed a plain number)
%   returns dry_mass: real[1] (passed a plain number)
%   returns mass: real[1] (passed a plain number)
%   returns volume: real[1] (passed a plain number)
%   returns isp_budget: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    thrust = 0;
    f_req = 0;
    arm_long = 0;
    arm_short = 0;
    it_det = 0;
    it_dump = 0;
    it_slew = 0;
    mprop = 0;
    mslew = 0;
    tank_volume = 0;
    tank_radius = 0;
    tank_wall = 0;
    dry_mass = 0;
    mass = 0;
    volume = 0;
    isp_budget = 0;
    g0 = 9.80665;
    isp = 60;
    jmax = (-(1.7976931348623157e+308));
    for i = (0):((3) - 1)
        jmax = asils.pc.fmax(jmax, j((i) + 1));
    end
    arm = [(0.45 * bx(2)); (0.45 * bx(1)); (0.45 * bx(1))];
    alpha = asils.models.sizedemand.size_max((tau_req / jmax), ((h_detumble / 600) / jmax));
    fr = (-(1.7976931348623157e+308));
    for i = (0):((3) - 1)
        fr = asils.pc.fmax(fr, ((j((i) + 1) * alpha) / (2 * arm((i) + 1))));
    end
    f_req = (fr * s);
    cls = [0.005; 0.01; 0.02; 0.05; 0.1];
    found = false;
    thrust = 0;
    for c = (0):((5) - 1)
        if ((~found) && (cls((c) + 1) >= f_req))
            thrust = cls((c) + 1);
            found = true;
        end
    end
    if (~found)
        thrust = (ceil((f_req / 0.05)) * 0.05);
    end
    arm_eff = (3 / (((1 / arm(1)) + (1 / arm(2))) + (1 / arm(3))));
    orbits = (((life * 365.25) * 86400) / period);
    it_det = ((2 * h_detumble) / arm_eff);
    it_dump = ((h_secular * orbits) / arm_eff);
    it_slew = (((((spd * 365.25) * life) * 2) * h_slew) / arm_eff);
    mprop = asils.models.sizedemand.size_max(((1.2 * (it_det + it_dump)) / (isp * g0)), 0.01);
    mslew = ((1.2 * it_slew) / (isp * g0));
    v = ((1.25 * mprop) / 745);
    rtank = asils.pc.pow_(((3 * v) / (4 * pi)), (1 / 3));
    pm = 7000000;
    sig = 250000000;
    t = asils.models.sizedemand.size_max(((pm * rtank) / (2 * sig)), 0.0005);
    mtank = (((((4 * pi) * rtank) * rtank) * t) * 2810);
    dry_mass = ((mtank + (12 * 0.01)) + 0.05);
    mass = (dry_mass + mprop);
    tank_volume = (v * 1000);
    tank_radius = rtank;
    tank_wall = t;
    arm_long = arm(2);
    arm_short = arm(1);
    volume = ((asils.pc.ipow((2 * rtank), 3) * 1000) + 0.05);
    isp_budget = isp;
end
