function [thrust_dist, thrust_mean, thrust_sigma, isp_dist, isp_lo, isp_hi, mis_dist, mis_mean, mis_sigma] = rcs_dispersion()
%RCS_DISPERSION  The thrusters' dispersion: the thrust's scale (normal, mean 1, sigma 3 %), the Isp [s] (uniform 60 to 80) and the
%   axis's misalignment [rad] (normal, mean 0, sigma 10 mrad).
%   returns thrust_dist: Dist (passed a choice, as its option's number)
%   returns thrust_mean: int (passed a whole number)
%   returns thrust_sigma: real[1] (passed a plain number)
%   returns isp_dist: Dist (passed a choice, as its option's number)
%   returns isp_lo: int (passed a whole number)
%   returns isp_hi: int (passed a whole number)
%   returns mis_dist: Dist (passed a choice, as its option's number)
%   returns mis_mean: int (passed a whole number)
%   returns mis_sigma: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    thrust_dist = 0;
    thrust_mean = 0;
    thrust_sigma = 0;
    isp_dist = 0;
    isp_lo = 0;
    isp_hi = 0;
    mis_dist = 0;
    mis_mean = 0;
    mis_sigma = 0;
    thrust_dist = 0;
    thrust_mean = 1;
    thrust_sigma = 0.03;
    isp_dist = 1;
    isp_lo = 60;
    isp_hi = 80;
    mis_dist = 0;
    mis_mean = 0;
    mis_sigma = 0.01;
end
