function [isp, thrusters, mib, valve_res, tank_pressure, meop, valve_power, power_steady] = rcs_part()
%RCS_PART  The thruster part's stated values: its nominal Isp [s], thrusters, minimum impulse bit [s], valve resolution [s], the
%   tank's pressure and MEOP [bar], a valve's power and the steady power [W].
%   returns isp: int (passed a whole number)
%   returns thrusters: int (passed a whole number)
%   returns mib: real[1] (passed a plain number)
%   returns valve_res: real[1] (passed a plain number)
%   returns tank_pressure: int (passed a whole number)
%   returns meop: int (passed a whole number)
%   returns valve_power: real[1] (passed a plain number)
%   returns power_steady: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    isp = 0;
    thrusters = 0;
    mib = 0;
    valve_res = 0;
    tank_pressure = 0;
    meop = 0;
    valve_power = 0;
    power_steady = 0;
    isp = 70;
    thrusters = 12;
    mib = 0.005;
    valve_res = 0.001;
    tank_pressure = 50;
    meop = 70;
    valve_power = 1;
    power_steady = 0.05;
end
