//! The design files (`design/schema.toml`, docs/RELEASE_PLAN.md P1), read from Rust.
//!
//! The schema is compiled in. A file is opened read-only: its `meta` names its format and format
//! version; a file of this version opens, an older one is named (tools/tndb.py upgrades it, keeping
//! the original), a newer one is refused (this program cannot know what it holds). `check` names
//! every table and column that is not what the schema says, as tools/tndb.py does; `ddl` is the SQL
//! that makes a file of a kind, and the tests hold it to design/ddl.sql, which tools/tndb.py writes.
//!
//! Owner: Agastya. Copyright (c) 2026 Agastya. All rights reserved.
use std::collections::BTreeMap;
use std::fmt;
use std::path::Path;

use rusqlite::{types::ValueRef, Connection, OpenFlags};
use serde::Deserialize;

/// design/schema.toml as this program was built with it.
pub const SCHEMA_TOML: &str = include_str!("../../../../design/schema.toml");
pub const SCHEMA_ID: &str = "trinetra-design-schema/1";

#[derive(Debug, Clone, Deserialize)]
pub struct Table {
    pub about: String,
    /// [name, "type" or "type key"]
    pub columns: Vec<[String; 2]>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Format {
    pub extension: String,
    pub version: u32,
    pub tables: Vec<String>,
    pub max_bytes: Option<u64>,
    pub max_attachment_bytes: Option<u64>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Schema {
    pub schema: String,
    pub tables: BTreeMap<String, Table>,
    pub formats: BTreeMap<String, Format>,
}

/// A file this program cannot take, said by name.
#[derive(Debug, Clone, PartialEq)]
pub struct FormatError(pub String);

impl fmt::Display for FormatError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::error::Error for FormatError {}

fn err<T>(msg: String) -> Result<T, FormatError> {
    Err(FormatError(msg))
}

impl Schema {
    /// The compiled-in schema.
    pub fn embedded() -> Result<Schema, FormatError> {
        Schema::parse(SCHEMA_TOML)
    }

    pub fn parse(text: &str) -> Result<Schema, FormatError> {
        let s: Schema = toml::from_str(text).map_err(|e| FormatError(format!("design/schema.toml: {e}")))?;
        if s.schema != SCHEMA_ID {
            return err(format!("the schema is {:?}, not {SCHEMA_ID}", s.schema));
        }
        for (kind, f) in &s.formats {
            let missing: Vec<&str> = f.tables.iter().filter(|t| !s.tables.contains_key(*t)).map(|t| t.as_str()).collect();
            if !missing.is_empty() {
                return err(format!("format {kind} names tables the schema does not define: {}", missing.join(", ")));
            }
        }
        Ok(s)
    }

    /// (name, SQLite type upper-case, is key) of one table.
    pub fn columns(&self, table: &str) -> Vec<(String, String, bool)> {
        self.tables[table]
            .columns
            .iter()
            .map(|[name, decl]| {
                let mut parts = decl.split_whitespace();
                let ty = parts.next().unwrap_or("").to_uppercase();
                (name.clone(), ty, parts.any(|p| p == "key"))
            })
            .collect()
    }

    /// The SQL that makes a file of this kind: the same statements tools/tndb.py makes.
    pub fn ddl(&self, kind: &str) -> Result<Vec<String>, FormatError> {
        let f = self.formats.get(kind).ok_or_else(|| FormatError(format!("no format {kind:?}")))?;
        Ok(f.tables
            .iter()
            .map(|t| {
                let cols = self.columns(t);
                let mut body = cols.iter().map(|(c, ty, _)| format!("\"{c}\" {ty}")).collect::<Vec<_>>().join(", ");
                let keys: Vec<String> = cols.iter().filter(|c| c.2).map(|c| format!("\"{}\"", c.0)).collect();
                if !keys.is_empty() {
                    body += &format!(", PRIMARY KEY ({})", keys.join(", "));
                }
                format!("CREATE TABLE \"{t}\" ({body})")
            })
            .collect())
    }

    /// design/ddl.sql as tools/tndb.py writes it.
    pub fn ddl_sql(&self) -> String {
        let mut out = vec!["-- Generated by tools/tndb.py gen from design/schema.toml; do not edit.".to_string()];
        // tools/tndb.py writes the formats in the file's order: node, group, release, design
        for kind in self.kinds_in_file_order() {
            out.push(format!("-- {kind} version {}", self.formats[&kind].version));
            out.extend(self.ddl(&kind).unwrap().into_iter().map(|s| s + ";"));
        }
        out.join("\n") + "\n"
    }

    fn kinds_in_file_order(&self) -> Vec<String> {
        let mut at: Vec<(usize, String)> = self
            .formats
            .keys()
            .map(|k| (SCHEMA_TOML.find(&format!("[formats.{k}]")).unwrap_or(usize::MAX), k.clone()))
            .collect();
        at.sort();
        at.into_iter().map(|(_, k)| k).collect()
    }
}

/// An open design file: its kind, its meta, its connection (read-only).
#[derive(Debug)]
pub struct DesignFile {
    pub kind: String,
    pub meta: BTreeMap<String, String>,
    pub conn: Connection,
}

fn meta(conn: &Connection) -> Result<BTreeMap<String, String>, FormatError> {
    let mut st = conn
        .prepare("SELECT \"key\", \"value\" FROM meta")
        .map_err(|e| FormatError(format!("no meta table: not a design file ({e})")))?;
    let rows = st
        .query_map([], |r| Ok((r.get::<_, String>(0)?, r.get::<_, String>(1)?)))
        .and_then(|it| it.collect::<Result<BTreeMap<_, _>, _>>())
        .map_err(|e| FormatError(format!("meta unreadable: {e}")))?;
    Ok(rows)
}

/// Open a design file read-only, of this kind when one is named.
pub fn open(path: &Path, kind: Option<&str>, s: &Schema) -> Result<DesignFile, FormatError> {
    let p = path.display();
    if !path.is_file() {
        return err(format!("{p}: no such file"));
    }
    let conn = Connection::open_with_flags(path, OpenFlags::SQLITE_OPEN_READ_ONLY)
        .map_err(|e| FormatError(format!("{p}: {e}")))?;
    let m = meta(&conn)?;
    let got = m.get("format").cloned().unwrap_or_default();
    let Some(f) = s.formats.get(&got) else {
        return err(format!("{p}: format {got:?} is not a design-file format"));
    };
    if let Some(k) = kind {
        if k != got {
            return err(format!("{p}: a {got} file, not a {k} file"));
        }
    }
    let have: u32 = m.get("format_version").and_then(|v| v.parse().ok()).unwrap_or(0);
    if have > f.version {
        return err(format!("{p}: {got} format version {have} is newer than this program's {}; open it with a newer TRI-NETRA", f.version));
    }
    if have < f.version {
        return err(format!("{p}: {got} format version {have} is older than this program's {}; upgrade it first (python3 tools/tndb.py check {p})", f.version));
    }
    Ok(DesignFile { kind: got, meta: m, conn })
}

/// Every problem with one file: its format, every table and column against the schema, its size.
pub fn check(path: &Path, s: &Schema) -> Vec<String> {
    let f = match open(path, None, s) {
        Ok(f) => f,
        Err(e) => return vec![e.0],
    };
    let p = path.display();
    let fmt = &s.formats[&f.kind];
    let mut errs = Vec::new();
    let have: Vec<String> = f
        .conn
        .prepare("SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name")
        .and_then(|mut st| st.query_map([], |r| r.get(0))?.collect())
        .unwrap_or_default();
    let mut want = fmt.tables.clone();
    want.sort();
    for t in want.iter().filter(|t| !have.contains(t)) {
        errs.push(format!("{p}: table {t} missing"));
    }
    for t in have.iter().filter(|t| !want.contains(t)) {
        errs.push(format!("{p}: table {t} is not in the {} format", f.kind));
    }
    for t in want.iter().filter(|t| have.contains(t)) {
        let got: Vec<(String, String)> = f
            .conn
            .prepare(&format!("PRAGMA table_info(\"{t}\")"))
            .and_then(|mut st| st.query_map([], |r| Ok((r.get::<_, String>(1)?, r.get::<_, String>(2)?.to_uppercase())))?.collect())
            .unwrap_or_default();
        let exp: Vec<(String, String)> = s.columns(t).into_iter().map(|(c, ty, _)| (c, ty)).collect();
        if got != exp {
            errs.push(format!("{p}: table {t} has columns {got:?}, the schema says {exp:?}"));
        }
    }
    if let (Some(max), Ok(md)) = (fmt.max_bytes, std::fs::metadata(path)) {
        if md.len() > max {
            errs.push(format!("{p}: {} bytes, over the {max} a {} file may hold", md.len(), f.kind));
        }
    }
    if let (Some(max), true) = (fmt.max_attachment_bytes, have.iter().any(|t| t == "attachment")) {
        let big: Vec<(String, i64)> = f
            .conn
            .prepare("SELECT name, size FROM attachment WHERE size > ?1")
            .and_then(|mut st| st.query_map([max as i64], |r| Ok((r.get(0)?, r.get(1)?)))?.collect())
            .unwrap_or_default();
        errs.extend(big.into_iter().map(|(n, z)| format!("{p}: attachment {n} is {z} bytes, over {max}")));
    }
    errs
}

/// One cell, as the reader hands it on.
#[derive(Debug, Clone, PartialEq)]
pub enum Cell {
    Null,
    Integer(i64),
    Real(f64),
    Text(String),
    Blob(Vec<u8>),
}

impl DesignFile {
    /// Every row of one of the file's tables, in the schema's column order.
    pub fn rows(&self, table: &str, s: &Schema) -> Result<Vec<Vec<Cell>>, FormatError> {
        if !s.formats[&self.kind].tables.iter().any(|t| t == table) {
            return err(format!("a {} file has no table {table}", self.kind));
        }
        let cols = s.columns(table);
        let sql = format!(
            "SELECT {} FROM \"{table}\"",
            cols.iter().map(|c| format!("\"{}\"", c.0)).collect::<Vec<_>>().join(", ")
        );
        let mut st = self.conn.prepare(&sql).map_err(|e| FormatError(format!("{table}: {e}")))?;
        let n = cols.len();
        let rows = st
            .query_map([], |r| {
                (0..n)
                    .map(|i| {
                        Ok(match r.get_ref(i)? {
                            ValueRef::Null => Cell::Null,
                            ValueRef::Integer(v) => Cell::Integer(v),
                            ValueRef::Real(v) => Cell::Real(v),
                            ValueRef::Text(v) => Cell::Text(String::from_utf8_lossy(v).into_owned()),
                            ValueRef::Blob(v) => Cell::Blob(v.to_vec()),
                        })
                    })
                    .collect::<Result<Vec<_>, _>>()
            })
            .and_then(|it| it.collect::<Result<Vec<_>, _>>())
            .map_err(|e| FormatError(format!("{table}: {e}")))?;
        Ok(rows)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn tmp(name: &str) -> PathBuf {
        let d = std::env::temp_dir().join(format!("trinetra-design-{}-{name}", std::process::id()));
        let _ = std::fs::remove_file(&d);
        d
    }

    fn make(path: &Path, kind: &str, version: &str, s: &Schema) -> Connection {
        let c = Connection::open(path).unwrap();
        for st in s.ddl(kind).unwrap() {
            c.execute(&st, []).unwrap();
        }
        for (k, v) in [("format", kind), ("format_version", version), ("id", "t"), ("written_by", "test")] {
            c.execute("INSERT INTO meta VALUES (?1, ?2)", [k, v]).unwrap();
        }
        c
    }

    #[test]
    fn the_sql_is_what_tools_tndb_py_writes() {
        let s = Schema::embedded().unwrap();
        let committed = include_str!("../../../../design/ddl.sql");
        assert_eq!(s.ddl_sql(), committed, "design/ddl.sql is not what this reader makes: run tools/tndb.py gen");
    }

    #[test]
    fn a_file_of_every_kind_checks_clean_and_reads_back() {
        let s = Schema::embedded().unwrap();
        for kind in s.formats.keys() {
            let p = tmp(&format!("{kind}.tndb"));
            drop(make(&p, kind, &s.formats[kind].version.to_string(), &s));
            assert_eq!(check(&p, &s), Vec::<String>::new(), "{kind}");
            let f = open(&p, Some(kind), &s).unwrap();
            assert_eq!(f.meta["id"], "t");
            std::fs::remove_file(&p).unwrap();
        }
    }

    #[test]
    fn a_node_reads_its_rows_and_a_big_picture_is_named() {
        let s = Schema::embedded().unwrap();
        let p = tmp("pic.node.tndb");
        let c = make(&p, "node", "1", &s);
        c.execute("INSERT INTO content VALUES ('spec', 'symbol', 't_epoch', 'spec:seed_content.toml')", []).unwrap();
        c.execute("INSERT INTO attachment VALUES ('big.png', 'image/png', 600000, x'00')", []).unwrap();
        drop(c);
        let f = open(&p, Some("node"), &s).unwrap();
        let rows = f.rows("content", &s).unwrap();
        assert_eq!(rows[0][2], Cell::Text("t_epoch".into()));
        assert!(f.rows("group_info", &s).is_err());
        drop(f);
        assert!(check(&p, &s).iter().any(|e| e.contains("attachment big.png is 600000 bytes")));
        std::fs::remove_file(&p).unwrap();
    }

    #[test]
    fn a_wrong_kind_an_older_and_a_newer_file_are_named() {
        let s = Schema::embedded().unwrap();
        let p = tmp("v.node.tndb");
        drop(make(&p, "node", "1", &s));
        assert!(open(&p, Some("group"), &s).unwrap_err().0.contains("a node file, not a group file"));
        let mut newer = s.clone();
        newer.formats.get_mut("node").unwrap().version = 2;
        assert!(open(&p, None, &newer).unwrap_err().0.contains("older than this program's 2"));
        let mut older = s.clone();
        older.formats.get_mut("node").unwrap().version = 0;
        assert!(open(&p, None, &older).unwrap_err().0.contains("newer than this program's 0"));
        std::fs::remove_file(&p).unwrap();
    }

    #[test]
    fn a_missing_table_and_a_stray_one_are_named() {
        let s = Schema::embedded().unwrap();
        let p = tmp("torn.node.tndb");
        let c = make(&p, "node", "1", &s);
        c.execute("DROP TABLE fixture", []).unwrap();
        c.execute("CREATE TABLE extra (x TEXT)", []).unwrap();
        drop(c);
        let e = check(&p, &s);
        assert!(e.iter().any(|x| x.contains("table fixture missing")));
        assert!(e.iter().any(|x| x.contains("table extra is not in the node format")));
        std::fs::remove_file(&p).unwrap();
    }
}
