function r = acos_(x)
%ACOS_  acos(x), nan where |x| > 1 (MATLAB's is complex there; C's, Rust's and the interpreter's nan).
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    r = acos(x);
    if ~isreal(r), r = NaN; end
end
