function ix = argsort_(v)
%ARGSORT_  the indices (from 0) of a vector in ascending order, equal values in their order: an insertion sort.
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    ix = (0:numel(v) - 1).';
    for i = 2:numel(ix)
        k = ix(i); j = i - 1;
        while j >= 1 && v(ix(j) + 1) > v(k + 1), ix(j + 1) = ix(j); j = j - 1; end
        ix(j + 1) = k;
    end
end
