function r = choose_lazy(c, a, b)
%CHOOSE_LAZY  a() when c, else b(): only the branch taken is evaluated.
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    if c, r = a(); else, r = b(); end
end
