function s = dot_(a, b)
%DOT_  sum of products, left to right.
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = a(1)*b(1);
    for i = 2:numel(a), s = s + a(i)*b(i); end
end
