function r = eig_sgn_(x, y)
%EIG_SGN_  |x| with the sign of y (y = 0 or -0: positive).
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    if y >= 0, r = abs(x); else, r = -abs(x); end
end
