function r = ipow(x, k)
%IPOW  x^k by repeated multiplication, left to right (x^-k = 1/(x^k)).
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    if k == 0, r = 1; return; end
    r = x;
    for i = 2:abs(k), r = r*x; end
    if k < 0, r = 1/r; end
end
