function C = mm(A, B)
%MM  matrix product, summed left to right.
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    C = zeros(size(A, 1), size(B, 2));
    for i = 1:size(A, 1)
        for j = 1:size(B, 2)
            s = A(i, 1)*B(1, j);
            for k = 2:size(B, 1), s = s + A(i, k)*B(k, j); end
            C(i, j) = s;
        end
    end
end
