function r = mv(M, v)
%MV  matrix times vector, each row summed left to right.
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    r = zeros(size(M, 1), 1);
    for i = 1:size(M, 1), r(i) = asils.pc.dot_(M(i, :), v); end
end
