function r = pow_(x, y)
%POW_  x^y, nan where x < 0 and y is not whole (MATLAB's is complex there; C's, Rust's and the interpreter's nan).
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    r = x^y;
    if ~isreal(r), r = NaN; end
end
