function [u, s] = stream_uniform(s)
%STREAM_UNIFORM  a uniform draw on (0, 1), and the stream advanced.
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    n = asils.pc.u64_add_([s(3), s(4)], [0, 1]);
    z = asils.pc.sm64_(asils.pc.u64_xor_([s(1), s(2)], asils.pc.sm64_(n)));
    u = (z(1)*2097152 + floor(z(2) / 2048) + 0.5)*(1/9007199254740992);
    s(3) = n(1); s(4) = n(2);
end
