function r = u64_shr_(a, k)
%U64_SHR_  a shifted right by k (0 < k < 32), in 32-bit halves [high, low].
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    r = [floor(a(1) / 2^k), mod(a(1), 2^k)*2^(32 - k) + floor(a(2) / 2^k)];
end
