function r = vfmax(a, b)
%VFMAX  the larger, element by element (b only where b > a).
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    o = ones(size(a)) .* ones(size(b));
    r = a .* o; b = b .* o; m = b > r;
    r(m) = b(m);
end
