function [q] = c2ixys(x, y, s)
%C2IXYS  The celestial-to-intermediate matrix from X, Y and s (iauC2ixys). (Its inputs' ranges are wider than the Earth's
%   pole and s ever are, so the vectors hold the matrix where its small elements do not come from cancellation.)
%   x: real[1] (passed a plain number)
%   y: real[1] (passed a plain number)
%   s: real[1] (passed a plain number)
%   returns q: real[1][3][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    q = zeros(3, 3);
    r2v = ((x * x) + (y * y));
    e = 0;
    if (r2v > 0)
        e = atan2(y, x);
    end
    d = atan(sqrt((r2v / (1 - r2v))));
    q = asils.pc.mm(asils.pc.mm(asils.models.earthframes.rot3((-((e + s)))), asils.models.earthframes.rot2(d)), asils.models.earthframes.rot3(e));
end
