function [fa] = fund_args(t)
%FUND_ARGS  The 14 fundamental arguments of the IERS Conventions 2003 [rad] at t TT centuries (l, l', F, D, Om; the planets'
%   mean longitudes Me .. Ne; the general precession in longitude).
%   t: real[1] (passed a plain number)
%   returns fa: real[1][14] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    fa = zeros(14, 1);
    fa(1) = (asils.models.timescales.omod((485868.249036 + (t * (1717915923.2178 + (t * (31.8792 + (t * (0.051635 + (t * (-(0.0002447)))))))))), 1296000) * 0.00000484813681109536);
    fa(2) = (asils.models.timescales.omod((1287104.793048 + (t * (129596581.0481 + (t * ((-(0.5532)) + (t * (0.000136 + (t * (-(0.00001149)))))))))), 1296000) * 0.00000484813681109536);
    fa(3) = (asils.models.timescales.omod((335779.526232 + (t * (1739527262.8478 + (t * ((-(12.7512)) + (t * ((-(0.001037)) + (t * 0.00000417)))))))), 1296000) * 0.00000484813681109536);
    fa(4) = (asils.models.timescales.omod((1072260.703692 + (t * (1602961601.209 + (t * ((-(6.3706)) + (t * (0.006593 + (t * (-(0.00003169)))))))))), 1296000) * 0.00000484813681109536);
    fa(5) = (asils.models.timescales.omod((450160.398036 + (t * ((-(6962890.5431)) + (t * (7.4722 + (t * (0.007702 + (t * (-(0.00005939)))))))))), 1296000) * 0.00000484813681109536);
    fa(6) = asils.models.timescales.omod((4.402608842 + (2608.7903141574 * t)), (2 * pi));
    fa(7) = asils.models.timescales.omod((3.176146697 + (1021.3285546211 * t)), (2 * pi));
    fa(8) = asils.models.timescales.omod((1.753470314 + (628.3075849991 * t)), (2 * pi));
    fa(9) = asils.models.timescales.omod((6.203480913 + (334.06124267 * t)), (2 * pi));
    fa(10) = asils.models.timescales.omod((0.599546497 + (52.9690962641 * t)), (2 * pi));
    fa(11) = asils.models.timescales.omod((0.874016757 + (21.329910496 * t)), (2 * pi));
    fa(12) = asils.models.timescales.omod((5.481293872 + (7.4781598567 * t)), (2 * pi));
    fa(13) = asils.models.timescales.omod((5.311886287 + (3.8133035638 * t)), (2 * pi));
    fa(14) = ((0.02438175 + (0.00000538691 * t)) * t);
end
