function [y] = ring_target(htgt, cmd, dt, h_max)
%RING_TARGET  The driver's momentum target [N m s] after a step dt of the commanded rate cmd [N m], within the capacity.
%   htgt: real[1] (passed a plain number)
%   cmd: real[1] (passed a plain number)
%   dt: real[1] (passed a plain number)
%   h_max: real[1] (passed a plain number)
%   returns y: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    y = 0;
    y = asils.models.coilsat.act_clamp((htgt + (cmd * dt)), (-(h_max)), h_max);
end
