function [pump] = ring_pump(cmd, hf, tsd, k_flow, htgt, torque_max)
%RING_PUMP  The pump torque [N m]: the commanded rate, the spin-down's loss of the filtered momentum hf and the target's error
%   times k_flow, within the largest torque.
%   cmd: real[1] (passed a plain number)
%   hf: real[1] (passed a plain number)
%   tsd: real[1] (passed a plain number)
%   k_flow: real[1] (passed a plain number)
%   htgt: real[1] (passed a plain number)
%   torque_max: real[1] (passed a plain number)
%   returns pump: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    pump = 0;
    pump = asils.models.coilsat.act_clamp(((cmd + (hf / tsd)) + (k_flow * (htgt - hf))), (-(torque_max)), torque_max);
end
