function [h, tau, w, j, radius, rotor_mass, coulomb, viscous, static_imbalance, dynamic_imbalance, peak, mass, rpm_assumed, peak_assumed] = catalogue_rotor(h_mnms, torque_mnm, rpm, mass_g, p_steady, p_peak)
%CATALOGUE_ROTOR  The rotor of a model from its datasheet's momentum h [mN m s], torque [mN m], speed at that momentum rpm [rpm, nan:
%   not stated], mass [g], steady and peak power [W, the peak nan when not stated]: its momentum [N m s], torque [N m],
%   speed [rad/s], inertia [kg m^2], radius [m], mass [kg], Coulomb [N m] and viscous [N m s] friction, static [kg m] and
%   dynamic [kg m^2] imbalance, the peak power [W] and the unit's mass [kg]; which values were assumed.
%   h_mnms: real[1] (passed a plain number)
%   torque_mnm: real[1] (passed a plain number)
%   rpm: real[1] (passed a plain number)
%   mass_g: real[1] (passed a plain number)
%   p_steady: real[1] (passed a plain number)
%   p_peak: real[1] (passed a plain number)
%   returns h: real[1] (passed a plain number)
%   returns tau: real[1] (passed a plain number)
%   returns w: real[1] (passed a plain number)
%   returns j: real[1] (passed a plain number)
%   returns radius: real[1] (passed a plain number)
%   returns rotor_mass: real[1] (passed a plain number)
%   returns coulomb: real[1] (passed a plain number)
%   returns viscous: real[1] (passed a plain number)
%   returns static_imbalance: real[1] (passed a plain number)
%   returns dynamic_imbalance: real[1] (passed a plain number)
%   returns peak: real[1] (passed a plain number)
%   returns mass: real[1] (passed a plain number)
%   returns rpm_assumed: bool (passed true or false)
%   returns peak_assumed: bool (passed true or false)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    h = 0;
    tau = 0;
    w = 0;
    j = 0;
    radius = 0;
    rotor_mass = 0;
    coulomb = 0;
    viscous = 0;
    static_imbalance = 0;
    dynamic_imbalance = 0;
    peak = 0;
    mass = 0;
    rpm_assumed = false;
    peak_assumed = false;
    [assumed_rpm, share, gyration, balance, c_coulomb, c_ref, c_viscous, peak_eff, a8, a9, a10, a11, a12, a13] = asils.models.catderive.catalogue_rules();
    rpm_rad = ((2 * pi) / 60);
    h = (h_mnms * 0.001);
    tau = (torque_mnm * 0.001);
    rpm_assumed = isnan(rpm);
    if rpm_assumed
        h__33 = assumed_rpm;
    else
        h__33 = rpm;
    end
    speed = h__33;
    w = (speed * rpm_rad);
    j = (h / w);
    mass = (mass_g * 0.001);
    rotor_mass = (share * mass);
    h__34 = (j / (gyration * rotor_mass));
    if h__34 < 0, h__34 = NaN; else, h__34 = sqrt(h__34); end
    radius = h__34;
    static_imbalance = ((rotor_mass * balance) / w);
    h__35 = (h / c_ref);
    if h__35 < 0, h__35 = NaN; else, h__35 = sqrt(h__35); end
    coulomb = (c_coulomb * h__35);
    viscous = c_viscous;
    dynamic_imbalance = ((static_imbalance * radius) / 2);
    peak_assumed = isnan(p_peak);
    if peak_assumed
        h__36 = (p_steady + ((tau * w) / peak_eff));
    else
        h__36 = p_peak;
    end
    peak = h__36;
end
