function [j] = rotor_jitter(n, h, jrot, us, ud, jmin, d, wbw)
%ROTOR_JITTER  The jitter [arcsec] of one sample: the n rotors' momenta h [N m s], their rotor inertias jrot [kg m^2], static and
%   dynamic imbalances us, ud, over the body's jmin and lever d and the loop's bandwidth wbw [rad/s]. A rotor with no
%   imbalance, or no rotor inertia, adds nothing; a speed that is not finite counts as zero.
%   n: int (passed a whole number)
%   h: real[1][JIT_NR] (passed a plain number)
%   jrot: real[1][JIT_NR] (passed a plain number)
%   us: real[1][JIT_NR] (passed a plain number)
%   ud: real[1][JIT_NR] (passed a plain number)
%   jmin: real[1] (passed a plain number)
%   d: real[1] (passed a plain number)
%   wbw: real[1] (passed a plain number)
%   returns j: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    j = 0;
    th2 = 0;
    for i = (0):((n) - 1)
        t = 0;
        if ((~((us((i) + 1) == 0) && (ud((i) + 1) == 0))) && (jrot((i) + 1) > 0))
            w = (asils.pc.fabs(h((i) + 1)) / jrot((i) + 1));
            if (~isfinite(w))
                w = 0;
            end
            th = (((((us((i) + 1) * d) + ud((i) + 1)) * w) * w) / (jmin * asils.pc.fmax((w * w), (wbw * wbw))));
            t = (th * th);
        end
        th2 = (th2 + t);
    end
    j = ((asils.pc.sqrt_(th2) * (180 / pi)) * 3600);
end
