function [us, ud, known] = rotor_imbalance(ring, us_part, ud_part)
%ROTOR_IMBALANCE  A rotor's imbalance for the jitter: a fluid ring has none (no rotating mass); a wheel or a gyro's rotor has its part's
%   static [kg m] and dynamic [kg m^2] imbalance when the part states both (nan where it does not), and is not known
%   otherwise (the jitter is then not computed).
%   ring: bool (passed true or false)
%   us_part: real[1] (passed a plain number)
%   ud_part: real[1] (passed a plain number)
%   returns us: real[1] (passed a plain number)
%   returns ud: real[1] (passed a plain number)
%   returns known: bool (passed true or false)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    us = 0;
    ud = 0;
    known = false;
    us = 0;
    ud = 0;
    known = false;
    if ring
        known = true;
    elseif ((~isnan(us_part)) && (~isnan(ud_part)))
        us = us_part;
        ud = ud_part;
        known = true;
    end
end
