function [a] = lense_thirring(r, v, mu, jvec, gamma)
%LENSE_THIRRING  relativity.lenseThirring(rSat, vSat, mu, Jvec, gamma).
%   r: real[1][3] (passed a plain number)
%   v: real[1][3] (passed a plain number)
%   mu: real[1] (passed a plain number)
%   jvec: real[1][3] (passed a plain number)
%   gamma: real[1] (passed a plain number)
%   returns a: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    a = zeros(3, 1);
    c = getfield(asils.models.de440.de440_constants(), 'c');
    rn = asils.pc.norm_(r);
    k = (((1 + gamma) * mu) / ((c * c) * asils.pc.pow_(rn, 3)));
    rxv = asils.pc.cross_(r, v);
    vxj = asils.pc.cross_(v, jvec);
    q = (3 / (rn * rn));
    rj = asils.pc.dot_(r, jvec);
    a = [(k * (((q * rxv(1)) * rj) + vxj(1))); (k * (((q * rxv(2)) * rj) + vxj(2))); (k * (((q * rxv(3)) * rj) + vxj(3)))];
end
