function s = RelParts_zero()
%RELPARTS_ZERO  a RelParts with every field zero
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = struct();
    s.has_schwarzschild = false;
    s.schwarzschild = zeros(3, 1);
    s.has_lensethirring = false;
    s.lensethirring = zeros(3, 1);
    s.has_desitter = false;
    s.desitter = zeros(3, 1);
end
