function [p] = prec_rot(jd)
%PREC_ROT  J2000 to the mean equator of date (IAU-76 precession): P = R3(-z) R2(theta) R3(-zeta).
%   jd: real[1] (passed a plain number)
%   returns p: real[1][3][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    p = zeros(3, 3);
    t = ((jd - 2451545) / 36525);
    as_ = (pi / (180 * 3600));
    ze = ((((2306.2181 * t) + ((0.30188 * t) * t)) + (((0.017998 * t) * t) * t)) * as_);
    z = ((((2306.2181 * t) + ((1.09468 * t) * t)) + (((0.018203 * t) * t) * t)) * as_);
    th = ((((2004.3109 * t) - ((0.42665 * t) * t)) - (((0.041833 * t) * t) * t)) * as_);
    cz = cos(ze);
    sz = sin(ze);
    cc = cos(z);
    sc = sin(z);
    ct = cos(th);
    st = sin(th);
    p = [([(((cc * ct) * cz) - (sc * sz)); ((((-(cc)) * ct) * sz) - (sc * cz)); ((-(cc)) * st)]).'; ([(((sc * ct) * cz) + (cc * sz)); ((((-(sc)) * ct) * sz) + (cc * cz)); ((-(sc)) * st)]).'; ([(st * cz); ((-(st)) * sz); ct]).'];
end
