function [q, ok] = triad(b1, b2, r1, r2)
%TRIAD  TRIAD from two body vectors and their references; ok = false when either pair is within
%   1e-3 (0.06 deg) of parallel, which fixes no attitude.
%   b1: real[1][3] (passed a plain number)
%   b2: real[1][3] (passed a plain number)
%   r1: real[1][3] (passed a plain number)
%   r2: real[1][3] (passed a plain number)
%   returns q: real[1][4] (passed a plain number)
%   returns ok: bool (passed true or false)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    q = zeros(4, 1);
    ok = false;
    ok = false;
    q = zeros(4, 1);
    h__74 = [b1(2)*b2(3) - b1(3)*b2(2); b1(3)*b2(1) - b1(1)*b2(3); b1(1)*b2(2) - b1(2)*b2(1)];
    if ((sqrt(h__74(1)*h__74(1) + h__74(2)*h__74(2) + h__74(3)*h__74(3)) > ((0.001 * sqrt(b1(1)*b1(1) + b1(2)*b1(2) + b1(3)*b1(3))) * sqrt(b2(1)*b2(1) + b2(2)*b2(2) + b2(3)*b2(3)))) && (asils.pc.norm_([r1(2)*r2(3) - r1(3)*r2(2); r1(3)*r2(1) - r1(1)*r2(3); r1(1)*r2(2) - r1(2)*r2(1)]) > ((0.001 * sqrt(r1(1)*r1(1) + r1(2)*r1(2) + r1(3)*r1(3))) * sqrt(r2(1)*r2(1) + r2(2)*r2(2) + r2(3)*r2(3)))))
        ok = true;
        h__75 = sqrt(b1(1)*b1(1) + b1(2)*b1(2) + b1(3)*b1(3));
        if 1e-30 > h__75, h__75 = 1e-30; end
        tb0 = (b1 / h__75);
        h__76 = [b1(2)*b2(3) - b1(3)*b2(2); b1(3)*b2(1) - b1(1)*b2(3); b1(1)*b2(2) - b1(2)*b2(1)];
        h__77 = sqrt(h__76(1)*h__76(1) + h__76(2)*h__76(2) + h__76(3)*h__76(3));
        if 1e-30 > h__77, h__77 = 1e-30; end
        tb1 = (h__76 / h__77);
        tb2 = [tb0(2)*tb1(3) - tb0(3)*tb1(2); tb0(3)*tb1(1) - tb0(1)*tb1(3); tb0(1)*tb1(2) - tb0(2)*tb1(1)];
        h__78 = sqrt(r1(1)*r1(1) + r1(2)*r1(2) + r1(3)*r1(3));
        if 1e-30 > h__78, h__78 = 1e-30; end
        tr0 = (r1 / h__78);
        h__79 = [r1(2)*r2(3) - r1(3)*r2(2); r1(3)*r2(1) - r1(1)*r2(3); r1(1)*r2(2) - r1(2)*r2(1)];
        h__80 = sqrt(h__79(1)*h__79(1) + h__79(2)*h__79(2) + h__79(3)*h__79(3));
        if 1e-30 > h__80, h__80 = 1e-30; end
        tr1 = (h__79 / h__80);
        tr2 = [tr0(2)*tr1(3) - tr0(3)*tr1(2); tr0(3)*tr1(1) - tr0(1)*tr1(3); tr0(1)*tr1(2) - tr0(2)*tr1(1)];
        a = zeros(3, 3);
        i = ((0):((3) - 1)).';
        j = (0):((3) - 1);
        a((i) + 1, (j) + 1) = (((reshape(tb0((i) + 1), [], 1) .* reshape(tr0((j) + 1), 1, [])) + (reshape(tb1((i) + 1), [], 1) .* reshape(tr1((j) + 1), 1, []))) + (reshape(tb2((i) + 1), [], 1) .* reshape(tr2((j) + 1), 1, [])));
        q = asils.relations.shared.fromdcm(a);
    end
end
