function [q, ok] = triad(b1, b2, r1, r2)
%TRIAD  TRIAD from two body vectors and their references; ok = false when either pair is within
%   1e-3 (0.06 deg) of parallel, which fixes no attitude.
%   b1: real[1][3] (passed a plain number)
%   b2: real[1][3] (passed a plain number)
%   r1: real[1][3] (passed a plain number)
%   r2: real[1][3] (passed a plain number)
%   returns q: real[1][4] (passed a plain number)
%   returns ok: bool (passed true or false)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    q = zeros(4, 1);
    ok = false;
    ok = false;
    q = zeros(4, 1);
    if ((asils.pc.norm_(asils.pc.cross_(b1, b2)) > ((0.001 * asils.pc.norm_(b1)) * asils.pc.norm_(b2))) && (asils.pc.norm_(asils.pc.cross_(r1, r2)) > ((0.001 * asils.pc.norm_(r1)) * asils.pc.norm_(r2))))
        ok = true;
        tb0 = asils.pc.unit_(b1);
        tb1 = asils.pc.unit_(asils.pc.cross_(b1, b2));
        tb2 = asils.pc.cross_(tb0, tb1);
        tr0 = asils.pc.unit_(r1);
        tr1 = asils.pc.unit_(asils.pc.cross_(r1, r2));
        tr2 = asils.pc.cross_(tr0, tr1);
        a = zeros(3, 3);
        for i = (0):((3) - 1)
            for j = (0):((3) - 1)
                a((i) + 1, (j) + 1) = (((tb0((i) + 1) * tr0((j) + 1)) + (tb1((i) + 1) * tr1((j) + 1))) + (tb2((i) + 1) * tr2((j) + 1)));
            end
        end
        q = asils.relations.shared.fromdcm(a);
    end
end
