function [APE] = gp_5(terms)
%GP_5  The node's answer, APE, as pointing_error_rss gives it.
%   terms: real[rad][5] (passed a plain number)
%   returns APE: real[rad] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    APE = 0;
    APE = asils.groups.pnt.pointing_error_rss(terms);
end
