function [lam, v] = jacobi_eig4(k)
%JACOBI_EIG4  Eigen-decomposition of a symmetric 4 x 4 by cyclic Jacobi: 12 sweeps over the pairs (0,1) (0,2)
%   (0,3) (1,2) (1,3) (2,3) in that order. Returns the eigenvalues and the eigenvectors as columns.
%   k: real[1][4][4] (passed a plain number)
%   returns lam: real[1][4] (passed a plain number)
%   returns v: real[1][4][4] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    lam = zeros(4, 1);
    v = zeros(4, 4);
    a = k;
    v = [([1; 0; 0; 0]).'; ([0; 1; 0; 0]).'; ([0; 0; 1; 0]).'; ([0; 0; 0; 1]).'];
    pp = [0; 0; 0; 1; 1; 2];
    qq = [1; 2; 3; 2; 3; 3];
    for sweep = (0):((12) - 1)
        for pi_ = (0):((6) - 1)
            p = pp((pi_) + 1);
            q = qq((pi_) + 1);
            apq = a((p) + 1, (q) + 1);
            if (asils.pc.fabs(apq) >= 1e-300)
                th = ((a((q) + 1, (q) + 1) - a((p) + 1, (p) + 1)) / (2 * apq));
                t = (sign(th) / (asils.pc.fabs(th) + sqrt(((th * th) + 1))));
                if (th == 0)
                    t = 1;
                end
                c = (1 / sqrt(((t * t) + 1)));
                sn = (t * c);
                for i = (0):((4) - 1)
                    aip = a((i) + 1, (p) + 1);
                    aiq = a((i) + 1, (q) + 1);
                    a((i) + 1, (p) + 1) = ((c * aip) - (sn * aiq));
                    a((i) + 1, (q) + 1) = ((sn * aip) + (c * aiq));
                end
                for i = (0):((4) - 1)
                    api = a((p) + 1, (i) + 1);
                    aqi = a((q) + 1, (i) + 1);
                    a((p) + 1, (i) + 1) = ((c * api) - (sn * aqi));
                    a((q) + 1, (i) + 1) = ((sn * api) + (c * aqi));
                end
                for i = (0):((4) - 1)
                    vip = v((i) + 1, (p) + 1);
                    viq = v((i) + 1, (q) + 1);
                    v((i) + 1, (p) + 1) = ((c * vip) - (sn * viq));
                    v((i) + 1, (q) + 1) = ((sn * vip) + (c * viq));
                end
            end
        end
    end
    for i = (0):((4) - 1)
        lam((i) + 1) = a((i) + 1, (i) + 1);
    end
end
