function [s] = spin_guards(st, mp, sun_ok, sun, dt)
%SPIN_GUARDS  The spin-up and Sun-spin guards (Standard Code modes.transitions) and the spin-sign flip.
%   vectors: 64
%   st: Modes (passed rec)
%   mp: ModeParams (passed rec)
%   sun_ok: bool (passed true or false)
%   sun: real[1][3] (passed a plain number)
%   dt: real[1] (passed a plain number)
%   returns s: Modes (passed rec)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = asils.alg.modes.Modes_zero();
    s = st;
    d = (pi / 180);
    wz = s.w_est(3);
    wp = asils.pc.sqrt_(((s.w_est(1) * s.w_est(1)) + (s.w_est(2) * s.w_est(2))));
    if (sqrt(s.w_est(1)*s.w_est(1) + s.w_est(2)*s.w_est(2) + s.w_est(3)*s.w_est(3)) > (mp.ss_omega_max_dps * d))
        s = asils.alg.modes.modes_enter(s, 0);
    elseif (s.mode == 5)
        conv = ((asils.pc.fabs((wz - ((s.sigma * mp.ss_spin_dps) * d))) < (mp.ss_z_in_dps * d)) && (wp < (mp.ss_perp_in_dps * d)));
        if (conv && sun_ok)
            s.sz_sum = (s.sz_sum + sun(3));
            s.sz_n = (s.sz_n + 1);
        end
        if ((((s.t - s.sz_t0) >= mp.ss_t_check_s) && (s.sz_n > 0)) && ((s.sz_sum / s.sz_n) > mp.ss_sun_min))
            s.sigma = (-(s.sigma));
            s.sz_sum = 0;
            s.sz_n = 0;
            s.sz_t0 = s.t;
        end
        ok = ((conv && sun_ok) && (sun(3) < 0));
        if ok
            s.hold = (s.hold + dt);
        else
            s.hold = 0;
        end
        if (s.hold >= mp.ss_dwell_in_s)
            s = asils.alg.modes.modes_enter(s, 6);
        end
    else
        bad = ((asils.pc.fabs(wz) < (mp.ss_omega_exit_dps * d)) || (wp > (mp.ss_perp_out_dps * d)));
        if bad
            s.hold = (s.hold + dt);
        else
            s.hold = 0;
        end
        if (s.hold >= mp.ss_dwell_out_s)
            s = asils.alg.modes.modes_enter(s, 5);
        end
    end
end
