/* The arithmetic every translation shares with the interpreter (design/js/pcode.js `rt`). Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit. */
#ifndef ADCS_ALG_RT_H
#define ADCS_ALG_RT_H
#include <math.h>
#include <stdint.h>
#include "adcs_alg.h"

/* x^k by repeated multiplication, left to right; x^-k = 1/(x^k). */
static inline double pc_ipow(double x, int k) { double r = x; int i, n = k < 0 ? -k : k; if (k == 0) { return 1.0; } for (i = 1; i < n; i++) { r = r * x; } return k < 0 ? 1.0 / r : r; }
static inline int64_t pc_ipowi(int64_t x, int k) { int64_t r = 1; int i; for (i = 0; i < k; i++) { r *= x; } return r; }
static inline double pc_fmin(double a, double b) { return b < a ? b : a; }
static inline double pc_fmax(double a, double b) { return b > a ? b : a; }
static inline int64_t pc_imin(int64_t a, int64_t b) { return b < a ? b : a; }
static inline int64_t pc_imax(int64_t a, int64_t b) { return b > a ? b : a; }
static inline int64_t pc_iabs(int64_t a) { return a < 0 ? -a : a; }
static inline double pc_fabs(double x) { if (x < 0.0) { return -x; } if (x == 0.0) { return 0.0; } return x; }
static inline double pc_clamp(double x, double lo, double hi) { return pc_fmin(pc_fmax(x, lo), hi); }
static inline double pc_sign(double x) { return x > 0.0 ? 1.0 : (x < 0.0 ? -1.0 : 0.0); }
/* The last row whose key is at or below x (the first row below the first key). */
static inline void pc_lookup_step(const double *t, int rows, int cols, double x, double *r) {
    int i = 0, j;
    while (i + 1 < rows && t[(i + 1) * cols] <= x) { i++; }
    for (j = 0; j < cols; j++) { r[j] = t[i * cols + j]; }
}
/* Straight-line between the two rows around x, held at the ends. */
static inline void pc_lookup_linear(const double *t, int rows, int cols, double x, double *r) {
    double xc = pc_clamp(x, t[0], t[(rows - 1) * cols]), s;
    int i = 0, j;
    while (i + 2 < rows && t[(i + 1) * cols] <= xc) { i++; }
    s = (xc - t[i * cols]) / (t[(i + 1) * cols] - t[i * cols]);
    for (j = 0; j < cols; j++) { r[j] = t[i * cols + j] + s * (t[(i + 1) * cols + j] - t[i * cols + j]); }
}
static inline double pc_dot_a3f(pc_a3f a, pc_a3f b) { double s = a.v[0] * b.v[0]; int i; for (i = 1; i < 3; i++) { s = s + a.v[i] * b.v[i]; } return s; }
static inline double pc_norm_a3f(pc_a3f a) { return sqrt(pc_dot_a3f(a, a)); }
static inline pc_a3a3f pc_mm_a3a3f_a3a3f(pc_a3a3f a, pc_a3a3f b) { pc_a3a3f r; int i, j, k; for (i = 0; i < 3; i++) { for (j = 0; j < 3; j++) { double s = a.v[i].v[0] * b.v[0].v[j]; for (k = 1; k < 3; k++) { s = s + a.v[i].v[k] * b.v[k].v[j]; } r.v[i].v[j] = s; } } return r; }
static inline pc_a3f pc_unit_a3f(pc_a3f a) { double n = pc_fmax(pc_norm_a3f(a), 1e-30); pc_a3f r = a; int i; for (i = 0; i < 3; i++) { r.v[i] = a.v[i] / n; } return r; }
static inline pc_a3f pc_mv_a3a3f(pc_a3a3f a, pc_a3f v) { pc_a3f r; int i; for (i = 0; i < 3; i++) { r.v[i] = pc_dot_a3f(a.v[i], v); } return r; }
static inline pc_a3f pc_sub_a3f(pc_a3f a, pc_a3f b) { pc_a3f r = a; int i; for (i = 0; i < 3; i++) { r.v[i] = a.v[i] - b.v[i]; } return r; }
static inline pc_a3f pc_scale_a3f(pc_a3f a, double s) { pc_a3f r = a; int i; for (i = 0; i < 3; i++) { r.v[i] = a.v[i] * s; } return r; }
static inline pc_a3f pc_cross_a3f(pc_a3f a, pc_a3f b) { pc_a3f r; r.v[0] = a.v[1] * b.v[2] - a.v[2] * b.v[1]; r.v[1] = a.v[2] * b.v[0] - a.v[0] * b.v[2]; r.v[2] = a.v[0] * b.v[1] - a.v[1] * b.v[0]; return r; }
static inline pc_a3f pc_add_a3f(pc_a3f a, pc_a3f b) { pc_a3f r = a; int i; for (i = 0; i < 3; i++) { r.v[i] = a.v[i] + b.v[i]; } return r; }

#endif
