function [lat] = fsw_gnss_latency(fitted, latency)
%FSW_GNSS_LATENCY  The age [s] of a GNSS fix when it arrives, which the flight software carries the fix forward by: the receiver's
%   latency, 0 with no receiver.
%   fitted: bool (passed true or false)
%   latency: real[1] (passed a plain number)
%   returns lat: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    lat = 0;
    if fitted
        h__568 = latency;
    else
        h__568 = 0;
    end
    lat = h__568;
end
