function [h] = fsw_hyp(a, b)
%FSW_HYP  sqrt(a^2 + b^2) of two errors, each 0 where unstated.
%   a: real[1] (passed a plain number)
%   b: real[1] (passed a plain number)
%   returns h: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    h = 0;
    x = asils.models.fswsens.fsw_or_zero(a);
    y = asils.models.fswsens.fsw_or_zero(b);
    h__558 = ((x * x) + (y * y));
    if h__558 < 0, h__558 = NaN; else, h__558 = sqrt(h__558); end
    h = h__558;
end
