function [gyro_arw, gyro_rrw, es] = fsw_rate_noises(arw, rrw, es_noise)
%FSW_RATE_NOISES  The gyro's angle random walk [rad/s^0.5] and rate random walk [rad/s^1.5] and the Earth sensor's noise [rad] as the
%   flight software is told of them, each 0 where unstated.
%   arw: real[1] (passed a plain number)
%   rrw: real[1] (passed a plain number)
%   es_noise: real[1] (passed a plain number)
%   returns gyro_arw: real[1] (passed a plain number)
%   returns gyro_rrw: real[1] (passed a plain number)
%   returns es: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    gyro_arw = 0;
    gyro_rrw = 0;
    es = 0;
    gyro_arw = asils.models.fswsens.fsw_or_zero(arw);
    gyro_rrw = asils.models.fswsens.fsw_or_zero(rrw);
    es = asils.models.fswsens.fsw_or_zero(es_noise);
end
