function [has_gyro, has_st, has_sun, has_es, has_gps, n_heads] = fsw_sensor_set(gyro, st, sun, css, es, gps, nh)
%FSW_SENSOR_SET  The sensors the flight software is told of: has_gyro, has_st, has_sun (fine or coarse Sun sensors), has_es, has_gps
%   (1 fitted, 0 not), and the star tracker's heads n_heads.
%   gyro: bool (passed true or false)
%   st: bool (passed true or false)
%   sun: bool (passed true or false)
%   css: bool (passed true or false)
%   es: bool (passed true or false)
%   gps: bool (passed true or false)
%   nh: int (passed a whole number)
%   returns has_gyro: int (passed a whole number)
%   returns has_st: int (passed a whole number)
%   returns has_sun: int (passed a whole number)
%   returns has_es: int (passed a whole number)
%   returns has_gps: int (passed a whole number)
%   returns n_heads: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    has_gyro = 0;
    has_st = 0;
    has_sun = 0;
    has_es = 0;
    has_gps = 0;
    n_heads = 0;
    has_gyro = asils.pc.choose(gyro, 1, 0);
    has_st = asils.pc.choose(st, 1, 0);
    has_sun = asils.pc.choose((sun || css), 1, 0);
    has_es = asils.pc.choose(es, 1, 0);
    has_gps = asils.pc.choose(gps, 1, 0);
    n_heads = nh;
end
