function [lat, lon, alt] = geodetic_wgs84(r)
%GEODETIC_WGS84  The same on WGS-84 (de440.constants: Re_earth, f_earth).
%   r: real[m][3] (passed in m)
%   returns lat: real[1] (passed a plain number)
%   returns lon: real[1] (passed a plain number)
%   returns alt: real[m] (passed in m)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    lat = 0;
    lon = 0;
    alt = 0;
    [t__66, t__67, t__68] = asils.models.geodesy.geodetic_with(r, 6378137, (1 / 298.257223563));
    lat = t__66;
    lon = t__67;
    alt = t__68;
end
