function [hs, taus] = fmr_spare_need(h, tau)
%FMR_SPARE_NEED  The spare ring's momentum and torque: the root sum square of the three rings' (h, tau each).
%   h: real[1] (passed a plain number)
%   tau: real[1] (passed a plain number)
%   returns hs: real[1] (passed a plain number)
%   returns taus: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    hs = 0;
    taus = 0;
    r = asils.pc.sqrt_(3);
    hs = (r * h);
    taus = (r * tau);
end
