function [h, tau] = fmr_need(h_req, tau_req, s)
%FMR_NEED  Each ring's momentum and torque: the case's (at least 0.2 mN m s and 10 uN m) times the authority scale s.
%   h_req: real[1] (passed a plain number)
%   tau_req: real[1] (passed a plain number)
%   s: real[1] (passed a plain number)
%   returns h: real[1] (passed a plain number)
%   returns tau: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    h = 0;
    tau = 0;
    h = (asils.models.sizedemand.size_max(h_req, 0.0002) * s);
    tau = (asils.models.sizedemand.size_max(tau_req, 0.00001) * s);
end
