function [p] = valve_power(on, power)
%VALVE_POWER  The valve's power [W] for an on-time on [s].
%   on: real[s] (passed in s)
%   power: real[W] (passed in m^2 kg/s^3)
%   returns p: real[W] (passed in m^2 kg/s^3)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    p = 0;
    if (on > 0)
        h__5 = power;
    else
        h__5 = 0;
    end
    p = h__5;
end
