function [m_dump] = gm_2(momentum, field, dump_time)
%GM_2  The node's answer, m_dump, as magnetorquer_dipole_required gives it.
%   momentum: real[N m s] (passed in m^2 kg/s)
%   field: real[T] (passed in kg/(s^2 A))
%   dump_time: real[s] (passed in s)
%   returns m_dump: real[A m^2] (passed in m^2 A)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    m_dump = 0;
    m_dump = asils.groups.act.magnetorquer_dipole_required(momentum, field, dump_time);
end
