function [tau_mtq] = gm_3(m_av, b_min, n_mtq)
%GM_3  The node's answer, tau_mtq, as torque_authority gives it.
%   m_av: real[A m^2] (passed in m^2 A)
%   b_min: real[T] (passed in kg/(s^2 A))
%   n_mtq: int (passed a whole number)
%   returns tau_mtq: real[N m] (passed in m^2 kg/s^2)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    tau_mtq = 0;
    tau_mtq = asils.groups.act.torque_authority(m_av, b_min, n_mtq);
end
