function y = call(name, x)
%CALL  a function by its registry name (module::name), inputs and outputs flattened (row-major, SI)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    switch name
        case 'selftest::root'
            [o1, o2, o3] = asils.pcselftest.selftest.root(x(1), x(2));
            y = [double(o1); double(o2); double(o3)];
        case 'selftest::algebra'
            [o1, o2, o3, o4, o5, o6] = asils.pcselftest.selftest.algebra(reshape(x(1:3), 3, 1), reshape(x(4:6), 3, 1), x(7));
            y = [reshape(o1, [], 1); reshape((o2).', [], 1); reshape(o3, [], 1); double(o4); reshape(o5, [], 1); reshape(o6, [], 1)];
        case 'selftest::numbers'
            [o1, o2, o3, o4, o5, o6, o7, o8, o9, o10] = asils.pcselftest.selftest.numbers(x(1), x(2), x(3), x(4));
            y = [double(o1); double(o2); double(o3); double(o4); double(o5); double(o6); double(o7); double(o8); double(o9); double(o10)];
        case 'selftest::bits'
            [o1, o2, o3, o4, o5, o6, o7] = asils.pcselftest.selftest.bits(reshape(x(1:4), 4, 1), x(5), x(6));
            y = [double(o1); double(o2); double(o3); double(o4); double(o5); double(o6); double(o7)];
        case 'selftest::loops'
            [o1, o2, o3, o4, o5] = asils.pcselftest.selftest.loops(reshape(x(1:6), 6, 1), x(7));
            y = [double(o1); double(o2); double(o3); double(o4); reshape(o5, [], 1)];
        case 'selftest::lookup'
            [o1, o2] = asils.pcselftest.selftest.lookup(x(1));
            y = [double(o1); double(o2)];
        case 'selftest::reuse'
            [o1, o2, o3] = asils.pcselftest.selftest.reuse(x(1));
            y = [double(o1); double(o2); double(o3)];
        case 'selftest::tabled'
            [o1, o2, o3, o4, o5, o6] = asils.pcselftest.selftest.tabled(x(1), x(2), x(3));
            y = [double(o1); reshape(o2, [], 1); double(o3); reshape((o4).', [], 1); double(o5); double(o6)];
        case 'selftest::nonfinite'
            [o1, o2, o3, o4, o5, o6] = asils.pcselftest.selftest.nonfinite(x(1), x(2), x(3));
            y = [double(o1); double(o2); double(o3); double(o4); double(o5); double(o6)];
        case 'selftest::chosen'
            [o1, o2, o3, o4, o5] = asils.pcselftest.selftest.chosen(x(1), x(2));
            y = [[double(o1.kind); double(o1.h)]; double(o2); double(o3); double(o4); double(o5)];
        case 'selftest::capacities'
            [o1, o2, o3] = asils.pcselftest.selftest.capacities(reshape(x(1:5), 5, 1));
            y = [double(o1); reshape(o2, [], 1); double(o3)];
        case 'selftest::sorted'
            [o1, o2, o3, o4, o5, o6] = asils.pcselftest.selftest.sorted(reshape(x(1:7), 7, 1), reshape(x(8:12), 5, 1));
            y = [reshape(o1, [], 1); reshape(o2, [], 1); double(o3); reshape(o4, [], 1); reshape(o5, [], 1); reshape(o6, [], 1)];
        case 'selftest::smear'
            [o1, io1] = asils.pcselftest.selftest.smear(reshape(x(1:8), 8, 1), x(9), x(10));
            y = [double(o1); reshape(io1, [], 1)];
        case 'selftest::render'
            [o1, o2, io1] = asils.pcselftest.selftest.render(struct('px', {reshape(x(1:6), 6, 1)}, 'n', {x(7)}), x(8), x(9));
            y = [double(o1); double(o2); [reshape(io1.px, [], 1); double(io1.n)]];
        case 'selftest::again'
            [o1, o2, io1, io2] = asils.pcselftest.selftest.again(reshape(x(1:8), 8, 1), struct('px', {reshape(x(9:14), 6, 1)}, 'n', {x(15)}), x(16));
            y = [double(o1); double(o2); reshape(io1, [], 1); [reshape(io2.px, [], 1); double(io2.n)]];
        case 'selftest::draws'
            [o1, o2, o3, o4] = asils.pcselftest.selftest.draws(x(1), x(2));
            y = [reshape(o1, [], 1); double(o2); double(o3); double(o4)];
        case 'selftest::gauss'
            [o1, o2, o3] = asils.pcselftest.selftest.gauss(x(1));
            y = [reshape(o1, [], 1); reshape(o2, [], 1); reshape(o3, [], 1)];
        case 'selftest::jitter'
            [o1, o2, io1] = asils.pcselftest.selftest.jitter(reshape(x(1:6), 6, 1), x(7));
            y = [double(o1); double(o2); reshape(io1, [], 1)];
        case 'selftest::platform'
            [o1, o2, o3, o4] = asils.pcselftest.selftest.platform(x(1), x(2), x(3), x(4));
            y = [double(o1); double(o2); double(o3); double(o4)];
        case 'selftest::errorfn'
            [o1, o2] = asils.pcselftest.selftest.errorfn(x(1));
            y = [double(o1); double(o2)];
        case 'selftest::spread'
            at = 0;
            n1 = x(at + 1);
            a1 = reshape(x(at + 2:at + 1 + n1), [], 1);
            at = at + 1 + n1;
            n2 = x(at + 1);
            a2 = reshape(x(at + 2:at + 1 + n2), [], 1);
            at = at + 1 + n2;
            xa = x(at + 1:end);
            a3 = xa(1);
            at = at + 1;
            [o1, o2, o3, io1, io2] = asils.pcselftest.selftest.spread(a1, a2, a3);
            y = [double(o1); double(o2); double(o3); numel(io1); reshape(io1, [], 1); numel(io2); reshape(io2, [], 1)];
        case 'selftest::blur'
            at = 0;
            n1 = x(at + 1);
            a1 = reshape(x(at + 2:at + 1 + n1), [], 1);
            at = at + 1 + n1;
            xa = x(at + 1:end);
            a2 = xa(1);
            at = at + 1;
            [o1, io1] = asils.pcselftest.selftest.blur(a1, a2);
            y = [double(o1); numel(io1); reshape(io1, [], 1)];
        otherwise
            error('pcode:call', 'no function %s', name);
    end
end
