function [st, a] = atmos_density(model, alt_km, lat_deg, lon_deg, lst_h, doy, utc, drv, f107, f107a, akp, f30, f30_bar, ap60, f30_is_derived, has_tinf, tinf)
%ATMOS_DENSITY  atmos.provider(model, geo, sw): the switch. geo: altitude [km], latitude and longitude [deg], local solar time [h],
%   day of year, UTC [Y M D h m s]; the drivers a run hands it (drv) and their values: F10.7, its 81-day mean, the Kp
%   array (spaceweather); F30, its mean, ap60 and whether the F30 is derived (research); the placeholder temperature
%   (jb2008). A model given drivers of another kind names the first driver it lacks.
%   model: AtmosModel (passed a choice, as its option's number)
%   alt_km: real[1] (passed a plain number)
%   lat_deg: real[1] (passed a plain number)
%   lon_deg: real[1] (passed a plain number)
%   lst_h: real[1] (passed a plain number)
%   doy: real[1] (passed a plain number)
%   utc: real[1][6] (passed a plain number)
%   drv: Drivers (passed a choice, as its option's number)
%   f107: real[1] (passed a plain number)
%   f107a: real[1] (passed a plain number)
%   akp: real[1][4] (passed a plain number)
%   f30: real[1] (passed a plain number)
%   f30_bar: real[1] (passed a plain number)
%   ap60: real[1] (passed a plain number)
%   f30_is_derived: bool (passed true or false)
%   has_tinf: bool (passed true or false)
%   tinf: real[1] (passed a plain number)
%   returns st: AtmosStatus (passed a choice, as its option's number)
%   returns a: AtmosOut (passed rec)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    st = 0;
    a = asils.models.densitymodel.AtmosOut_zero();
    a = asils.models.densitymodel.AtmosOut_zero();
    st = 0;
    if (model == 0)
        [rho, t, mmol, n_o] = asils.models.expatmos.exponential_atm(alt_km);
        a.rho = rho;
        a.t = t;
        a.species = false;
        a.mmol = mmol;
        a.n_o = n_o;
    elseif (model == 1)
        st = 11;
    elseif (model == 3)
        if (drv == 1)
            [t__2, t__3] = asils.models.densitymodel.dtm2020_atm(alt_km, lat_deg, lon_deg, lst_h, doy, f107, f107a, akp);
            st = t__2;
            a = t__3;
        else
            st = 1;
        end
    elseif (model == 4)
        if (drv == 2)
            [t__4, t__5] = asils.models.densitymodel.dtm2020_research_atm(alt_km, lat_deg, lon_deg, lst_h, doy, utc, f30, f30_bar, ap60, f30_is_derived);
            st = t__4;
            a = t__5;
        else
            st = 4;
        end
    else
        if (drv == 3)
            [t__6, t__7] = asils.models.densitymodel.jb2008_atm(alt_km, lat_deg, lon_deg, utc, has_tinf, tinf);
            st = t__6;
            a = t__7;
        else
            st = 7;
        end
    end
end
