function [st, a] = jb2008_atm(alt_km, lat_deg, lon_deg, utc, has_tinf, tinf)
%JB2008_ATM  atmos.jb2008(geo, sw): the JB2008 density over env's SET indices; Mmol = 16, nO = rho N_A 1000/16, the temperature
%   sw.Tinf if given (has_tinf), else the MATLAB's 1000 K placeholder.
%   alt_km: real[1] (passed a plain number)
%   lat_deg: real[1] (passed a plain number)
%   lon_deg: real[1] (passed a plain number)
%   utc: real[1][6] (passed a plain number)
%   has_tinf: bool (passed true or false)
%   tinf: real[1] (passed a plain number)
%   returns st: AtmosStatus (passed a choice, as its option's number)
%   returns a: AtmosOut (passed rec)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    st = 0;
    a = asils.models.densitymodel.AtmosOut_zero();
    a = asils.models.densitymodel.AtmosOut_zero();
    st = 0;
    [rho, out, inp] = asils.models.jb2008.jb2008_density(utc, lon_deg, lat_deg, alt_km);
    if (~isfinite(rho))
        st = 10;
    else
        avog16 = ((6.02214076e+23 * 1000) / 16);
        a.rho = rho;
        a.t = asils.pc.choose(has_tinf, tinf, 1000);
        a.species = false;
        a.mmol = 16;
        a.n_o = (rho * avog16);
    end
end
