function [tau] = coil_torque(m, b)
%COIL_TORQUE  The torque [N m] of the body dipole m [A m^2] in the body field b [T].
%   m: real[1][3] (passed a plain number)
%   b: real[1][3] (passed a plain number)
%   returns tau: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    tau = zeros(3, 1);
    tau = asils.pc.cross_(m, b);
end
