function [re] = reynolds(rho, v, d, mu)
%REYNOLDS  The Reynolds number of the flow: Re = rho v d/mu.
%   rho: real[kg/m^3] (passed in kg/m^3)
%   v: real[m/s] (passed in m/s)
%   d: real[mm] (passed in m)
%   mu: real[Pa s] (passed in kg/(m s))
%   returns re: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    re = 0;
    re = (((rho * v) * d) / mu);
end
