function [h] = ring_momentum(d, s, rho, v)
%RING_MOMENTUM  The momentum of a ring of bore d around an area S, fluid of density rho at speed v:
%   H = 2 rho A v S, A = pi d^2/4.
%   d: real[mm] (passed in m)
%   s: real[m^2] (passed in m^2)
%   rho: real[kg/m^3] (passed in kg/m^3)
%   v: real[m/s] (passed in m/s)
%   returns h: real[N m s] (passed in m^2 kg/s)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    h = 0;
    a = ((pi * asils.pc.ipow(d, 2)) / 4);
    h = ((((2 * rho) * a) * v) * s);
end
