function [m] = body_to_wind(alpha, beta)
%BODY_TO_WIND  drag.bodyToWind(alpha, beta): the body-to-wind matrix (F_wind = [-D; S; -L]).
%   alpha: real[1] (passed a plain number)
%   beta: real[1] (passed a plain number)
%   returns m: real[1][3][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    m = zeros(3, 3);
    ca = cos(alpha);
    sa = sin(alpha);
    cb = cos(beta);
    sb = sin(beta);
    m = [([(cb * ca); sb; (cb * sa)]).'; ([((-(sb)) * ca); cb; ((-(sb)) * sa)]).'; ([(-(sa)); 0; ca]).'];
end
