function s = CannonballOut_zero()
%CANNONBALLOUT_ZERO  a CannonballOut with every field zero
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = struct();
    s.f = zeros(3, 1);
    s.a = zeros(3, 1);
    s.drag = 0;
    s.uhat = zeros(3, 1);
    s.vrel = 0;
    s.cd = 0;
    s.qd = 0;
    s.a_proj = 0;
end
