function [g] = drag_facets(f, aref)
%DRAG_FACETS  The facets the panel models take: the spacecraft's, or a single +x plate of the reference area when it has none.
%   f: ScFacets (passed rec)
%   aref: real[1] (passed a plain number)
%   returns g: ScFacets (passed rec)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    g = asils.models.srp.ScFacets_zero();
    if (f.nf > 0)
        g = f;
    else
        g = asils.models.srp.facet_add(asils.models.srp.ScFacets_zero(), 0, [1; 0; 0], aref, 0, 0, 0, [0; 0; 0], false);
    end
end
