function [st, k, a, v_rel, cb, po] = drag_force(model, pm, r, v, atm, has_omega, omega, corotate, has_cfg_cd, cfg_cd, has_sc_cd, sc_cd, aref, mass, r_bi, f, g, has_sun, sun)
%DRAG_FORCE  [a, info] = forces.drag(ctx) after the density: the acceleration [m/s^2] at r, v (ECI) of the air atm on the
%   spacecraft (mass, aref, its Cd when it states one, its attitude r_bi and facets) by the model (cannonball or panel,
%   the force set's Cd when it states one, the gsi), in an atmosphere that turns with the Earth (corotate) at omega (the
%   world's, has_omega, else the nominal rate about z); the velocity relative to the air and the model's out.
%   model: DragModel (passed a choice, as its option's number)
%   pm: PanelModel (passed a choice, as its option's number)
%   r: real[1][3] (passed a plain number)
%   v: real[1][3] (passed a plain number)
%   atm: AtmosOut (passed rec)
%   has_omega: bool (passed true or false)
%   omega: real[1][3] (passed a plain number)
%   corotate: bool (passed true or false)
%   has_cfg_cd: bool (passed true or false)
%   cfg_cd: real[1] (passed a plain number)
%   has_sc_cd: bool (passed true or false)
%   sc_cd: real[1] (passed a plain number)
%   aref: real[1] (passed a plain number)
%   mass: real[1] (passed a plain number)
%   r_bi: real[1][3][3] (passed a plain number)
%   f: ScFacets (passed rec)
%   g: Gsi (passed rec)
%   has_sun: bool (passed true or false)
%   sun: real[1][3] (passed a plain number)
%   returns st: DragStatus (passed a choice, as its option's number)
%   returns k: int (passed a whole number)
%   returns a: real[1][3] (passed a plain number)
%   returns v_rel: real[1][3] (passed a plain number)
%   returns cb: CannonballOut (passed rec)
%   returns po: PanelOut (passed rec)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    st = 0;
    k = 0;
    a = zeros(3, 1);
    v_rel = zeros(3, 1);
    cb = asils.models.drag.CannonballOut_zero();
    po = asils.models.drag.PanelOut_zero();
    om_ctx = [0; 0; getfield(asils.models.de440.de440_constants(), 'omega_earth')];
    if has_omega
        om_ctx = omega;
    end
    om = [0; 0; 0];
    v_rel = v;
    if corotate
        c = [om_ctx(2)*r(3) - om_ctx(3)*r(2); om_ctx(3)*r(1) - om_ctx(1)*r(3); om_ctx(1)*r(2) - om_ctx(2)*r(1)];
        v_rel = [(v(1) - c(1)); (v(2) - c(2)); (v(3) - c(3))];
        om = om_ctx;
    end
    st = 0;
    k = 0;
    cb = asils.models.drag.CannonballOut_zero();
    po = asils.models.drag.PanelOut_zero();
    if (model == 0)
        cb = asils.models.drag.drag_cannonball(r, v, atm.rho, asils.models.drag.drag_cd(has_cfg_cd, cfg_cd, has_sc_cd, sc_cd), aref, mass, [0; 0; 0], om);
        a = cb.a;
    else
        [t__388, t__389, t__390] = asils.models.drag.panel_force(r, v, atm, asils.models.drag.drag_facets(f, aref), pm, g, mass, aref, r_bi, [0; 0; 0], om, has_sun, sun);
        st = t__388;
        k = t__389;
        po = t__390;
        a = po.a;
    end
end
