function [o] = drag_cannonball(r, v, rho, cd, area, mass, wind, omega)
%DRAG_CANNONBALL  drag.cannonball(r, v, rho, Cd, A, opts): -1/2 Cd A rho |v_r| v_r / m, v_r = v - omega x r - wind.
%   r: real[1][3] (passed a plain number)
%   v: real[1][3] (passed a plain number)
%   rho: real[1] (passed a plain number)
%   cd: real[1] (passed a plain number)
%   area: real[1] (passed a plain number)
%   mass: real[1] (passed a plain number)
%   wind: real[1][3] (passed a plain number)
%   omega: real[1][3] (passed a plain number)
%   returns o: CannonballOut (passed rec)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    o = asils.models.drag.CannonballOut_zero();
    c = asils.pc.cross_(omega, r);
    t = [(v(1) - c(1)); (v(2) - c(2)); (v(3) - c(3))];
    vrel = [(t(1) - wind(1)); (t(2) - wind(2)); (t(3) - wind(3))];
    vm = asils.models.gravity.onorm(vrel);
    o = asils.models.drag.CannonballOut_zero();
    o.uhat = [(vrel(1) / vm); (vrel(2) / vm); (vrel(3) / vm)];
    k = (((((-(0.5)) * cd) * area) * rho) * vm);
    o.f = [(k * vrel(1)); (k * vrel(2)); (k * vrel(3))];
    o.a = [(o.f(1) / mass); (o.f(2) / mass); (o.f(3) / mass)];
    o.drag = ((((0.5 * cd) * area) * rho) * asils.pc.pow_(vm, 2));
    o.vrel = vm;
    o.cd = cd;
    o.qd = ((0.5 * rho) * asils.pc.pow_(vm, 2));
    o.a_proj = area;
end
