function [st, k, o] = panel_force(r, v, atm, f, model, g, mass, aref, r_bi, wind, omega, has_sun, sun)
%PANEL_FORCE  drag.force(r, v, atm, facets, model, gsi, opts): the free-molecular force on the facets (body frame; the attitude
%   r_bi body to ECI), summed over the air's species (atm: the six DTM species, or one mean species), with the panel
%   model and the gsi; mass and aref [kg, m^2], the wind and the Earth's rate omega (ECI), the Sun's direction where a
%   facet tracks it (has_sun). The status names a facet the force cannot take (k, from 1).
%   r: real[1][3] (passed a plain number)
%   v: real[1][3] (passed a plain number)
%   atm: AtmosOut (passed rec)
%   f: ScFacets (passed rec)
%   model: PanelModel (passed a choice, as its option's number)
%   g: Gsi (passed rec)
%   mass: real[1] (passed a plain number)
%   aref: real[1] (passed a plain number)
%   r_bi: real[1][3][3] (passed a plain number)
%   wind: real[1][3] (passed a plain number)
%   omega: real[1][3] (passed a plain number)
%   has_sun: bool (passed true or false)
%   sun: real[1][3] (passed a plain number)
%   returns st: DragStatus (passed a choice, as its option's number)
%   returns k: int (passed a whole number)
%   returns o: PanelOut (passed rec)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    st = 0;
    k = 0;
    o = asils.models.drag.PanelOut_zero();
    st = 0;
    k = 0;
    o = asils.models.drag.PanelOut_zero();
    [vrel, uhat, vm] = asils.models.drag.rel_velocity(r, v, wind, omega);
    [alpha, beta, vw, vb] = asils.models.drag.wind_angles(vrel, r_bi);
    rho_s = zeros(6, 1);
    ms = zeros(6, 1);
    ns = 1;
    n_o = atm.n_o;
    if atm.species
        ns = 6;
        mdtm = asils.models.gsi.dtm_molar_masses();
        i = ((0):((6) - 1)).';
        ms((i) + 1) = reshape(mdtm((i) + 1), [], 1);
        rho_s((i) + 1) = ((reshape(atm.n((i) + 1), [], 1) .* reshape(ms((i) + 1), [], 1)) ./ 6.02214076e+26);
        n_o = atm.n(3);
    else
        rho_s(1) = atm.rho;
        ms(1) = atm.mmol;
    end
    a_t = 0;
    if ((model == 1) || (model == 2))
        a_t = asils.models.gsi.sesam(n_o, atm.t);
    elseif (model == 0)
        a_t = g.a_t;
    end
    fs = [0; 0; 0];
    aproj = 0;
    s_o = asils.models.gsi.speed_ratio(vm, atm.t, asils.models.gsi.molar_mass(0));
    for j = (0):((f.nf) - 1)
        if (st == 0)
            nb = (f.n((j) + 1, :)).';
            if (f.kind((j) + 1) == fix(2))
                if (~has_sun)
                    st = 1;
                    k = (j + 1);
                else
                    nsun = asils.models.gravity.onorm(sun);
                    sh = [(sun(1) / nsun); (sun(2) / nsun); (sun(3) / nsun)];
                    h__173 = (r_bi).';
                    sb = [h__173(1, 1)*sh(1) + h__173(1, 2)*sh(2) + h__173(1, 3)*sh(3); h__173(2, 1)*sh(1) + h__173(2, 2)*sh(2) + h__173(2, 3)*sh(3); h__173(3, 1)*sh(1) + h__173(3, 2)*sh(2) + h__173(3, 3)*sh(3)];
                    nb = asils.models.drag.drag_array_normal((f.axis((j) + 1, :)).', sb);
                end
            end
            if ((st == 0) && (asils.models.gravity.onorm(nb) < 2.220446049250313e-16))
                st = 2;
                k = (j + 1);
            end
            if (st == 0)
                n0 = [r_bi(1, 1)*nb(1) + r_bi(1, 2)*nb(2) + r_bi(1, 3)*nb(3); r_bi(2, 1)*nb(1) + r_bi(2, 2)*nb(2) + r_bi(2, 3)*nb(3); r_bi(3, 1)*nb(1) + r_bi(3, 2)*nb(2) + r_bi(3, 3)*nb(3)];
                nn = asils.models.gravity.onorm(n0);
                n = [(n0(1) / nn); (n0(2) / nn); (n0(3) / nn)];
                cosd = (n(1)*uhat(1) + n(2)*uhat(2) + n(3)*uhat(3));
                if ((f.dbl((j) + 1) == 1) && (cosd < 0))
                    n = [(-(n(1))); (-(n(2))); (-(n(3)))];
                    cosd = (-(cosd));
                end
                if (~(cosd <= 0))
                    aproj = (aproj + (f.a((j) + 1) * cosd));
                    h__174 = acos(asils.models.srp.min_one(cosd));
                    if ~isreal(h__174), h__174 = NaN; end
                    delta = h__174;
                    h__175 = (cosd)^(2);
                    if ~isreal(h__175), h__175 = NaN; end
                    s2 = (1 - h__175);
                    if (s2 > 0)
                        h__176 = s2;
                    else
                        h__176 = 0;
                    end
                    h__177 = h__176;
                    if h__177 < 0, h__177 = NaN; else, h__177 = sqrt(h__177); end
                    sind = h__177;
                    tgas = [0; 0; 0];
                    if (sind > 1e-9)
                        tgas = [(((-(uhat(1))) + (cosd * n(1))) / sind); (((-(uhat(2))) + (cosd * n(2))) / sind); (((-(uhat(3))) + (cosd * n(3))) / sind)];
                    end
                    for jj = (0):((ns) - 1)
                        s = asils.models.gsi.speed_ratio(vm, atm.t, ms((jj) + 1));
                        cp = 0;
                        ct = 0;
                        if (model == 3)
                            [t__384, t__385] = asils.models.gsi.cll(s, delta, g.sig_n, g.sig_t, g.tw, atm.t);
                            cp = t__384;
                            ct = t__385;
                        else
                            [t__386, t__387] = asils.models.gsi.sentman(s, delta, a_t, g.tw, atm.t);
                            cp = t__386;
                            ct = t__387;
                        end
                        h__178 = (vm)^(2);
                        if ~isreal(h__178), h__178 = NaN; end
                        q = (((0.5 * rho_s((jj) + 1)) * h__178) * f.a((j) + 1));
                        i = ((0):((3) - 1)).';
                        fs((i) + 1) = (reshape(fs((i) + 1), [], 1) + (q .* ((ct .* reshape(tgas((i) + 1), [], 1)) - (cp .* reshape(n((i) + 1), [], 1)))));
                    end
                end
            end
        end
    end
    if (st == 0)
        h__179 = (r_bi).';
        fbody = [h__179(1, 1)*fs(1) + h__179(1, 2)*fs(2) + h__179(1, 3)*fs(3); h__179(2, 1)*fs(1) + h__179(2, 2)*fs(2) + h__179(2, 3)*fs(3); h__179(3, 1)*fs(1) + h__179(3, 2)*fs(2) + h__179(3, 3)*fs(3)];
        h__180 = asils.models.drag.body_to_wind(alpha, beta);
        fwind = [h__180(1, 1)*fbody(1) + h__180(1, 2)*fbody(2) + h__180(1, 3)*fbody(3); h__180(2, 1)*fbody(1) + h__180(2, 2)*fbody(2) + h__180(2, 3)*fbody(3); h__180(3, 1)*fbody(1) + h__180(3, 2)*fbody(2) + h__180(3, 3)*fbody(3)];
        d = (-(fwind(1)));
        sd = fwind(2);
        l = (-(fwind(3)));
        rho_tot = 0;
        for i2 = (0):((ns) - 1)
            rho_tot = (rho_tot + rho_s((i2) + 1));
        end
        h__181 = (vm)^(2);
        if ~isreal(h__181), h__181 = NaN; end
        qd = ((0.5 * rho_tot) * h__181);
        fu = (fs(1)*uhat(1) + fs(2)*uhat(2) + fs(3)*uhat(3));
        dv = [(fu * uhat(1)); (fu * uhat(2)); (fu * uhat(3))];
        o.f = fs;
        o.a = [(fs(1) / mass); (fs(2) / mass); (fs(3) / mass)];
        o.fbody = fbody;
        o.drag = d;
        o.side = sd;
        o.lift = l;
        o.drag_vec = dv;
        o.lift_vec = [(fs(1) - dv(1)); (fs(2) - dv(2)); (fs(3) - dv(3))];
        o.uhat = uhat;
        o.vrel = vm;
        o.s_o = s_o;
        o.qd = qd;
        o.alpha = alpha;
        o.beta = beta;
        o.cd = (d / (qd * aref));
        o.cl = (l / (qd * aref));
        o.cs = (sd / (qd * aref));
        o.a_proj = aproj;
        if (aproj > 0)
            h__182 = (d / (qd * aproj));
        else
            h__182 = NaN;
        end
        o.cd_a = h__182;
        o.aref_used = aref;
    end
end
