function [alt_km, lat_deg, lon_deg, lst_h] = probe_geo(lat_rad, lon_rad, alt_m, utc)
%PROBE_GEO  The geodetic probe point of forces.drag: the altitude [km], latitude and longitude [deg] and the local solar time
%   mod(UT + lon/15, 24) [h] of a geodetic latitude and longitude [rad] and height [m] at the UTC date utc.
%   lat_rad: real[1] (passed a plain number)
%   lon_rad: real[1] (passed a plain number)
%   alt_m: real[1] (passed a plain number)
%   utc: real[1][6] (passed a plain number)
%   returns alt_km: real[1] (passed a plain number)
%   returns lat_deg: real[1] (passed a plain number)
%   returns lon_deg: real[1] (passed a plain number)
%   returns lst_h: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    alt_km = 0;
    lat_deg = 0;
    lon_deg = 0;
    lst_h = 0;
    lon_deg = (lon_rad * (180 / pi));
    utsec = (((utc(4) * 3600) + (utc(5) * 60)) + utc(6));
    alt_km = (alt_m / 1000);
    lat_deg = (lat_rad * (180 / pi));
    lst_h = asils.models.timescales.omod(((utsec / 3600) + (lon_deg / 15)), 24);
end
