function [m] = r_lvlh(r, v)
%R_LVLH  sgeom.R_lvlh(r, v): body to ECI of a nadir-pointing attitude (z to nadir, y against the orbit normal, x completing,
%   about along the velocity).
%   r: real[1][3] (passed a plain number)
%   v: real[1][3] (passed a plain number)
%   returns m: real[1][3][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    m = zeros(3, 3);
    nr = asils.models.gravity.onorm(r);
    zb = [((-(r(1))) / nr); ((-(r(2))) / nr); ((-(r(3))) / nr)];
    h = asils.pc.cross_(r, v);
    nh = asils.models.gravity.onorm(h);
    yb = [((-(h(1))) / nh); ((-(h(2))) / nh); ((-(h(3))) / nh)];
    xb = asils.models.drag.ounit(asils.pc.cross_(yb, zb));
    m = asils.models.drag.from_cols(xb, yb, zb);
end
