function [m] = ram_attitude(vrel)
%RAM_ATTITUDE  dgeom.ramAttitude(vrel): body to ECI with body +x along vrel and body +y = zref x x (zref +z, or +y when x is within
%   about 11 degrees of it).
%   vrel: real[1][3] (passed a plain number)
%   returns m: real[1][3][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    m = zeros(3, 3);
    x = asils.models.drag.ounit(vrel);
    zref = [0; 0; 1];
    h__183 = (x(1)*zref(1) + x(2)*zref(2) + x(3)*zref(3));
    if h__183 < 0, h__183 = -h__183; elseif h__183 == 0, h__183 = 0; end
    if (h__183 > 0.98)
        zref = [0; 1; 0];
    end
    y = asils.models.drag.ounit([zref(2)*x(3) - zref(3)*x(2); zref(3)*x(1) - zref(1)*x(3); zref(1)*x(2) - zref(2)*x(1)]);
    z = [x(2)*y(3) - x(3)*y(2); x(3)*y(1) - x(1)*y(3); x(1)*y(2) - x(2)*y(1)];
    m = asils.models.drag.from_cols(x, y, z);
end
