function [alpha, beta, vm, vb] = wind_angles(vrel, r_bi)
%WIND_ANGLES  drag.windAngles(vrel, R_bi): the angle of attack atan2(w, u) and sideslip asin(v/V) of the relative wind in body
%   axes, its speed and its body components.
%   vrel: real[1][3] (passed a plain number)
%   r_bi: real[1][3][3] (passed a plain number)
%   returns alpha: real[1] (passed a plain number)
%   returns beta: real[1] (passed a plain number)
%   returns vm: real[1] (passed a plain number)
%   returns vb: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    alpha = 0;
    beta = 0;
    vm = 0;
    vb = zeros(3, 1);
    vb = asils.pc.mv((r_bi).', vrel);
    vm = asils.models.gravity.onorm(vb);
    alpha = atan2(vb(3), vb(1));
    beta = asin(asils.models.thirdbody.unit_clip((vb(2) / vm)));
end
