function [f] = eclipse_fraction(r, beta)
%ECLIPSE_FRACTION  The share of a circular orbit in the Earth's cylindrical shadow, at Sun angle beta:
%   f = acos(sqrt(1 - (R_E/r)^2)/cos beta)/pi while |beta| < asin(R_E/r), else 0.
%   r: real[km] (passed in m)
%   beta: real[deg] (passed a plain number)
%   returns f: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    f = 0;
    rho = (6378137 / r);
    if (asils.pc.fabs(beta) < asin(rho))
        f = (acos((sqrt((1 - asils.pc.ipow(rho, 2))) / cos(beta))) / pi);
    else
        f = 0;
    end
end
