function v = GRAV_DEFAULT_J(varargin)
%GRAV_DEFAULT_J  GRAV_DEFAULT_J: Pavlis, Holmes, Kenyon and Factor (2012), The development and evaluation of the Earth Gravitational Model 2008 (EGM2008), J. Geophys. Res. 117, B04406: GM 3.986004415e14 m^3/s^2 and a = 6378136.3 m, the unnormalised zonals J2..J6; as the Octave POP's grav.defaultField
%   read by tools/readers.py (matlab_matrix) from matlab_sils/pop/01_core/+grav/defaultField.m (sha256 d82d9ec0de6544e4), the developer's revision S7.3d
%   data: real[1][5]; SI: a plain number
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    persistent T
    if isempty(T)
        T = [
            0.00108262668355; -0.00000253265648533; -0.00000161962159137; -2.27296082869e-7; 5.40681239107e-7
        ];
    end
    if nargin == 0, v = T; else, v = T(varargin{:}); end
end
