function s = CssDesc_zero()
%CSSDESC_ZERO  a CssDesc with every field zero
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = struct();
    s.n = 0;
    s.normals = zeros(8, 3);
    s.noise = 0;
    s.albedo = 0;
    s.scale_sigma = 0;
    s.misalign = 0;
end
