function s = CssUnit_zero()
%CSSUNIT_ZERO  a CssUnit with every field zero
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = struct();
    s.scale = zeros(8, 1);
    s.dead = zeros(8, 1);
    s.r = zeros(3, 3);
    s.g = zeros(6, 1);
end
