function [tau] = residual_dipole_torque(rm, m_res, b_eci)
%RESIDUAL_DIPOLE_TORQUE  The residual-dipole torque [N m], body axes, of the dipole m_res (body axes) in the field b_eci (inertial), rm the
%   inertial-to-body matrix.
%   rm: real[1][3][3] (passed a plain number)
%   m_res: real[A m^2][3] (passed in m^2 A)
%   b_eci: real[T][3] (passed in kg/(s^2 A))
%   returns tau: real[N m][3] (passed in m^2 kg/s^2)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    tau = zeros(3, 1);
    tau = asils.pc.cross_(m_res, asils.pc.mv(rm, b_eci));
end
