function [u] = kpi_unit_bs(a)
%KPI_UNIT_BS  The boresight made unit as the toolbox makes it (la::unit: a times 1/|a|, a zero vector below 1e-300).
%   a: real[1][3] (passed a plain number)
%   returns u: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    u = zeros(3, 1);
    h__625 = (((a(1) * a(1)) + (a(2) * a(2))) + (a(3) * a(3)));
    if h__625 < 0, h__625 = NaN; else, h__625 = sqrt(h__625); end
    n = h__625;
    if (n < 1e-300)
        u = [0; 0; 0];
    else
        k = (1 / n);
        u = [(a(1) * k); (a(2) * k); (a(3) * k)];
    end
end
