function [v, e] = kpi_ecss_vec(e, j, los, b)
%KPI_ECSS_VEC  The error vector of sample j [rad] (e holds three numbers a sample), across the boresight b (unit) when los: less
%   its part along b.
%   length: 96
%   e: inout real[1][*] (passed a plain number)
%   j: int (passed a whole number)
%   los: bool (passed true or false)
%   b: real[1][3] (passed a plain number)
%   returns v: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    v = zeros(3, 1);
    v = [e(((3 * j)) + 1); e((((3 * j) + 1)) + 1); e((((3 * j) + 2)) + 1)];
    if los
        d = (((v(1) * b(1)) + (v(2) * b(2))) + (v(3) * b(3)));
        v = [(v(1) - (b(1) * d)); (v(2) - (b(2) * d)); (v(3) - (b(3) * d))];
    end
end
