function [lo, pa] = st_first_not_below(pa, np, x)
%ST_FIRST_NOT_BELOW  The first of the np angles pa (ascending) that is not below x: a binary search.
%   length: 64
%   pa: inout real[1][*] (passed a plain number)
%   np: int (passed a whole number)
%   x: real[1] (passed a plain number)
%   returns lo: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    lo = 0;
    lo = 0;
    hi = np;
    n__241 = 64; k__240 = 0;
    while true
        if (lo < hi)
            mid = (lo + fix(((hi - lo)) / (2)));
            left = (pa((mid) + 1) < x);
            lo = asils.pc.choose(left, (mid + 1), lo);
            hi = asils.pc.choose(left, hi, mid);
        end
        k__240 = k__240 + 1;
        if (~(lo < hi)), break; end
        if k__240 >= n__241
            break;
        end
    end
end
