function [np, cr, pi, pj, pa, ti, tj, ta] = st_pairs(cr, nc, fov, pi, pj, pa, ti, tj, ta)
%ST_PAIRS  The onboard pair table of the first nc catalogue stars: every pair i < j closer than the field's diagonal, its two
%   indices and its angle [rad], sorted by angle (equal angles by j, then i), into (pi, pj, pa), built in (ti, tj, ta);
%   every one of the six as long as st_pair_count says. How many.
%   length: 4096
%   vectors: 6
%   cr: inout real[1][3][N_STARS] (passed a plain number)
%   nc: int (passed a whole number)
%   fov: real[1] (passed a plain number)
%   pi: inout int[*] (passed a whole number)
%   pj: inout int[*] (passed a whole number)
%   pa: inout real[1][*] (passed a plain number)
%   ti: inout int[*] (passed a whole number)
%   tj: inout int[*] (passed a whole number)
%   ta: inout real[1][*] (passed a plain number)
%   returns np: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    np = 0;
    cd = cos(((2 * sqrt(2)) * fov));
    np = 0;
    for j = (0):((nc) - 1)
        for i = (0):((j) - 1)
            d = asils.pc.dot_((cr((i) + 1, :)).', (cr((j) + 1, :)).');
            if (d > cd)
                ti((np) + 1) = i;
                tj((np) + 1) = j;
                ta((np) + 1) = acos(asils.pc.fmin(d, 1));
                np = (np + 1);
            end
        end
    end
    passes = 0;
    w = 1;
    for it = (0):((62) - 1)
        if (w < np)
            if (rem(passes, 2) == 0)
                [t__166, t__167, t__168, t__169, t__170, t__171, t__172] = asils.models.stidentify.st_merge_pairs(ti, tj, ta, pi, pj, pa, np, w);
                z0 = t__166;
                ti = t__167;
                tj = t__168;
                ta = t__169;
                pi = t__170;
                pj = t__171;
                pa = t__172;
            else
                [t__173, t__174, t__175, t__176, t__177, t__178, t__179] = asils.models.stidentify.st_merge_pairs(pi, pj, pa, ti, tj, ta, np, w);
                z1 = t__173;
                pi = t__174;
                pj = t__175;
                pa = t__176;
                ti = t__177;
                tj = t__178;
                ta = t__179;
            end
            passes = (passes + 1);
            w = (2 * w);
        end
    end
    if (rem(passes, 2) == 0)
        for k = (0):((np) - 1)
            pi((k) + 1) = ti((k) + 1);
            pj((k) + 1) = tj((k) + 1);
            pa((k) + 1) = ta((k) + 1);
        end
    end
end
