function [np, cr, pi, pj, pa, ti, tj, ta] = st_pairs(cr, nc, fov, pi, pj, pa, ti, tj, ta)
%ST_PAIRS  The onboard pair table of the first nc catalogue stars: every pair i < j closer than the field's diagonal, its two
%   indices and its angle [rad], sorted by angle (equal angles by j, then i), into (pi, pj, pa), built in (ti, tj, ta);
%   every one of the six as long as st_pair_count says. How many.
%   length: 4096
%   vectors: 6
%   cr: inout real[1][3][N_STARS] (passed a plain number)
%   nc: int (passed a whole number)
%   fov: real[1] (passed a plain number)
%   pi: inout int[*] (passed a whole number)
%   pj: inout int[*] (passed a whole number)
%   pa: inout real[1][*] (passed a plain number)
%   ti: inout int[*] (passed a whole number)
%   tj: inout int[*] (passed a whole number)
%   ta: inout real[1][*] (passed a plain number)
%   returns np: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    np = 0;
    cd = cos(((2 * asils.pc.sqrt_(2)) * fov));
    np = 0;
    for j = (0):((nc) - 1)
        for i = (0):((j) - 1)
            d = asils.pc.dot_((cr((i) + 1, :)).', (cr((j) + 1, :)).');
            if (d > cd)
                ti((np) + 1) = i;
                tj((np) + 1) = j;
                ta((np) + 1) = asils.pc.acos_(asils.pc.fmin(d, 1));
                np = (np + 1);
            end
        end
    end
    passes = 0;
    w = 1;
    for it = (0):((62) - 1)
        if (w < np)
            if (rem(passes, 2) == 0)
                [t__531, t__532, t__533, t__534, t__535, t__536, t__537] = asils.models.stidentify.st_merge_pairs(ti, tj, ta, pi, pj, pa, np, w);
                z0 = t__531;
                ti = t__532;
                tj = t__533;
                ta = t__534;
                pi = t__535;
                pj = t__536;
                pa = t__537;
            else
                [t__538, t__539, t__540, t__541, t__542, t__543, t__544] = asils.models.stidentify.st_merge_pairs(pi, pj, pa, ti, tj, ta, np, w);
                z1 = t__538;
                pi = t__539;
                pj = t__540;
                pa = t__541;
                ti = t__542;
                tj = t__543;
                ta = t__544;
            end
            passes = (passes + 1);
            w = (2 * w);
        end
    end
    if (rem(passes, 2) == 0)
        for k = (0):((np) - 1)
            pi((k) + 1) = ti((k) + 1);
            pj((k) + 1) = tj((k) + 1);
            pa((k) + 1) = ta((k) + 1);
        end
    end
end
