function [w] = earth_rate_from(ctp, ctm, c0, d)
%EARTH_RATE_FROM  earthRateECI: the Earth's angular velocity in the inertial frame [rad/s] from the frames d seconds after and before
%   (their transposes, Ct = C') and at the epoch: [omega]x = Cdot C0, Cdot = (Ct(+d) - Ct(-d))/(2 d).
%   ctp: real[1][3][3] (passed a plain number)
%   ctm: real[1][3][3] (passed a plain number)
%   c0: real[1][3][3] (passed a plain number)
%   d: real[s] (passed in s)
%   returns w: real[1/s][3] (passed in 1/s)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    w = zeros(3, 1);
    cdot = zeros(3, 3);
    for i = (0):((3) - 1)
        for j = (0):((3) - 1)
            cdot((i) + 1, (j) + 1) = ((ctp((i) + 1, (j) + 1) - ctm((i) + 1, (j) + 1)) / (2 * d));
        end
    end
    m = asils.pc.mm(cdot, c0);
    w = [m(3, 2); m(1, 3); m(2, 1)];
end
