function [p] = field_power(on, power)
%FIELD_POWER  The field's power [W]: field_power when on, else none.
%   on: bool (passed true or false)
%   power: real[1] (passed a plain number)
%   returns p: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    p = 0;
    if on
        h__6 = power;
    else
        h__6 = 0;
    end
    p = h__6;
end
