function [ok, s, u] = sun_sample(u, d, s_body, nu)
%SUN_SAMPLE  The Sun the sensors give (body, unit) and whether they give one, for the Sun s_body (body, unit) and the sunlit
%   fraction nu.
%   u: inout SunUnit (passed rec)
%   d: SunDesc (passed rec)
%   s_body: real[1][3] (passed a plain number)
%   nu: real[1] (passed a plain number)
%   returns ok: bool (passed true or false)
%   returns s: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    ok = false;
    s = zeros(3, 1);
    ok = false;
    s = [0; 0; 0];
    if (~(nu < 0.5))
        cm = (-(2));
        jm = 0;
        for j = (0):((d.n) - 1)
            c = asils.pc.dot_(s_body, (d.normals((j) + 1, :)).');
            if (c > cm)
                cm = c;
                jm = j;
            end
        end
        if (~(cm < cos(d.fov)))
            g = u.g;
            if d.chain
                rh = asils.models.sunquad.head_frame((d.normals((jm) + 1, :)).');
                sb = asils.pc.mv(asils.models.coildisp.small_rotation((u.bias((jm) + 1, :)).'), s_body);
                [t__164, t__165] = asils.models.sunquad.quad_currents(asils.pc.mv(rh, sb), d.head, g);
                cur = t__164;
                g = t__165;
                [sh, okh] = asils.models.sunangles.quad_angles(cur, d.head);
                ok = okh;
                if ok
                    s = asils.models.math.mat3t_vec(rh, sh);
                end
            else
                [t__166, t__167] = asils.pc.stream_normal3(g);
                n = t__166;
                g = t__167;
                e = ((u.bias((jm) + 1, :)).' + (n * d.noise));
                s = asils.models.facets.unit_or_zero(asils.pc.mv(asils.models.coildisp.small_rotation(e), s_body));
                ok = true;
            end
            u.g = g;
        end
    end
end
