function [u, disp] = sun_new(d, disp, noise)
%SUN_NEW  The fine Sun sensors of a description, their mount biases drawn from disp, their noise from noise.
%   d: SunDesc (passed rec)
%   disp: inout stream (passed a random stream, as six numbers)
%   noise: stream (passed a random stream, as six numbers)
%   returns u: SunUnit (passed rec)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    u = asils.models.finesun.SunUnit_zero();
    u = asils.models.finesun.SunUnit_zero();
    for j = (0):((d.n) - 1)
        [t__102, t__103] = asils.pc.stream_normal3(disp);
        e = t__102;
        disp = t__103;
        u.bias((j) + 1, :) = (e * d.bias_sigma).';
    end
    u.g = noise;
end
