function s = SunUnit_zero()
%SUNUNIT_ZERO  a SunUnit with every field zero
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = struct();
    s.bias = zeros(8, 3);
    s.g = zeros(6, 1);
end
