function [a] = rotor_axes(nr, rot_a0, rot_gi, gim_axis, delta)
%ROTOR_AXES  The axis of each of the nr rotors (columns of a 3 x 8): its nominal axis, turned about its
%   gimbal (rot_gi = gimbal index + 1, 0 fixed) by the gimbal angle.
%   nr: int (passed a whole number)
%   rot_a0: real[1][3][8] (passed a plain number)
%   rot_gi: int[8] (passed a whole number)
%   gim_axis: real[1][3][4] (passed a plain number)
%   delta: real[1][4] (passed a plain number)
%   returns a: real[1][8][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    a = zeros(3, 8);
    a = zeros(3, 8);
    for i = (0):((nr) - 1)
        a0 = (rot_a0((i) + 1, :)).';
        if (rot_gi((i) + 1) > 0)
            j = (rot_gi((i) + 1) - 1);
            t0 = [gim_axis((j) + 1, 2)*a0(3) - gim_axis((j) + 1, 3)*a0(2); gim_axis((j) + 1, 3)*a0(1) - gim_axis((j) + 1, 1)*a0(3); gim_axis((j) + 1, 1)*a0(2) - gim_axis((j) + 1, 2)*a0(1)];
            for k = (0):((3) - 1)
                a((k) + 1, (i) + 1) = ((cos(delta((j) + 1)) * a0((k) + 1)) + (sin(delta((j) + 1)) * t0((k) + 1)));
            end
        else
            for k = (0):((3) - 1)
                a((k) + 1, (i) + 1) = a0((k) + 1);
            end
        end
    end
end
