function [gdot, hdot] = steer_sr(tau, a, h, nr, ng, rot_gi, gim_axis, gim_rate_max, cmg_lam0, cmg_mu, wheels)
%STEER_SR  Singularity-robust steering: gimbal rates (and, with wheels, rotor momentum rates) that give
%   the torque tau, weighted away from the singular set, the gimbal rates held to gim_rate_max.
%   tau: real[1][3] (passed a plain number)
%   a: real[1][8][3] (passed a plain number)
%   h: real[1][8] (passed a plain number)
%   nr: int (passed a whole number)
%   ng: int (passed a whole number)
%   rot_gi: int[8] (passed a whole number)
%   gim_axis: real[1][3][4] (passed a plain number)
%   gim_rate_max: real[1] (passed a plain number)
%   cmg_lam0: real[1] (passed a plain number)
%   cmg_mu: real[1] (passed a plain number)
%   wheels: bool (passed true or false)
%   returns gdot: real[1][4] (passed a plain number)
%   returns hdot: real[1][8] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    gdot = zeros(4, 1);
    hdot = zeros(8, 1);
    jg = zeros(3, 4);
    h0 = 0;
    t__19 = ((0):((nr) - 1)).';
    for i = t__19(logical((rot_gi((t__19) + 1) > 0))).'
        j = (rot_gi((i) + 1) - 1);
        c = asils.pc.cross_((gim_axis((j) + 1, :)).', [a(1, (i) + 1); a(2, (i) + 1); a(3, (i) + 1)]);
        for k = (0):((3) - 1)
            jg((k) + 1, (j) + 1) = ((-(h((i) + 1))) * c((k) + 1));
        end
        if (asils.pc.fabs(h((i) + 1)) > h0)
            h0 = asils.pc.fabs(h((i) + 1));
        end
    end
    m = zeros(3, 3);
    for i = (0):((3) - 1)
        for j = (0):((3) - 1)
            m((i) + 1, (j) + 1) = 0;
            for k = (0):((ng) - 1)
                m((i) + 1, (j) + 1) = (m((i) + 1, (j) + 1) + (jg((i) + 1, (k) + 1) * jg((j) + 1, (k) + 1)));
            end
        end
    end
    if (h0 < 1e-12)
        h0 = 1e-12;
    end
    ms = (asils.alg.math.det3(m) / (((((h0 * h0) * h0) * h0) * h0) * h0));
    n = asils.pc.choose(wheels, (ng + nr), ng);
    jj = zeros(3, 12);
    for i = (0):((3) - 1)
        for j = (0):((ng) - 1)
            jj((i) + 1, (j) + 1) = jg((i) + 1, (j) + 1);
        end
        if wheels
            for j = (0):((nr) - 1)
                jj((i) + 1, ((ng + j)) + 1) = (-(a((i) + 1, (j) + 1)));
            end
        end
    end
    w = zeros(12, 1);
    for j = (0):((n) - 1)
        w((j) + 1) = asils.pc.choose((j < ng), 1, (0.01 + (2 * exp(((-(10)) * ms)))));
    end
    lam = (cmg_lam0 * exp(((-(cmg_mu)) * ms)));
    for i = (0):((3) - 1)
        for j = (0):((3) - 1)
            m((i) + 1, (j) + 1) = asils.pc.choose((i == j), lam, 0);
            for k = (0):((n) - 1)
                m((i) + 1, (j) + 1) = (m((i) + 1, (j) + 1) + ((jj((i) + 1, (k) + 1) * w((k) + 1)) * jj((j) + 1, (k) + 1)));
            end
        end
    end
    [mi, ok] = asils.alg.math.inv3(m);
    x = [mi(1, 1)*tau(1) + mi(1, 2)*tau(2) + mi(1, 3)*tau(3); mi(2, 1)*tau(1) + mi(2, 2)*tau(2) + mi(2, 3)*tau(3); mi(3, 1)*tau(1) + mi(3, 2)*tau(2) + mi(3, 3)*tau(3)];
    u = zeros(12, 1);
    for k = (0):((n) - 1)
        u((k) + 1) = (w((k) + 1) * (((jj(1, (k) + 1) * x(1)) + (jj(2, (k) + 1) * x(2))) + (jj(3, (k) + 1) * x(3))));
    end
    s = 1;
    gdot = zeros(4, 1);
    for j = (0):((ng) - 1)
        gdot((j) + 1) = u((j) + 1);
        if ((asils.pc.fabs(u((j) + 1)) / gim_rate_max) > s)
            s = (asils.pc.fabs(u((j) + 1)) / gim_rate_max);
        end
    end
    for j = (0):((ng) - 1)
        gdot((j) + 1) = (gdot((j) + 1) / s);
    end
    hdot = zeros(8, 1);
    for i = (0):((nr) - 1)
        hdot((i) + 1) = asils.pc.choose_lazy(wheels, @() (u(((ng + i)) + 1) / s), @() 0);
    end
end
