function [phi] = phi_quad(a_sat, gm_body, r_body, e_body, mu)
%PHI_QUAD  thirdbody.secular.phiQuad(a_sat, GM_body, r_body, e_body, mu): the secular quadrupole frequency [rad/s] of a
%   perturber of GM gm_body on an orbit of radius r_body and eccentricity e_body, the satellite's semi-major axis a_sat.
%   a_sat: real[1] (passed a plain number)
%   gm_body: real[1] (passed a plain number)
%   r_body: real[1] (passed a plain number)
%   e_body: real[1] (passed a plain number)
%   mu: real[1] (passed a plain number)
%   returns phi: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    phi = 0;
    h__526 = (a_sat)^(3);
    if ~isreal(h__526), h__526 = NaN; end
    h__527 = (mu / h__526);
    if h__527 < 0, h__527 = NaN; else, h__527 = sqrt(h__527); end
    n = h__527;
    h__528 = (r_body)^(3);
    if ~isreal(h__528), h__528 = NaN; end
    h__529 = ((1 - (e_body * e_body)))^(1.5);
    if ~isreal(h__529), h__529 = NaN; end
    phi = (((0.75 * (gm_body / h__528)) / n) / h__529);
end
