function [a] = tb_direct(s, b, gm)
%TB_DIRECT  thirdbody.direct(rSat, rBody, GM): GM ((b - s)/|b - s|^3 - b/|b|^3), with Octave's scaled norms (the two terms cancel
%   to about five digits for the Sun, so the norm's last bit matters).
%   The cancellation amplifies pow's last bit about 1e5 times: a translation is held to 1e-8 of the largest output.
%   tolerance: 1e-8
%   s: real[1][3] (passed a plain number)
%   b: real[1][3] (passed a plain number)
%   gm: real[1] (passed a plain number)
%   returns a: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    a = zeros(3, 1);
    d = [(b(1) - s(1)); (b(2) - s(2)); (b(3) - s(3))];
    nd3 = asils.pc.pow_(asils.models.gravity.onorm(d), 3);
    nb3 = asils.pc.pow_(asils.models.gravity.onorm(b), 3);
    a = zeros(3, 1);
    for i = (0):((3) - 1)
        a((i) + 1) = (gm * ((d((i) + 1) / nd3) - (b((i) + 1) / nb3)));
    end
end
