function [a] = tb_legendre(s, b, gm, nmax)
%TB_LEGENDRE  thirdbody.legendre(rSat, rBody, GM, nmax): the Legendre series of the third body's potential to degree nmax (at most
%   64).
%   s: real[1][3] (passed a plain number)
%   b: real[1][3] (passed a plain number)
%   gm: real[1] (passed a plain number)
%   nmax: int (passed a whole number)
%   returns a: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    a = zeros(3, 1);
    rho = sqrt(s(1)*s(1) + s(2)*s(2) + s(3)*s(3));
    rb = sqrt(b(1)*b(1) + b(2)*b(2) + b(3)*b(3));
    rs = [(s(1) / rho); (s(2) / rho); (s(3) / rho)];
    rbh = [(b(1) / rb); (b(2) / rb); (b(3) / rb)];
    u = (rs(1)*rbh(1) + rs(2)*rbh(2) + rs(3)*rbh(3));
    p = zeros(65, 1);
    dp = zeros(65, 1);
    p(1) = 1;
    if (nmax >= 1)
        p(2) = u;
        dp(2) = 1;
    end
    for n = (2):(((nmax + 1)) - 1)
        nf = n;
        p((n) + 1) = ((((((2 * nf) - 1) * u) * p(((n - 1)) + 1)) - ((nf - 1) * p(((n - 2)) + 1))) / nf);
        dp((n) + 1) = ((u * dp(((n - 1)) + 1)) + (nf * p(((n - 1)) + 1)));
    end
    a = zeros(3, 1);
    for m = (2):(((nmax + 1)) - 1)
        mf = m;
        h__518 = (rb)^((mf + 1));
        if ~isreal(h__518), h__518 = NaN; end
        h__519 = (rho)^((mf - 1));
        if ~isreal(h__519), h__519 = NaN; end
        k = ((gm / h__518) * h__519);
        i = ((0):((3) - 1)).';
        a((i) + 1) = (reshape(a((i) + 1), [], 1) + (k .* (((mf * p((m) + 1)) .* reshape(rs((i) + 1), [], 1)) + (dp((m) + 1) .* (reshape(rbh((i) + 1), [], 1) - (u .* reshape(rs((i) + 1), [], 1)))))));
    end
end
