function [a] = tb_tidal(s, b, gm)
%TB_TIDAL  thirdbody.tidal(rSat, rBody, GM): the degree-2 gradient, -GM/|b|^3 (s - 3 (s.bhat) bhat).
%   s: real[1][3] (passed a plain number)
%   b: real[1][3] (passed a plain number)
%   gm: real[1] (passed a plain number)
%   returns a: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    a = zeros(3, 1);
    rb = asils.pc.norm_(b);
    rh = [(b(1) / rb); (b(2) / rb); (b(3) / rb)];
    k = ((-(gm)) / asils.pc.pow_(rb, 3));
    sr = (3 * asils.pc.dot_(s, rh));
    a = [(k * (s(1) - (sr * rh(1)))); (k * (s(2) - (sr * rh(2)))); (k * (s(3) - (sr * rh(3))))];
end
