function [y] = unit_clip(x)
%UNIT_CLIP  x.min(1).max(-1) of the code (MATLAB's max(min(x, 1), -1)): a nan gives 1.
%   x: real[1] (passed a plain number)
%   returns y: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    y = 0;
    if (x < 1)
        h__520 = x;
    else
        h__520 = 1;
    end
    m = h__520;
    if (m > (-(1)))
        h__521 = m;
    else
        h__521 = (-(1));
    end
    y = h__521;
end
