function [q] = fromdcm(r)
%FROMDCM  The quaternion of a rotation matrix: the largest of (trace, R11, R22, R33) picks the form, then
%   it is made unit (no sign forced).
%   r: real[1][3][3] (passed a plain number)
%   returns q: real[1][4] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    q = zeros(4, 1);
    tr = ((r(1, 1) + r(2, 2)) + r(3, 3));
    idx = 0;
    best = tr;
    if (r(1, 1) > best)
        best = r(1, 1);
        idx = 1;
    end
    if (r(2, 2) > best)
        best = r(2, 2);
        idx = 2;
    end
    if (r(3, 3) > best)
        idx = 3;
    end
    u = zeros(4, 1);
    if (idx == 0)
        u = [(r(2, 3) - r(3, 2)); (r(3, 1) - r(1, 3)); (r(1, 2) - r(2, 1)); (1 + tr)];
    elseif (idx == 1)
        u = [((1 + (2 * r(1, 1))) - tr); (r(1, 2) + r(2, 1)); (r(1, 3) + r(3, 1)); (r(2, 3) - r(3, 2))];
    elseif (idx == 2)
        u = [(r(2, 1) + r(1, 2)); ((1 + (2 * r(2, 2))) - tr); (r(2, 3) + r(3, 2)); (r(3, 1) - r(1, 3))];
    else
        u = [(r(3, 1) + r(1, 3)); (r(3, 2) + r(2, 3)); ((1 + (2 * r(3, 3))) - tr); (r(1, 2) - r(2, 1))];
    end
    q = asils.relations.shared.qnorm(u);
end
