function [f] = f30_to_f107scale(f30, decimal_year)
%F30_TO_F107SCALE  f30_to_f107scale: the native F30 on the F10.7 scale, the DTM2020 paper's eq. 2 with its drift in the decimal year.
%   f30: real[1] (passed a plain number)
%   decimal_year: real[1] (passed a plain number)
%   returns f: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    f = 0;
    f = (((-(1.5998)) + (1.553755 * f30)) + ((0.22446 * decimal_year) - 447.13328));
end
