function [gmlat, gmlong, ok] = geogm(xlat, xlong_in)
%GEOGM  geogm: geographic latitude and longitude [deg] to geomagnetic [deg], the dipole pole at 78.5 N, 291 E; ok is false
%   where the MATLAB raises its angle error (a NaN quadrant).
%   xlat: real[1] (passed a plain number)
%   xlong_in: real[1] (passed a plain number)
%   returns gmlat: real[1] (passed a plain number)
%   returns gmlong: real[1] (passed a plain number)
%   returns ok: bool (passed true or false)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    gmlat = 0;
    gmlong = 0;
    ok = false;
    rfac = (pi / 180);
    platr = (78.5 * rfac);
    plongr = (291 * rfac);
    xlong = xlong_in;
    if (xlong == 291)
        xlong = 291.1;
    end
    spl = sin(platr);
    cpl = cos(platr);
    rlat = (xlat * rfac);
    rlong = (xlong * rfac);
    slm = ((spl * sin(rlat)) + ((cpl * cos(rlat)) * cos((plongr - rlong))));
    clm = sqrt((1 - (slm)^(2)));
    phim1 = ((cos(rlat) * sin((rlong - plongr))) / clm);
    phim2 = (((spl * slm) - sin(rlat)) / (cpl * clm));
    gmlat = (asin(slm) / rfac);
    gmlong = 0;
    ok = true;
    if ((phim1 >= 0) && (phim2 >= 0))
        gmlong = (asin(phim1) / rfac);
    elseif ((phim1 >= 0) && (phim2 < 0))
        gmlong = ((pi - asils.pc.fabs(asin(phim1))) / rfac);
    elseif ((phim1 < 0) && (phim2 < 0))
        gmlong = ((pi + asils.pc.fabs(asin(phim1))) / rfac);
    elseif ((phim1 < 0) && (phim2 >= 0))
        gmlong = (((2 * pi) - asils.pc.fabs(asin(phim1))) / rfac);
    else
        ok = false;
    end
end
