function [t] = dtc_hour(k)
%DTC_HOUR  The hour [datenum] of the k-th hourly DSTDTC sample (row k/24, hour k mod 24).
%   k: int (passed a whole number)
%   returns t: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    t = 0;
    r = fix((k) / (24));
    h = rem(k, 24);
    base = ((asils.models.timescales.datenum(asils.models.jbset.DTCFILE((r) + 1, 1), 1, 1, 0, 0, 0) + asils.models.jbset.DTCFILE((r) + 1, 2)) - 1);
    t = (base + (h / 24));
end
