function [y] = dtc_interp(x)
%DTC_INTERP  The same over the hourly DSTDTC [K].
%   x: real[1] (passed a plain number)
%   returns y: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    y = 0;
    n = (10729 * 24);
    lo = 0;
    hi = n;
    n__418 = 64; k__417 = 0;
    while true
        mid = fix(((lo + hi)) / (2));
        if (asils.models.jb2008.dtc_hour(mid) <= x)
            lo = (mid + 1);
        else
            hi = mid;
        end
        k__417 = k__417 + 1;
        if (lo >= hi), break; end
        if k__417 >= n__418
            break;
        end
    end
    i = 0;
    if (lo > 0)
        i = (lo - 1);
    end
    i = asils.pc.fmin(i, (n - 2));
    x0 = asils.models.jb2008.dtc_hour(i);
    x1 = asils.models.jb2008.dtc_hour((i + 1));
    y0 = asils.models.jbset.DTCFILE((fix((i) / (24))) + 1, ((rem(i, 24) + 2)) + 1);
    y1 = asils.models.jbset.DTCFILE((fix(((i + 1)) / (24))) + 1, ((rem((i + 1), 24) + 2)) + 1);
    slope = ((y1 - y0) / (x1 - x0));
    y = ((slope * (x - x0)) + y0);
end
