function [dtc] = dtsub(f10, xlst, xlat, zht)
%DTSUB  DTSUB: the dTc correction [K] for the local solar time [h], the latitude [rad] and the height [km].
%   f10: real[1] (passed a plain number)
%   xlst: real[1] (passed a plain number)
%   xlat: real[1] (passed a plain number)
%   zht: real[1] (passed a plain number)
%   returns dtc: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    dtc = 0;
    kb = [(-(4.57512297)); (-(5.12114909)); (-(69.3003609)); 203.716701; 703.316291; (-(1943.49234)); 1106.51308; (-(174.378996)); 1885.94601; (-(7093.71517)); 9224.54523; (-(3845.08073)); (-(6.45841789)); 40.9703319; (-(482.00656)); 1818.70931; (-(2373.89204)); 996.703815; 36.1416936];
    kc = [(-(15.5986211)); (-(5.12114909)); (-(69.3003609)); 203.716701; 703.316291; (-(1943.49234)); 1106.51308; (-(220.835117)); 1432.56989; (-(3184.81844)); 3289.81513; (-(1353.32119)); 19.9956489; (-(12.7093998)); 21.2825156; (-(2.75555432)); 11.0234982; 148.881951; (-(751.640284)); 637.876542; 12.7093998; (-(21.2825156)); 2.75555432];
    dtc = 0;
    tx = (xlst / 24);
    ycs = cos(xlat);
    f = ((f10 - 100) / 100);
    h = 0;
    sum = 0;
    aa = 0;
    bb = 0;
    cc = 0;
    dd = 0;
    zp = 0;
    if ((zht >= 120) && (zht <= 200))
        dtc200 = ((((((kc(17) + ((kc(18) * tx) * ycs)) + ((kc(19) * (tx)^(2)) * ycs)) + ((kc(20) * (tx)^(3)) * ycs)) + ((kc(21) * f) * ycs)) + (((kc(22) * tx) * f) * ycs)) + (((kc(23) * (tx)^(2)) * f) * ycs));
        sum = (((((((((((((((kc(1) + (kb(2) * f)) + ((kc(3) * tx) * f)) + ((kc(4) * (tx)^(2)) * f)) + ((kc(5) * (tx)^(3)) * f)) + ((kc(6) * (tx)^(4)) * f)) + ((kc(7) * (tx)^(5)) * f)) + ((kc(8) * tx) * ycs)) + ((kc(9) * (tx)^(2)) * ycs)) + ((kc(10) * (tx)^(3)) * ycs)) + ((kc(11) * (tx)^(4)) * ycs)) + ((kc(12) * (tx)^(5)) * ycs)) + (kc(13) * ycs)) + ((kc(14) * f) * ycs)) + (((kc(15) * tx) * f) * ycs)) + (((kc(16) * (tx)^(2)) * f) * ycs));
        dtc200dz = sum;
        cc = ((3 * dtc200) - dtc200dz);
        dd = (dtc200 - cc);
        zp = ((zht - 120) / 80);
        dtc = (((cc * zp) * zp) + (((dd * zp) * zp) * zp));
    end
    if ((zht > 200) && (zht <= 240))
        h = ((zht - 200) / 50);
        sum = (((((((((((((((((((((((kc(1) * h) + ((kb(2) * f) * h)) + (((kc(3) * tx) * f) * h)) + (((kc(4) * (tx)^(2)) * f) * h)) + (((kc(5) * (tx)^(3)) * f) * h)) + (((kc(6) * (tx)^(4)) * f) * h)) + (((kc(7) * (tx)^(5)) * f) * h)) + (((kc(8) * tx) * ycs) * h)) + (((kc(9) * (tx)^(2)) * ycs) * h)) + (((kc(10) * (tx)^(3)) * ycs) * h)) + (((kc(11) * (tx)^(4)) * ycs) * h)) + (((kc(12) * (tx)^(5)) * ycs) * h)) + ((kc(13) * ycs) * h)) + (((kc(14) * f) * ycs) * h)) + ((((kc(15) * tx) * f) * ycs) * h)) + ((((kc(16) * (tx)^(2)) * f) * ycs) * h)) + kc(17)) + ((kc(18) * tx) * ycs)) + ((kc(19) * (tx)^(2)) * ycs)) + ((kc(20) * (tx)^(3)) * ycs)) + ((kc(21) * f) * ycs)) + (((kc(22) * tx) * f) * ycs)) + (((kc(23) * (tx)^(2)) * f) * ycs));
        dtc = sum;
    end
    if ((zht > 240) && (zht <= 300))
        h = (40 / 50);
        sum = (((((((((((((((((((((((kc(1) * h) + ((kb(2) * f) * h)) + (((kc(3) * tx) * f) * h)) + (((kc(4) * (tx)^(2)) * f) * h)) + (((kc(5) * (tx)^(3)) * f) * h)) + (((kc(6) * (tx)^(4)) * f) * h)) + (((kc(7) * (tx)^(5)) * f) * h)) + (((kc(8) * tx) * ycs) * h)) + (((kc(9) * (tx)^(2)) * ycs) * h)) + (((kc(10) * (tx)^(3)) * ycs) * h)) + (((kc(11) * (tx)^(4)) * ycs) * h)) + (((kc(12) * (tx)^(5)) * ycs) * h)) + ((kc(13) * ycs) * h)) + (((kc(14) * f) * ycs) * h)) + ((((kc(15) * tx) * f) * ycs) * h)) + ((((kc(16) * (tx)^(2)) * f) * ycs) * h)) + kc(17)) + ((kc(18) * tx) * ycs)) + ((kc(19) * (tx)^(2)) * ycs)) + ((kc(20) * (tx)^(3)) * ycs)) + ((kc(21) * f) * ycs)) + (((kc(22) * tx) * f) * ycs)) + (((kc(23) * (tx)^(2)) * f) * ycs));
        aa = sum;
        bb = (((((((((((((((kc(1) + (kb(2) * f)) + ((kc(3) * tx) * f)) + ((kc(4) * (tx)^(2)) * f)) + ((kc(5) * (tx)^(3)) * f)) + ((kc(6) * (tx)^(4)) * f)) + ((kc(7) * (tx)^(5)) * f)) + ((kc(8) * tx) * ycs)) + ((kc(9) * (tx)^(2)) * ycs)) + ((kc(10) * (tx)^(3)) * ycs)) + ((kc(11) * (tx)^(4)) * ycs)) + ((kc(12) * (tx)^(5)) * ycs)) + (kc(13) * ycs)) + ((kc(14) * f) * ycs)) + (((kc(15) * tx) * f) * ycs)) + (((kc(16) * (tx)^(2)) * f) * ycs));
        h = (300 / 100);
        sum = ((((((((((((((((((kb(1) + (kb(2) * f)) + ((kb(3) * tx) * f)) + ((kb(4) * (tx)^(2)) * f)) + ((kb(5) * (tx)^(3)) * f)) + ((kb(6) * (tx)^(4)) * f)) + ((kb(7) * (tx)^(5)) * f)) + ((kb(8) * tx) * ycs)) + ((kb(9) * (tx)^(2)) * ycs)) + ((kb(10) * (tx)^(3)) * ycs)) + ((kb(11) * (tx)^(4)) * ycs)) + ((kb(12) * (tx)^(5)) * ycs)) + ((kb(13) * h) * ycs)) + (((kb(14) * tx) * h) * ycs)) + (((kb(15) * (tx)^(2)) * h) * ycs)) + (((kb(16) * (tx)^(3)) * h) * ycs)) + (((kb(17) * (tx)^(4)) * h) * ycs)) + (((kb(18) * (tx)^(5)) * h) * ycs)) + (kb(19) * ycs));
        dtc300 = sum;
        sum = ((((((kb(13) * ycs) + ((kb(14) * tx) * ycs)) + ((kb(15) * (tx)^(2)) * ycs)) + ((kb(16) * (tx)^(3)) * ycs)) + ((kb(17) * (tx)^(4)) * ycs)) + ((kb(18) * (tx)^(5)) * ycs));
        dtc300dz = sum;
        cc = ((((3 * dtc300) - dtc300dz) - (3 * aa)) - (2 * bb));
        dd = (((dtc300 - aa) - bb) - cc);
        zp = ((zht - 240) / 60);
        dtc = (((aa + (bb * zp)) + ((cc * zp) * zp)) + (((dd * zp) * zp) * zp));
    end
    if ((zht > 300) && (zht <= 600))
        h = (zht / 100);
        sum = ((((((((((((((((((kb(1) + (kb(2) * f)) + ((kb(3) * tx) * f)) + ((kb(4) * (tx)^(2)) * f)) + ((kb(5) * (tx)^(3)) * f)) + ((kb(6) * (tx)^(4)) * f)) + ((kb(7) * (tx)^(5)) * f)) + ((kb(8) * tx) * ycs)) + ((kb(9) * (tx)^(2)) * ycs)) + ((kb(10) * (tx)^(3)) * ycs)) + ((kb(11) * (tx)^(4)) * ycs)) + ((kb(12) * (tx)^(5)) * ycs)) + ((kb(13) * h) * ycs)) + (((kb(14) * tx) * h) * ycs)) + (((kb(15) * (tx)^(2)) * h) * ycs)) + (((kb(16) * (tx)^(3)) * h) * ycs)) + (((kb(17) * (tx)^(4)) * h) * ycs)) + (((kb(18) * (tx)^(5)) * h) * ycs)) + (kb(19) * ycs));
        dtc = sum;
    end
    if ((zht > 600) && (zht <= 800))
        zp = ((zht - 600) / 100);
        hp = (600 / 100);
        aa = ((((((((((((((((((kb(1) + (kb(2) * f)) + ((kb(3) * tx) * f)) + ((kb(4) * (tx)^(2)) * f)) + ((kb(5) * (tx)^(3)) * f)) + ((kb(6) * (tx)^(4)) * f)) + ((kb(7) * (tx)^(5)) * f)) + ((kb(8) * tx) * ycs)) + ((kb(9) * (tx)^(2)) * ycs)) + ((kb(10) * (tx)^(3)) * ycs)) + ((kb(11) * (tx)^(4)) * ycs)) + ((kb(12) * (tx)^(5)) * ycs)) + ((kb(13) * hp) * ycs)) + (((kb(14) * tx) * hp) * ycs)) + (((kb(15) * (tx)^(2)) * hp) * ycs)) + (((kb(16) * (tx)^(3)) * hp) * ycs)) + (((kb(17) * (tx)^(4)) * hp) * ycs)) + (((kb(18) * (tx)^(5)) * hp) * ycs)) + (kb(19) * ycs));
        bb = ((((((kb(13) * ycs) + ((kb(14) * tx) * ycs)) + ((kb(15) * (tx)^(2)) * ycs)) + ((kb(16) * (tx)^(3)) * ycs)) + ((kb(17) * (tx)^(4)) * ycs)) + ((kb(18) * (tx)^(5)) * ycs));
        cc = ((-(((3 * aa) + (4 * bb)))) / 4);
        dd = ((aa + bb) / 4);
        dtc = (((aa + (bb * zp)) + ((cc * zp) * zp)) + (((dd * zp) * zp) * zp));
    end
end
