function [s] = jb_sign(a, b)
%JB_SIGN  sign_(a, b): |a| with the sign of b (b >= 0 positive).
%   a: real[1] (passed a plain number)
%   b: real[1] (passed a plain number)
%   returns s: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = 0;
    if (b >= 0)
        h__306 = a;
        if h__306 < 0, h__306 = -h__306; elseif h__306 == 0, h__306 = 0; end
        s = h__306;
    else
        h__307 = a;
        if h__307 < 0, h__307 = -h__307; elseif h__307 == 0, h__307 = 0; end
        s = (-(h__307));
    end
end
