function [s] = jb_sign(a, b)
%JB_SIGN  sign_(a, b): |a| with the sign of b (b >= 0 positive).
%   a: real[1] (passed a plain number)
%   b: real[1] (passed a plain number)
%   returns s: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = 0;
    if (b >= 0)
        s = asils.pc.fabs(a);
    else
        s = (-(asils.pc.fabs(a)));
    end
end
