function s = JbOut_zero()
%JBOUT_ZERO  a JbOut with every field zero
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = struct();
    s.temp = zeros(2, 1);
    s.rho = 0;
end
