function [y] = sol_interp(j, x)
%SOL_INTERP  Octave's interp1(t, F, x, 'linear', 'extrap') over column j (F10 F81 S10 S81 M10 M81 Y10 Y81) of the daily
%   indices: the interval at or below x by bisection (the edge one outside), then the straight line through it.
%   j: int (passed a whole number)
%   x: real[1] (passed a plain number)
%   returns y: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    y = 0;
    n = 10729;
    lo = 0;
    hi = n;
    n__19 = 64; k__18 = 0;
    while true
        mid = fix(((lo + hi)) / (2));
        if (asils.models.jb2008.sol_day(mid) <= x)
            lo = (mid + 1);
        else
            hi = mid;
        end
        k__18 = k__18 + 1;
        if (lo >= hi), break; end
        if k__18 >= n__19
            break;
        end
    end
    i = 0;
    if (lo > 0)
        i = (lo - 1);
    end
    i = asils.pc.fmin(i, (n - 2));
    x0 = asils.models.jb2008.sol_day(i);
    x1 = asils.models.jb2008.sol_day((i + 1));
    y0 = asils.models.jbset.SOLFSMY((i) + 1, ((j + 2)) + 1);
    y1 = asils.models.jbset.SOLFSMY(((i + 1)) + 1, ((j + 2)) + 1);
    slope = ((y1 - y0) / (x1 - x0));
    y = ((slope * (x - x0)) + y0);
end
