function [ra, dec] = sun_radec(mjd)
%SUN_RADEC  sun_radec of jb2008_density.m: the low-precision Sun's right ascension and declination [rad] (mean equinox of
%   date) at an MJD.
%   mjd: real[1] (passed a plain number)
%   returns ra: real[1] (passed a plain number)
%   returns dec: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    ra = 0;
    dec = 0;
    t = ((mjd - 51544.5) / 36525);
    l = asils.models.timescales.omod((280.46 + (36000.771 * t)), 360);
    m = asils.models.timescales.deg2rad(asils.models.timescales.omod((357.528 + (35999.05 * t)), 360));
    lam = asils.models.timescales.deg2rad(((l + (1.915 * sin(m))) + (0.02 * sin((2 * m)))));
    eps = asils.models.timescales.deg2rad((23.439 - (0.013 * t)));
    ra = asils.models.timescales.omod(atan2((cos(eps) * sin(lam)), cos(lam)), (2 * pi));
    h__432 = asin((sin(eps) * sin(lam)));
    if ~isreal(h__432), h__432 = NaN; end
    dec = h__432;
end
