function [d] = tmoutd(mjd)
%TMOUTD  TMOUTD(MJD) = finddays(invjday(MJD + 2400000.5)): as the MATLAB, which hands invjday a Julian date where it takes a
%   modified one, so the calendar date of the semiannual phase is offset by 2400000.5 days.
%   mjd: real[1] (passed a plain number)
%   returns d: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    d = 0;
    u = asils.models.jb2008.invjday((mjd + 2400000.5));
    d = asils.models.jb2008.finddays(u(1), u(2), u(3), u(4), u(5), u(6));
end
