function [n, mmax, c_mjd, c_xp, c_yp, c_ut, c_dx, c_dy, f_mjd, f_xp, f_yp, f_ut, f_dx, f_dy, o_mjd, o_xp, o_yp, o_ut, o_dx, o_dy, ix, tmp, w] = splice(c_mjd, c_xp, c_yp, c_ut, c_dx, c_dy, has_cdx, f_mjd, f_xp, f_yp, f_ut, f_dx, f_dy, o_mjd, o_xp, o_yp, o_ut, o_dx, o_dy, ix, tmp, w)
%SPLICE  The spliced table of builds B and C (o_*, as long as both inputs together): the C04 rows (its MJD, x, y, UT1 - UTC and,
%   when it carries them, has_cdx, its dX, dY), then the finals rows (f_*) whose MJD is after C04's last, ordered by MJD
%   (equal ones in that order); without C04's dX, dY each row takes the finals' interpolated at its MJD, 0 outside them.
%   How many rows, and C04's last MJD; ix, tmp and w are scratch as long as the output.
%   length: 12
%   c_mjd: inout real[1][*] (passed a plain number)
%   c_xp: inout real[1][*] (passed a plain number)
%   c_yp: inout real[1][*] (passed a plain number)
%   c_ut: inout real[1][*] (passed a plain number)
%   c_dx: inout real[1][*] (passed a plain number)
%   c_dy: inout real[1][*] (passed a plain number)
%   has_cdx: bool (passed true or false)
%   f_mjd: inout real[1][*] (passed a plain number)
%   f_xp: inout real[1][*] (passed a plain number)
%   f_yp: inout real[1][*] (passed a plain number)
%   f_ut: inout real[1][*] (passed a plain number)
%   f_dx: inout real[1][*] (passed a plain number)
%   f_dy: inout real[1][*] (passed a plain number)
%   o_mjd: inout real[1][*] (passed a plain number)
%   o_xp: inout real[1][*] (passed a plain number)
%   o_yp: inout real[1][*] (passed a plain number)
%   o_ut: inout real[1][*] (passed a plain number)
%   o_dx: inout real[1][*] (passed a plain number)
%   o_dy: inout real[1][*] (passed a plain number)
%   ix: inout int[*] (passed a whole number)
%   tmp: inout int[*] (passed a whole number)
%   w: inout real[1][*] (passed a plain number)
%   returns n: int (passed a whole number)
%   returns mmax: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    n = 0;
    mmax = 0;
    mmax = (-(Inf));
    for i = (0):((numel(c_mjd)) - 1)
        mmax = asils.pc.fmax(mmax, c_mjd((i) + 1));
    end
    n = 0;
    for i1 = (0):((numel(c_mjd)) - 1)
        o_mjd((n) + 1) = c_mjd((i1) + 1);
        o_xp((n) + 1) = c_xp((i1) + 1);
        o_yp((n) + 1) = c_yp((i1) + 1);
        o_ut((n) + 1) = c_ut((i1) + 1);
        if has_cdx
            o_dx((n) + 1) = c_dx((i1) + 1);
            o_dy((n) + 1) = c_dy((i1) + 1);
        end
        n = (n + 1);
    end
    for i2 = (0):((numel(f_mjd)) - 1)
        if (f_mjd((i2) + 1) > mmax)
            o_mjd((n) + 1) = f_mjd((i2) + 1);
            o_xp((n) + 1) = f_xp((i2) + 1);
            o_yp((n) + 1) = f_yp((i2) + 1);
            o_ut((n) + 1) = f_ut((i2) + 1);
            if has_cdx
                o_dx((n) + 1) = f_dx((i2) + 1);
                o_dy((n) + 1) = f_dy((i2) + 1);
            end
            n = (n + 1);
        end
    end
    if (~has_cdx)
        for i3 = (0):((n) - 1)
            [t__408, t__409, t__410] = asils.models.eop.interp1_linear(f_mjd, f_dx, o_mjd((i3) + 1), true, 0);
            vx = t__408;
            f_mjd = t__409;
            f_dx = t__410;
            [t__411, t__412, t__413] = asils.models.eop.interp1_linear(f_mjd, f_dy, o_mjd((i3) + 1), true, 0);
            vy = t__411;
            f_mjd = t__412;
            f_dy = t__413;
            o_dx((i3) + 1) = vx;
            o_dy((i3) + 1) = vy;
        end
    end
    [t__414, t__415, t__416, t__417] = asils.models.eop.sort_asc(o_mjd, ix, tmp, n);
    p = t__414;
    o_mjd = t__415;
    ix = t__416;
    tmp = t__417;
    [t__418, t__419, t__420, t__421] = asils.models.eop.permute(o_mjd, ix, w, n);
    z1 = t__418;
    o_mjd = t__419;
    ix = t__420;
    w = t__421;
    [t__422, t__423, t__424, t__425] = asils.models.eop.permute(o_xp, ix, w, n);
    z2 = t__422;
    o_xp = t__423;
    ix = t__424;
    w = t__425;
    [t__426, t__427, t__428, t__429] = asils.models.eop.permute(o_yp, ix, w, n);
    z3 = t__426;
    o_yp = t__427;
    ix = t__428;
    w = t__429;
    [t__430, t__431, t__432, t__433] = asils.models.eop.permute(o_ut, ix, w, n);
    z4 = t__430;
    o_ut = t__431;
    ix = t__432;
    w = t__433;
    [t__434, t__435, t__436, t__437] = asils.models.eop.permute(o_dx, ix, w, n);
    z5 = t__434;
    o_dx = t__435;
    ix = t__436;
    w = t__437;
    [t__438, t__439, t__440, t__441] = asils.models.eop.permute(o_dy, ix, w, n);
    z6 = t__438;
    o_dy = t__439;
    ix = t__440;
    w = t__441;
end
