function [q_body, ok, spots, identified, used, cr, cm, img, work, ia, ib, pi, pj, pa, g] = st_chain(q_true, r_body2head, r_head_nominal, cr, cm, nc, cam, img, work, ia, ib, pi, pj, pa, noisy, g)
%ST_CHAIN  The whole chain for one head: the frame rendered at the true attitude q_true (ECI to body, at the exposure) through the
%   head's true mount r_body2head (misalignment included), its spots, their directions through the pinhole and magnitudes
%   from their fluxes, identified, and the attitude with the residual check reported through the head's nominal mount
%   r_head_nominal: (q_body, solved, how many spots, identified, used); q_true when not solved.
%   length: 576
%   q_true: real[1][4] (passed a plain number)
%   r_body2head: real[1][3][3] (passed a plain number)
%   r_head_nominal: real[1][3][3] (passed a plain number)
%   cr: inout real[1][3][N_STARS] (passed a plain number)
%   cm: inout real[1][N_STARS] (passed a plain number)
%   nc: int (passed a whole number)
%   cam: StCamera (passed rec)
%   img: inout real[1][*] (passed a plain number)
%   work: inout real[1][*] (passed a plain number)
%   ia: inout int[*] (passed a whole number)
%   ib: inout int[*] (passed a whole number)
%   pi: inout int[*] (passed a whole number)
%   pj: inout int[*] (passed a whole number)
%   pa: inout real[1][*] (passed a plain number)
%   noisy: bool (passed true or false)
%   g: inout stream (passed a random stream, as six numbers)
%   returns q_body: real[1][4] (passed a plain number)
%   returns ok: bool (passed true or false)
%   returns spots: int (passed a whole number)
%   returns identified: int (passed a whole number)
%   returns used: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    q_body = zeros(4, 1);
    ok = false;
    spots = 0;
    identified = 0;
    used = 0;
    q_body = q_true;
    ok = false;
    identified = 0;
    used = 0;
    r_eh = asils.pc.mm(r_body2head, asils.models.math.dcm(q_true));
    tx = zeros(1, 1);
    ty = zeros(1, 1);
    tk = zeros(1, 1);
    [t__568, t__569, t__570, t__571, t__572, t__573, t__574, t__575] = asils.models.strender.st_render(r_eh, cr, cm, nc, cam, img, noisy, g, tx, ty, tk);
    drawn = t__568;
    cr = t__569;
    cm = t__570;
    img = t__571;
    g = t__572;
    tx = t__573;
    ty = t__574;
    tk = t__575;
    [t__576, t__577, t__578, t__579, t__580, t__581] = asils.models.stcentroid.st_centroid(img, cam, work, ia, ib);
    sp = t__576;
    ns = t__577;
    img = t__578;
    work = t__579;
    ia = t__580;
    ib = t__581;
    spots = ns;
    if (ns >= 3)
        b = zeros(32, 3);
        mag = zeros(32, 1);
        for k = (0):((ns) - 1)
            b((k) + 1, :) = asils.models.facets.unit_or_zero([((sp((k) + 1, 1) - cam.c) / cam.f); ((sp((k) + 1, 2) - cam.c) / cam.f); 1]).';
            mag((k) + 1) = (6 - (2.5 * asils.pc.log10_((asils.pc.fmax(sp((k) + 1, 3), 1) / cam.flux0))));
        end
        [t__582, t__583, t__584, t__585, t__586, t__587, t__588] = asils.models.stidentify.st_identify(b, mag, ns, pi, pj, pa, cr, cm, nc, cam.id_tol, cam.mag_tol);
        id = t__582;
        okid = t__583;
        pi = t__584;
        pj = t__585;
        pa = t__586;
        cr = t__587;
        cm = t__588;
        t__589 = ((0):((ns) - 1)).';
        for k2 = t__589(logical((id((t__589) + 1) >= 0))).'
            identified = (identified + 1);
        end
        if okid
            rs = zeros(32, 3);
            ig = zeros(32, 1);
            for p = (0):((32) - 1)
                ig((p) + 1) = (-(1));
            end
            t__590 = ((0):((ns) - 1)).';
            for p2 = t__590(logical((id((t__590) + 1) >= 0))).'
                rs((p2) + 1, :) = (cr((id((p2) + 1)) + 1, :)).'.';
                ig((p2) + 1) = id((p2) + 1);
            end
            [t__591, t__592, t__593] = asils.models.stattitude.st_attitude(b, rs, ns, ig, cam.fit_tol);
            q_eh = t__591;
            oka = t__592;
            ig = t__593;
            t__594 = ((0):((ns) - 1)).';
            for p3 = t__594(logical((ig((t__594) + 1) >= 0))).'
                used = (used + 1);
            end
            if oka
                q_body = asils.models.math.fromdcm(asils.pc.mm((r_head_nominal).', asils.models.math.dcm(q_eh)));
                ok = true;
            end
        end
    end
end
