function [q_body, ok, spots, identified, used, cr, cm, img, work, ia, ib, pi, pj, pa, g] = st_chain(q_true, r_body2head, r_head_nominal, cr, cm, nc, cam, img, work, ia, ib, pi, pj, pa, noisy, g)
%ST_CHAIN  The whole chain for one head: the frame rendered at the true attitude q_true (ECI to body, at the exposure) through the
%   head's true mount r_body2head (misalignment included), its spots, their directions through the pinhole and magnitudes
%   from their fluxes, identified, and the attitude with the residual check reported through the head's nominal mount
%   r_head_nominal: (q_body, solved, how many spots, identified, used); q_true when not solved.
%   length: 576
%   q_true: real[1][4] (passed a plain number)
%   r_body2head: real[1][3][3] (passed a plain number)
%   r_head_nominal: real[1][3][3] (passed a plain number)
%   cr: inout real[1][3][N_STARS] (passed a plain number)
%   cm: inout real[1][N_STARS] (passed a plain number)
%   nc: int (passed a whole number)
%   cam: StCamera (passed rec)
%   img: inout real[1][*] (passed a plain number)
%   work: inout real[1][*] (passed a plain number)
%   ia: inout int[*] (passed a whole number)
%   ib: inout int[*] (passed a whole number)
%   pi: inout int[*] (passed a whole number)
%   pj: inout int[*] (passed a whole number)
%   pa: inout real[1][*] (passed a plain number)
%   noisy: bool (passed true or false)
%   g: inout stream (passed a random stream, as six numbers)
%   returns q_body: real[1][4] (passed a plain number)
%   returns ok: bool (passed true or false)
%   returns spots: int (passed a whole number)
%   returns identified: int (passed a whole number)
%   returns used: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    q_body = zeros(4, 1);
    ok = false;
    spots = 0;
    identified = 0;
    used = 0;
    q_body = q_true;
    ok = false;
    identified = 0;
    used = 0;
    r_eh = asils.pc.mm(r_body2head, asils.models.math.dcm(q_true));
    tx = zeros(1, 1);
    ty = zeros(1, 1);
    tk = zeros(1, 1);
    [t__553, t__554, t__555, t__556, t__557, t__558, t__559, t__560] = asils.models.strender.st_render(r_eh, cr, cm, nc, cam, img, noisy, g, tx, ty, tk);
    drawn = t__553;
    cr = t__554;
    cm = t__555;
    img = t__556;
    g = t__557;
    tx = t__558;
    ty = t__559;
    tk = t__560;
    [t__561, t__562, t__563, t__564, t__565, t__566] = asils.models.stcentroid.st_centroid(img, cam, work, ia, ib);
    sp = t__561;
    ns = t__562;
    img = t__563;
    work = t__564;
    ia = t__565;
    ib = t__566;
    spots = ns;
    if (ns >= 3)
        b = zeros(32, 3);
        mag = zeros(32, 1);
        for k = (0):((ns) - 1)
            b((k) + 1, :) = asils.models.facets.unit_or_zero([((sp((k) + 1, 1) - cam.c) / cam.f); ((sp((k) + 1, 2) - cam.c) / cam.f); 1]).';
            mag((k) + 1) = (6 - (2.5 * asils.pc.log10_((asils.pc.fmax(sp((k) + 1, 3), 1) / cam.flux0))));
        end
        [t__567, t__568, t__569, t__570, t__571, t__572, t__573] = asils.models.stidentify.st_identify(b, mag, ns, pi, pj, pa, cr, cm, nc, cam.id_tol, cam.mag_tol);
        id = t__567;
        okid = t__568;
        pi = t__569;
        pj = t__570;
        pa = t__571;
        cr = t__572;
        cm = t__573;
        for k2 = (0):((ns) - 1)
            if (id((k2) + 1) >= 0)
                identified = (identified + 1);
            end
        end
        if okid
            rs = zeros(32, 3);
            ig = zeros(32, 1);
            for p = (0):((32) - 1)
                ig((p) + 1) = (-(1));
            end
            for p2 = (0):((ns) - 1)
                if (id((p2) + 1) >= 0)
                    rs((p2) + 1, :) = (cr((id((p2) + 1)) + 1, :)).'.';
                    ig((p2) + 1) = id((p2) + 1);
                end
            end
            [t__574, t__575, t__576] = asils.models.stattitude.st_attitude(b, rs, ns, ig, cam.fit_tol);
            q_eh = t__574;
            oka = t__575;
            ig = t__576;
            for p3 = (0):((ns) - 1)
                if (ig((p3) + 1) >= 0)
                    used = (used + 1);
                end
            end
            if oka
                q_body = asils.models.math.fromdcm(asils.pc.mm((r_head_nominal).', asils.models.math.dcm(q_eh)));
                ok = true;
            end
        end
    end
end
