function [ok, q, u, cr, cm, img, work, ia, ib, pi, pj, pa] = st_image(u, d, cam, valid, dq, q_old, cr, cm, nc, img, work, ia, ib, pi, pj, pa)
%ST_IMAGE  The image model's heads: each head that answers (valid) renders its frame through its true mount, the nominal head
%   frame of its boresight turned by its mount dq, at the attitude the frame saw (q_old, sttracker's st_sample), its noise
%   from the tracker's stream, and gives the attitude its chain solves (ok, q). The frame's buffers are the caller's.
%   length: 576
%   u: inout StUnit (passed rec)
%   d: StDesc (passed rec)
%   cam: StCamera (passed rec)
%   valid: bool[ST_NH] (passed true or false)
%   dq: real[1][4][ST_NH] (passed a plain number)
%   q_old: real[1][4] (passed a plain number)
%   cr: inout real[1][3][N_STARS] (passed a plain number)
%   cm: inout real[1][N_STARS] (passed a plain number)
%   nc: int (passed a whole number)
%   img: inout real[1][*] (passed a plain number)
%   work: inout real[1][*] (passed a plain number)
%   ia: inout int[*] (passed a whole number)
%   ib: inout int[*] (passed a whole number)
%   pi: inout int[*] (passed a whole number)
%   pj: inout int[*] (passed a whole number)
%   pa: inout real[1][*] (passed a plain number)
%   returns ok: bool[ST_NH] (passed true or false)
%   returns q: real[1][4][ST_NH] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    ok = zeros(2, 1);
    q = zeros(2, 4);
    t__683 = ((0):((d.nh) - 1)).';
    for h = t__683(logical(valid((t__683) + 1))).'
        rbh = asils.models.sunquad.head_frame((d.bs((h) + 1, :)).');
        rtrue = asils.pc.mm(rbh, (asils.models.math.dcm((dq((h) + 1, :)).')).');
        g = u.g;
        [t__684, t__685, t__686, t__687, t__688, t__689, t__690, t__691, t__692, t__693, t__694, t__695, t__696, t__697, t__698] = asils.models.stimage.st_chain(q_old, rtrue, rbh, cr, cm, nc, cam, img, work, ia, ib, pi, pj, pa, true, g);
        qc = t__684;
        okc = t__685;
        ns = t__686;
        nid = t__687;
        nused = t__688;
        cr = t__689;
        cm = t__690;
        img = t__691;
        work = t__692;
        ia = t__693;
        ib = t__694;
        pi = t__695;
        pj = t__696;
        pa = t__697;
        g = t__698;
        u.g = g;
        if okc
            ok((h) + 1) = true;
            q((h) + 1, :) = qc.';
        end
    end
end
