function [arm] = couple_arms(arm_short, arm_long)
%COUPLE_ARMS  The couples' arms [m] about x, y and z: the part's short arm about x, its long arm about y and about z.
%   arm_short: real[m] (passed in m)
%   arm_long: real[m] (passed in m)
%   returns arm: real[m][3] (passed in m)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    arm = zeros(3, 1);
    arm = [arm_short; arm_long; arm_long];
end
