function s = FastCtx_zero()
%FASTCTX_ZERO  a FastCtx with every field zero
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = struct();
    s.sun = zeros(3, 1);
    s.moon = zeros(3, 1);
    s.p_srp = 0;
    s.rho = 0;
end
