//! Every node's own test vectors (answers from outside the code), through the generated Rust.
//! Generated by tools/engine_build.py from design/groups/*.wire.json; do not edit.

#[test]
fn every_node_reproduces_its_own_test_vectors() {
    let v: serde_json::Value = serde_json::from_str(include_str!("fixtures.json")).unwrap();
    let mut n = 0;
    for f in v.as_array().unwrap() {
        let name = f["call"].as_str().unwrap();
        let x: Vec<f64> = f["inputs"].as_array().unwrap().iter().map(|a| a.as_f64().unwrap()).collect();
        let got = adcs_relations::dispatch::call(name, &x).unwrap_or_else(|| panic!("{name}: no such function"))[0];
        let (want, tol) = (f["expected"].as_f64().unwrap(), f["tolerance"].as_f64().unwrap());
        let err = (got - want).abs();
        assert!(err <= tol * want.abs().max(if want == 0.0 { 1.0 } else { 0.0 }),
                "{} {}: Rust gives {got:e}, the node expects {want:e} within {tol:e}", f["node"].as_str().unwrap(), f["vector"].as_str().unwrap());
        n += 1;
    }
    assert!(n > 0, "no test vector at all");
}

#[test]
fn every_function_of_the_test_apps_is_called_where_the_crate_holds_it() {
    use adcs_relations::wasm::{CALLS, NAMES};
    assert_eq!(NAMES.len(), CALLS.len());
    let groups: serde_json::Value = serde_json::from_str(include_str!("groups_vectors.json")).unwrap();
    for (n, c) in NAMES.iter().zip(CALLS) {
        let e = groups["vectors"].get(*n).unwrap_or_else(|| panic!("{n}: the groups' package drew no vector"));
        assert_eq!(groups["library"].get(*n).map(|x| x.as_str().unwrap()).unwrap_or(n), *c, "{n}: called where the crate does not hold it");
        if let Some(s) = e["sets"].as_array().unwrap().first().filter(|_| !e["proc"].as_bool().unwrap_or(false)) {
            let x: Vec<f64> = s["in"].as_array().unwrap().iter().map(|a| a.as_f64().unwrap()).collect();
            assert!(adcs_relations::dispatch::call(c, &x).is_some(), "{n}: the crate cannot call {c}");
        }
    }
}
