function [tau] = mtq_pd(q, w, q_ref, w_ref, kp, kd)
%MTQ_PD  The magnetic PD law: the error quaternion without a sign fix, its sign taken from w.
%   q: real[1][4] (passed a plain number)
%   w: real[1][3] (passed a plain number)
%   q_ref: real[1][4] (passed a plain number)
%   w_ref: real[1][3] (passed a plain number)
%   kp: real[1][3] (passed a plain number)
%   kd: real[1][3] (passed a plain number)
%   returns tau: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    tau = zeros(3, 1);
    qe = asils.alg.math.qmult(asils.alg.math.qconj(q_ref), q);
    s = sign(qe(4));
    if (s == 0)
        s = 1;
    end
    h__59 = asils.alg.math.dcm(qe);
    wr = [h__59(1, 1)*w_ref(1) + h__59(1, 2)*w_ref(2) + h__59(1, 3)*w_ref(3); h__59(2, 1)*w_ref(1) + h__59(2, 2)*w_ref(2) + h__59(2, 3)*w_ref(3); h__59(3, 1)*w_ref(1) + h__59(3, 2)*w_ref(2) + h__59(3, 3)*w_ref(3)];
    i = ((0):((3) - 1)).';
    tau((i) + 1) = (((-(reshape(kp((i) + 1), [], 1))) .* (s .* reshape(qe((i) + 1), [], 1))) - (reshape(kd((i) + 1), [], 1) .* (reshape(w((i) + 1), [], 1) - reshape(wr((i) + 1), [], 1))));
end
