function [tau] = mtq_celani(q, w, q_ref, w_ref, eps, k1, k2)
%MTQ_CELANI  P4 Celani 2015: u = -(eps^2 k1 q_v + eps k2 w_e).
%   q: real[1][4] (passed a plain number)
%   w: real[1][3] (passed a plain number)
%   q_ref: real[1][4] (passed a plain number)
%   w_ref: real[1][3] (passed a plain number)
%   eps: real[1] (passed a plain number)
%   k1: real[1] (passed a plain number)
%   k2: real[1] (passed a plain number)
%   returns tau: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    tau = zeros(3, 1);
    [qe, s, wr, we] = asils.alg.control.mtq_err(q, w, q_ref, w_ref);
    i = ((0):((3) - 1)).';
    tau((i) + 1) = (-(((((eps * eps) * k1) .* (s .* reshape(qe((i) + 1), [], 1))) + ((eps * k2) .* reshape(we((i) + 1), [], 1)))));
end
