function [valid, u] = st_head_valid(u, d, h, t, sun_b, moon_b, nadir_b, earth_ang, slow)
%ST_HEAD_VALID  Whether head h answers at t: below the largest rate (slow), not failed, not dazzled by the Sun or the Moon (sun_b,
%   moon_b, body, unit) nor blind since, and the Earth's limb (nadir_b, the Earth's half-angle earth_ang [rad]) outside
%   its exclusion. A dazzled head stays blind for the blind time.
%   u: inout StUnit (passed rec)
%   d: StDesc (passed rec)
%   h: int (passed a whole number)
%   t: real[1] (passed a plain number)
%   sun_b: real[1][3] (passed a plain number)
%   moon_b: real[1][3] (passed a plain number)
%   nadir_b: real[1][3] (passed a plain number)
%   earth_ang: real[1] (passed a plain number)
%   slow: bool (passed true or false)
%   returns valid: bool (passed true or false)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    valid = false;
    bs = (d.bs((h) + 1, :)).';
    dazzled = ((acos(asils.models.coilsat.act_clamp(asils.pc.dot_(bs, sun_b), (-(1)), 1)) <= d.sun_excl) || (acos(asils.models.coilsat.act_clamp(asils.pc.dot_(bs, moon_b), (-(1)), 1)) <= d.moon_excl));
    if dazzled
        u.blind_until((h) + 1) = (t + d.blind_s);
    end
    valid = ((((slow && (~u.dead((h) + 1))) && (~dazzled)) && (t >= u.blind_until((h) + 1))) && (acos(asils.models.coilsat.act_clamp(asils.pc.dot_(bs, nadir_b), (-(1)), 1)) > (earth_ang + d.earth_excl)));
end
