function [q] = st_slerp(a, b, s)
%ST_SLERP  The spherical linear interpolation from a to b at s, the shorter arc; above a cosine of 0.9995 the linear one, made
%   unit (la.rs slerp).
%   a: real[1][4] (passed a plain number)
%   b: real[1][4] (passed a plain number)
%   s: real[1] (passed a plain number)
%   returns q: real[1][4] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    q = zeros(4, 1);
    d = ((((a(1) * b(1)) + (a(2) * b(2))) + (a(3) * b(3))) + (a(4) * b(4)));
    bb = b;
    if (d < 0)
        d = (-(d));
        bb = [(-(b(1))); (-(b(2))); (-(b(3))); (-(b(4)))];
    end
    if (d > 0.9995)
        q = asils.models.math.qnorm([(a(1) + (s * (bb(1) - a(1)))); (a(2) + (s * (bb(2) - a(2)))); (a(3) + (s * (bb(3) - a(3)))); (a(4) + (s * (bb(4) - a(4))))]);
    else
        h__745 = acos(d);
        if ~isreal(h__745), h__745 = NaN; end
        th = h__745;
        ka = (sin(((1 - s) * th)) / sin(th));
        kb = (sin((s * th)) / sin(th));
        q = [((ka * a(1)) + (kb * bb(1))); ((ka * a(2)) + (kb * bb(2))); ((ka * a(3)) + (kb * bb(3))); ((ka * a(4)) + (kb * bb(4)))];
    end
end
