function [ok, q, valid, dq, q_old, u, ht, hq, cr, cm] = st_sample(u, d, ht, hq, hn, cr, cm, q_true, t, w, sun_b, moon_b, nadir_b, earth_ang)
%ST_SAMPLE  Each head's attitude (ECI to body) and whether it answers, for the true attitude q_true and body rate w [rad/s] at t,
%   the Sun, the Moon and nadir (body, unit) and the Earth's half-angle earth_ang [rad], from the history (ht, hq, hn) and
%   the catalogue (cr, cm). The image model's heads answer through the chain (comp.rs, S7.10): here only their validity
%   (valid), their mount (dq) and the attitude the frame saw (q_old).
%   u: inout StUnit (passed rec)
%   d: StDesc (passed rec)
%   ht: inout real[1][ST_HIST] (passed a plain number)
%   hq: inout real[1][4][ST_HIST] (passed a plain number)
%   hn: int (passed a whole number)
%   cr: inout real[1][3][N_STARS] (passed a plain number)
%   cm: inout real[1][N_STARS] (passed a plain number)
%   q_true: real[1][4] (passed a plain number)
%   t: real[1] (passed a plain number)
%   w: real[1][3] (passed a plain number)
%   sun_b: real[1][3] (passed a plain number)
%   moon_b: real[1][3] (passed a plain number)
%   nadir_b: real[1][3] (passed a plain number)
%   earth_ang: real[1] (passed a plain number)
%   returns ok: bool[ST_NH] (passed true or false)
%   returns q: real[1][4][ST_NH] (passed a plain number)
%   returns valid: bool[ST_NH] (passed true or false)
%   returns dq: real[1][4][ST_NH] (passed a plain number)
%   returns q_old: real[1][4] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    ok = zeros(2, 1);
    q = zeros(2, 4);
    valid = zeros(2, 1);
    dq = zeros(2, 4);
    q_old = zeros(4, 1);
    [t__241, t__242, t__243] = asils.models.sttracker.st_delayed(ht, hq, hn, d.latency, t, q_true);
    q_old = t__241;
    ht = t__242;
    hq = t__243;
    slow = (asils.pc.norm_(w) < d.max_rate);
    smear = (1 + (asils.pc.norm_(w) / d.noise_rate_ref));
    rold = asils.models.math.dcm(q_old);
    ok = [false; false];
    q = zeros(2, 4);
    valid = [false; false];
    dq = zeros(2, 4);
    for h = (0):((d.nh) - 1)
        [t__244, t__245] = asils.models.sttracker.st_head_valid(u, d, h, t, sun_b, moon_b, nadir_b, earth_ang, slow);
        valid((h) + 1) = t__244;
        u = t__245;
        dq((h) + 1, :) = asils.models.math.qmult((u.q_mis((h) + 1, :)).', (u.q_bias((h) + 1, :)).').';
        g = u.g;
        if (d.model == 1)
            [t__246, t__247, t__248, t__249, t__250] = asils.models.sttracker.st_quest_head(rold, (dq((h) + 1, :)).', (d.bs((h) + 1, :)).', d.fov, d.noise_cross, smear, cr, cm, valid((h) + 1), g);
            qh = t__246;
            enough = t__247;
            cr = t__248;
            cm = t__249;
            g = t__250;
            if (enough && valid((h) + 1))
                ok((h) + 1) = true;
                q((h) + 1, :) = qh.';
            end
        elseif (d.model == 0)
            [t__251, t__252] = asils.models.sttracker.st_noise_head(q_old, (dq((h) + 1, :)).', (d.bs((h) + 1, :)).', d.noise_cross, d.noise_roll, smear, g);
            qn = t__251;
            g = t__252;
            if valid((h) + 1)
                ok((h) + 1) = true;
                q((h) + 1, :) = qn.';
            end
        end
        u.g = g;
    end
end
