function s = StDesc_zero()
%STDESC_ZERO  a StDesc with every field zero
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = struct();
    s.nh = 0;
    s.bs = zeros(2, 3);
    s.noise_cross = 0;
    s.noise_roll = 0;
    s.latency = 0;
    s.max_rate = 0;
    s.sun_excl = 0;
    s.earth_excl = 0;
    s.fov = 0;
    s.model = 0;
    s.bias_sigma = 0;
    s.misalign_sigma = 0;
    s.moon_excl = 0;
    s.blind_s = 0;
    s.noise_rate_ref = 0;
end
