function [s] = fdir_safe(st)
%FDIR_SAFE  Safe mode: a magnetometer (once seen) or a gyro silent more than 60 s sets its fault bit (8 and 9)
%   and holds the spacecraft in magnetorquer detumble.
%   vectors: 48
%   st: Modes (passed rec)
%   returns s: Modes (passed rec)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = asils.groups.shared.Modes_zero();
    s = st;
    f = 0;
    if (s.mag_seen && (s.mag_age > 60))
        f = bitor(f, 256);
    end
    if (s.gyro_age > 60)
        f = bitor(f, 512);
    end
    s.faults = bitor(bitand(s.faults, bitxor(65535, bitor(256, 512))), f);
    if ((f ~= 0) && (s.mode ~= 0))
        s = asils.groups.shared.modes_enter(s, 0);
    end
end
