function [law] = fsw_bdot_law(a)
%FSW_BDOT_LAW  bdot_law: 0 gyro, 1 magnetometer (also when no detumble flies), 2 bang-bang, 3 generalised L1.
%   a: DetumbleAlg (passed a choice, as its option's number)
%   returns law: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    law = 0;
    law = 1;
    if (a == 0)
        law = 0;
    elseif (a == 2)
        law = 2;
    elseif (a == 3)
        law = 3;
    end
end
