function [law] = fsw_mtq_law(a)
%FSW_MTQ_LAW  mtq_law: 0 PD (also when no magnetic law flies), 1 LQR, 2 sliding mode, 3 rate damping, 4 Lovera-Astolfi 2004,
%   5 Celani 2015, 6 Avanzini 2021, 7 Celani 2026 boresight, 8 TANGO 2013.
%   a: MtqAlg (passed a choice, as its option's number)
%   returns law: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    law = 0;
    law = 0;
    if (a == 1)
        law = 1;
    elseif (a == 2)
        law = 2;
    elseif (a == 3)
        law = 3;
    elseif (a == 4)
        law = 4;
    elseif (a == 5)
        law = 5;
    elseif (a == 6)
        law = 6;
    elseif (a == 7)
        law = 7;
    elseif (a == 8)
        law = 8;
    end
end
