function Y = call_seq(name, X)
%CALL_SEQ  a proc called once per column of X, its state carried from each call to the next; Y has a column per call
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    st = []; Y = [];
    for c = 1:size(X, 2)
        x = X(:, c);
        switch name
            otherwise
                error('pcode:call', 'no proc %s', name);
        end
        Y = [Y, y];
    end
end
