function y = call(name, x)
%CALL  a function by its registry name (module::name), inputs and outputs flattened (row-major, SI)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    switch name
        case 'act::rotor_axes'
            [o1] = asils.groups.act.rotor_axes(x(1), reshape(x(2:25), 3, 8).', reshape(x(26:33), 8, 1), reshape(x(34:45), 3, 4).', reshape(x(46:49), 4, 1));
            y = [reshape((o1).', [], 1)];
        case 'act::det3'
            [o1] = asils.groups.act.det3(reshape(x(1:9), 3, 3).');
            y = [double(o1)];
        case 'act::inv3'
            [o1, o2] = asils.groups.act.inv3(reshape(x(1:9), 3, 3).');
            y = [reshape((o1).', [], 1); double(o2)];
        case 'act::steer_sr'
            [o1, o2] = asils.groups.act.steer_sr(reshape(x(1:3), 3, 1), reshape(x(4:27), 8, 3).', reshape(x(28:35), 8, 1), x(36), x(37), reshape(x(38:45), 8, 1), reshape(x(46:57), 3, 4).', x(58), x(59), x(60), (x(61) ~= 0));
            y = [reshape(o1, [], 1); reshape(o2, [], 1)];
        case 'act::ring_momentum'
            [o1] = asils.groups.act.ring_momentum(x(1), x(2), x(3), x(4));
            y = [double(o1)];
        case 'act::gf_6'
            [o1] = asils.groups.act.gf_6(x(1), x(2), x(3), x(4));
            y = [double(o1)];
        case 'act::spin_down_time'
            [o1] = asils.groups.act.spin_down_time(x(1), x(2), x(3));
            y = [double(o1)];
        case 'act::gf_7'
            [o1] = asils.groups.act.gf_7(x(1), x(2), x(3));
            y = [double(o1)];
        case 'act::holding_power_laminar'
            [o1] = asils.groups.act.holding_power_laminar(x(1), x(2), x(3), x(4), x(5), x(6));
            y = [double(o1)];
        case 'act::gf_8'
            [o1] = asils.groups.act.gf_8(x(1), x(2), x(3), x(4), x(5), x(6));
            y = [double(o1)];
        case 'act::pump_pressure_for_torque'
            [o1] = asils.groups.act.pump_pressure_for_torque(x(1), x(2), x(3), x(4));
            y = [double(o1)];
        case 'act::dipole_to_reject'
            [o1] = asils.groups.act.dipole_to_reject(x(1), x(2));
            y = [double(o1)];
        case 'act::gm_1'
            [o1] = asils.groups.act.gm_1(x(1), x(2));
            y = [double(o1)];
        case 'act::magnetorquer_dipole_required'
            [o1] = asils.groups.act.magnetorquer_dipole_required(x(1), x(2), x(3));
            y = [double(o1)];
        case 'act::gm_2'
            [o1] = asils.groups.act.gm_2(x(1), x(2), x(3));
            y = [double(o1)];
        case 'act::torque_authority'
            [o1] = asils.groups.act.torque_authority(x(1), x(2), x(3));
            y = [double(o1)];
        case 'act::gm_3'
            [o1] = asils.groups.act.gm_3(x(1), x(2), x(3));
            y = [double(o1)];
        case 'act::propellant_per_slew'
            [o1] = asils.groups.act.propellant_per_slew(x(1), x(2), x(3));
            y = [double(o1)];
        case 'act::propellant_per_year'
            [o1] = asils.groups.act.propellant_per_year(x(1), x(2), x(3));
            y = [double(o1)];
        case 'act::bang_bang_peak_momentum'
            [o1] = asils.groups.act.bang_bang_peak_momentum(x(1), x(2), x(3));
            y = [double(o1)];
        case 'act::gw_3'
            [o1] = asils.groups.act.gw_3(x(1), x(2), x(3));
            y = [double(o1)];
        case 'act::bang_bang_peak_torque'
            [o1] = asils.groups.act.bang_bang_peak_torque(x(1), x(2), x(3));
            y = [double(o1)];
        case 'act::gw_4'
            [o1] = asils.groups.act.gw_4(x(1), x(2), x(3));
            y = [double(o1)];
        case 'ctl::settling_time_2pct'
            [o1] = asils.groups.ctl.settling_time_2pct(x(1), x(2));
            y = [double(o1)];
        case 'env::gravity_gradient_torque_worst'
            [o1] = asils.groups.env.gravity_gradient_torque_worst(x(1), x(2), x(3));
            y = [double(o1)];
        case 'env::gd_0'
            [o1] = asils.groups.env.gd_0(x(1), x(2), x(3));
            y = [double(o1)];
        case 'env::aero_torque'
            [o1] = asils.groups.env.aero_torque(x(1), x(2), x(3), x(4), x(5));
            y = [double(o1)];
        case 'env::gd_1'
            [o1] = asils.groups.env.gd_1(x(1), x(2), x(3), x(4), x(5));
            y = [double(o1)];
        case 'env::solar_pressure_torque_at'
            [o1] = asils.groups.env.solar_pressure_torque_at(x(1), x(2), x(3), x(4));
            y = [double(o1)];
        case 'env::gd_2'
            [o1] = asils.groups.env.gd_2(x(1), x(2), x(3), x(4));
            y = [double(o1)];
        case 'env::magnetic_torque'
            [o1] = asils.groups.env.magnetic_torque(x(1), x(2));
            y = [double(o1)];
        case 'env::gd_3'
            [o1] = asils.groups.env.gd_3(x(1), x(2));
            y = [double(o1)];
        case 'env::total_disturbance_torque'
            [o1] = asils.groups.env.total_disturbance_torque(x(1), x(2), x(3), x(4));
            y = [double(o1)];
        case 'env::gd_4'
            [o1] = asils.groups.env.gd_4(x(1), x(2), x(3), x(4));
            y = [double(o1)];
        case 'env::secular_momentum_per_orbit'
            [o1] = asils.groups.env.secular_momentum_per_orbit(x(1), x(2));
            y = [double(o1)];
        case 'env::gd_5'
            [o1] = asils.groups.env.gd_5(x(1), x(2));
            y = [double(o1)];
        case 'env::radius'
            [o1] = asils.groups.env.radius(x(1));
            y = [double(o1)];
        case 'env::circular_period'
            [o1] = asils.groups.env.circular_period(x(1));
            y = [double(o1)];
        case 'env::m2_5'
            [o1] = asils.groups.env.m2_5(x(1));
            y = [double(o1)];
        case 'env::mean_motion'
            [o1] = asils.groups.env.mean_motion(x(1));
            y = [double(o1)];
        case 'env::dipole'
            [o1, o2] = asils.groups.env.dipole();
            y = [double(o1); double(o2)];
        case 'env::dipole_field_equator'
            [o1] = asils.groups.env.dipole_field_equator(x(1));
            y = [double(o1)];
        case 'env::m3_0'
            [o1] = asils.groups.env.m3_0(x(1));
            y = [double(o1)];
        case 'env::dipole_field_max'
            [o1] = asils.groups.env.dipole_field_max(x(1), x(2));
            y = [double(o1)];
        case 'env::m3_1'
            [o1] = asils.groups.env.m3_1(x(1), x(2));
            y = [double(o1)];
        case 'env::max_magnetic_latitude'
            [o1] = asils.groups.env.max_magnetic_latitude(x(1));
            y = [double(o1)];
        case 'env::density_at'
            [o1] = asils.groups.env.density_at(x(1), x(2));
            y = [double(o1)];
        case 'env::circular_speed'
            [o1] = asils.groups.env.circular_speed(x(1));
            y = [double(o1)];
        case 'env::sun_distance_au'
            [o1] = asils.groups.env.sun_distance_au(x(1));
            y = [double(o1)];
        case 'env::solar_pressure'
            [o1] = asils.groups.env.solar_pressure(x(1));
            y = [double(o1)];
        case 'env::m3_5'
            [o1] = asils.groups.env.m3_5(x(1));
            y = [double(o1)];
        case 'fdir::fdir_sensors'
            [o1, o2, o3, o4, o5, o6, o7] = asils.groups.fdir.fdir_sensors((x(1) ~= 0), reshape(x(2:4), 3, 1), (x(5) ~= 0), reshape(x(6:8), 3, 1), reshape(x(9:11), 3, 1), x(12), (x(13) ~= 0), (x(14) ~= 0), (x(15) ~= 0), reshape(x(16:18), 3, 1), x(19), x(20));
            y = [double(o1); reshape(o2, [], 1); reshape(o3, [], 1); reshape(o4, [], 1); double(o5); double(o6); double(o7)];
        case 'gdn::boresight_offset'
            [o1] = asils.groups.gdn.boresight_offset(reshape(x(1:3), 3, 1));
            y = [reshape(o1, [], 1)];
        case 'gdn::dcm'
            [o1] = asils.groups.gdn.dcm(reshape(x(1:4), 4, 1));
            y = [reshape((o1).', [], 1)];
        case 'gdn::guidance'
            [o1, o2, o3] = asils.groups.gdn.guidance(x(1), reshape(x(2:4), 3, 1), reshape(x(5:7), 3, 1), x(8), reshape(x(9:12), 4, 1), x(13), x(14), x(15), reshape(x(16:18), 3, 1), reshape(x(19:22), 4, 1), reshape(x(23:25), 3, 1), reshape(x(26:28), 3, 1), reshape(x(29:31), 3, 1), (x(32) ~= 0));
            y = [reshape(o1, [], 1); reshape(o2, [], 1); reshape(o3, [], 1)];
        case 'gdn::yaw_flip'
            [o1] = asils.groups.gdn.yaw_flip(reshape(x(1:3), 3, 1), reshape(x(4:6), 3, 1), reshape(x(7:10), 4, 1), reshape(x(11:13), 3, 1), reshape(x(14:16), 3, 1), reshape(x(17:19), 3, 1), (x(20) ~= 0), x(21));
            y = [double(o1)];
        case 'nav::latency'
            [o1] = asils.groups.nav.latency(reshape(x(1:4), 4, 1), reshape(x(5:7), 3, 1), x(8));
            y = [reshape(o1, [], 1)];
        case 'nav::mekf_predict'
            [o1, o2] = asils.groups.nav.mekf_predict(reshape(x(1:4), 4, 1), reshape(x(5:7), 3, 1), reshape(x(8:43), 6, 6).', x(44), x(45), reshape(x(46:48), 3, 1), x(49));
            y = [reshape(o1, [], 1); reshape((o2).', [], 1)];
        case 'nav::orbit_acc'
            [o1] = asils.groups.nav.orbit_acc(reshape(x(1:3), 3, 1), x(4));
            y = [reshape(o1, [], 1)];
        case 'nav::jacobi_eig4'
            [o1, o2] = asils.groups.nav.jacobi_eig4(reshape(x(1:16), 4, 4).');
            y = [reshape(o1, [], 1); reshape((o2).', [], 1)];
        case 'nav::quest'
            [o1, o2] = asils.groups.nav.quest(reshape(x(1:48), 3, 16).', reshape(x(49:96), 3, 16).', reshape(x(97:112), 16, 1), x(113));
            y = [reshape(o1, [], 1); double(o2)];
        case 'nav::gmst_rot'
            [o1] = asils.groups.nav.gmst_rot(x(1));
            y = [reshape((o1).', [], 1)];
        case 'nav::prec_rot'
            [o1] = asils.groups.nav.prec_rot(x(1));
            y = [reshape((o1).', [], 1)];
        case 'nav::eci2ecef'
            [o1] = asils.groups.nav.eci2ecef(x(1));
            y = [reshape((o1).', [], 1)];
        case 'nav::triad'
            [o1, o2] = asils.groups.nav.triad(reshape(x(1:3), 3, 1), reshape(x(4:6), 3, 1), reshape(x(7:9), 3, 1), reshape(x(10:12), 3, 1));
            y = [reshape(o1, [], 1); double(o2)];
        case 'pnt::pointing_error_rss'
            [o1] = asils.groups.pnt.pointing_error_rss(reshape(x(1:5), 5, 1));
            y = [double(o1)];
        case 'pnt::gp_5'
            [o1] = asils.groups.pnt.gp_5(reshape(x(1:5), 5, 1));
            y = [double(o1)];
        case 'risk::highest_level'
            [o1] = asils.groups.risk.highest_level(reshape(x(1:7), 7, 1));
            y = [double(o1)];
        case 'risk::rk4_0'
            [o1] = asils.groups.risk.rk4_0(reshape(x(1:7), 7, 1));
            y = [double(o1)];
        case 'risk::net_closed'
            [o1] = asils.groups.risk.net_closed(x(1), x(2));
            y = [double(o1)];
        case 'risk::share_tested'
            [o1, o2] = asils.groups.risk.share_tested(x(1), x(2));
            y = [double(o1); double(o2)];
        case 'shared::fromdcm'
            [o1] = asils.groups.shared.fromdcm(reshape(x(1:9), 3, 3).');
            y = [reshape(o1, [], 1)];
        case 'shared::fromrotvec'
            [o1] = asils.groups.shared.fromrotvec(reshape(x(1:3), 3, 1));
            y = [reshape(o1, [], 1)];
        case 'shared::qmult'
            [o1] = asils.groups.shared.qmult(reshape(x(1:4), 4, 1), reshape(x(5:8), 4, 1));
            y = [reshape(o1, [], 1)];
        case 'shared::qnorm'
            [o1] = asils.groups.shared.qnorm(reshape(x(1:4), 4, 1));
            y = [reshape(o1, [], 1)];
        case 'shared::skew'
            [o1] = asils.groups.shared.skew(reshape(x(1:3), 3, 1));
            y = [reshape((o1).', [], 1)];
        otherwise
            error('pcode:call', 'no function %s', name);
    end
end
