function [q] = st_qmethod(b, r, n)
%ST_QMETHOD  Davenport's q-method on the first n pairs: b[l] = A r[l] (unit vectors); the attitude q (ECI to body, scalar last).
%   b: real[1][3][ST_SPOTS] (passed a plain number)
%   r: real[1][3][ST_SPOTS] (passed a plain number)
%   n: int (passed a whole number)
%   returns q: real[1][4] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    q = zeros(4, 1);
    bm = zeros(3, 3);
    for l = (0):((n) - 1)
        i = ((0):((3) - 1)).';
        j = (0):((3) - 1);
        bm((i) + 1, (j) + 1) = (bm((i) + 1, (j) + 1) + ((b((l) + 1, (i) + 1)).' .* r((l) + 1, (j) + 1)));
    end
    sg = ((bm(1, 1) + bm(2, 2)) + bm(3, 3));
    z = [(bm(2, 3) - bm(3, 2)); (bm(3, 1) - bm(1, 3)); (bm(1, 2) - bm(2, 1))];
    k = zeros(4, 4);
    for i = (0):((3) - 1)
        j = ((0):((3) - 1)).';
        k((i) + 1, (j) + 1) = ((((bm((i) + 1, (j) + 1)).' + bm((j) + 1, (i) + 1)) - asils.pc.vchoose((i == j), sg, 0))).';
        k((i) + 1, 4) = z((i) + 1);
        k(4, (i) + 1) = z((i) + 1);
    end
    k(4, 4) = sg;
    [lam, v] = asils.models.math.jacobi_eig4(k);
    im = 0;
    for i = (1):((4) - 1)
        if (lam((i) + 1) > lam((im) + 1))
            im = i;
        end
    end
    q = asils.models.math.qnorm([v(1, (im) + 1); v(2, (im) + 1); v(3, (im) + 1); v(4, (im) + 1)]);
end
