function [fit] = loop_redundancy(fmr, ring_gap, spare)
%LOOP_REDUNDANCY  The fault campaign's lever (pipeline_design's node_redundancy): a family that carries fluid rings (fmr), loses a
%   requirement to a single ring's failure (ring_gap) and has no spare yet fits the spare ring, once.
%   fmr: bool (passed true or false)
%   ring_gap: bool (passed true or false)
%   spare: bool (passed true or false)
%   returns fit: bool (passed true or false)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    fit = false;
    fit = ((fmr && ring_gap) && (~spare));
end
