function [n, ek, eo, ep, ea, eb, ec, ef] = loop_robust(f_power, f_perf, f_know, fmr, coils_only, fine, has_lambda, lambda, has_fmr_scale, fmr_scale, has_mtqp_scale, mtqp_scale, star_tracker, lambda_max, scale_max, up, ek, eo, ep, ea, eb, ec, ef)
%LOOP_ROBUST  The Monte Carlo's feedback (pipeline_verify's node_robust): the selected family's lever for each class of failure in
%   the dispersed runs (power, performance, knowledge, in that order), the lever against it closed. The family (fmr: it
%   carries the fluid loop; coils_only: it is the coils-only family, whose lever is the pointing-grade coil), its class,
%   the knobs (has_*: set; else the sizing's default) and the registry's bounds and step; the events.
%   length: 8
%   f_power: bool (passed true or false)
%   f_perf: bool (passed true or false)
%   f_know: bool (passed true or false)
%   fmr: bool (passed true or false)
%   coils_only: bool (passed true or false)
%   fine: bool (passed true or false)
%   has_lambda: bool (passed true or false)
%   lambda: real[1] (passed a plain number)
%   has_fmr_scale: bool (passed true or false)
%   fmr_scale: real[1] (passed a plain number)
%   has_mtqp_scale: bool (passed true or false)
%   mtqp_scale: real[1] (passed a plain number)
%   star_tracker: bool (passed true or false)
%   lambda_max: real[1] (passed a plain number)
%   scale_max: real[1] (passed a plain number)
%   up: real[1] (passed a plain number)
%   ek: inout int[*] (passed a whole number)
%   eo: inout int[*] (passed a whole number)
%   ep: inout int[*] (passed a whole number)
%   ea: inout real[1][*] (passed a plain number)
%   eb: inout real[1][*] (passed a plain number)
%   ec: inout real[1][*] (passed a plain number)
%   ef: inout int[*] (passed a whole number)
%   returns n: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    n = 0;
    [d_k_tau, d_lambda, d_heads, d_sigma, d_grade, b0, b1, b2, b3, b4, b5, b6, b7, b8, b9] = asils.models.sizedemand.sizing_knobs();
    n = 0;
    if f_power
        if has_lambda
            h__98 = lambda;
        else
            h__98 = d_lambda;
        end
        lam = h__98;
        if (fmr && (lam < lambda_max))
            h__99 = lambda_max;
            h__100 = (lam * 3);
            if h__100 < h__99, h__99 = h__100; end
            [t__307, t__308, t__309, t__310, t__311, t__312, t__313, t__314] = asils.models.looprules.loop_event(ek, eo, ep, ea, eb, ec, ef, n, 27, (-(1)), (-(1)), lam, h__99, 0, 0);
            n = t__307;
            ek = t__308;
            eo = t__309;
            ep = t__310;
            ea = t__311;
            eb = t__312;
            ec = t__313;
            ef = t__314;
        else
            [t__315, t__316, t__317, t__318, t__319, t__320, t__321, t__322] = asils.models.looprules.loop_event(ek, eo, ep, ea, eb, ec, ef, n, 28, (-(1)), (-(1)), 0, 0, 0, 0);
            n = t__315;
            ek = t__316;
            eo = t__317;
            ep = t__318;
            ea = t__319;
            eb = t__320;
            ec = t__321;
            ef = t__322;
        end
    end
    if f_perf
        part = (-(1));
        s0 = 1;
        if fmr
            part = fix(1);
            if has_fmr_scale
                s0 = fmr_scale;
            end
        elseif coils_only
            part = fix(3);
            if has_mtqp_scale
                s0 = mtqp_scale;
            end
        end
        if ((part >= 0) && (s0 < scale_max))
            h__101 = scale_max;
            h__102 = (s0 * up);
            if h__102 < h__101, h__101 = h__102; end
            [t__323, t__324, t__325, t__326, t__327, t__328, t__329, t__330] = asils.models.looprules.loop_event(ek, eo, ep, ea, eb, ec, ef, n, 29, (-(1)), part, s0, h__101, 0, 0);
            n = t__323;
            ek = t__324;
            eo = t__325;
            ep = t__326;
            ea = t__327;
            eb = t__328;
            ec = t__329;
            ef = t__330;
        else
            [t__331, t__332, t__333, t__334, t__335, t__336, t__337, t__338] = asils.models.looprules.loop_event(ek, eo, ep, ea, eb, ec, ef, n, 30, (-(1)), part, 0, 0, 0, 0);
            n = t__331;
            ek = t__332;
            eo = t__333;
            ep = t__334;
            ea = t__335;
            eb = t__336;
            ec = t__337;
            ef = t__338;
        end
    end
    if f_know
        if ((~star_tracker) && (~fine))
            [t__339, t__340, t__341, t__342, t__343, t__344, t__345, t__346] = asils.models.looprules.loop_event(ek, eo, ep, ea, eb, ec, ef, n, 31, (-(1)), (-(1)), 0, 0, 0, 0);
            n = t__339;
            ek = t__340;
            eo = t__341;
            ep = t__342;
            ea = t__343;
            eb = t__344;
            ec = t__345;
            ef = t__346;
        else
            [t__347, t__348, t__349, t__350, t__351, t__352, t__353, t__354] = asils.models.looprules.loop_event(ek, eo, ep, ea, eb, ec, ef, n, 32, (-(1)), (-(1)), 0, 0, 0, 0);
            n = t__347;
            ek = t__348;
            eo = t__349;
            ep = t__350;
            ea = t__351;
            eb = t__352;
            ec = t__353;
            ef = t__354;
        end
    end
end
