function [rv, vval, vrate] = loop_rate_violation(vval, vrate, nv)
%LOOP_RATE_VIOLATION  The rate-stability violation of an iteration: the sum, over its options in the loop's order and each option's
%   violations in order (vval, those of a rate-stability metric flagged vrate), of each capped at 10.
%   length: 16
%   vval: inout real[1][*] (passed a plain number)
%   vrate: inout int[*] (passed a whole number)
%   nv: int (passed a whole number)
%   returns rv: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    rv = 0;
    rv = 0;
    h__53 = nv;
    h__54 = numel(vval);
    if h__54 < h__53, h__53 = h__54; end
    for i = (0):((h__53) - 1)
        if (vrate((i) + 1) == 1)
            h__55 = vval((i) + 1);
            h__56 = 10;
            if h__56 < h__55, h__55 = h__56; end
            rv = (rv + h__55);
        end
    end
end
