function [p] = loop_part(a)
%LOOP_PART  The part (its Part's number) that gives an option of actuator a (its Actuator's number) its authority: the
%   pointing-grade coil for the coils, else the actuator's.
%   a: int (passed a whole number)
%   returns p: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    p = 0;
    p = fix(3);
    if (a == fix(1))
        p = fix(5);
    elseif (a == fix(2))
        p = fix(0);
    elseif (a == fix(3))
        p = fix(6);
    elseif (a == fix(4))
        p = fix(1);
    elseif (a == fix(5))
        p = fix(4);
    end
end
