function [n, ek, eo, ep, ea, eb, ec, ef] = loop_robust(f_power, f_perf, f_know, fmr, coils_only, fine, has_lambda, lambda, has_fmr_scale, fmr_scale, has_mtqp_scale, mtqp_scale, star_tracker, lambda_max, scale_max, up, ek, eo, ep, ea, eb, ec, ef)
%LOOP_ROBUST  The Monte Carlo's feedback (pipeline_verify's node_robust): the selected family's lever for each class of failure in
%   the dispersed runs (power, performance, knowledge, in that order), the lever against it closed. The family (fmr: it
%   carries the fluid loop; coils_only: it is the coils-only family, whose lever is the pointing-grade coil), its class,
%   the knobs (has_*: set; else the sizing's default) and the registry's bounds and step; the events.
%   length: 8
%   f_power: bool (passed true or false)
%   f_perf: bool (passed true or false)
%   f_know: bool (passed true or false)
%   fmr: bool (passed true or false)
%   coils_only: bool (passed true or false)
%   fine: bool (passed true or false)
%   has_lambda: bool (passed true or false)
%   lambda: real[1] (passed a plain number)
%   has_fmr_scale: bool (passed true or false)
%   fmr_scale: real[1] (passed a plain number)
%   has_mtqp_scale: bool (passed true or false)
%   mtqp_scale: real[1] (passed a plain number)
%   star_tracker: bool (passed true or false)
%   lambda_max: real[1] (passed a plain number)
%   scale_max: real[1] (passed a plain number)
%   up: real[1] (passed a plain number)
%   ek: inout int[*] (passed a whole number)
%   eo: inout int[*] (passed a whole number)
%   ep: inout int[*] (passed a whole number)
%   ea: inout real[1][*] (passed a plain number)
%   eb: inout real[1][*] (passed a plain number)
%   ec: inout real[1][*] (passed a plain number)
%   ef: inout int[*] (passed a whole number)
%   returns n: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    n = 0;
    [d_k_tau, d_lambda, d_heads, d_sigma, d_grade, b0, b1, b2, b3, b4, b5, b6, b7, b8, b9] = asils.models.sizedemand.sizing_knobs();
    n = 0;
    if f_power
        lam = asils.pc.choose(has_lambda, lambda, d_lambda);
        if (fmr && (lam < lambda_max))
            [t__306, t__307, t__308, t__309, t__310, t__311, t__312, t__313] = asils.models.looprules.loop_event(ek, eo, ep, ea, eb, ec, ef, n, 27, (-(1)), (-(1)), lam, asils.pc.fmin(lambda_max, (lam * 3)), 0, 0);
            n = t__306;
            ek = t__307;
            eo = t__308;
            ep = t__309;
            ea = t__310;
            eb = t__311;
            ec = t__312;
            ef = t__313;
        else
            [t__314, t__315, t__316, t__317, t__318, t__319, t__320, t__321] = asils.models.looprules.loop_event(ek, eo, ep, ea, eb, ec, ef, n, 28, (-(1)), (-(1)), 0, 0, 0, 0);
            n = t__314;
            ek = t__315;
            eo = t__316;
            ep = t__317;
            ea = t__318;
            eb = t__319;
            ec = t__320;
            ef = t__321;
        end
    end
    if f_perf
        part = (-(1));
        s0 = 1;
        if fmr
            part = fix(1);
            if has_fmr_scale
                s0 = fmr_scale;
            end
        elseif coils_only
            part = fix(3);
            if has_mtqp_scale
                s0 = mtqp_scale;
            end
        end
        if ((part >= 0) && (s0 < scale_max))
            [t__322, t__323, t__324, t__325, t__326, t__327, t__328, t__329] = asils.models.looprules.loop_event(ek, eo, ep, ea, eb, ec, ef, n, 29, (-(1)), part, s0, asils.pc.fmin(scale_max, (s0 * up)), 0, 0);
            n = t__322;
            ek = t__323;
            eo = t__324;
            ep = t__325;
            ea = t__326;
            eb = t__327;
            ec = t__328;
            ef = t__329;
        else
            [t__330, t__331, t__332, t__333, t__334, t__335, t__336, t__337] = asils.models.looprules.loop_event(ek, eo, ep, ea, eb, ec, ef, n, 30, (-(1)), part, 0, 0, 0, 0);
            n = t__330;
            ek = t__331;
            eo = t__332;
            ep = t__333;
            ea = t__334;
            eb = t__335;
            ec = t__336;
            ef = t__337;
        end
    end
    if f_know
        if ((~star_tracker) && (~fine))
            [t__338, t__339, t__340, t__341, t__342, t__343, t__344, t__345] = asils.models.looprules.loop_event(ek, eo, ep, ea, eb, ec, ef, n, 31, (-(1)), (-(1)), 0, 0, 0, 0);
            n = t__338;
            ek = t__339;
            eo = t__340;
            ep = t__341;
            ea = t__342;
            eb = t__343;
            ec = t__344;
            ef = t__345;
        else
            [t__346, t__347, t__348, t__349, t__350, t__351, t__352, t__353] = asils.models.looprules.loop_event(ek, eo, ep, ea, eb, ec, ef, n, 32, (-(1)), (-(1)), 0, 0, 0, 0);
            n = t__346;
            ek = t__347;
            eo = t__348;
            ep = t__349;
            ea = t__350;
            eb = t__351;
            ec = t__352;
            ef = t__353;
        end
    end
end
