function [cp, ct] = panel_coeffs(model, s, delta, g, talt, n_o)
%PANEL_COEFFS  drag.panelCoeffs(model, s, delta, gsi) with the gas temperature talt and the atomic oxygen's density n_o.
%   model: PanelModel (passed a choice, as its option's number)
%   s: real[1] (passed a plain number)
%   delta: real[1] (passed a plain number)
%   g: Gsi (passed rec)
%   talt: real[1] (passed a plain number)
%   n_o: real[1] (passed a plain number)
%   returns cp: real[1] (passed a plain number)
%   returns ct: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    cp = 0;
    ct = 0;
    if (model == 0)
        [t__403, t__404] = asils.models.gsi.sentman(s, delta, g.a_t, g.tw, talt);
        cp = t__403;
        ct = t__404;
    elseif (model == 1)
        [t__405, t__406] = asils.models.gsi.dria(s, delta, n_o, talt, g.tw);
        cp = t__405;
        ct = t__406;
    elseif (model == 3)
        [t__407, t__408] = asils.models.gsi.cll(s, delta, g.sig_n, g.sig_t, g.tw, talt);
        cp = t__407;
        ct = t__408;
    else
        [t__409, t__410] = asils.models.gsi.sentman(s, delta, asils.models.gsi.sesam(n_o, talt), g.tw, talt);
        cp = t__409;
        ct = t__410;
    end
end
