function [drawn, cr, cm, img, g, tx, ty, tk] = st_render(r_eh, cr, cm, nc, cam, img, noisy, g, tx, ty, tk)
%ST_RENDER  The frame the detector reads at the head attitude r_eh (ECI to head): every one of the first nc catalogue stars (cr, cm)
%   within the field's diagonal through the pinhole, more than 5 pixels inside the edge, its flux spread by the PSF over the
%   9 x 9 pixels round it, on the background; when noisy, shot and read noise on every pixel from g. Into img (n x n,
%   column by column). The stars drawn: how many, and the first as many as tk holds (x, y, catalogue index) into tx, ty, tk.
%   length: 576
%   r_eh: real[1][3][3] (passed a plain number)
%   cr: inout real[1][3][N_STARS] (passed a plain number)
%   cm: inout real[1][N_STARS] (passed a plain number)
%   nc: int (passed a whole number)
%   cam: StCamera (passed rec)
%   img: inout real[1][*] (passed a plain number)
%   noisy: bool (passed true or false)
%   g: inout stream (passed a random stream, as six numbers)
%   tx: inout real[1][*] (passed a plain number)
%   ty: inout real[1][*] (passed a plain number)
%   tk: inout int[*] (passed a whole number)
%   returns drawn: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    drawn = 0;
    n = cam.n;
    np = (n * n);
    nf = n;
    for l = (0):((np) - 1)
        img((l) + 1) = cam.bg;
    end
    cmin = cos((cam.fov * sqrt(2)));
    s2 = ((2 * cam.psf_px) * cam.psf_px);
    drawn = 0;
    for k = (0):((nc) - 1)
        v = asils.pc.mv(r_eh, (cr((k) + 1, :)).');
        if (v(3) > cmin)
            x = (((cam.f * v(1)) / v(3)) + cam.c);
            y = (((cam.f * v(2)) / v(3)) + cam.c);
            if (~((((x < 6) || (y < 6)) || (x > (nf - 5))) || (y > (nf - 5))))
                fl = (cam.flux0 * (10)^(((-(0.4)) * (cm((k) + 1) - 6))));
                rx = round(x);
                ry = round(y);
                w = zeros(9, 9);
                sum = 0;
                for c = (0):((9) - 1)
                    for rr = (0):((9) - 1)
                        gx = (c - 4);
                        gy = (rr - 4);
                        dx = ((rx + gx) - x);
                        dy = ((ry + gy) - y);
                        w((c) + 1, (rr) + 1) = exp(((-(((dx * dx) + (dy * dy)))) / s2));
                        sum = (sum + w((c) + 1, (rr) + 1));
                    end
                end
                ix = fix(rx);
                iy = fix(ry);
                for c2 = (0):((9) - 1)
                    for r2 = (0):((9) - 1)
                        l2 = (((((ix + c2) - 4) - 1) * n) + (((iy + r2) - 4) - 1));
                        img((l2) + 1) = (img((l2) + 1) + (fl * (w((c2) + 1, (r2) + 1) / sum)));
                    end
                end
                if (drawn < numel(tk))
                    tx((drawn) + 1) = x;
                    ty((drawn) + 1) = y;
                    tk((drawn) + 1) = k;
                end
                drawn = (drawn + 1);
            end
        end
    end
    if noisy
        for l3 = (0):((np) - 1)
            v3 = img((l3) + 1);
            [t__287, t__288] = asils.pc.stream_normal(g);
            n1 = t__287;
            g = t__288;
            [t__289, t__290] = asils.pc.stream_normal(g);
            n2 = t__289;
            g = t__290;
            img((l3) + 1) = ((v3 + (sqrt(asils.pc.fmax(v3, 0)) * n1)) + (cam.read_noise * n2));
        end
    end
end
