function [ap] = kp2ap(kp)
%KP2AP  kp2ap (atmos.spaceweather): the nearest node of the standard table, Kp clamped to [0, 9].
%   kp: real[1] (passed a plain number)
%   returns ap: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    ap = 0;
    if isnan(kp)
        ap = NaN;
    else
        h__497 = kp;
        h__498 = 9;
        if h__498 < h__497, h__497 = h__498; end
        h__499 = h__497;
        h__500 = 0;
        if h__500 > h__499, h__499 = h__500; end
        ap = asils.models.swindex.kp_ap_nearest(true, h__499);
    end
end
