function s = SwManual_zero()
%SWMANUAL_ZERO  a SwManual with every field zero
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = struct();
    s.f107 = 0;
    s.f107a = 0;
    s.kp_is_array = false;
    s.kp = 0;
    s.akp = zeros(4, 1);
    s.ap = 0;
    s.ap3 = 0;
    s.aph = zeros(7, 1);
    s.f107_today = 0;
end
