function [half] = rotor_vscmg(u)
%ROTOR_VSCMG  Whether use u runs the rotor at the catalogue's VSCMG momentum in place of its datasheet momentum.
%   u: RotorUse (passed a choice, as its option's number)
%   returns half: bool (passed true or false)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    half = false;
    half = (u == 2);
end
