function [c] = kpi_max(a, b)
%KPI_MAX  The larger of a and b as the code's f64::max takes it: a value that is not a number left out, equal values the first.
%   a: real[1] (passed a plain number)
%   b: real[1] (passed a plain number)
%   returns c: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    c = 0;
    if isnan(a)
        c = b;
    else
        c = asils.pc.fmax(a, b);
    end
end
