function [v, t, x] = kpi_time_to(t, x, n, thr, hold)
%KPI_TIME_TO  The first time [s] at which the channel x[0..n] (at times t [s]) goes below thr and stays below it for hold [s] or
%   more; nan if it never does.
%   length: 64
%   t: inout real[1][*] (passed a plain number)
%   x: inout real[1][*] (passed a plain number)
%   n: int (passed a whole number)
%   thr: real[1] (passed a plain number)
%   hold: real[1] (passed a plain number)
%   returns v: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    v = 0;
    v = NaN;
    found = false;
    start = 0;
    inrun = false;
    for k = (0):((n) - 1)
        if (~found)
            if (x((k) + 1) < thr)
                if (~inrun)
                    start = k;
                    inrun = true;
                end
                ends = (k == (n - 1));
                if (~ends)
                    ends = (~(x(((k + 1)) + 1) < thr));
                end
                if ends
                    if ((t((k) + 1) - t((start) + 1)) >= hold)
                        v = t((start) + 1);
                        found = true;
                    end
                    inrun = false;
                end
            else
                inrun = false;
            end
        end
    end
end
