function [passes, x, tmp] = kpi_sort(x, m, tmp)
%KPI_SORT  x[0..m] in ascending order, equal values in the order given (the code's stable sort): a bottom-up merge sort (Knuth,
%   The Art of Computer Programming 3, 5.2.4) over tmp. How many passes.
%   length: 64
%   x: inout real[1][*] (passed a plain number)
%   m: int (passed a whole number)
%   tmp: inout real[1][*] (passed a plain number)
%   returns passes: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    passes = 0;
    passes = 0;
    wd = 1;
    for it = (0):((62) - 1)
        if (wd < m)
            if (rem(passes, 2) == 0)
                [t__439, t__440, t__441] = asils.models.kpistats.kpi_merge(x, tmp, m, wd);
                z0 = t__439;
                x = t__440;
                tmp = t__441;
            else
                [t__442, t__443, t__444] = asils.models.kpistats.kpi_merge(tmp, x, m, wd);
                z1 = t__442;
                tmp = t__443;
                x = t__444;
            end
            passes = (passes + 1);
            wd = (2 * wd);
        end
    end
    if (rem(passes, 2) == 1)
        for i = (0):((m) - 1)
            x((i) + 1) = tmp((i) + 1);
        end
    end
end
