function [v, x, w, tmp] = kpi_statistic(x, n, st, w, tmp)
%KPI_STATISTIC  The statistic st of the finite values among x[0..n] (copied into w; tmp the sort's).
%   length: 64
%   x: inout real[1][*] (passed a plain number)
%   n: int (passed a whole number)
%   st: MetricStat (passed a choice, as its option's number)
%   w: inout real[1][*] (passed a plain number)
%   tmp: inout real[1][*] (passed a plain number)
%   returns v: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    v = 0;
    m = 0;
    for i = (0):((n) - 1)
        if isfinite(x((i) + 1))
            w((m) + 1) = x((i) + 1);
            m = (m + 1);
        end
    end
    [t__458, t__459, t__460] = asils.models.kpistats.kpi_stat_of(w, m, st, tmp);
    v = t__458;
    w = t__459;
    tmp = t__460;
end
