function [s] = default_forces()
%DEFAULT_FORCES  config.defaultConfig's force set: the SILS set on the exponential atmosphere, the solar pressure's Cr 1.3.
%   returns s: ForceSet (passed rec)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = asils.models.forcemodel.ForceSet_zero();
    s = asils.models.forcemodel.sils_forces(1.3);
    s.drag_atmos = 0;
end
