function [a] = empirical_accel(r, v, acc)
%EMPIRICAL_ACCEL  An empirical constant acceleration acc (radial, along-track, cross-track [m/s^2]) in ECI at r, v.
%   r: real[1][3] (passed a plain number)
%   v: real[1][3] (passed a plain number)
%   acc: real[1][3] (passed a plain number)
%   returns a: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    a = zeros(3, 1);
    nr = asils.pc.norm_(r);
    rr = [(r(1) * (1 / nr)); (r(2) * (1 / nr)); (r(3) * (1 / nr))];
    h = asils.pc.cross_(r, v);
    nh = asils.pc.norm_(h);
    nn = [(h(1) * (1 / nh)); (h(2) * (1 / nh)); (h(3) * (1 / nh))];
    tt = asils.pc.cross_(nn, rr);
    a = zeros(3, 1);
    for i = (0):((3) - 1)
        a((i) + 1) = (((acc(1) * rr((i) + 1)) + (acc(2) * tt((i) + 1))) + (acc(3) * nn((i) + 1)));
    end
end
