function [sun, p_srp, moon] = no_ephem_env()
%NO_EPHEM_ENV  The environment an orbit node carries when no force needs the ephemeris (asils.orbit.node): the Sun at 1.496e11 m
%   and the Moon at 3.84e8 m along x, the solar pressure 4.56e-6 N/m^2.
%   returns sun: real[1][3] (passed a plain number)
%   returns p_srp: real[1] (passed a plain number)
%   returns moon: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    sun = zeros(3, 1);
    p_srp = 0;
    moon = zeros(3, 1);
    sun = [149600000000; 0; 0];
    p_srp = 0.00000456;
    moon = [384000000; 0; 0];
end
