function [r, v] = pop_coe2rv(a, e, inc, raan, argp, nu, mu)
%POP_COE2RV  op.coe2rv(a, e, i, RAAN, w, nu, mu): classical elements [m, rad] to an ECI position and velocity (closed orbits).
%   a: real[1] (passed a plain number)
%   e: real[1] (passed a plain number)
%   inc: real[1] (passed a plain number)
%   raan: real[1] (passed a plain number)
%   argp: real[1] (passed a plain number)
%   nu: real[1] (passed a plain number)
%   mu: real[1] (passed a plain number)
%   returns r: real[1][3] (passed a plain number)
%   returns v: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    r = zeros(3, 1);
    v = zeros(3, 1);
    p = (a * (1 - asils.pc.ipow(e, 2)));
    rmag = (p / (1 + (e * cos(nu))));
    r_pf = [(rmag * cos(nu)); (rmag * sin(nu)); 0];
    k = asils.pc.sqrt_((mu / p));
    v_pf = [(k * (-(sin(nu)))); (k * (e + cos(nu))); 0];
    co = cos(raan);
    so = sin(raan);
    ci = cos(inc);
    si = sin(inc);
    cw = cos(argp);
    sw = sin(argp);
    q = [([((co * cw) - ((so * sw) * ci)); (((-(co)) * sw) - ((so * cw) * ci)); (so * si)]).'; ([((so * cw) + ((co * sw) * ci)); (((-(so)) * sw) + ((co * cw) * ci)); ((-(co)) * si)]).'; ([(sw * si); (cw * si); ci]).'];
    r = asils.pc.mv(q, r_pf);
    v = asils.pc.mv(q, v_pf);
end
