function [r, v] = pop_coe2rv(a, e, inc, raan, argp, nu, mu)
%POP_COE2RV  op.coe2rv(a, e, i, RAAN, w, nu, mu): classical elements [m, rad] to an ECI position and velocity (closed orbits).
%   a: real[1] (passed a plain number)
%   e: real[1] (passed a plain number)
%   inc: real[1] (passed a plain number)
%   raan: real[1] (passed a plain number)
%   argp: real[1] (passed a plain number)
%   nu: real[1] (passed a plain number)
%   mu: real[1] (passed a plain number)
%   returns r: real[1][3] (passed a plain number)
%   returns v: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    r = zeros(3, 1);
    v = zeros(3, 1);
    p = (a * (1 - (e * e)));
    rmag = (p / (1 + (e * cos(nu))));
    r_pf = [(rmag * cos(nu)); (rmag * sin(nu)); 0];
    h__262 = (mu / p);
    if h__262 < 0, h__262 = NaN; else, h__262 = sqrt(h__262); end
    k = h__262;
    v_pf = [(k * (-(sin(nu)))); (k * (e + cos(nu))); 0];
    co = cos(raan);
    so = sin(raan);
    ci = cos(inc);
    si = sin(inc);
    cw = cos(argp);
    sw = sin(argp);
    q = [([((co * cw) - ((so * sw) * ci)); (((-(co)) * sw) - ((so * cw) * ci)); (so * si)]).'; ([((so * cw) + ((co * sw) * ci)); (((-(so)) * sw) + ((co * cw) * ci)); ((-(co)) * si)]).'; ([(sw * si); (cw * si); ci]).'];
    r = [q(1, 1)*r_pf(1) + q(1, 2)*r_pf(2) + q(1, 3)*r_pf(3); q(2, 1)*r_pf(1) + q(2, 2)*r_pf(2) + q(2, 3)*r_pf(3); q(3, 1)*r_pf(1) + q(3, 2)*r_pf(2) + q(3, 3)*r_pf(3)];
    v = [q(1, 1)*v_pf(1) + q(1, 2)*v_pf(2) + q(1, 3)*v_pf(3); q(2, 1)*v_pf(1) + q(2, 2)*v_pf(2) + q(2, 3)*v_pf(3); q(3, 1)*v_pf(1) + q(3, 2)*v_pf(2) + q(3, 3)*v_pf(3)];
end
