function [s] = sils_forces(cr)
%SILS_FORCES  The SILS force set of asils.orbit.init, the solar pressure's Cr given: the degree and order 6 field, Battin's Sun and
%   Moon, cannonball drag in DTM2020 with the air turning with the Earth (forces.drag's gsi), cannonball solar pressure
%   in the conical shadow; no Earth radiation, relativity, tides or empirical acceleration.
%   cr: real[1] (passed a plain number)
%   returns s: ForceSet (passed rec)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = asils.models.forcemodel.ForceSet_zero();
    s = asils.models.forcemodel.ForceSet_zero();
    s.grav_model = 2;
    s.grav_degree = 6;
    s.has_grav_order = true;
    s.grav_order = 6;
    s.tb_on = true;
    s.tb_model = 0;
    s.tb_nmax = 4;
    s.drag_on = true;
    s.drag_model = 0;
    s.drag_panel = 0;
    s.drag_atmos = 3;
    s.has_drag_cd = false;
    s.drag_corotate = true;
    s.drag_gsi = asils.models.gsi.gsi_default();
    s.srp_on = true;
    s.srp_model = 0;
    s.srp_eclipse = 1;
    s.has_srp_cr = true;
    s.srp_cr = cr;
end
