function [r, v, raan] = sso_initial(sun_unit, alt_km, ecc, inc_deg, ltan_h, argp_deg, u0_deg)
%SSO_INITIAL  The orbit geometry of asils.orbit.init: a = Re + alt, the RAAN from the LTAN and the Sun's right ascension (its unit
%   vector at the epoch, DE440), the argument of latitude u0 [deg]: the state and the RAAN [rad].
%   sun_unit: real[1][3] (passed a plain number)
%   alt_km: real[1] (passed a plain number)
%   ecc: real[1] (passed a plain number)
%   inc_deg: real[1] (passed a plain number)
%   ltan_h: real[1] (passed a plain number)
%   argp_deg: real[1] (passed a plain number)
%   u0_deg: real[1] (passed a plain number)
%   returns r: real[1][3] (passed a plain number)
%   returns v: real[1][3] (passed a plain number)
%   returns raan: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    r = zeros(3, 1);
    v = zeros(3, 1);
    raan = 0;
    k = asils.models.de440.de440_constants();
    a = (k.re_earth + (alt_km * 1000));
    inc = ((inc_deg * pi) / 180);
    ra_sun = atan2(sun_unit(2), sun_unit(1));
    raan = asils.models.timescales.omod((ra_sun + ((((ltan_h - 12) * 15) * pi) / 180)), (2 * pi));
    [t__60, t__61] = asils.models.forcemodel.pop_coe2rv(a, ecc, inc, raan, ((argp_deg * pi) / 180), ((u0_deg * pi) / 180), k.mu_earth);
    r = t__60;
    v = t__61;
end
