function s = GyroUnit_zero()
%GYROUNIT_ZERO  a GyroUnit with every field zero
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = struct();
    s.m = zeros(3, 3);
    s.b = zeros(3, 1);
    s.brw = zeros(3, 1);
    s.g = zeros(6, 1);
end
