#!/usr/bin/env python3
"""docs/NODES.md and docs/CATALOGUE.md from the node registry and the datasheet catalogue.

    python3 tools/nodes_doc.py

matlab_sils/data/pipeline/nodes.json is the single definition of every node (what it reads,
writes, runs with and decides); matlab_sils/data/catalogue/*.json holds the bought actuators as
their datasheets state them. Both documents are generated, never typed.
Copyright (c) 2026 Agastya. All rights reserved.
"""
import json
from common import write_text, ROOT

DATA = ROOT / "matlab_sils" / "data"


def fmt(v):
    if isinstance(v, dict):
        return "<br>".join(f"{k}: {fmt(x)}" for k, x in v.items())
    if isinstance(v, list) and v and all(isinstance(x, dict) for x in v):     # a list of records: one per line
        return "<br>".join("; ".join(f"{k} {fmt(y)}" for k, y in x.items()) for x in v)
    if isinstance(v, list):
        return ", ".join(fmt(x) for x in v)
    return str(v)


def nodes_md():
    R = json.loads((DATA / "pipeline" / "nodes.json").read_text())
    L = ["# Nodes of the design loop and verification chain", "",
         "**Owner: Agastya.** Generated by `tools/nodes_doc.py` from `matlab_sils/data/pipeline/nodes.json`; "
         "`tools/pipeline.py` reads its parameters from the same file.", "",
         R["about"], "", "![From customer case to flight](figures/flow_design_to_hils.svg)", "",
         "| # | node | stage | runs in | inputs | outputs |", "|---:|---|---|---|---|---|"]
    for i, n in enumerate(R["nodes"], 1):
        L.append(f"| {i} | [`{n['id']}`](#{n['id']}) | {n['stage']} | {n['runs_in']} | {'<br>'.join(n['inputs']) or '—'} | {'<br>'.join(n['outputs'])} |")
    for n in R["nodes"]:
        L += ["", f"## {n['id']}", "", n["does"], "", f"- **Stage:** {n['stage']}. **Runs in:** {n['runs_in']}.",
              f"- **Inputs:** {', '.join(n['inputs']) or 'none'}.", f"- **Outputs:** {', '.join(n['outputs'])}."]
        if n["parameters"]:
            L += ["", "| parameter | value |", "|---|---|"] + [f"| `{k}` | {fmt(v)} |" for k, v in n["parameters"].items()]
        if n["rules"]:
            L += ["", "Rules:", ""] + [f"- {r}" for r in n["rules"]]
    write_text(ROOT / "docs" / "NODES.md", "\n".join(L) + "\n")


def catalogue_md():
    files = sorted((DATA / "catalogue").glob("*.json"))
    L = ["# Actuator catalogue (bought parts, from datasheets)", "",
         "**Owner: Agastya.** Generated by `tools/nodes_doc.py` from `matlab_sils/data/catalogue/*.json`. "
         "Reaction wheels, CMGs and VSCMGs are bought, not designed: the `select_rotor` node (docs/NODES.md) "
         "picks the lightest model that meets the case's demand. We design only the magnetorquers, the fluid "
         "loop and the RCS.", "",
         "Numbers are the vendor's (`datasheet`); what the engine needs but a datasheet omits is `derived` in each "
         "file, with its rule. Null means not stated.", "",
         "| vendor | model | type | h [mNms] | torque [mNm] | speed [rpm] | mass [g] | power steady [W] | power peak [W] | size [mm] | source |",
         "|---|---|---|---:|---:|---:|---:|---:|---:|---|---|"]
    g = lambda d, k: "—" if d.get(k) is None else f"{d[k]:g}" if isinstance(d[k], (int, float)) else str(d[k])
    for f in files:
        c = json.loads(f.read_text())
        d = c["datasheet"]
        L.append(f"| {c['vendor']} | {c['model']} | {c['type']} | {g(d, 'h_mNms')} | {g(d, 'torque_mNm')} | {g(d, 'speed_max_rpm')} | "
                 f"{g(d, 'mass_g')} | {g(d, 'power_steady_W')} | {g(d, 'power_peak_W')} | {g(d, 'dims_mm')} | "
                 f"[{c['source_kind']}]({c['source_url']}) |")
    L += ["", "## Derived modelling values", "", "| model | rotor inertia [kg m2] | volume [L] | per-unit mass for the budget [kg] | notes |", "|---|---:|---:|---:|---|"]
    for f in files:
        c = json.loads(f.read_text())
        m = c["derived"]
        L.append(f"| {c['model']} | {m.get('rotor_inertia_kgm2', 0):.3g} | {m.get('volume_L', 0):.3g} | {m.get('mass_kg', 0):.3g} | {'; '.join(c.get('assumptions', []))} |")
    write_text(ROOT / "docs" / "CATALOGUE.md", "\n".join(L) + "\n")


if __name__ == "__main__":
    nodes_md()
    if (DATA / "catalogue").exists():
        catalogue_md()
    print("wrote docs/NODES.md" + (", docs/CATALOGUE.md" if (DATA / "catalogue").exists() else ""))
