#!/usr/bin/env python3
"""The node app's catalogue (docs/RELEASE_PLAN.md P5): what a node may declare and read, from the
spec package, as a browser module.

    python3 tools/node_catalog.py [--check]     write (or check) design/js/node_catalog.js

It holds the units and the quantities each may express (spec/plan/units.toml), the physics
functions (physics.toml), the sources, the simulator's metrics and the verification rungs, the
belief areas and statuses, the test-vector provenances the checker accepts, and every tree row of
layers 1 and 2 with its spec kind, quantity and unit (spec/tools/plan_model.py catalog(), the same
pick-lists the spec's node form uses), so the node app checks what the checker (spec/tools/intake.py)
will check, while the person types.

Owner: Agastya. Copyright (c) 2026 Agastya. All rights reserved.
"""
import argparse
import json
import sys

from common import ROOT, V1, write_text

sys.path.insert(0, str(V1 / "spec" / "tools"))
import plan_model as pm  # noqa: E402

OUT = ROOT / "design" / "js" / "node_catalog.js"


def catalogue():
    c = pm.Plan().catalog()
    return {
        "units": [[n, sym, q] for n, sym, q, _note in c["units"]],
        "quantities": c["quantities"],
        "physics": [[n, args] for n, args, _src in c["physics"]],
        "sources": [[i, t] for i, t, _u in c["sources"]],
        "metrics": sorted(c["metrics"]) if not isinstance(c["metrics"], dict) else sorted(c["metrics"]),
        "rungs": c["rungs"], "provenance": c["provenance"], "areas": c["areas"], "belief_statuses": c["belief_statuses"],
        "tags": c["tags"],
        # tree id -> [label, spec kind, quantity, unit, layer]
        "rows": {n[1]: [n[2], n[7], n[3], n[4], n[5]] for n in c["nodes"]},
    }


def text():
    body = json.dumps(catalogue(), ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return ("// Generated by tools/node_catalog.py from spec/plan (units, physics, sources, tree); do not edit.\n"
            "// What a node may declare and read: the node app checks it as the spec's checker will.\n"
            f"export const CATALOG = {body};\n")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="exit 1 if design/js/node_catalog.js is not current")
    a = ap.parse_args(argv)
    t = text()
    if a.check:
        ok = OUT.is_file() and OUT.read_text() == t
        print(f"node_catalog: {OUT.relative_to(ROOT)} {'is current' if ok else 'is stale: run python3 tools/node_catalog.py'}")
        return 0 if ok else 1
    write_text(OUT, t)
    print(f"node_catalog: wrote {OUT.relative_to(ROOT)} ({len(t)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
