function [closed, margin] = closure(req, ach, sense)
%CLOSURE  Whether an achieved value closes a requirement, and by how much. sense 0: the achieved value is
%   at most the requirement; 1: at least. Requirement and achieved value are the same quantity in
%   SI (the language has no generic units: the caller holds them to one).
%   req: real[1] (passed a plain number)
%   ach: real[1] (passed a plain number)
%   sense: int (passed a whole number)
%   returns closed: bool (passed true or false)
%   returns margin: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    closed = false;
    margin = 0;
    if (sense == 0)
        margin = (req - ach);
    else
        margin = (ach - req);
    end
    closed = (margin >= 0);
end
