function s = SunHead_zero()
%SUNHEAD_ZERO  a SunHead with every field zero
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = struct();
    s.a = 0;
    s.h = 0;
    s.noise = 0;
    s.min_frac = 0;
end
