function [o] = dtm3(day, f, fbar, akp, alti, hl, alat, xlon)
%DTM3  dtm3: the operational DTM2020 at day of year day, F10.7 of the day before f and its 81-day mean fbar [sfu], the Kp
%   array akp, altitude alti [km] (above 120), local solar time hl [rad], latitude alat and longitude xlon [rad].
%   day: real[1] (passed a plain number)
%   f: real[1] (passed a plain number)
%   fbar: real[1] (passed a plain number)
%   akp: real[1][4] (passed a plain number)
%   alti: real[1] (passed a plain number)
%   hl: real[1] (passed a plain number)
%   alat: real[1] (passed a plain number)
%   xlon: real[1] (passed a plain number)
%   returns o: DtmRaw (passed rec)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    o = asils.models.dtm2020.DtmRaw_zero();
    cpmg = 0.19081;
    spmg = 0.98163;
    xlmg = (-(1.2392));
    plg = asils.models.dtm2020.plg_geographic(alat);
    c = sin(alat);
    s = cos(alat);
    clmlmg = cos((xlon - xlmg));
    sp = (((s * cpmg) * clmlmg) + (c * spmg));
    cmg = sp;
    cmg2 = (cmg)^(2);
    cmg4 = (cmg2)^(2);
    plg.p10mg = cmg;
    plg.p20mg = ((1.5 * cmg2) - 0.5);
    plg.p40mg = (((4.375 * cmg4) - (3.75 * cmg2)) + 0.375);
    hloc = asils.models.dtm2020.hloc_of(hl);
    [gd_tt, gd_t0, gd_tp, gd] = asils.models.dtm2020.dtm3_gdel(f, fbar, akp, day, plg, hloc, xlon);
    o = asils.models.dtm2020.dtm_profile(0, gd_tt, gd_t0, gd_tp, gd, alti);
end
