function [v] = dtm_vma()
%DTM_VMA  The particle masses [g] of H, He, O, N2, O2, N (vma).
%   returns v: real[1][6] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    v = zeros(6, 1);
    v = [1.6606e-24; 6.6423e-24; 2.6569e-23; 4.64958e-23; 5.31381e-23; 2.32479e-23];
end
