function [a] = dtm_column(set, j)
%DTM_COLUMN  Column j of a coefficient set (tt h he o az2 o2 az t0 tp), as the code's 1-based 96-term vector: a[0] unused.
%   set: DtmSet (passed a choice, as its option's number)
%   j: int (passed a whole number)
%   returns a: real[1][97] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    a = zeros(97, 1);
    a = zeros(97, 1);
    for k = (1):((97) - 1)
        if (set == 0)
            a((k) + 1) = asils.models.dtm2020coeffs.DTM2020_OPER(((k - 1)) + 1, (j) + 1);
        else
            a((k) + 1) = asils.models.dtm2020coeffs.DTM2020_RESEARCH(((k - 1)) + 1, (j) + 1);
        end
    end
end
