function [o] = dtm_pack(r)
%DTM_PACK  The densities of dtm3 or dtm5 in the wrappers' form: number densities [1/cm^3] from the partial densities.
%   r: DtmRaw (passed rec)
%   returns o: DtmDensity (passed rec)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    o = asils.models.dtm2020.DtmDensity_zero();
    vma = asils.models.dtm2020.dtm_vma();
    o = asils.models.dtm2020.DtmDensity_zero();
    i = ((0):((6) - 1)).';
    o.n_cm3((i) + 1) = (reshape(r.d((i) + 1), [], 1) ./ reshape(vma((i) + 1), [], 1));
    o.rho_gcm3 = r.ro;
    o.rho_kgm3 = (r.ro * 1000);
    o.t_k = r.tz;
    o.tinf_k = r.tinf;
    o.rho_species = r.d;
    o.mbar_amu = r.wmm;
end
