function [h] = fsw_rotor_targets(n, kind, hmax, h0, h_bias)
%FSW_ROTOR_TARGETS  The momentum [N m s] each rotor holds when the scenario states none: a wheel min(h_bias, 0.25 h_max), a CMG's or a
%   VSCMG's rotor its own momentum h0, a ring none.
%   n: int (passed a whole number)
%   kind: int[FSW_NR] (passed a whole number)
%   hmax: real[1][FSW_NR] (passed a plain number)
%   h0: real[1][FSW_NR] (passed a plain number)
%   h_bias: real[1] (passed a plain number)
%   returns h: real[1][FSW_NR] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    h = zeros(8, 1);
    h = zeros(8, 1);
    for i = (0):((8) - 1)
        if (i < n)
            if (kind((i) + 1) == 0)
                h((i) + 1) = asils.pc.fmin(h_bias, (0.25 * hmax((i) + 1)));
            elseif ((kind((i) + 1) == 2) || (kind((i) + 1) == 3))
                h((i) + 1) = h0((i) + 1);
            end
        end
    end
end
