function [b0, tilt] = dipole()
%DIPOLE  The dipole strength B0 = sqrt(g10^2 + g11^2 + h11^2) and its tilt from the spin axis.
%   returns b0: real[T] (passed in kg/(s^2 A))
%   returns tilt: real[rad] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    b0 = 0;
    tilt = 0;
    b0 = asils.pc.sqrt_(((asils.pc.ipow((-0.0000294048), 2) + asils.pc.ipow((-0.0000014509000000000002), 2)) + asils.pc.ipow(0.0000046525, 2)));
    tilt = asils.pc.acos_(((-((-0.0000294048))) / b0));
end
