function [e_c] = pointing_control(ape, ake)
%POINTING_CONTROL  gp_1, the control contribution, inferred from the flown loop: the flown APE ape [deg] with the knowledge ake [deg]
%   removed in quadrature, sqrt(max(ape^2 - ake^2, 0)).
%   ape: real[1] (passed a plain number)
%   ake: real[1] (passed a plain number)
%   returns e_c: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    e_c = 0;
    e_c = sqrt(asils.pc.fmax(((ape * ape) - (ake * ake)), 0));
end
