function [total, room, verdict] = pointing_budget(ape, e_a, e_t, e_j, req)
%POINTING_BUDGET  The budget against the requirement req [deg]: the total, the root-sum-square of the flown APE and the terms the loop
%   does not fly (alignment e_a, thermal e_t, jitter e_j); the room req.ape leaves for alignment and thermal together once
%   the flown loop and the jitter are in, sqrt(max(req^2 - ape^2 - e_j^2, 0)); and the verdict.
%   ape: real[1] (passed a plain number)
%   e_a: real[1] (passed a plain number)
%   e_t: real[1] (passed a plain number)
%   e_j: real[1] (passed a plain number)
%   req: real[1] (passed a plain number)
%   returns total: real[1] (passed a plain number)
%   returns room: real[1] (passed a plain number)
%   returns verdict: BudgetVerdict (passed a choice, as its option's number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    total = 0;
    room = 0;
    verdict = 0;
    total = asils.pc.sqrt_(((((ape * ape) + (e_a * e_a)) + (e_t * e_t)) + (e_j * e_j)));
    room = asils.pc.sqrt_(asils.pc.fmax((((req * req) - (ape * ape)) - (e_j * e_j)), 0));
    verdict = 2;
    if ((isnan(e_a) || isnan(e_t)) || isnan(e_j))
        verdict = 0;
    elseif (total <= req)
        verdict = 1;
    end
end
