function [v, t, x, tt, xx] = kpi_time_to_threshold(t, x, n, t0, thr, hold, unit_min, tt, xx)
%KPI_TIME_TO_THRESHOLD  The time to a threshold [s, or min when unit_min]: from t0 [s], the first time the channel x goes below thr [deg]
%   and stays below it for hold [s] (tt and xx the samples from t0 on).
%   length: 64
%   t: inout real[1][*] (passed a plain number)
%   x: inout real[1][*] (passed a plain number)
%   n: int (passed a whole number)
%   t0: real[1] (passed a plain number)
%   thr: real[1] (passed a plain number)
%   hold: real[1] (passed a plain number)
%   unit_min: bool (passed true or false)
%   tt: inout real[1][*] (passed a plain number)
%   xx: inout real[1][*] (passed a plain number)
%   returns v: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    v = 0;
    [t__526, t__527, t__528, t__529, t__530] = asils.models.kpistats.kpi_time_to_from(t, x, n, t0, thr, hold, tt, xx);
    v = t__526;
    t = t__527;
    x = t__528;
    tt = t__529;
    xx = t__530;
    if unit_min
        v = (v / 60);
    end
end
