function [v, t, mode] = kpi_time_to_mode(t, mode, n, m)
%KPI_TIME_TO_MODE  The time to a mode [min]: the first sample (times t [s], modes mode, n samples) in the mode m; nan if none is.
%   length: 64
%   t: inout real[1][*] (passed a plain number)
%   mode: inout int[*] (passed a whole number)
%   n: int (passed a whole number)
%   m: int (passed a whole number)
%   returns v: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    v = 0;
    v = NaN;
    found = false;
    for j = (0):((n) - 1)
        if ((~found) && (mode((j) + 1) == m))
            v = (t((j) + 1) / 60);
            found = true;
        end
    end
end
