function [v, prop] = kpi_propellant(prop, n)
%KPI_PROPELLANT  The propellant used [g]: the most of the run's n samples prop [kg] (from none).
%   length: 64
%   prop: inout real[1][*] (passed a plain number)
%   n: int (passed a whole number)
%   returns v: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    v = 0;
    acc = 0;
    for j = (0):((n) - 1)
        acc = asils.models.kpistats.kpi_max(acc, prop((j) + 1));
    end
    v = (1000 * acc);
end
