function [v, h, idx] = kpi_wheel_peak(h, nr, idx, ni)
%KPI_WHEEL_PEAK  The wheels' peak momentum [N m s]: the largest |h| of the nr rotors (h, nr numbers a sample) over the window's
%   samples idx[0..ni]; nan with none.
%   length: 64
%   h: inout real[1][*] (passed a plain number)
%   nr: int (passed a whole number)
%   idx: inout int[*] (passed a whole number)
%   ni: int (passed a whole number)
%   returns v: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    v = 0;
    v = NaN;
    for i = (0):((ni) - 1)
        for r = (0):((nr) - 1)
            h__628 = h((((idx((i) + 1) * nr) + r)) + 1);
            if h__628 < 0, h__628 = -h__628; elseif h__628 == 0, h__628 = 0; end
            v = asils.models.kpistats.kpi_max(v, h__628);
        end
    end
end
