function [f] = eclipse_fraction(r, beta)
%ECLIPSE_FRACTION  The share of a circular orbit in the Earth's cylindrical shadow, at Sun angle beta:
%   f = acos(sqrt(1 - (R_E/r)^2)/cos beta)/pi while |beta| < asin(R_E/r), else 0.
%   r: real[km] (passed in m)
%   beta: real[deg] (passed a plain number)
%   returns f: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    f = 0;
    rho = (6378137 / r);
    h__19 = beta;
    if h__19 < 0, h__19 = -h__19; elseif h__19 == 0, h__19 = 0; end
    h__20 = asin(rho);
    if ~isreal(h__20), h__20 = NaN; end
    if (h__19 < h__20)
        h__21 = (1 - (rho * rho));
        if h__21 < 0, h__21 = NaN; else, h__21 = sqrt(h__21); end
        h__22 = acos((h__21 / cos(beta)));
        if ~isreal(h__22), h__22 = NaN; end
        f = (h__22 / pi);
    else
        f = 0;
    end
end
