function [u] = utc_of_jd(j)
%UTC_OF_JD  The UTC calendar date [Y M D h m s] of a Julian date (the inverse, Meeus's form).
%   j: real[1] (passed a plain number)
%   returns u: real[1][6] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    u = zeros(6, 1);
    z = floor((j + 0.5));
    f = ((j + 0.5) - z);
    a = floor(((z - 1867216.25) / 36524.25));
    aa = (((z + 1) + a) - floor((a / 4)));
    b = (aa + 1524);
    c = floor(((b - 122.1) / 365.25));
    d = floor((365.25 * c));
    e = floor(((b - d) / 30.6001));
    day = ((b - d) - floor((30.6001 * e)));
    if (e < 14)
        h__161 = (e - 1);
    else
        h__161 = (e - 13);
    end
    mon = h__161;
    if (mon > 2)
        h__162 = (c - 4716);
    else
        h__162 = (c - 4715);
    end
    yr = h__162;
    s = (f * 86400);
    h = floor((s / 3600));
    s = (s - (3600 * h));
    mi = floor((s / 60));
    s = (s - (60 * mi));
    u = [yr; mon; day; h; mi; s];
end
