function [share, defined] = share_tested(untested, total)
%SHARE_TESTED  The share of beliefs tested: 1 - untested/total; with none recorded it is undefined, not 1.
%   untested: int (passed a whole number)
%   total: int (passed a whole number)
%   returns share: real[1] (passed a plain number)
%   returns defined: bool (passed true or false)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    share = 0;
    defined = false;
    if (total > 0)
        share = (1 - (untested / total));
        defined = true;
    else
        share = 0;
        defined = false;
    end
end
