//! navorbit: 02 at the level of the tick (08_mode_manager.md, the tick's step 1): nav's onboard orbit - the GNSS fix taken in (its validity gate, its frame and its age) and the orbit carried between fixes - transcribed operation for operation from the tick of fsw/src/adcs_fsw.c and fsw-rs/src/fsw.rs (adcs_fsw_step, Fsw::step: step 1), which S6 left in the runtime. A fix is taken when the receiver says it is good and it lies outside 0.9 R_E (R_E = 6378137 m, WGS-84, NIMA TR8350.2): one inside the Earth is no fix. An Earth-fixed fix (ECEF) is taken to J2000 at its epoch by the onboard frame (env's eci2ecef) with the transport theorem, v = C' (v_e + w_E x r_e), w_E = 7.2921158553e-5 rad/s (the IAU-76/FK5 rate, Vallado 2013). The orbit is carried by one velocity-Verlet step (Swope, Andersen, Berens and Wilson 1982, J. Chem. Phys. 76:637) over the two-body + J2 acceleration (steplaws' orbit_acc): a late fix by its age, the orbit between fixes by the tick. The developer's transcription (S7.19b), unsigned.
//! Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
#![allow(unused_mut, unused_variables, unused_parens, unused_assignments, unused_imports, unreachable_code, non_snake_case, clippy::all)]
use crate::alg::rt;
use crate::alg::steplaws::{CtlState, CtlParams};
use crate::alg::modes::{Modes, ModeParams, RotorFdir, RotorParams};

/// Whether a GNSS fix may be taken: the receiver's flag, and the fix outside 0.9 R_E.
/// - ok: bool (passed true or false)
/// - r: real[1][3] (passed a plain number)
/// - returns good: bool (passed true or false)
#[allow(clippy::too_many_arguments)]
pub fn gnss_usable(ok: bool, r: [f64; 3]) -> bool {
    let mut good: bool = false;
    good = (ok && (rt::norm(r) > (0.9 * 6378137.0)));
    good
}

/// One velocity-Verlet step of h over the two-body + J2 acceleration: r + (v h + a0 h h/2), then v + (a0 + a1) h/2 with
/// a1 at the new r, element by element as the tick wrote them.
/// - r0: real[1][3] (passed a plain number)
/// - v0: real[1][3] (passed a plain number)
/// - h: real[1] (passed a plain number)
/// - mu: real[1] (passed a plain number)
/// - returns r: real[1][3] (passed a plain number)
/// - returns v: real[1][3] (passed a plain number)
#[allow(clippy::too_many_arguments)]
pub fn verlet(r0: [f64; 3], v0: [f64; 3], h: f64, mu: f64) -> ([f64; 3], [f64; 3]) {
    let mut r: [f64; 3] = [0.0; 3];
    let mut v: [f64; 3] = [0.0; 3];
    let mut a0: [f64; 3] = crate::alg::steplaws::orbit_acc(r0, mu);
    r = [(r0[0] + ((v0[0] * h) + (((0.5 * a0[0]) * h) * h))), (r0[1] + ((v0[1] * h) + (((0.5 * a0[1]) * h) * h))), (r0[2] + ((v0[2] * h) + (((0.5 * a0[2]) * h) * h)))];
    let mut a1: [f64; 3] = crate::alg::steplaws::orbit_acc(r, mu);
    v = [(v0[0] + ((0.5 * (a0[0] + a1[0])) * h)), (v0[1] + ((0.5 * (a0[1] + a1[1])) * h)), (v0[2] + ((0.5 * (a0[2] + a1[2])) * h))];
    (r, v)
}

/// An Earth-fixed fix taken to J2000 at the Julian date jd: r = C' r_e, v = C' (v_e + w_E x r_e), C the onboard
/// eci2ecef at jd.
/// - r_e: real[1][3] (passed a plain number)
/// - v_e: real[1][3] (passed a plain number)
/// - jd: real[1] (passed a plain number)
/// - returns r: real[1][3] (passed a plain number)
/// - returns v: real[1][3] (passed a plain number)
#[allow(clippy::too_many_arguments)]
pub fn fix_eci(r_e: [f64; 3], v_e: [f64; 3], jd: f64) -> ([f64; 3], [f64; 3]) {
    let mut r: [f64; 3] = [0.0; 3];
    let mut v: [f64; 3] = [0.0; 3];
    let mut c: [[f64; 3]; 3] = crate::alg::frames::eci2ecef(jd);
    let mut ve: [f64; 3] = rt::vadd(v_e, rt::cross([0.0, 0.0, 0.000072921158553], r_e));
    r = crate::alg::math::mat3t_vec(c, r_e);
    v = crate::alg::math::mat3t_vec(c, ve);
    (r, v)
}

/// The onboard orbit after the tick's step 1, from the orbit it held (r0, v0; have: whether it holds one) and the
/// receiver's fix (ok, r_fix, v_fix; in ECEF when ecef; lat seconds old) at the Julian date jd: a usable fix, taken from
/// ECEF at its epoch jd - lat when it is Earth-fixed, carried forward to now by one Verlet step of lat when lat > 0; else
/// the orbit held carried one tick dt; else none. The orbit, and whether there is one.
/// vectors: 48
/// - r0: real[1][3] (passed a plain number)
/// - v0: real[1][3] (passed a plain number)
/// - have: bool (passed true or false)
/// - ok: bool (passed true or false)
/// - r_fix: real[1][3] (passed a plain number)
/// - v_fix: real[1][3] (passed a plain number)
/// - ecef: bool (passed true or false)
/// - lat: real[1] (passed a plain number)
/// - jd: real[1] (passed a plain number)
/// - dt: real[1] (passed a plain number)
/// - mu: real[1] (passed a plain number)
/// - returns r: real[1][3] (passed a plain number)
/// - returns v: real[1][3] (passed a plain number)
/// - returns have_r: bool (passed true or false)
#[allow(clippy::too_many_arguments)]
pub fn onboard_orbit(r0: [f64; 3], v0: [f64; 3], have: bool, ok: bool, r_fix: [f64; 3], v_fix: [f64; 3], ecef: bool, lat: f64, jd: f64, dt: f64, mu: f64) -> ([f64; 3], [f64; 3], bool) {
    let mut r: [f64; 3] = [0.0; 3];
    let mut v: [f64; 3] = [0.0; 3];
    let mut have_r: bool = false;
    r = r0;
    v = v0;
    have_r = have;
    if crate::alg::navorbit::gnss_usable(ok, r_fix) {
        if ecef {
            let __t73 = crate::alg::navorbit::fix_eci(r_fix, v_fix, (jd - (lat / 86400.0)));
            r = __t73.0;
            v = __t73.1;
        } else {
            r = r_fix;
            v = v_fix;
        }
        if (lat > 0.0) {
            let __t74 = crate::alg::navorbit::verlet(r, v, lat, mu);
            r = __t74.0;
            v = __t74.1;
        }
        have_r = true;
    } else if have {
        let __t75 = crate::alg::navorbit::verlet(r0, v0, dt, mu);
        r = __t75.0;
        v = __t75.1;
    }
    (r, v, have_r)
}
