//! The arithmetic every translation shares with the interpreter (design/js/pcode.js `rt`). Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
#![allow(clippy::all)]

/// x^k by repeated multiplication, left to right; x^-k = 1/(x^k).
pub fn ipow(x: f64, k: i32) -> f64 {
    if k == 0 { return 1.0; }
    let mut r = x;
    let mut i = 1;
    while i < k.abs() { r = r * x; i += 1; }
    if k < 0 { 1.0 / r } else { r }
}
pub fn ipowi(x: i64, k: i32) -> i64 { let mut r: i64 = 1; for _ in 0..k { r *= x; } r }
pub fn fmin(a: f64, b: f64) -> f64 { if b < a { b } else { a } }
pub fn fmax(a: f64, b: f64) -> f64 { if b > a { b } else { a } }
pub fn imin(a: i64, b: i64) -> i64 { if b < a { b } else { a } }
pub fn imax(a: i64, b: i64) -> i64 { if b > a { b } else { a } }
pub fn fabs(x: f64) -> f64 { if x < 0.0 { -x } else if x == 0.0 { 0.0 } else { x } }
pub fn clamp(x: f64, lo: f64, hi: f64) -> f64 { fmin(fmax(x, lo), hi) }
pub fn sign(x: f64) -> f64 { if x > 0.0 { 1.0 } else if x < 0.0 { -1.0 } else { 0.0 } }
pub fn dot<const N: usize>(a: [f64; N], b: [f64; N]) -> f64 { let mut s = a[0] * b[0]; for i in 1..N { s = s + a[i] * b[i]; } s }
pub fn cross(a: [f64; 3], b: [f64; 3]) -> [f64; 3] { [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]] }
pub fn norm<const N: usize>(a: [f64; N]) -> f64 { crate::m::sqrt(dot(a, a)) }
pub fn unit<const N: usize>(a: [f64; N]) -> [f64; N] { let n = fmax(norm(a), 1e-30); let mut r = a; for i in 0..N { r[i] = a[i] / n; } r }
pub fn vadd<const N: usize>(a: [f64; N], b: [f64; N]) -> [f64; N] { let mut r = a; for i in 0..N { r[i] = a[i] + b[i]; } r }
pub fn vsub<const N: usize>(a: [f64; N], b: [f64; N]) -> [f64; N] { let mut r = a; for i in 0..N { r[i] = a[i] - b[i]; } r }
pub fn vneg<const N: usize>(a: [f64; N]) -> [f64; N] { let mut r = a; for i in 0..N { r[i] = -a[i]; } r }
pub fn vscale<const N: usize>(a: [f64; N], s: f64) -> [f64; N] { let mut r = a; for i in 0..N { r[i] = a[i] * s; } r }
pub fn vscale_l<const N: usize>(s: f64, a: [f64; N]) -> [f64; N] { let mut r = a; for i in 0..N { r[i] = s * a[i]; } r }
pub fn vdiv<const N: usize>(a: [f64; N], s: f64) -> [f64; N] { let mut r = a; for i in 0..N { r[i] = a[i] / s; } r }
pub fn madd<const N: usize, const M: usize>(a: [[f64; M]; N], b: [[f64; M]; N]) -> [[f64; M]; N] { let mut r = a; for i in 0..N { r[i] = vadd(a[i], b[i]); } r }
pub fn msub<const N: usize, const M: usize>(a: [[f64; M]; N], b: [[f64; M]; N]) -> [[f64; M]; N] { let mut r = a; for i in 0..N { r[i] = vsub(a[i], b[i]); } r }
pub fn mneg<const N: usize, const M: usize>(a: [[f64; M]; N]) -> [[f64; M]; N] { let mut r = a; for i in 0..N { r[i] = vneg(a[i]); } r }
pub fn mscale<const N: usize, const M: usize>(a: [[f64; M]; N], s: f64) -> [[f64; M]; N] { let mut r = a; for i in 0..N { r[i] = vscale(a[i], s); } r }
pub fn mscale_l<const N: usize, const M: usize>(s: f64, a: [[f64; M]; N]) -> [[f64; M]; N] { let mut r = a; for i in 0..N { r[i] = vscale_l(s, a[i]); } r }
pub fn mdiv<const N: usize, const M: usize>(a: [[f64; M]; N], s: f64) -> [[f64; M]; N] { let mut r = a; for i in 0..N { r[i] = vdiv(a[i], s); } r }
pub fn mv<const N: usize, const M: usize>(a: [[f64; M]; N], v: [f64; M]) -> [f64; N] { let mut r = [0.0; N]; for i in 0..N { r[i] = dot(a[i], v); } r }
pub fn mm<const N: usize, const K: usize, const M: usize>(a: [[f64; K]; N], b: [[f64; M]; K]) -> [[f64; M]; N] {
    let mut r = [[0.0; M]; N];
    for i in 0..N { for j in 0..M { let mut s = a[i][0] * b[0][j]; for k in 1..K { s = s + a[i][k] * b[k][j]; } r[i][j] = s; } }
    r
}
pub fn tr<const N: usize, const M: usize>(a: [[f64; M]; N]) -> [[f64; N]; M] { let mut r = [[0.0; N]; M]; for i in 0..N { for j in 0..M { r[j][i] = a[i][j]; } } r }
/// The last row whose key is at or below x (the first row below the first key).
pub fn lookup_step<const C: usize, const R: usize>(t: &[[f64; C]; R], x: f64) -> [f64; C] {
    let mut i = 0;
    while i + 1 < R && t[i + 1][0] <= x { i += 1; }
    t[i]
}
/// Straight-line between the two rows around x, held at the ends.
pub fn lookup_linear<const C: usize, const R: usize>(t: &[[f64; C]; R], x: f64) -> [f64; C] {
    let xc = clamp(x, t[0][0], t[R - 1][0]);
    let mut i = 0;
    while i + 2 < R && t[i + 1][0] <= xc { i += 1; }
    let s = (xc - t[i][0]) / (t[i + 1][0] - t[i][0]);
    let mut r = t[i];
    for j in 0..C { r[j] = t[i][j] + s * (t[i + 1][j] - t[i][j]); }
    r
}
