function [delta, omega, z] = flexible_mode(fmode, mpart, zeta, axis, j)
%FLEXIBLE_MODE  The flexible mode on the truth body: its coupling delta along the body axis it bends about (axis 1, 2 or 3), with
%   |delta|^2 the share mpart of that axis's inertia; its natural frequency omega = 2 pi fmode [rad/s]; its damping zeta.
%   fmode: real[1] (passed a plain number)
%   mpart: real[1] (passed a plain number)
%   zeta: real[1] (passed a plain number)
%   axis: int (passed a whole number)
%   j: real[1][3][3] (passed a plain number)
%   returns delta: real[1][3] (passed a plain number)
%   returns omega: real[1] (passed a plain number)
%   returns z: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    delta = zeros(3, 1);
    omega = 0;
    z = 0;
    delta = zeros(3, 1);
    a = (axis - 1);
    delta((a) + 1) = asils.pc.sqrt_((mpart * j((a) + 1, (a) + 1)));
    omega = ((2 * pi) * fmode);
    z = zeta;
end
