function [jo, pd] = inertia_products(j, f)
%INERTIA_PRODUCTS  The inertia with products of inertia f = [xy, xz, yz], each a fraction of sqrt(I_ii I_jj) (each below 1 in size), and
%   whether it is still positive definite (its leading 2 x 2 minor and its determinant above 0).
%   j: real[1][3][3] (passed a plain number)
%   f: real[1][3] (passed a plain number)
%   returns jo: real[1][3][3] (passed a plain number)
%   returns pd: bool (passed true or false)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    jo = zeros(3, 3);
    pd = false;
    jo = j;
    pxy = (f(1) * asils.pc.sqrt_((j(1, 1) * j(2, 2))));
    jo(1, 2) = pxy;
    jo(2, 1) = pxy;
    pxz = (f(2) * asils.pc.sqrt_((j(1, 1) * j(3, 3))));
    jo(1, 3) = pxz;
    jo(3, 1) = pxz;
    pyz = (f(3) * asils.pc.sqrt_((j(2, 2) * j(3, 3))));
    jo(2, 3) = pyz;
    jo(3, 2) = pyz;
    d2 = ((jo(1, 1) * jo(2, 2)) - (jo(1, 2) * jo(2, 1)));
    d3 = (((jo(1, 1) * ((jo(2, 2) * jo(3, 3)) - (jo(2, 3) * jo(3, 2)))) - (jo(1, 2) * ((jo(2, 1) * jo(3, 3)) - (jo(2, 3) * jo(3, 1))))) + (jo(1, 3) * ((jo(2, 1) * jo(3, 2)) - (jo(2, 2) * jo(3, 1)))));
    pd = ((d2 > 0) && (d3 > 0));
end
