function [b, disp] = gyro_bias(sigma, disp)
%GYRO_BIAS  A gyro's turn-on bias [rad/s]: three normal draws times sigma.
%   sigma: real[1] (passed a plain number)
%   disp: inout stream (passed a random stream, as six numbers)
%   returns b: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    b = zeros(3, 1);
    [t__132, t__133] = asils.pc.stream_normal3(disp);
    e = t__132;
    disp = t__133;
    b = (e * sigma);
end
