function [w, g] = gyro_bias_walk(brw, rrw, dt, g)
%GYRO_BIAS_WALK  The rate random walk's bias brw [rad/s] after a step dt [s], rrw the walk's density [rad/s/sqrt(s)].
%   brw: real[1][3] (passed a plain number)
%   rrw: real[1] (passed a plain number)
%   dt: real[1] (passed a plain number)
%   g: inout stream (passed a random stream, as six numbers)
%   returns w: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    w = zeros(3, 1);
    [t__499, t__500] = asils.pc.stream_normal3(g);
    n1 = t__499;
    g = t__500;
    w = (brw + ((rrw * asils.pc.sqrt_(dt)) * n1));
end
