function [u, disp] = es_new(d, disp, noise)
%ES_NEW  The Earth sensor of a description, its mount bias drawn from disp, its noise from noise.
%   d: EsDesc (passed rec)
%   disp: inout stream (passed a random stream, as six numbers)
%   noise: stream (passed a random stream, as six numbers)
%   returns u: EsUnit (passed rec)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    u = asils.models.earthsensor.EsUnit_zero();
    u = asils.models.earthsensor.EsUnit_zero();
    [t__98, t__99] = asils.pc.stream_normal3(disp);
    e = t__98;
    disp = t__99;
    u.bias = asils.models.math.fromrotvec((e * d.bias_sigma));
    u.g = noise;
end
