function s = EsUnit_zero()
%ESUNIT_ZERO  a EsUnit with every field zero
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    s = struct();
    s.bias = zeros(4, 1);
    s.g = zeros(6, 1);
end
