function [eta, disp] = pump_efficiency(lo, hi, disp)
%PUMP_EFFICIENCY  The unit's pump efficiency, uniform between lo and hi, drawn from disp.
%   lo: real[1] (passed a plain number)
%   hi: real[1] (passed a plain number)
%   disp: inout stream (passed a random stream, as six numbers)
%   returns eta: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    eta = 0;
    [t__17, t__18] = asils.pc.stream_uniform(disp);
    u = t__17;
    disp = t__18;
    eta = (lo + ((hi - lo) * u));
end
