function [b_max] = dipole_field_max(r, lambda_max)
%DIPOLE_FIELD_MAX  The dipole field at magnetic latitude lambda_max: B_max = B0 (R_E/r)^3 sqrt(1 + 3 sin^2 lambda).
%   r: real[km] (passed in m)
%   lambda_max: real[deg] (passed a plain number)
%   returns b_max: real[T] (passed in kg/(s^2 A))
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    b_max = 0;
    [b0, tilt] = asils.relations.env.dipole();
    h__10 = (6378137 / r);
    h__11 = sin(lambda_max);
    h__12 = (1 + (3 * (h__11 * h__11)));
    if h__12 < 0, h__12 = NaN; else, h__12 = sqrt(h__12); end
    b_max = ((b0 * (h__10 * h__10 * h__10)) * h__12);
end
