function [tau_a] = gd_1(rho, v, c_d, a_fr, c_pa)
%GD_1  The node's answer, tau_a, as aero_torque gives it.
%   rho: real[kg/m^3] (passed in kg/m^3)
%   v: real[m/s] (passed in m/s)
%   c_d: real[1] (passed a plain number)
%   a_fr: real[m^2] (passed in m^2)
%   c_pa: real[m] (passed in m)
%   returns tau_a: real[N m] (passed in m^2 kg/s^2)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    tau_a = 0;
    tau_a = asils.relations.gnc.aero_torque(rho, v, c_d, a_fr, c_pa);
end
