function [p_srp] = solar_pressure(t_epoch)
%SOLAR_PRESSURE  The Sun's radiation pressure at the Earth's distance: P = (F_sun/c) (1 AU/d)^2.
%   t_epoch: real[yr] (passed in s)
%   returns p_srp: real[Pa] (passed in kg/(m s^2))
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    p_srp = 0;
    d = asils.relations.env.sun_distance_au(t_epoch);
    p_srp = ((1360.8 / 299792458) / (d * d));
end
