function [beta] = doodson(jd_tt)
%DOODSON  oceantides.doodson(jd_tt): the six Doodson arguments [tau, s, h, p, N', ps] [rad] at a TT Julian date.
%   jd_tt: real[1] (passed a plain number)
%   returns beta: real[1][6] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    beta = zeros(6, 1);
    t = ((jd_tt - 2451545) / 36525);
    d2r = (pi / 180);
    s = asils.models.oceantides.ocean_mod((218.3164477 + (481267.88123421 * t)), 360);
    h = asils.models.oceantides.ocean_mod((280.4664567 + (36000.76982779 * t)), 360);
    p = asils.models.oceantides.ocean_mod((83.3532465 + (4069.0137287 * t)), 360);
    np = asils.models.oceantides.ocean_mod((234.9554736 + (1934.1362608 * t)), 360);
    ps = asils.models.oceantides.ocean_mod((282.9373409 + (1.7195366 * t)), 360);
    gmst = asils.models.oceantides.ocean_mod((280.46061837 + (360.98564736629 * (jd_tt - 2451545))), 360);
    tau = asils.models.oceantides.ocean_mod(((gmst + 180) - s), 360);
    beta = [(tau * d2r); (s * d2r); (h * d2r); (p * d2r); (np * d2r); (ps * d2r)];
end
