function [n] = fes_nmax()
%FES_NMAX  The largest degree of the FES2004 table (fromModel's nmax).
%   returns n: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    n = 0;
    D__FES2004 = asils.models.tidelines.FES2004();
    n = 0;
    for i = (0):((1052) - 1)
        h__435 = n;
        h__436 = fix(D__FES2004((i) + 1, 7));
        if h__436 > h__435, h__435 = h__436; end
        n = h__435;
    end
end
