function [n] = fes_nmax()
%FES_NMAX  The largest degree of the FES2004 table (fromModel's nmax).
%   returns n: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    n = 0;
    n = 0;
    for i = (0):((1052) - 1)
        n = asils.pc.fmax(n, fix(asils.models.tidelines.FES2004((i) + 1, 7)));
    end
end
