function [a] = ocean_tides_accel(tt_jd, r_ecef, c, mu, re)
%OCEAN_TIDES_ACCEL  forces.oceantides(ctx): the main lines' degree-2 corrections at TT, their acceleration in ECEF, rotated to ECI with
%   C'. [m/s^2]
%   The central difference amplifies the maths library's last bit about a million times: a translation is held to
%   1e-8 of the largest output, not 1e-12 (the browser's sin, cos, asin, atan2 and pow differ from the platform's).
%   tolerance: 1e-8
%   tt_jd: real[1] (passed a plain number)
%   r_ecef: real[1][3] (passed a plain number)
%   c: real[1][3][3] (passed a plain number)
%   mu: real[1] (passed a plain number)
%   re: real[1] (passed a plain number)
%   returns a: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    a = zeros(3, 1);
    d = asils.models.oceantides.main_lines(tt_jd);
    dc2 = [d.dc(3, 1); d.dc(3, 2); d.dc(3, 3)];
    ds2 = [d.ds(3, 1); d.ds(3, 2); d.ds(3, 3)];
    ae = asils.models.solidtides.accel_from_deg2(r_ecef, dc2, ds2, mu, re);
    h__437 = (c).';
    a = [h__437(1, 1)*ae(1) + h__437(1, 2)*ae(2) + h__437(1, 3)*ae(3); h__437(2, 1)*ae(1) + h__437(2, 2)*ae(2) + h__437(2, 3)*ae(3); h__437(3, 1)*ae(1) + h__437(3, 2)*ae(2) + h__437(3, 3)*ae(3)];
end
