function [rg, vg, g] = gps_sample(r, v, pos_sigma, vel_sigma, g)
%GPS_SAMPLE  The fix the receiver reports: the position r [m] and velocity v [m/s] (ECEF) with their noise, the sigmas pos_sigma
%   [m] and vel_sigma [m/s], the position's draws first.
%   r: real[1][3] (passed a plain number)
%   v: real[1][3] (passed a plain number)
%   pos_sigma: real[1] (passed a plain number)
%   vel_sigma: real[1] (passed a plain number)
%   g: inout stream (passed a random stream, as six numbers)
%   returns rg: real[1][3] (passed a plain number)
%   returns vg: real[1][3] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    rg = zeros(3, 1);
    vg = zeros(3, 1);
    [t__168, t__169] = asils.pc.stream_normal3(g);
    a = t__168;
    g = t__169;
    [t__170, t__171] = asils.pc.stream_normal3(g);
    b = t__170;
    g = t__171;
    rg = (r + (a * pos_sigma));
    vg = (v + (b * vel_sigma));
end
