function [a] = kpi_three_axis(q, qr)
%KPI_THREE_AXIS  The angle between the attitudes q and qr [deg], three-axis (the toolbox's qangle). The engine takes it with its
%   portable maths (adcs-sim-core's, the pure-Rust libm the toolbox's qangle flew), the other angles with the platform's.
%   q: real[1][4] (passed a plain number)
%   qr: real[1][4] (passed a plain number)
%   returns a: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    a = 0;
    a = (asils.models.math.qangle(q, qr) * (180 / pi));
end
