function [geo, lit] = kpi_sun_angle(sun_axis, sun_body, nu)
%KPI_SUN_ANGLE  The Sun's angle from the power face sun_axis (body) [deg], the Sun along sun_body (body): geometric, and only where
%   the spacecraft is lit (the sunlit fraction nu at least one half; nan in the shadow).
%   sun_axis: real[1][3] (passed a plain number)
%   sun_body: real[1][3] (passed a plain number)
%   nu: real[1] (passed a plain number)
%   returns geo: real[1] (passed a plain number)
%   returns lit: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    geo = 0;
    lit = 0;
    geo = asils.models.kpichannels.kpi_acosd(asils.pc.dot_(sun_axis, sun_body));
    lit = geo;
    if (nu < 0.5)
        lit = NaN;
    end
end
