function [lag] = kpi_rks_lag(record_dt)
%KPI_RKS_LAG  How many record steps the rate stability looks back: one second at the record step record_dt [s] (a plain number),
%   at least one.
%   record_dt: real[1] (passed a plain number)
%   returns lag: int (passed a whole number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    lag = 0;
    lag = fix(round((1 / asils.pc.fmax(record_dt, 1e-9))));
    if (lag < 1)
        lag = 1;
    end
end
