function [has, qr] = kpi_reference(kind, r, v, t, q_off, roll_deg, t0, t_slew, axis, q_inertial, sun_axis, bs, sun_eci, flip)
%KPI_REFERENCE  The reference attitude of a sample in a mode whose guidance is kind (the flight software's guidance, fsw_guidance;
%   -1, a mode with none: no reference, has false): the attitude the guidance gives at t on the orbit (r, v), the payload
%   boresight bs its roll axis, the nadir family turned by flip.
%   kind: int (passed a whole number)
%   r: real[m][3] (passed in m)
%   v: real[m/s][3] (passed in m/s)
%   t: real[s] (passed in s)
%   q_off: real[1][4] (passed a plain number)
%   roll_deg: real[1] (passed a plain number)
%   t0: real[s] (passed in s)
%   t_slew: real[s] (passed in s)
%   axis: real[1][3] (passed a plain number)
%   q_inertial: real[1][4] (passed a plain number)
%   sun_axis: real[1][3] (passed a plain number)
%   bs: real[1][3] (passed a plain number)
%   sun_eci: real[1][3] (passed a plain number)
%   flip: bool (passed true or false)
%   returns has: bool (passed true or false)
%   returns qr: real[1][4] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    has = false;
    qr = zeros(4, 1);
    has = (kind >= 0);
    qr = [0; 0; 0; 1];
    if has
        [q, w, wd] = asils.models.guidance.guidance(kind, r, v, t, q_off, roll_deg, t0, t_slew, axis, q_inertial, sun_axis, bs, sun_eci, flip);
        qr = q;
    end
end
