function [a] = kpi_acosd(x)
%KPI_ACOSD  The angle [deg] whose cosine is x, x held to [-1, 1].
%   x: real[1] (passed a plain number)
%   returns a: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    a = 0;
    a = (asils.pc.acos_(asils.pc.clamp(x, (-(1)), 1)) * (180 / pi));
end
