function [rks] = kpi_rks(e, e_lag, lag, record_dt)
%KPI_RKS  The rate stability [deg/s] of a sample: the change of the performance error vector from e_lag, lag record steps of
%   record_dt [s] before, to e.
%   e: real[1][3] (passed a plain number)
%   e_lag: real[1][3] (passed a plain number)
%   lag: int (passed a whole number)
%   record_dt: real[1] (passed a plain number)
%   returns rks: real[1] (passed a plain number)
%   Generated by tools/pcode.py from the pseudocode (trinetra-pcode/2); do not edit.
    rks = 0;
    h__624 = (e - e_lag);
    rks = ((sqrt(h__624(1)*h__624(1) + h__624(2)*h__624(2) + h__624(3)*h__624(3)) * (180 / pi)) / (lag * record_dt));
end
